### ISSUE TITLE
Add a build of the SELinux API for unsupported platforms

### ISSUE THREAD

**Issue by pmorie** [opencontainers/runc#102]
Currently, in projects that consume the SELinux api from libcontainer, you need to differentiate files for builds for linux and other platforms.  It might be really convenient to have an implementation of `SelinuxEnabled` for non-supported platforms.  Thoughts? @mrunalp @crosbymichael @rhatdan @vbatts

**Comment by pmorie** [comment]
For the record, I don't expect this will solve having to differentiate files for selinux specific code.  The exact situation that I ran into is that I'm writing some unit tests that do not test selinux directly (and so do not use the selinux API), but that should be skipped when SELinux is disabled.  I wound up making a package-level func for this right now that I call from the tests.

**Comment by rhatdan** [comment]
Maybe add label.Enabled()?

**Comment by crosbymichael** [comment]
You could just check in the tests and skip the test if selinux is not enabled.

**Comment by crosbymichael** [comment]
Is this still needed?

**Comment by pmorie** [comment]
For my use-case personally in kubernetes we just use build flags, this can be closed IMO
