### ISSUE TITLE
make dbuild with golang1.7 error

### ISSUE THREAD

**Issue by ibuildthehealth** [opencontainers/runc#1021]
when change golang:1.7.0 to golang1.6.2, we can `make dbuild` successfully.

```
root@ubuntu:/go/src/github.com/opencontainers/runc# make dbuild
docker build -t runc_dev:master .
Sending build context to Docker daemon 20.99 MB
Step 1 : FROM golang:1.7.0
....
...
....
 ---> 7d798c567ea4
Successfully built 7d798c567ea4
docker run --name=runc_dev runc_dev:master make
mount: permission denied
go build -i -ldflags "-X main.gitCommit=7b0b628a9be0c0a2e237edd48cadac03ee29e73a -X main.version=1.0.0-rc1" -tags "seccomp" -o runc .
# _/go/src/github.com/opencontainers/runc
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-696435819/000000.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

Makefile:27: recipe for target 'all' failed
make: *** [all] Error 2
Makefile:36: recipe for target 'dbuild' failed
make: *** [dbuild] Error 2
```

**Comment by hqhq** [comment]
Looks like a library issue but I'm not able to reproduce :(

**Comment by cyphar** [comment]
It looks like you're using gcc-go. There's probably a compiler issue (this error looks familiar, and we fixed it in openSUSE but I can't remember the hack you needed to do to fix it).

**Comment by cyphar** [comment]
Weird, this looks similar to a compiler issue we saw in SLE (there was some hack you could do to fix it, but I can't remember the exact flags). However, you're getting mount errors as well as the compile errors, maybe there's some other issues going on.

**Comment by ibuildthehealth** [comment]
@hqhq ,may be the issue caused by the updated golang1.7.0.

**Comment by hqhq** [comment]
@cyphar I've fixed the mount error in #1022 it should be non-relevant, the `/tmp` mount is only used by CRIU tests.

**Comment by cyphar** [comment]
But `dbuild` doesn't run the tests?

**Comment by hqhq** [comment]
@ibuildthehealth I deleted my local golang:1.7.0 image and still can't reproduce.

**Comment by hqhq** [comment]
@ibuildthehealth Go 1.7.1 is out, can golang:1.7.1 fix your problem?

**Comment by ibuildthehealth** [comment]
@hqhq ,when I update the golang:1.7.1, it works fine, thanks
