### ISSUE TITLE
No package 'libseccomp' found error during runc build

### ISSUE THREAD

**Issue by lizhuqi** [opencontainers/runc#1032]
Following the steps from the release note:

```
$ # create a 'github.com/opencontainers' in your GOPATH/src
$ cd github.com/opencontainers
$ git clone https://github.com/opencontainers/runc
$ cd runc
$ make
$ sudo make install
```

It failed in make step with following errors:
```
$ make
go build -i -ldflags "-X main.gitCommit="99c683a84fcfb0675883dc98eaa8c0bc3311e436" -X main.version=1.0.0-rc1" -tags "seccomp" -o runc .
# pkg-config --cflags libseccomp libseccomp
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
pkg-config: exit status 1
make: *** [all] Error 2
```

**Comment by cyphar** [comment]
Does your distribution include the `pkg-config` information for `libseccomp`? If not, please get them to do so. If you built `libseccomp` from scratch, install the `libseccomp.pc` file available in the source tree.

**Comment by lizhuqi** [comment]
Hi Aleksa, thanks for reply! I've just run sudo apt-get install libseccomp2 to install the libseccomp2, can you tell me how to include the pkg-config information for libseccomp?

**Comment by cyphar** [comment]
You should install `pkg-config` in your distribution. Though, the error makes me think that you do have `pkg-config` installed.

**Comment by lizhuqi** [comment]
I've already installed the latest version of pkg-config. However, still it is saying No pacakge 'libseccomp' found. I am using "sudo apt-get install libseccomp2" to install the libseccomp. Is there any extra command I need to run to set up libseccomp?

go build -i -ldflags "-X main.gitCommit="f516b5d0821f90515d38e79c4f5d4d221dc0c331" -X main.version=1.0.0-rc1" -tags "seccomp" -o runc .
# pkg-config --cflags libseccomp libseccomp
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
pkg-config: exit status 1
make: *** [all] Error 2

**Comment by lizhuqi** [comment]
Close this issue as I just build it with make BUILDTAGS=""

**Comment by rhdojun** [comment]
You can click through with the other pull request from @resouer of course, but for people who just come here from google:

`libseccomp` is not enough. You need either `libseccomp-devel` or `libseccomp-dev`, depending on your OS.

**Comment by profnandaa** [comment]
Just posting this here in case someone ends up here from search. 
Be aware when you [skip this with `BUILDTAGS=""`](https://github.com/opencontainers/runc/issues/1032#issuecomment-247169377). You might end up with such a thing when running docker for instance:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: seccomp: config provided but seccomp not supported: unknown.
ERRO[0000] error waiting for container:
```
The right fix is to install both `seccomp2` and `seccomp-dev`, in the case of Ubuntu.
