### ISSUE TITLE
runc pause fails

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#1034]
Upon starting the container, tried to pause the container it failed to write to freezer.state file

failed to write FROZEN to freezer.state: open /sys/fs/cgroup/freezer/user.slice/user-1000.slice/session-6344.scope/container1/freezer.state: no such file or directory

Looks like cgroup path is wrong

But state.json is having the right path.
/sys/fs/cgroup/freezer/user.slice/user-1000.slice/session-6336.scope/container1/freezer.state

**Comment by cyphar** [comment]
I'm pretty sure this is caused by the same thing as #1031.

**Comment by rajasec** [comment]
I could dig and reverted the following changes #1009 
then it started working.

**Comment by hqhq** [comment]
It is similar as https://github.com/opencontainers/runc/pull/1013
I'll look into it later today.
