### ISSUE TITLE
Error in ''runc list''  output

### ISSUE THREAD

**Issue by kunalkushwaha** [opencontainers/runc#1037]
I getting this error with upstream code of runc while listing the containers.

Platform: ubuntu 16.04

```
$ sudo runc list 
json: cannot unmarshal string into Go value of type uint32  

$ sudo runc list -f table
json: cannot unmarshal string into Go value of type uint32  

$ sudo runc list -f json
json: cannot unmarshal string into Go value of type uint32
```

I did a initial debugging, the error is generated in ``loadState()`` function at [factory_linux.go#L286](https://github.com/opencontainers/runc/blob/master/libcontainer/factory_linux.go#L286)

**Comment by cyphar** [comment]
This is a dup of #999, closing. Feel free to reopen it if I'm incorrect.

**Comment by kunalkushwaha** [comment]
Thanks. Also, suggestion in #999 fixes my issue.
