### ISSUE TITLE
Support recording stats on container destruction

### ISSUE THREAD

**Issue by delcypher** [opencontainers/runc#1061]
I'd like to be able to record statistics for a container just before the cgroup for it is destroyed. Specifically  I'm interested in total cpu (user and sys) time used by the container over its lifetime.

I hacked together change just to see if this was possible to do this

https://github.com/delcypher/runc/commit/e2ca66baae3791c0b406d0fdc2b5a6b45ce3c25d

With the hack when the container is destroyed the statistics for the container are gathered just before destroying the cgroup and then logged.

This is clearly not the right way to do this but I'd like to discuss the right approach (if there is one...)

## Why do I want this feature?

My use case is running a command line tool (that may fork multiple processes) for which I want to

1. Monitor its resources and kill the tool (in the appropriate way) if necessary. Streaming the stats from the running container to an external process is perfect for this so the existing implementation serves this need.

2. When the tool finishes executing (either on its own or because it was killed) record the used CPU time is user and kernel space.

It is the second objective that runc currently can't do.

At a high level, what I am trying to do is benchmark a tool while also making sure it doesn't run away with resources.The tool ships as a Docker image so using Docker to record the stats itself seems sensible to me because this information is already recorded by the kernel.

I actually want this feature in Docker and I raised an issue about this ( https://github.com/docker/docker/issues/18166 ) but I hadn't really needed the feature until now. I started taking a look at Docker's implementation and it seems it has many layers of indirection but it seems that eventually it gets runc to actually run the container (via `containerd`). So runc is where the first change will need to happen.

## Wait. Why can't I just stream the stats and assume the last received event describes the resources used by the container over its lifetime?

This is racey and therefore unreliable because although I could periodically poll the stats I might not get the stats at the time of container destruction. I also will be using `runc` via docker which because of its layers of indirection will be quite slow at retrieving stats.

## Where should the recorded stats go?

This what I'm not really sure about. It seems that runc leaves no state behind after a container finishes executing (unlike Docker) so there isn't an obvious place to store the stats. My guess is that we would want to emit the stats to a JSON file. That JSON file could be specified as a command line argument to `runc` or in `config.json` (I'm not sure which is better).

We would probably want some boolean in `config.json` to indicate whether stats should be recorded on container destruction because clients of runc might not want to pay the overhead of collecting this information if they don't want it.

Eventually I want to be able to access this information from Docker so I'm going to have to figure out how to propagate this information through to containerd and across the grpc boundary to the docker daemon. My guess is I would stick this extra information in the container's state. Also if recording stats on container destruction is optional (which I think it should be) then this information will also need to be propagated from docker to runc.

Thoughts?

**Comment by delcypher** [comment]
Rather than modifying runc in the end I wrote a tool which is a small wrapper program that executes a provided command, waits for it to exit and then records the container statistics. It uses runc's infrastructure for accessing the cgroup information.

https://github.com/delcypher/docker-stats-on-exit-shim

**Comment by crosbymichael** [comment]
Ya, I think a post stop hook would work better for this instead of modifying runc. Its a cool idea though.  

Thanks!

**Comment by delcypher** [comment]
@crosbymichael 
> Ya, I think a post stop hook would work better for this instead of modifying runc. Its a cool idea though.

IIRC that would not work because when the "post stop" hooks are run the cgroup for the container has already been destroyed so the container stats cannot be collected.
