### ISSUE TITLE
len condition in ParseCgroupFile

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [opencontainers/runc#1085]
I was wondering, if there is any specific reason for:

https://github.com/opencontainers/runc/blob/20c7c3bb3769e18fef93e6787dbe6c08606d3ad9/libcontainer/cgroups/utils.go#L302. 

Shouldn't it be =!3 instead of <3 as it passes the scenario of having more than 3 and there are chances of file having a entry like 2:cpuset:/::::: being postively validated instead of throwing an error. Also, a refactoring for having a seperate validation function and constant separation would be great.

**Comment by hqhq** [comment]
It could be valid that cgroup path contains colons, see #904 for more info.

I'll close this since it's not an issue, but feel free to comment after closed.

**Comment by ravisantoshgudimetla** [comment]
@hqhq , Thanks for clearing that out but it may not still validate the entry if its something like :::cpuset:. What I wanted to know- is there some validation for 1,2,3  where <1>:<2>:<3> is an entry cgroup file. I may be missing out something here.

**Comment by cyphar** [comment]
In some cases you can get valid cgroup files where you have something like `1::/` or smth. Ultimately, this doesn't matter -- it's a kernel interface that is not going to change (and being too restrictive in these matters is something that I've personally learned to avoid -- for example if you read the `man` page for `/etc/passwd` to read that kind of file you would end up writing a parser that doesn't work on CentOS 7).

**Comment by ravisantoshgudimetla** [comment]
Cool, thanks for information.
