### ISSUE TITLE
runc exit status

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#1098]
When application gets crashed inside the container, from end user it is not obvious that process got crashed. only if enable the debug log, we can determine which signal caused the crash.
though exit status is being passed to supervisor, but not sure whether supervisor application would check for exit status > 128.

**Comment by cyphar** [comment]
I'm confused. What do you mean by this:

> from end user it is not obvious that process got crashed. only if enable the debug log, we can determine which signal caused the crash

Are you saying that it's not obvious that the container's init process returned a non-zero exit code? `runc` mirrors the exit code of the container init, so if your supervisor can handle a process exiting with a non-zero exit code then it's fine.

Or are you saying that when `runc` crashes (not the container init) then it's not obvious that runC crashed? IIRC `runc` will (as you mention) return an "unusally high" error code to indicate such cases -- is that not sufficient? I would prefer that we don't start spamming "information" like that to stdout. Is there a specific case where that isn't enough?

**Comment by rajasec** [comment]
I'm mentioning about container init getting crashed, not the runc.
I'm starting an app using   following command 
runc run sampleapp
If there is an issue with sampleapp and getting crashed, how do you know about the failure ?
i'm not asking to spam the stdout, but there should be an easy way to get to know whether started application really crashed or not. If it crashes how it crashed.
can we have tracebacks generated if the application crashed ( especially container init process)

**Comment by crosbymichael** [comment]
This is beyond runc and you should handle this in your application code.  If your application exits with exit(128), runc exits with 128.  If your app returns on stderr, so does runc.

At this level there is nothing that we should do, its just mirroring the process inside the container and if it is not acting correctly you should fix your app, not runc.

For exit status, runc follows these rules on how to tell if the process exited or was signaled.

http://tldp.org/LDP/abs/html/exitcodes.html
