### ISSUE TITLE
Provide an option to specify pivot root directory

### ISSUE THREAD

**Issue by rhvgoyal** [opencontainers/runc#1122]
Right now runc seems to assume that container root file system is writable and *always* tries to create a directory needed for pivot_root().

Slowly people are moving towards moving container rootfs read-only and don't expect runc to be scribbling on container rootfs. 

May be provide an option say --pivot-root-dir which specifies the directory to be used as pivot_root dir inside container rootfs. That way runc does not have to create/remove it and image builder/caller is responsible to make sure it is present.

**Comment by rhvgoyal** [comment]
cc @mrunalp

**Comment by mrunalp** [comment]
:+1: This takes us one step closer to making the rootfs readonly before it is passed to runc.

**Comment by rhatdan** [comment]
Correct.  I believe the rootfs should be fully configured before runc uses it.  Anything that runc needs to use on the rootfs, that does not exist, should generate an error in this mode.

**Comment by criupatchwork** [comment]
You can look at LXC how they do pivot_root without any additional directories
https://github.com/lxc/lxc/blob/master/src/lxc/conf.c#L1023

**Comment by avagin** [comment]
You can look at LXC how they do pivot_root without any additional directories
https://github.com/lxc/lxc/blob/master/src/lxc/conf.c#L1023

**Comment by cyphar** [comment]
`pivot_root(".", ".")` sounds like something that would break with SELinux. :wink:

**Comment by mrunalp** [comment]
@avagin cool, we can try that out.

**Comment by cyphar** [comment]
Ah, reading the kernel code for `sys_pivot_root` shows that the "non-zero number of `/..`" is actually checked with the `is_path_reachable` function which **does** allow for the two directories to be the same. The kernel docs (and comments) are wrong -- as usual.

**Comment by cyphar** [comment]
I'm writing up a patch for this. I'll send it tonight.

**Comment by rhatdan** [comment]
I don't believe SELinux will block this access.
