### ISSUE TITLE
Should runc kill give user a warning when they send signal(except SIGKILL and SIGSTOP) to init process

### ISSUE THREAD

**Issue by datawolf** [opencontainers/runc#1126]
If the container enable `PID namespaces` and run `sleep` in `init` process.
Only the signals for which the `init` process has established a handler can
be sent using `runc kill` command, with two exceptions: **SIGKILL** and **SIGSTOP**.

see details [man 7 pid namespaces](http://man7.org/linux/man-pages/man7/pid_namespaces.7.html):

```
       Only signals for which the "init" process has established a signal
       handler can be sent to the "init" process by other members of the PID
       namespace.  This restriction applies even to privileged processes,
       and prevents other members of the PID namespace from accidentally
       killing the "init" process.

       Likewise, a process in an ancestor namespace can—subject to the usual
       permission checks described in kill(2)—send signals to the "init"
       process of a child PID namespace only if the "init" process has
       established a handler for that signal.  (Within the handler, the
       siginfo_t si_pid field described in sigaction(2) will be zero.)
       SIGKILL or SIGSTOP are treated exceptionally: these signals are
       forcibly delivered when sent from an ancestor PID namespace.  Neither
       of these signals can be caught by the "init" process, and so will
       result in the usual actions associated with those signals
       (respectively, terminating and stopping the process).

```

So at most cases(enable PID namespace). we only can send `SIGKILL` or `SIGSTOP` signal to `init` process
in the namespaces. and the current implementation of `runc kill` command can send many different signals.

When enabled `PID namespaces`, should `runc kill` give user a warning when they send signal(except SIGKILL and SIGSTOP) to `init` process

**Comment by cyphar** [comment]
I believe this is a somewhat well-documented issue with PID namespaces. All of the talk about creating an init for Docker is because of this issue -- there's nothing really "special" about these semantics -- they're the same as PID 1 on the host. I don't really think it's necessary to give a warning, IMO the user should know what they're doing here.

**Comment by hqhq** [comment]
Maybe it'll make more sense if we merge https://github.com/opencontainers/runc/pull/808 , since you can send signals to all processes in the container.

**Comment by crosbymichael** [comment]
I don't think we need a warning.  Some processes can setup signal handlers and handle other signals even if they are running as pid1.  So there are too many edge cases and configurations to account for so that a warning would be of any use.

**Comment by datawolf** [comment]
Thanks, Got it.
