### ISSUE TITLE
Does Poststart hooks run at the right position?

### ISSUE THREAD

**Issue by gao-feng** [opencontainers/runc#1135]
Seems like poststart hooks are called after container is created and before container init process is executed.
Poststart hooks are executed [here](https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go#L272), but container process hasn't been started until user calls runc start.

**Comment by crosbymichael** [comment]
@gao-feng yes they are in the right place.  One of the reasons for post-start hooks is to setup different settings inside the container namespaces so these should be run after the container is created but before the container's user defined process is started.  This gives hooks a chance to create network interfaces and bring them up in the container before the user's mysql process has started.
