### ISSUE TITLE
io: container output becomes windows-ised

### ISSUE THREAD

**Issue by cyphar** [opencontainers/runc#1145]
For some reason, all container output gets a `\n` translated to `\r\n` on output. This is not caused directly by runC (we're not adding it), the `read` syscall is literally giving us a windows version of what the container process ran. This happens for both `runc run` and `runc exec`.

```
% runc run test | cat -v
lol^M
% runc exec test echo lol | cat -v
lol^M
```

Here's a snippet of the strace output for `runc exec test pwd`:

```
[pid 22107] getcwd("/", 192)            = 2
[pid 22107] fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 7), ...}) = 0
[pid 22107] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ffbaf0b6000
[pid 22107] write(1, "/\n", 2)          = 2
[pid 22099] <... read resumed> "/\r\n", 32768) = 3
[pid 22107] exit_group(0)               = ?
[pid 22099] futex(0xc589d0, FUTEX_WAKE, 1) = 1
[pid 22098] <... futex resumed> )       = 0
[pid 22099] write(1, "/\r\n", 3/
 <unfinished ...>
[pid 22098] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid 22099] <... write resumed> )       = 3
```

I've tried playing around with `stty` and nothing seems to help.

This was discovered as part of #1133 as it affects how we write tests.

**Comment by cyphar** [comment]
This doesn't happen if `process.terminal = false`. Which means that there's some wacky translation going on in the Linux tty driver.

**Comment by cyphar** [comment]
Alright, it's because we didn't set `stty -onlcr`. For some reason this is *actually* **not** the default behavior but we don't notice it because shells don't create new pty pairs for each subprocess. The fix is to just set the right termios ioctl.

@hqhq should I make it a separate PR or combine it with #1018?

**Comment by hqhq** [comment]
@cyphar If it doesn't affect #1018 a lot, I would prefer it be separate, I always prefer small PR than big bunch :wink:

**Comment by cyphar** [comment]
Sure, it's just that I'll have to reproduce it in #1018. Not a big deal though.
