### ISSUE TITLE
Pullapprove doesn't manage merge authority correctly

### ISSUE THREAD

**Issue by hqhq** [opencontainers/runc#1152]
Maintainers can still merge without approval from pullapprove.

I don't see anything wrong with `.pullapprove.yml`, maybe related to janky?

@caniszczyk @crosbymichael Any ideas?

**Comment by caniszczyk** [comment]
@hqhq branch protection wasn't enabled within GitHub, I fixed that now

**Comment by hqhq** [comment]
@caniszczyk Thanks for the quick response, looks like all PRs need to rebased now, is that an intended side affection.

**Comment by hqhq** [comment]
OK, looks like clicking `Update branch` button would work, no need to rebase, thanks.

**Comment by hqhq** [comment]
Oops, click that button would change commit and cause dco issue, I'm confused, still needs to rebase?

**Comment by hqhq** [comment]
@caniszczyk Looks like we enabled out-of-data branch checking which seems not necessary, and it'll forbid janky from running, the former conflict check would be good.

**Comment by caniszczyk** [comment]
@hqhq ok I changed the setting, lets see if this works now :)

**Comment by cyphar** [comment]
I merge things by hand (so I can sign merge commits). Will this break that functionality?

**Comment by hqhq** [comment]
@caniszczyk Yeah, looks good now, thanks.

**Comment by hqhq** [comment]
@cyphar I don't think it'll affect that functionality, you can try that out and ping Chris if that's broken.
