### ISSUE TITLE
Proposal, bind mount don't used / as source

### ISSUE THREAD

**Issue by keloyang** [opencontainers/runc#1167]
```
root@SZV1000154432:~/workspace/tools# docker run --rm -ti -v /:/tmp busybox ash     
/ # chroot /tmp
root@e60cadd7cc60:/# passwd root
Enter new UNIX password: 
Retype new UNIX password: 
passwd: password updated successfully
root@e60cadd7cc60:/#
```
Could we need a pr to limit that the source don't use / of host ?

**Comment by hqhq** [comment]
It's enabled on purpose in https://github.com/opencontainers/runc/pull/1090 .

**Comment by keloyang** [comment]
https://github.com/opencontainers/runc/pull/1090/files limit for dest, not for source.

**Comment by cyphar** [comment]
I don't really see why we should be stopping people from foot-gunning (there might be legitimate usecases for having `/` as the source of a bindmount inside the container). For example you could create a read-only version for some weird reason (like generating a new distro image based on the host filesystem).

In addition, this isn't the right place to make such a PR even if it were a concern. I'd recommend making a PR against Docker (which is separate from this project and has separate design concerns) or in the OCI runtime-spec (which doesn't have such a limitation and thus adding a limitation here might be seen as making runC non-compliant).
