### ISSUE TITLE
How can I add seccomp filter for per process using libcontainer?

### ISSUE THREAD

**Issue by magicae** [opencontainers/runc#1179]
Hi!
I found there is no seccomp config in `Process` struct. Is there a way to enable seccomp for a single process executed in the container?
Thanks!

**Comment by cyphar** [comment]
It's in the `"linux"`-specific section. You can check the relevant section of the spec[1] for more information.

[1]: https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#seccomp

**Comment by cyphar** [comment]
Unless by "single process" you mean exactly that (only setting the limit for a single process, not the entire container). Unfortunately, that's not possible with the spec. You'll have to implement it yourself in the application code that you're running a container.

It should also be noted that seccomp rules apply to `fork`s. So technically the seccomp setting does only set the setting for one process (though it does also apply it to `runc exec` processes), it's just that every process in the container is a `fork` of the container's init. So even if you implemented single-process `seccomp` settings it would still mean that all `fork`s of that process have the same seccomp profile.

**Comment by magicae** [comment]
Great! Thank you. 😉
