### ISSUE TITLE
pids cgroup path

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#1189]
@cyphar @hqhq 
When I ran with latest 4.8.7 kernel, where I've included the pids cgroup.
After running the container called "test"
Only pids subsystem is not listing under session.scope.. 

cat /proc/11511/cgroup
11:blkio:/user.slice/user-1000.slice/session-67.scope/test
10:pids:/test
9:memory:/user.slice/user-1000.slice/session-67.scope/test
8:cpuset:/user.slice/user-1000.slice/session-67.scope/test
7:perf_event:/user.slice/user-1000.slice/session-67.scope/test
6:hugetlb:/user.slice/user-1000.slice/session-67.scope/test
5:cpu,cpuacct:/user.slice/user-1000.slice/session-67.scope/test
4:devices:/user.slice/user-1000.slice/session-67.scope/test
3:freezer:/user.slice/user-1000.slice/session-67.scope/test
2:net_cls,net_prio:/user.slice/user-1000.slice/session-67.scope/test
1:name=systemd:/user.slice/user-1000.slice/session-67.scope/test

**Comment by hqhq** [comment]
It's because the bash process you run container was not in the session-67.scope, that's distro's behavior, and runc only creates cgroup under parent's cgroup.

**Comment by rajasec** [comment]
@hqhq 
Thanks for your quick response.
Then this is not an issue. I'm closing. Let me figure out the distro behavior.
