### ISSUE TITLE
make failed without detail report

### ISSUE THREAD

**Issue by xianwei2016** [opencontainers/runc#1191]
$make BUILDTAGS=""
go build -i -ldflags "-X main.gitCommit="43c43004ef0563ceab23bb8f254cd5061a6f607e" -X main.version=1.0.0-rc2" -tags "" -o runc .
\# _/home/xianwei.zw/runc
usage: 6l [options] main.6
  -1	use alternate profiling code
  -8	assume 64-bit addresses
  -B info
    	define ELF NT_GNU_BUILD_ID note
  -C	check Go calls to C code
  -D addr
    	data address
  -E sym
    	entry symbol
  -I interp
    	set ELF interp
  -L dir
    	add dir to library path
  -H head
    	header type
  -K	add stack underflow checks
  -O	print pc-line tables
  -Q	debug byte-register code gen
  -R rnd
    	address rounding
  -S	check type signatures
  -T addr
    	text address
  -V	print version and exit
  -W	disassemble input
  -X name value
    	define string data
  -Z	clear stack frame on entry
  -a	disassemble output
  -c	dump call graph
  -d	disable dynamic executable
  -extld ld
    	linker to run in external mode
  -extldflags ldflags
    	flags for external linker
  -f	ignore version mismatch
  -g	disable go package data checks
  -installsuffix suffix
    	pkg directory suffix
  -k sym
    	set field tracking symbol
  -linkmode mode
    	set link mode (internal, external, auto)
  -n	dump symbol table
  -o outfile
    	set output file
  -r dir1:dir2:...
    	set ELF dynamic linker search path
  -race
    	enable race detector
  -s	disable symbol table
  -shared
    	generate shared object (implies -linkmode external)
  -tmpdir dir
    	leave temporary files in this directory
  -u	reject unsafe packages
  -v	print link trace
  -w	disable DWARF generation
make: *** [all] Error 2

**Comment by xianwei2016** [comment]
It's my first time trying to use runc, but I cannot make it, also it's seems hard to figure out the failed reason. Any tips? Thanks.

**Comment by kunalkushwaha** [comment]
What is your system os details?

``go env``

Also, can you try ``$ make dbuild``, if docker is installed on you machine

**Comment by xianwei2016** [comment]
$go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by xianwei2016** [comment]
There have some network problem to start docker daemon in my system, not sure this will affect building runc.

**Comment by kunalkushwaha** [comment]
No docker is not required if you are not using ``make dbuild``.

I suspect, issue is with your ``go`` environment.

what go version you are using?

**Comment by xianwei2016** [comment]
$go version
go version go1.4.2 linux/amd64

**Comment by kunalkushwaha** [comment]
I think, you should update your golang to  preferably >= 1.6 version

**Comment by xianwei2016** [comment]
Ok, I will try it. Thanks a lot. @kunalkushwaha
