### ISSUE TITLE
checkpoint fails with latest runc

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#1195]
With  criu version 1.6 and latest runc, not able to checkpoint the container ( Kernel : 4.8.7)
Not able to checkpoint when we enable user namespace.

Below  is dump.log
(00.002876) Found /sys/fs/cgroup/blkio mapping for ./sys/fs/cgroup/blkio mountpoint
(00.002878) Found /sys/fs/cgroup/pids mapping for ./sys/fs/cgroup/pids mountpoint
(00.002880) Found /sys/fs/cgroup/memory mapping for ./sys/fs/cgroup/memory mountpoint
(00.002882) Found /sys/fs/cgroup/cpuset mapping for ./sys/fs/cgroup/cpuset mountpoint
(00.002884) Found /sys/fs/cgroup/perf_event mapping for ./sys/fs/cgroup/perf_event mountpoint
(00.002886) Found /sys/fs/cgroup/hugetlb mapping for ./sys/fs/cgroup/hugetlb mountpoint
(00.002887) Found /sys/fs/cgroup/cpu,cpuacct mapping for ./sys/fs/cgroup/cpu,cpuacct mountpoint
(00.002889) Found /sys/fs/cgroup/devices mapping for ./sys/fs/cgroup/devices mountpoint
(00.002891) Found /sys/fs/cgroup/freezer mapping for ./sys/fs/cgroup/freezer mountpoint
(00.002892) Found /sys/fs/cgroup/net_cls,net_prio mapping for ./sys/fs/cgroup/net_cls,net_prio mountpoint
(00.002894) Found /sys/fs/cgroup/systemd mapping for ./sys/fs/cgroup/systemd mountpoint
(00.002902) Error (mount.c:713): 1147:./proc/sched_debug doesn't have a proper root mount

**Comment by rajasec** [comment]
@cyphar 
This problem was observed when we enabled user name space, After removing the uid/gid mappings from config.json, able to checkpoint the container.

**Comment by avagin** [comment]
I think this issue was fixed in https://github.com/opencontainers/runc/commit/db99936a0e694e61e247a1aec6f793119fe88f04
