### ISSUE TITLE
Checkpoint fails with type NOTIFY errno 0

### ISSUE THREAD

**Issue by kunalkushwaha** [opencontainers/runc#1202]
##### System information
```
$ uname -r
4.4.0-47-generic

$ runc --version
runc version 1.0.0-rc1
commit: 6b8f696614e472bc404d31a327fb308d039d2d7a-dirty
spec: 1.0.0-rc1-dev

$ criu --version
Version: 2.6
```

#### Steps to reproduce.

```
$ sudo runc create alpine
$ sudo runc start alpine
$ sudo runc list                             
ID          PID         STATUS      BUNDLE                                CREATED
alpine      0           running     /home/kunal/work/runc-images/alpine   2016-11-28T02:44:25.680187033Z
$ sudo runc checkpoint alpine
criu failed: type NOTIFY errno 0
log file: /run/runc/alpine/criu.work/dump.log
```

#### Log
```
433 (00.101993) Dumping opened files (pid: 32148)
434 (00.101995) ----------------------------------------
435 (00.102002) Sent msg to daemon 12 0 0
436 pie: 1: __fetched msg: 12 0 0
437 pie: 1: __sent ack msg: 12 12 0
438 pie: 1: Daemon waits for command
439 (00.102020) Wait for ack 12 on daemon socket    
440 (00.102025) Fetched ack: 12 12 0
441 (00.102052) 32148 fdinfo 0: pos:                0 flags:           100002/0
442 (00.102065) tty: Dumping tty 10 with id 0x3
443 (00.102068) Error (criu/files-reg.c:1122): Can't lookup mount=21 for fd=0 path=/dev/pts/2
444 (00.102074) ----------------------------------------
445 (00.102080) Error (criu/cr-dump.c:1313): Dump files (pid: 32148) failed with -1
446 (00.102105) Waiting for 32148 to trap
447 (00.102108) Daemon 32148 exited trapping
448 (00.102112) Sent msg to daemon 5 0 0
449 pie: 1: __fetched msg: 5 0 0
450 pie: 1: 1: new_sp=0x7f3a1a5a7008 ip 0x7f3a1a3781e0
451 (00.102706) 32148 was trapped 
452 (00.102708) `- Expecting exit
453 (00.102717) 32148 was trapped
454 (00.102719) 32148 is going to execute the syscall 15
455 (00.102729) 32148 was stopped
456 (00.102738) 32148 was trapped
457 (00.102741) 32148 is going to execute the syscall 186
458 (00.102747) 32148 was trapped
459 (00.102749) `- Expecting exit
460 (00.102755) 32148 was trapped
461 (00.102757) 32148 is going to execute the syscall 1
462 (00.102764) 32148 was trapped
463 (00.102765) `- Expecting exit
464 (00.102771) 32148 was trapped
465 (00.102773) 32148 is going to execute the syscall 11
466 (00.102789) 32148 was stopped
467 (00.102848) Unlock network
468 (00.102851) Running network-unlock scripts
469 (00.102852)     RPC
470 (00.104537) Unfreezing tasks into 1
471 (00.104542)     Unseizing 32148 into 1
472 (00.104552) Error (criu/cr-dump.c:1628): Dumping FAILED.
```

I am able to reproduce this with ubuntu and redis container too.

**Comment by avagin** [comment]
It is the known issue. This container uses an "external" tty.
https://criu.org/Inheriting_FDs_on_restore#External_TTYs

**Comment by cyphar** [comment]
@avagin Does #1018 unbreak this?

**Comment by kunalkushwaha** [comment]
@avagin @cyphar Does #1018 fix this? 

I will try to test the PR and update.

**Comment by marcosnils** [comment]
> @avagin @cyphar Does #1018 fix this?
> 
> I will try to test the PR and update.

No, it's a CRIU thing.

**Comment by avagin** [comment]
The problem is that one end of a pty pair is used externally. You can look how we work with pipes in runc now and do the similar things for a console. It should not be hard. Unfortunately I don't have time for this now.

**Comment by kunalkushwaha** [comment]
Thanks, Will look into it and make a PR

**Comment by cyphar** [comment]
@kunalkushwaha I would wait for #1018 to be merged before touching any console code, just because that patch is very large and very annoying to keep up-to-date with master when people touch all of the various parts it touches.

**Comment by kunalkushwaha** [comment]
@cyphar I agree. Actually I am studying #1018 patch to understand whole new console fix :)

**Comment by cyphar** [comment]
@keloyang #1018 has been merged now. I've just tested this and it no longer fails on the `/dev/console` resolution. However, now it fails with a different error in the log.

```
% recvtty test.sock &
% runc create --console-socket test.sock ctr
% runc start ctr
% runc checkpoint ctr
criu failed: type NOTIFY errno 0
log file: /run/runc/ctr/criu.work/dump.log
```

Here is the relevant tail of the log:

```
(00.416041) mnt: Dumping mountpoints
(00.416043) mnt:        287: 87:/ @ ./sys/firmware
(00.416050) mnt: Path `/sys/firmware' resolved to `./sys/firmware' mountpoint
(00.443342) mnt:        286: 76:/null @ ./proc/sched_debug
(00.443347) mnt: Something is mounted on top of ./dev
(00.443374) Error (criu/mount.c:1053): mnt: Can't create a temporary directory: Read-only file system
(00.443447) Unlock network
(00.443449) Running network-unlock scripts
(00.443449)     RPC
(00.471881) Unfreezing tasks into 1
(00.471893)     Unseizing 30626 into 1
(00.471908) Error (criu/cr-dump.c:1635): Dumping FAILED.
```

**Comment by kunalkushwaha** [comment]
I am able to reproduce this issue. 

Now it seems CRIU bug now. It is not able to mount /dev folder inside the [``criu namespace``](https://github.com/xemul/criu/blob/master/criu/mount.c#L1094)

and function [``get_clean_mnt()`` ](https://github.com/xemul/criu/blob/master/criu/mount.c#L1110) is failing.

**Comment by avagin** [comment]
@kunalkushwaha @cyphar Could you try out runc and criu from these repos:

https://github.com/avagin/criu/tree/runc-console
https://github.com/avagin/runc/tree/cr-console

This is a draft version and it works for me:
https://asciinema.org/a/0n84xjgga83rshdbu49gj2wz8

**Comment by avagin** [comment]
@kunalkushwaha what criu do you use? Did you get it from my repo?

**Comment by avagin** [comment]
> $ criu --version
> Version: 2.9
> GitID: v1.2-4041-gdcb5df7

I didn't notice this part of your answer. You got the right criu.

> runc from https://github.com/avagin/runc/tree/cr-console build hits cr-console/libcontainer/container_linux.go#L543 . So skipping this condition results in same issue.

It's very suspicious. I have never seen this error and I can't reproduce this issue with your config. I think runc can use a wrong criu. Could you update runc from my repo and try to reproduce the issue? Now the error will contain the current and required criu versions.

If you are sure that the right criu is used, I need dump.log, restore.log and runc.log to investigate the issue. Thanks you for the time.
