### ISSUE TITLE
seccomp: Thread Sync bit not set

### ISSUE THREAD

**Issue by thorduri** [opencontainers/runc#1212]
Hi,

[InitSeccomp](https://github.com/opencontainers/runc/blob/master/libcontainer/seccomp/seccomp_linux.go#L31) does not set the thread synchronization bit prior to loading the filter.

This is unfortunate as the `go` runtime starts a number of threads right off the bat, meaning that
the loaded filter will not be shared among them -- new threads created after the filter is loaded
do inherit the filter of course.

This does have some implications, and it's easy to verify. Running a docker container with the
a small modification to the default seccomp profile (remove say, mkdir/getpid) and serving up a small net/http server where a handler does an mkdir/getpid and doing repeated calls to it -- some will get caught by the filter, others wont (depending on which thread the go routine runs on).

Something like this:
```golang
if err = filter.SetTsync(true); err != nil {
        return err
}
```
around [here](https://github.com/opencontainers/runc/blob/master/libcontainer/seccomp/seccomp_linux.go#L73) ought to do the trick.

This doesn't work with libseccomp (2.2.3) as shipped by most of the LTS distributions (Ubuntu, Debian, Centos etc), however 2.3.1 works fine.

**Comment by mrunalp** [comment]
@thorduri SGTM. Can you create a PR?

**Comment by justincormack** [comment]
Can you provide a reproduction? As we `exec`, all the rest of the threads go away, and we should be on the same thread, which will then become the child process. So this explanation is not correct.

**Comment by cyphar** [comment]
And we use `runtime.LockOSThread()` which ensures that once we set seccomp on the current thread, that the same thread will be executing `execve` -- which means that the profiles will (or rather should) always apply to the process that hits `execve`.

**Comment by thorduri** [comment]
@justincormack Yes, my explanation is incorrect (I attributed success in my tests to this, but in reality they where from a botched harness).

Apologies for not closing this issue sooner.

As for `libseccomp-golang` in general, the right fix is to set the TSYNC bit by default in the package, see the referenced discussion in this thread.

However it has no impact on `runc`.
