### ISSUE TITLE
Switch away from godep

### ISSUE THREAD

**Issue by cyphar** [opencontainers/runc#1235]
Godep is going to be deprecated with the release of Go 1.8. In addition, `godep` has always struck me as a _bit_ too dodgy. So I recommend we switch to either [`vndr`](https://github.com/LK4D4/vndr) or `hack/vendor.sh`. I'd prefer we use `vndr` but I've had some previous issues with it.

**Comment by cyphar** [comment]
Apologies, this is already being done by #998. I thought I'd already seen a PR for this.

**Comment by hqhq** [comment]
Close since https://github.com/opencontainers/runc/pull/1340 is merged.
