### ISSUE TITLE
cgroup issue in hook

### ISSUE THREAD

**Issue by moypray** [opencontainers/runc#1238]
Hi, I will use 'prestart hook' to add block devices to container.  But I found that when I add cgroup permissions of the devices to container, the cgroup permission of device.list is  "a *:* rwm" and I can not write my devices permission.  But when container starts up the permission will be re-config and my device has no permission either...

From runC code, I see that setting cgroup config will be done in  "procReady" state and run prestart hook is in "procHooks" state.  I wonder if we could move cgroup operation before prestart hook run?

thanks

**Comment by moypray** [comment]
I have a fix  and have done some basic test:
https://github.com/opencontainers/runc/pull/1239

**Comment by marcosps** [comment]
The PR was merged, so can this issue be closed?

**Comment by crosbymichael** [comment]
@marcosps thanks for the reminder
