### ISSUE TITLE
runc exec requires command to be passed on CLI

### ISSUE THREAD

**Issue by teddyking** [opencontainers/runc#1264]
It seems that [this commit](https://github.com/opencontainers/runc/commit/b517076907b7c18d7a1f296ec390cf3f275e2375) introduced a minArgs requirement of 2 for `runc exec`, with the second arg consisting of a process to run.

Is this actually a requirement here? Previously we were able to run `runc exec` by passing `-p process.json` containing the command to run etc.

Would it be ok to make the `<container command>` optional again?
We'd be happy to submit the PR.

Thanks!
Ed & Konstantinos

**Comment by WeiZhang555** [comment]
I think this makes sense :+1:  , it looks like a mistake made by me :cry:

**Comment by cyphar** [comment]
Yeah, looks like a regression to me too. @WeiZhang555 can you make a patch?

**Comment by WeiZhang555** [comment]
@cyphar Yep, happy to do that~
