### ISSUE TITLE
Add support for setting console size for runc exec -d -tty -console-socket ... 

### ISSUE THREAD

**Issue by teddyking** [opencontainers/runc#1269]
Hi,

We'd like to be able to configure an initial console size when running a `runc exec -d -tty -console-socket /path/to/socket.sock ...`. We've started work on a possible PR to add this functionality but I wanted to open this up for discussion/feedback.

Our current thoughts are to add a `setConsoleSize` func just after opening up `/dev/ptmx` [here](https://github.com/opencontainers/runc/blob/eedebb8c40ca598ed45f4ea023c1f1f43d442189/libcontainer/console_linux.go#L12-L31). The values for the height/width would be defined by `consoleSize` in the process.json and passed down via initConfig.

Does this sound reasonable? We've been testing this out today and it seems to do what we want.

For context, we're looking to pull in the latest version of runc (incl. the new console work), but the changes are causing flakey behaviour in our tests. Being able to define the initial size for the console will help to alleviate this.

Thanks!
Ed & Petar

**Comment by mrunalp** [comment]
I think that sounds reasonable. Could you open a PR for that?

**Comment by teddyking** [comment]
Great thanks - we've opened up PR #1275 so I'll close this one off.
