### ISSUE TITLE
CentOs 6.7: runc run command exits with "write parent:broken pipe" exception

### ISSUE THREAD

**Issue by Nabarun** [opencontainers/runc#1270]
Environment
#cat /etc/centos-release
CentOS release 6.7 (Final)
#uname -a
Linux machinename 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
#go version
go version go1.7.4 linux/amd64
#runc --version
runc version 1.0.0-rc2
commit: eedebb8c40ca598ed45f4ea023c1f1f43d442189
spec: 1.0.0-rc3

Issue 

The issue is we cannot run a container using runc. It throws the following exception
#/usr/local/sbin/runc run --no-new-keyring testcontainer
**container_linux.go:247: starting container process caused "write parent: broken pipe"**

#/usr/local/sbin/runc run testcontainer
**container_linux.go:247: starting container process caused "write parent: broken pipe"**

Attached config.json file
[runc-config.txt](https://github.com/opencontainers/runc/files/700445/runc-config.txt)

Any suggestion will indeed be helpful

**Comment by Nabarun** [comment]
Figured out the fix. 
There might be 2 issues that you need to fix

1. Your runc binary was built with some argument like ‘selinux’ which is no longer compatible to your version. Rather building runc with args you should be using make BUILDTAGS=’’ (empty args)

2. If you still see the issue the problem might be because of cgroup. Try to start the service by executing
  $ Service cgconfig start

Hopefully these 2 solutions will fix the issue.

**Comment by AkihiroSuda** [comment]
The ecosystem no longer supports CentOS 6. Closing.
