### ISSUE TITLE
runc is not using opencontainers/runtime-spec config for seccomp format

### ISSUE THREAD

**Issue by GrantSeltzer** [opencontainers/runc#1273]
The [seccomp struct](https://github.com/opencontainers/runc/blob/master/libcontainer/configs/config.go#L31) used in runc is redefined from [runtime-spec's definition](https://github.com/opencontainers/runtime-spec/blob/master/specs-go/config.go#L369) which is already vendored in. They're almost the same except for the Operator type being an int instead of a string. I'm fairly certain this is a relic from Docker. 

If I can get some feedback, I can switch it over for consistencies sake without making any changes to the `configs` package api.

**Comment by GrantSeltzer** [comment]
It's also worth noting that there's [discussion](https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/BkTgy0bZrXQ) to update runtime-spec's seccomp format to a more expressive version currently being used in cri-o. If that comes to fruition it'd make more sense to do this afterwards.

**Comment by justincormack** [comment]
We could probably fix this anyway now.

**Comment by GrantSeltzer** [comment]
@justincormack I have a fix ready locally, going to wait for more discussion on the runtime-spec PR before opening something here

**Comment by crosbymichael** [comment]
This has been fixed when we bumped to runtime-spec rc5

**Comment by dklyle** [comment]
I think the code here https://github.com/opencontainers/runc/blob/master/libcontainer/seccomp/seccomp_linux.go#L161 is broken in the processing of the syscall names.
