### ISSUE TITLE
running exec setns process for init caused \"exit status 26\"

### ISSUE THREAD

**Issue by teddyking** [opencontainers/runc#1281]
We're seeing the following error on a semi-regular basis when running `runc create`s in our (CF Garden) test suite:

```
container_linux.go:247: starting container process caused "process_linux.go:272: running exec setns process for init caused \"exit status 26\""
```

The issue can be reproduced by repeatedly running the tty bats tests.
For example, we've been using the following bash script run from the root of the runc repo:

```
#!/bin/bash

set -e -x

for (( ; ; ))
do
    make integration TESTFLAGS="/tty.bats"
done
```

After ~10 or so runs the failure has usually occurred (note that we also saw the failure when repeatedly running the create bats tests, but it seems to occur much more frequently on the tty bats).

We saw from [this comment](https://github.com/opencontainers/runc/issues/1130#issuecomment-255034614) that this means we are reaching the 26th `bail` in [nsexec.c](https://github.com/opencontainers/runc/blob/master/libcontainer/nsenter/nsexec.c)? 
We ran the `gcc -E nsexec.c -o nsexec.i` mentioned in [this comment](https://github.com/opencontainers/runc/issues/1130#issuecomment-267010524) and _think_ this means we are actually hitting the `unexpected sync value` bail found [here](https://github.com/opencontainers/runc/blob/master/libcontainer/nsenter/nsexec.c#L585).

Has anyone else noticed this? And would you be able to provide some help for debugging the root issue here?

Thanks,
Ed & Petar

**Comment by hqhq** [comment]
Yes, #1237 is gonna fix it.
