### ISSUE TITLE
How to set rlimit value to `unlimited` in config.json?

### ISSUE THREAD

**Issue by Naitreey** [opencontainers/runc#1283]
[OCI spec](ng8w/conf/container/elasticsearch/limits.conf) defines the hard/soft value of resource limits to be of type `unit64`. But how to set `RLIM_INFINITY`?

I've tried `-1` and `0`. The former obviously caused the invalid value error 

```
json: cannot unmarshal number -1 into Go value of type uint64
```
and the latter caused error

```
error setting rlimit type 7: invalid argument
```

**Comment by hqhq** [comment]
@Naitreey rlimit is defined as the same semantics as http://man7.org/linux/man-pages/man2/setrlimit.2.html in OCI spec, and runc just follow it, so I guess you'll need to use `RLIM_INFINITY` directly. Note that runc config is low level configuration and usually generated by high level tools which can use `RLIM_INFINITY` as input.

If you have concern about this, you can open an issue in [runtime-spec](https://github.com/opencontainers/runtime-spec) and get more feed back there, I'll close this by now, feel free to comment if you have more questions.
