### ISSUE TITLE
runc exec -d with --tty too fast

### ISSUE THREAD

**Issue by crosbymichael** [opencontainers/runc#1302]
With the new tty functionality if you are using `--console-socket` on runc exec, because exec has no create/start there is no way to get the console before a command like `true` exits or `echo hi` and get the output because the command will exit before runc returns the console master to the caller.  

We need the sending of the console to block on the caller reading the master instead of continuing.  I think its is because runc uses two sockets, one from the child to parent, and one for runc to its caller.  

@cyphar can we just use one socket for this?

**Comment by cyphar** [comment]
Using one socket _might_ work, but the issue with using it is:

1. We now expose internals of `libcontainer` to callers.
2. I'm not sure how the terminal handling code of `libcontainer.Process` will look if we expose the internal socket for containers where the socket is created inside the container -- all of the various `setupIO` functions would have to be rewritten and we'd have to come up with other ways of making that API work.

I'm not against the change, just that I'm not sure whether the API that will come from it will work nicely.

What if we just delayed the runC parent from exiting until the console is set up?

**Comment by crosbymichael** [comment]
its not the parent exiting, its the process running inside exiting before.  we have to block somehow and only continue after the console has been sent back to the calling process

**Comment by crosbymichael** [comment]
I would rather just use the same socket and it blocks on send, seems so much simpler than adding more code to this and two sockets are already complex
