### ISSUE TITLE
adding _LIBCONTAINER to environment breaks state

### ISSUE THREAD

**Issue by cyphar** [opencontainers/runc#1311]
Because of some **very** questionable logic when determining the state of a container, if you have a container with `_LIBCONTAINER` anywhere in its environment then `runc state` will show the container as `created` not `running`.

This is because of this code (which isn't correct IMO):

```go
	// check if the process that is running is the init process or the user's process.
	// this is the difference between the container Running and Created.
	environ, err := ioutil.ReadFile(fmt.Sprintf("/proc/%d/environ", pid))
	if err != nil {
		return Stopped, newSystemErrorWithCausef(err, "reading /proc/%d/environ", pid)
	}
	check := []byte("_LIBCONTAINER")
	if bytes.Contains(environ, check) {
		return Created, nil
	}
	return Running, nil

```

**Comment by cyphar** [comment]
This is causing issues with rootless containers when trying to make `!dumpable` also safe with rootless containers.

**Comment by hqhq** [comment]
Can we check the status of fifo file to get if the container is in `created` state?

**Comment by crosbymichael** [comment]
We can have something like `runc start` update that state or to keep this check dynamic we could maybe look at `/proc/<pid>/exe` readlilnk on it to see if its the runc binary( though this is hard to match up ).  

Checking if the fifo is there or not could work as we delete it after start.  Its probably our best option.
