### ISSUE TITLE
Does running runc inside a docker container require the outer container to be privileged?

### ISSUE THREAD

**Issue by deitch** [opencontainers/runc#1324]
I guess since docker engine uses runc under the covers as well, the question could be renamed runc-in-runc, but question remains.

I have a pattern wherein I often need to run another containerized app inside a containerized app. I _could_ use the peer/sibling pattern (actually, it is what I do now), but volume mounting gets messy and debugging is not pretty. 

All of the commands are one-offs: run a container as a process until it exits, usually within seconds. The real benefit to me of doing it this way is isolation of building. My manager container is clean and independent, it can find whatever processor "image" it needs and run it.

Do I need `--privileged` on my outer container for this pattern to work?

**Comment by hqhq** [comment]
Short answer is YES, you can find more information about the restriction and possible solution from: https://github.com/opencontainers/runc/pull/774

I'm closing this issue since it's not an **issue**, feel free to comment if you have more question or reach to our [dev mailing list](https://groups.google.com/a/opencontainers.org/forum/#!forum/dev).

**Comment by deitch** [comment]
@hqhq thanks.

So it is a specific case of the general problem of rootless containers? My use case is more of taking advantage of packaging than isolation (cgroups and namespaces), but it is helpful.

I think for now I will run with privileged but slowly migrate towards some of the workarounds. Will be nice when rootless comes to fore, though. I think there is an entire class of problems that can be solved by having a non-privileged container able to launch other containers that are within its own space. Containers as hierarchy, not as flat.
