### ISSUE TITLE
panic: standard_init_linux.go:164: openat exec fifo caused "permission denied" 

### ISSUE THREAD

**Issue by ianpark** [opencontainers/runc#1330]
Hi,

Using 1.0.0-rc2, "runc run" stuck in a strange situation. The process is defunct and never return.
`sv-file  26388 26379  0 12:35 ?        00:00:00 [exe] <defunct>`

A python script main.py which runs with 'sv-file' user executes an external python script called run.py using subprocess.call(['sudo', 'run.py', ...). The sudoer file for sv-file user only allows 'run.py' so that I can prevent sv-file to sudo something else. 
The run.py, which is run as 'root', just does
`subprocess.call(["runc", "run", "-b",'/path', 'random_id'])`

if I run run.py in terminal using sv-file user, it works fine while it fails when it is run through main.py.

The back trace message look like this:
`panic: standard_init_linux.go:164: openat exec fifo caused "permission denied" [recovered]
	panic: standard_init_linux.go:164: openat exec fifo caused "permission denied"

goroutine 1 [running, locked to thread]:
panic(0x7e7900, 0xc820137880)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200ab310)
	/home/vagrant/git/safeview/build/out/debbuild_stage/runc-menlosec_work/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7e7900, 0xc820137880)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200aac20, 0xc82001e0c8, 0xc8200aad30)
	/home/vagrant/git/safeview/build/out/debbuild_stage/runc-menlosec_work/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820069630, 0x7f1ec5742688, 0xc820137880)
	/home/vagrant/git/safeview/build/out/debbuild_stage/runc-menlosec_work/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82008aa00, 0x0, 0x0)
	/home/vagrant/git/safeview/build/out/debbuild_stage/runc-menlosec_work/runc-1.0.0-rc2/main_unix.go:26 +0x68
reflect.Value.call(0x74c6c0, 0x8fd428, 0x13, 0x843f30, 0x4, 0xc8200ab290, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74c6c0, 0x8fd428, 0x13, 0xc8200ab290, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74c6c0, 0x8fd428, 0xc82008aa00, 0x0, 0x0)
	/home/vagrant/git/safeview/build/out/debbuild_stage/runc-menlosec_work/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x846de8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8dc8e0, 0x51, 0x0, ...)
	/home/vagrant/git/safeview/build/out/debbuild_stage/runc-menlosec_work/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/home/vagrant/git/safeview/build/out/debbuild_stage/runc-menlosec_work/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/home/vagrant/git/safeview/build/out/debbuild_stage/runc-menlosec_work/runc-1.0.0-rc2/main.go:132 +0xd98
`

config.json
`{  
   "process":{  
      "args":[  
         "./test"
      ],
      "capabilities":[  
         "CAP_AUDIT_WRITE",
         "CAP_KILL"
      ],
      "terminal":true,
      "rlimits":[  
         {  
            "soft":1024,
            "hard":1024,
            "type":"RLIMIT_NOFILE"
         }
      ],
      "user":{  
         "gid":1019,
         "uid":1078
      },
      "env":[  
         "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
         "LD_LIBRARY_PATH=/usr/local/lib",
         "TERM=xterm"
      ],
      "noNewPrivileges":true,
      "cwd":"/usr/local/bin"
   },
   "hooks":{  

   },
   "hostname":"runc",
   "platform":{  
      "arch":"amd64",
      "os":"linux"
   },
   "linux":{  
      "seccomp":{  
         "defaultAction":"SCMP_ACT_ALLOW",
         "architectures":[  
            "SCMP_ARCH_X86_64"
         ],
         "syscalls":[  
            {  
               "action":"SCMP_ACT_ERRNO",
               "name":"getcwd"
            }
         ]
      },
      "maskedPaths":[  
         "/proc/kcore",
         "/proc/latency_stats",
         "/proc/timer_list",
         "/proc/timer_stats",
         "/proc/sched_debug"
      ],
      "readonlyPaths":[  
         "/proc/asound",
         "/proc/bus",
         "/proc/fs",
         "/proc/irq",
         "/proc/sys",
         "/proc/sysrq-trigger"
      ],
      "namespaces":[  
         {  
            "type":"pid"
         },
         {  
            "type":"network"
         },
         {  
            "type":"ipc"
         },
         {  
            "type":"uts"
         },
         {  
            "type":"mount"
         }
      ],
      "resources":{  
         "cpu":{  

         },
         "devices":[  
            {  
               "access":"rwm",
               "allow":false
            }
         ],
         "memory":{  
            "kernel":0,
            "swappiness":0,
            "limit":536870912,
            "swap":536870912,
            "kernelTCP":0,
            "reservation":536870912
         }
      }
   },
   "mounts":[  
      {  
         "source":"proc",
         "destination":"/proc",
         "type":"proc"
      },
      {  
         "source":"tmpfs",
         "destination":"/dev",
         "type":"tmpfs",
         "options":[  
            "nosuid",
            "strictatime",
            "mode=755",
            "size=65536k"
         ]
      },
      {  
         "source":"devpts",
         "destination":"/dev/pts",
         "type":"devpts",
         "options":[  
            "nosuid",
            "noexec",
            "newinstance",
            "ptmxmode=0666",
            "mode=0620",
            "gid=5"
         ]
      },
      {  
         "source":"shm",
         "destination":"/dev/shm",
         "type":"tmpfs",
         "options":[  
            "nosuid",
            "noexec",
            "nodev",
            "mode=1777",
            "size=65536k"
         ]
      },
      {  
         "source":"mqueue",
         "destination":"/dev/mqueue",
         "type":"mqueue",
         "options":[  
            "nosuid",
            "noexec",
            "nodev"
         ]
      },
      {  
         "source":"sysfs",
         "destination":"/sys",
         "type":"sysfs",
         "options":[  
            "nosuid",
            "noexec",
            "nodev",
            "ro"
         ]
      },
      {  
         "source":"cgroup",
         "destination":"/sys/fs/cgroup",
         "type":"cgroup",
         "options":[  
            "nosuid",
            "noexec",
            "nodev",
            "relatime",
            "ro"
         ]
      },
      {  
         "source":"/bin",
         "destination":"/bin",
         "type":"bind",
         "options":[  
            "rbind",
            "ro"
         ]
      },
      {  
         "source":"/sbin",
         "destination":"/sbin",
         "type":"bind",
         "options":[  
            "rbind",
            "ro"
         ]
      },
      {  
         "source":"/lib",
         "destination":"/lib",
         "type":"bind",
         "options":[  
            "rbind",
            "ro"
         ]
      },
      {  
         "source":"/lib64",
         "destination":"/lib64",
         "type":"bind",
         "options":[  
            "rbind",
            "ro"
         ]
      },
      {  
         "source":"/lib32",
         "destination":"/lib32",
         "type":"bind",
         "options":[  
            "rbind",
            "ro"
         ]
      },
      {  
         "source":"/usr",
         "destination":"/usr",
         "type":"bind",
         "options":[  
            "rbind",
            "ro"
         ]
      },
      {  
         "source":"/opt",
         "destination":"/opt",
         "type":"bind",
         "options":[  
            "rbind",
            "ro"
         ]
      },
      {  
         "source":"/etc",
         "destination":"/etc",
         "type":"bind",
         "options":[  
            "rbind",
            "ro"
         ]
      }
   ],
   "ociVersion":"1.0.0-rc1",
   "root":{  
      "path":"rootfs",
      "readonly":true
   }
}`

**Comment by ianpark** [comment]
I think this is because I run the python script using aa-exec (AppArmor). Let me check further. Thanks!

**Comment by cyphar** [comment]
Yeah, you need to make sure that `runc` has permissions to access the `--root` of runC's state directory. And then the actual container process needs to (initially) also have access to that file.
