### ISSUE TITLE
Using Runc as a go library?

### ISSUE THREAD

**Issue by sithembiso** [opencontainers/runc#134]
I notice that almost all functions within the main package are private. Is there any advice you can give for using Runc as a library inside another Go application?
If this isn't possible yet, should I repackage the core functions and make a pull request (in other words, is it in the project's interest to account for such use cases?)

**Comment by robinmonjo** [comment]
As far as I know, if you need a go library to create containers, you should use `libcontainer`, `runc` is meant to be an executable easy to orchestrate. Not sure if in the future docker will directly use `runc` or stick with `libcontainer`.
I guess `runc` can be seen as a reference on how to use `libcontainer`

**Comment by LK4D4** [comment]
@sithembiso yes, @robinmonjo is right, libcontainer is underlying library for runc and you can use it too. Thanks for your interest!
