### ISSUE TITLE
1.0.0-rc3 spec changed tty output while terminal = true

### ISSUE THREAD

**Issue by qiancai** [opencontainers/runc#1345]
The recent version of runc changed the tty output while terminal = true.

        "process": {
                "terminal": true,
                "args": [
                        "tty"
                ],

`# runc -v`
runc version 1.0.0-rc2
commit: 1f4dd3056f3b581046e2274808b07739357ac03b
spec: 1.0.0-rc3

`# runc run root`
/dev/pts/0

While earlier version gave something else.

`# runc -v`
runc version 1.0.0-rc2
spec: 1.0.0-rc2-dev

`# runc run root`
/dev/console

**Comment by qiancai** [comment]
This change-of-behaviours seems introduced by this commit.

commit 34f23cb99c30040e2ca82442eeb22d15a757f78d
Merge: 47ea5c7 b0fc85e
Author: Mrunal Patel <mrunal@me.com>
Date:   Wed Dec 7 14:37:19 2016 -0800

    Merge pull request #1018 from cyphar/console-rewrite
    
    Consoles, consoles, consoles.

**Comment by qiancai** [comment]
@mrunalp @cyphar

**Comment by hqhq** [comment]
This is expected, exactly what #1018 tried to fix.

**Comment by cyphar** [comment]
Yup. This is very much intended -- the old behaviour was badly broken (and in fact, `glibc` implemented some hacks to work around our bugs).
