### ISSUE TITLE
Unable to update kmem limit only

### ISSUE THREAD

**Issue by qiancai** [opencontainers/runc#1347]
Due to commit 11222ee1f18f2ca2847a126dbda9cf057dd85f78 , it is not possible update item limit if not specified a default value in the config in the first place.

`# runc update --kernel-memory 50331648 root`
failed to set memory.kmem.limit_in_bytes, because either tasks have already joined this cgroup or it has children

However, it is fine to update other memory limits even if did not specify default values in the config.json.

`# runc update --memory-reservation 50331648 root`
`# runc update --memory 50331648 root`
`# runc update --memory-swap 50331648 root`

@crosbymichael PTAL

**Comment by hqhq** [comment]
@qiancai Can you confirm if https://github.com/opencontainers/runc/pull/1350 is gonna fix this?

**Comment by qiancai** [comment]
Yes, it fixed the problem.
