### ISSUE TITLE
Leaked namespace and network interfaces if prestart hook fails

### ISSUE THREAD

**Issue by krisztian-kovacs-balabit** [opencontainers/runc#1352]
We've observed an issue where occasionally container startup fails with the following error:

```
docker[28335]: /usr/bin/docker: Error response from daemon: oci runtime error: process_linux.go:334: running prestart hook 0 caused "exit status 1: time=\"2017-01-27T11:04:33+01:00\" level=fatal msg=\"failed to add interface veth944fac0 to sandbox: failed to set link up: device or resource busy\" \n".
```

The containers are run via `docker run --net=ournetwork --ip=10.10.10.1 --ip6=fec0::a123:10:10:10:1 image-name`. We're running CoreOS 1235.1.0 with the following docker version:

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64
```

After the above failure, all subsequent docker run commands with the same IP address specified fail with the following error:

```
docker[28335]: /usr/bin/docker: Error response from daemon: oci runtime error: process_linux.go:334: running prestart hook 0 caused "exit status 1: time=\"2017-01-27T11:04:33+01:00\" level=fatal msg=\"failed to add interface veth944fac0 to sandbox: failed to set link up: device or resource busy\" \n".
```

We're using a custom network with the macvlan driver:

```
docker network inspect scb
[
    {
        "Name": "ournetwork",
        "Id": "55f89666fe515afb05927762eadad282f663ade59f34dd11fb0ffe2894428eb1",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.10.0.0/16",
                    "Gateway": "10.10.255.254"
                },
                {
                    "Subnet": "fec0:0:0:a123::/64"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "parent": "eth0"
        },
        "Labels": {}
    }
]
```

I've found some seemingly unused netns mounts in /var/run/docker/netns, and running `ip address show` in those unused network namespaces reveals that the namespace and a network interface in it with IP address 10.10.10.1 is leaked after each and every error where the prestart hook fails.

For example, in netns fc371b062ac8, running `ip address show` shows the following:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
10006: eth0@if2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default 
    link/ether 02:42:0a:6e:1e:1c brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.1/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fec0::a123:10:10:10:1/64 scope site nodad 
       valid_lft forever preferred_lft forever
```

Based on the code in initProcess.start(), I don't quite see how in case of prestart hook execution failure the network interfaces are supposed to be cleaned up -- however, based on my experience it never happens.

This effectively prevents us from starting the container after the first failure. (And what's worse, the IP address can be pinged even if the container is seemingly not running.)

**Comment by cyphar** [comment]
@krisztian-kovacs-balabit This sounds like a Docker bug (specifically `libnetwork`) because runC really has nothing to do with all of the network setup done inside `libnetwork`. `libnetwork` should be cleaning up after itself if the creation failed.

**Comment by krisztian-kovacs-balabit** [comment]
Ah, OK. It seems that docker is supposed to clean up the network namespace (via libnetwork) if starting up the container fails via containerd.

I'll open an issue for docker, then, because based on the code I fail to see what goes wrong in this case.

Thanks!
