### ISSUE TITLE
Handle GetClockTicks without cgo

### ISSUE THREAD

**Issue by dadgar** [opencontainers/runc#1379]
Hey,

It would be great if [the GetClockTicks code](https://github.com/opencontainers/runc/blob/master/libcontainer/system/sysconfig_notcgo.go#L5-L15) could be updated to use [gopsutil](https://github.com/shirou/gopsutil/blob/master/cpu/cpu_linux.go#L114) which doesn't use cgo except for Darwin.

**Comment by crosbymichael** [comment]
@dadgar Hi.  Is there a reason why cgo is an issue for you? What problems is it causing?

**Comment by dadgar** [comment]
Hey @crosbymichael,

It is not causing a problem but it would nice to be able to remove CGO since there already exist well tested portable solutions.

**Comment by crosbymichael** [comment]
A couple of the problems I see is that runc does not have to be cross platform portable, it runs on linux.  The other issue is that gopsutil us shelling out to a binary that is getting the clock ticks.  It would break portability by requiring that every linux system has to have `getconf` installed for that package to work.  

ref: https://github.com/shirou/gopsutil/blob/master/cpu/cpu_linux.go#L17

The other issue is that `cgo` provides a lot and we link to other C libs (libapparmor for security) in runc as well as our entire init `nsenter` is written in C.  

Is the issue you are having with runc or libcontainer?

**Comment by dadgar** [comment]
@crosbymichael Thanks for taking the time to look into this. That library will actually parse the /proc file system (https://github.com/shirou/gopsutil/blob/master/cpu/cpu_linux.go#L115).

I am using libcontainer as a library, specifically for cgroups, and am trying to minimize the usage of cgo. It is only used [here](https://github.com/opencontainers/runc/blob/52454cf90807727923b375afd7d84ac8fd523959/libcontainer/cgroups/fs/cpuacct.go#L22)  which is guarded to only build for linux. By using gopsutil to implement GetClockTicks, that cgo dependency should go away! 

My issue should have been more clear. I don't really care about the non-linux version of GetClockTicks but figured you can remove the whole build flagging around that method.

**Comment by crosbymichael** [comment]
From what I remember you cannot get the clock_ticks from cpuinfo and that is the only thing we care about in libcontainer.  You can only get it from the syscall and the way the lib is handling that is an `execve` in the `init()` of the package.

**Comment by dadgar** [comment]
Ah! Ticks vs MHz! Will close!
