### ISSUE TITLE
runc is throwing exception with symlinks

### ISSUE THREAD

**Issue by Nabarun** [opencontainers/runc#1389]
I am having runc 1.0.0-rc2 version. I am seeing issues where the rootfs is a symlink. Is there any discussion or bug around this?

$ /usr/local/sbin/runc run --no-new-keyring -b ./ 2323432
<parent folder path>/rootfs1 is not an absolute path or is a symlink

$ ls -l <parent folder path>
total 8
-rwxr-xr-x 1 abc abc 2616 Mar 22 21:29 config.json
drwxr-xr-x 13 abc abc 4096 Mar 22 23:31 rootfs
lrwxrwxrwx 1 abc abc 58 Mar 23 00:25 rootfs1 -> <parent folder path>/rootfs/

**Comment by cyphar** [comment]
This is by design, IIRC because of some interactions between mounting and symlinks.

**Comment by Nabarun** [comment]
Ah thanks for the clarification
