### ISSUE TITLE
runc run fails with "mkdir /run/runc: permission denied"

### ISSUE THREAD

**Issue by jwendell** [opencontainers/runc#1413]
I followed the instructions found on README.md:

1. Create the filesystem: `docker export $(docker create busybox) | tar -C rootfs -xvf -`
2. Create the config: `runc spec`
3. Run the image: `runc run mycontainerid`

Got the error: `mkdir /run/runc: permission denied`

Am I missing something?

**Comment by jwendell** [comment]
hmm, it seems runc must be executed as root. If that's the case, I think it's worth to mention it on README, right?

**Comment by cyphar** [comment]
@jwendell It used to be the case that runc could only be run as root. Recently (#774) runc can now be run as an unprivileged user. Though you're right that the README probably should be cleaned up significantly (the shell examples aren't very pretty).
