### ISSUE TITLE
Remove jenkins CI

### ISSUE THREAD

**Issue by crosbymichael** [opencontainers/runc#1427]
Just to double check, I believe we have travis running the full test suite for runc now, including all the integration tests.  

If someone else can confirm we can remove `janky`(jenkins) as its just redundant and not needed anymore.

**Comment by dqminh** [comment]
Yah i think we can remove janky. I have never seen cases where janky reveals false positive, but it failed pretty often.

**Comment by crosbymichael** [comment]
@dqminh thanks for confirming.  I went ahead and removed it.
