### ISSUE TITLE
regex for checking id 

### ISSUE THREAD

**Issue by harche** [opencontainers/runc#1429]
The regex for validating the container id, https://github.com/opencontainers/runc/blob/master/libcontainer/factory_linux.go#L31 lets anyone specify an unlimited string length for an id. 

For all practical purposes id of 64 characters is more than sufficient (which is what docker daemon generates too, e.g. `8b72c0494d86930f8eb5c2f972b75813e225bceb3d3f9c7713be1977b8031456`). Should we have a tighter regex to enforce that? Or having unrestricted string length is ok for id string?

IMO, it should be replaced with something like, 
`
^[\w+-\.]{1,64}$
`

Any thoughts?

**Comment by cyphar** [comment]
I'm not sure why we would intentionally limit the length of container IDs, it's not something that makes much sense to me. Practically speaking there is a limit to the length of the container ID (since we store state information in a directory, the maximum file name length on the filesystem is a factor) but I don't see why we should artificially limit something.

Is there a security or other argument for this?

**Comment by harche** [comment]
@cyphar I wrote that from the security point of view only. At this point, I don't know if it opens any security related issue, but having something defined of arbitrary length and completely unbounded makes me little uncomfortable. But again, I could be just overthinking about it.

**Comment by harche** [comment]
@cyphar In fact you do check for legth of id,
https://github.com/opencontainers/runc/blob/master/libcontainer/factory_linux.go#L333

Then why not to handle it in regex itself instead of doing if else later on?

**Comment by harche** [comment]
So in go version `1.7.4` that I am using `^[\w+-\.]{1,1000}$` is valid but `^[\w+-\.]{1,1024}$` is not. So it limits the characters to 1000, not 1024. But if we do this, we can avoid one `if else` at https://github.com/opencontainers/runc/blob/master/libcontainer/factory_linux.go#L333

**Comment by harche** [comment]
So in go version `1.7.4` that I am using `^[\w+-\.]{1,1000}$` is valid but `^[\w+-\.]{1,1024}$` is not. So it limits the characters to 1000, not 1024.

But if we do this, we can avoid one if else at https://github.com/opencontainers/runc/blob/master/libcontainer/factory_linux.go#L333

**Comment by cyphar** [comment]
@harche Apparently we switched away from regex [in the past](https://github.com/opencontainers/runc/commit/de57f78590cefdf08249118e2d710908cc81b16a). I'm not entirely sure why we are limiting the length though -- @mrunalp?

> At this point, I don't know if it opens any security related issue, but having something defined of arbitrary length and completely unbounded makes me little uncomfortable.

... why? I mean, I definitely take security seriously (having found several past vulnerabilities) but "the name of a container could in theory be very long" seems far fetched to me from the security angle. IDs aren't used outside of state management which is all done in Go (so no C code handling arbitrary length strings). Not to mention that (as I mentioned) it *is* bounded by the filesystem (and also the `cmdline` length which is a separate thing).

**Comment by harche** [comment]
@cyphar I don't buy an argument that it's fine because it's bounded by the filesystem. 

I know that the limitations from the underlying filesystem will make it bounded, but when we can make the behavior absolutely predictable rather than relying on 3rd party component (filesystem in this case) then we should do our part and close the doors within `runc` itself.

**Comment by cyphar** [comment]
@harche 

> I don't buy an argument that it's fine because it's bounded by the filesystem.

My argument is that it doesn't matter if it's unbounded because I don't see how it could lead to a security issue. But I'm *also* saying that *in practice* it will be bounded.

**Comment by crosbymichael** [comment]
I'm not sure why we would want to limit this.  Maybe @justincormack has any ideas about the security side of this.

**Comment by harche** [comment]
I will like to keep this issue open until we know why we are checking for length. @mrunalp

**Comment by mrunalp** [comment]
I don't think that we should have any restrictions on the ID length. That particular commit was more about fixing what we already had.
