### ISSUE TITLE
runc:[2:INIT] processes not progressing when calling runc exec

### ISSUE THREAD

**Issue by williammartin** [opencontainers/runc#1432]
We are occasionally seeing failures to proceed when calling `runc exec`. For us this manifests as a zombie `runc:[1:CHILD]` process with sibling `runc[2:INIT]` process never progressing to `exec` the user process. Additionally, attempts to read `/proc/<pid>/cmdline` hang forever, so `ps aux` is out of the question. 

When running `ps -e --forest` we see a process tree like:

```
2526643 ?        00:00:00      \_ dadoo
2526650 ?        00:00:00      |   \_ runc
2526668 ?        00:00:00      |       \_ runc:[1:CHILD] <defunct>
2526669 ?        03:59:18      |       \_ runc:[2:INIT]
```

For anyone unfamiliar with Garden, `dadoo` is a process that calls `runc exec`. The expected behaviour here (that occurs nearly 100% of the time) is that `runc exec` exits, `runc:[2:INIT]` execs the user process and `dadoo` acts as a subreaper, parenting the user process. In the detach case, `runc exec` does not act as a subreaper.

On one machine that was exhibiting these issues, we noticed extremely frequent OOM events. These may or may not be related. Additionally, when running `cat /proc/<pid>/stack` on the hanging INIT process, we saw the stack trace oscillate between no function calls and attempting to shrink slabs with references to memory cgroups. Unfortunately I do not have the trace now but it roughly contained:

```
shrink_slab.40
shrink_zone
...
mem_cgroup_try_charge
...
```

and oscillated to the empty trace:

```
[<ffffffffffffffff>] 0xffffffffffffffff
```

Hopefully the above snippet will mean something to someone.

`kill -9` on the `runc:[2:INIT]` process cleans everything up.

Since this started occurring between versions of Garden that included a runc bump, we can track the commits that might have introduced this change to:

```
1b4de2a Merge remote-tracking branch 'williammartin/1269-initial-console-sizing'
c50d024 Merge pull request #1280 from datawolf/user
770e37f Merge pull request #1350 from hqhq/fix_kmem_accouting
fe898e7 Fix kmem accouting when use with cgroupsPath
cf883a8 Merge pull request #1340 from dqminh/vndr-take2
899b074 Merge pull request #1308 from giuseppe/fix-systemd-notify
707dd48 Merge pull request #1001 from x1022as/predump
17966ce Merge pull request #1320 from ijc25/preserve-fds
1f4dd30 Merge pull request #1342 from sak0/dev
912d20c mention vndr in README
993cbf9 move from Godeps to vndr
02141ce merge branch 'pr-1317'
5f1afec small cleanup for `runc ps` man pages
d5026f0 signals: support detach and notify socket together
c8593c4 sanitize systemd-notify message
892f2de fix systemd-notify when using a different PID namespace
bd2f9c5 Merge pull request #1339 from cpuguy83/dont_override_errors
7335635 Fix state when _LIBCONTAINER in environment
805b8c7 Do not create exec fifo in factory.Create
d193f95 Don't override system error
3293874 Merge pull request #1332 from sak0/dev
08937e9 ps: --format value check
3d7cd1f merge branch 'pr-1335'
8438b26 Merge pull request #1237 from hqhq/fix_sync_race
6ccc209 Merge pull request #1336 from crosbymichael/size_t
4a164a8 Use %zu for printing of size_t values
e773f96 update go version at travis-ci
f5adb05 Add --preserve-fds=N to create and run
a54316b Fix race condition when sync with child and grandchild
6b1d0e7 Merge pull request #1127 from boynux/fix-set-mem-to-unlimited
b433dea Merge pull request #1328 from sak0/dev
f6524df fix typo
18ebc51 Reset Swap when memory is set to unlimited (-1)
98f0041 add pre-dump and parent-path to checkpoint
4f21aea Merge pull request #1321 from Mashimiao/support-device-new-type
06e2747 support create device with type p and u
e944298 Merge pull request #1316 from hqhq/cleanup_dest
a8d7eb7 Merge pull request #1314 from runcom/overlay-mounts
45a8341 Small cleanup
ca14e7b libcontainer: rootfs_linux: support overlayfs
b3f43f4 Set initial console size based on process spec
dde4b1a user: fix the parameter error
```

The only commit in here that isn't in `runc master` is `b3f43f4` which can be found as PR here: https://github.com/opencontainers/runc/pull/1275

Though very tenuous, since `runc:[2:INIT]` stack trace occasionally contains memory cgroup related entries, https://github.com/opencontainers/runc/pull/1127 and https://github.com/opencontainers/runc/pull/1350 seemed of note.

It *is* possible that there is something outside of `runc` that introduced this change (we've not seen this outside of a production environment, and haven't been able to isolate runc) but it feels like `runc` should not be behaving this way nonetheless.

Additionally, it feels sort of strange to me that when `runc exec` doesn't act as a subreaper, we need to wait for it to die before `runc:[1:CHILD]` processes get cleaned. Not sure if there is a good solution for this, just felt a little unusual to me.

**Comment by crosbymichael** [comment]
@williammartin are you setting `runc exec --no-subreaper`?

**Comment by crosbymichael** [comment]
Oh wait, we disabled that by default on `exec`

**Comment by williammartin** [comment]
Yep, disabled by default as you say.

**Comment by gfiedler** [comment]
I have a similar problem with `runc create`:

    # runc -v
    runc version 1.0.0-rc3
    commit: 75f8da7c889acc4509a0cf6f0d3a8f9584778375
    spec: 1.0.0-rc5
    # runc create --bundle /opt/apps/bundles/A A
    # runc list
    ID          PID         STATUS      BUNDLE                CREATED
    A           2183        created     /opt/apps/bundles/A   2017-08-16T14:59:51.247351794Z
    # ps -e --forest
       PID TTY          TIME CMD
        86 pts/3    00:00:00 bash
       139 pts/3    00:00:00  \_ journalctl
      2236 pts/3    00:00:00  \_ ps
         1 ?        00:00:00 systemd
        15 ?        00:00:00 systemd-journal
        63 ?        00:00:00 dhclient
        78 ?        00:00:00 sshd
        80 pts/2    00:00:00 agetty
        81 pts/3    00:00:00 agetty
        82 pts/0    00:00:00 agetty
        83 pts/1    00:00:00 agetty
        84 pts/2    00:00:00 agetty
      2183 ?        00:00:00 runc:[2:INIT]

A `runc` process is hanging in `open()`:

    # strace -p 2183    
    strace: Process 2183 attached
    openat(4, "exec.fifo", O_WRONLY|O_CLOEXEC

When `runc create`is wrapped inside `systemd-run`:

    # systemd-run runc create --bundle /opt/apps/bundles/A B
    # runc list
    ID          PID         STATUS      BUNDLE                CREATED
    A           2183        created     /opt/apps/bundles/A   2017-08-16T14:59:51.247351794Z
    B           0           stopped     /opt/apps/bundles/A   2017-08-16T15:13:21.264041641Z

... the container state is `stopped`.

Host OS is Debian 9 running as LXC container.

**Comment by williammartin** [comment]
@gfiedler For the most part (everything before systemd), I believe that is the expected state after `runc create`. `runc create/start` are analogous to `runc run`. 

```
openat(4, "exec.fifo", O_WRONLY|O_CLOEXEC
```

`4`, represents fd 4, the file named "exec.fifo". This is a pipe that is opened to signal `runc init (runc:[2:INIT]` to exec into the "user process" 

https://github.com/opencontainers/runc/blob/master/libcontainer/standard_init_linux.go#L184
https://github.com/opencontainers/runc/blob/master/libcontainer/standard_init_linux.go#L167-L169

So for your container `A`, I suggest you call `runc run` to make it progress. I'm not familiar with systemd but it looks like a separate issue.

**Comment by cyphar** [comment]
@gfiedler That is working by design. `runc create` creates a container but does not start it, you need to call `runc start` to signal the container process to actually start (the process you see blocking on `exec.fifo` is doing that intentionally right before the final `execve`).

**Comment by cyphar** [comment]
@williammartin Have you checked whether #1506 might have fixed this issue? Did you end up getting more information on this bug in the meantime?

**Comment by gfiedler** [comment]
@williammartin @cyphar Thank you! `runc run` worked as expected:

    # runc run --detach --bundle /opt/apps/bundles/A A
    # systemd-run runc run --detach --bundle /opt/apps/bundles/A B
    # runc list
    ID          PID         STATUS      BUNDLE                CREATED
    A           1033        running     /opt/apps/bundles/A   2017-08-16T17:20:28.347399079Z
    B           1081        running     /opt/apps/bundles/A   2017-08-16T17:20:58.252714066Z

I doesn't expect the state `stopped` after running `systemd-run runc create`. Is this conform to the [lifecycle definition of the runtime spec](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#create)? But maybe this is another issue.

**Comment by cyphar** [comment]
@gfiedler 

>  doesn't expect the state stopped after running systemd-run runc create. Is this conform to the lifecycle definition of the runtime spec? But maybe this is another issue.

It looks like the container actually had died at that point (the `PID` field is empty). Given that you were using `runc create` rather than `runc create --detach` I would check the error logs to see if runc had some error message.

**Comment by williammartin** [comment]
@cyphar Not sure sorry, we were only seeing this on a production environment and we built a workaround in the layer above to be resilient which effectively hides this issue. 

We could probably close this out as it's not directly an issue for us anymore if you want to do some issue housekeeping. I suspect there was something environmentally like the OOMs that was causing a lower level issue, but I don't forsee us getting anymore useful info on this.

**Comment by cyphar** [comment]
Alright. In which case I'm going to close this for housekeeping reasons. If you find any more information feel free to re-open this or create a new issue. Thanks @williammartin.
