### ISSUE TITLE
"mkdir /run/runc/<container name>: permission denied" for rootless container

### ISSUE THREAD

**Issue by piersharding** [opencontainers/runc#1441]
Hi -
When trying to run a rootless container with runc I get the following error:
mkdir /run/runc/test-pscap: permission denied

Which is correct as running ls -ld /run/runc shows:
`drwxr-xr-x 2 root runc 40 May 10 06:57 /run/runc`

I can fix the situation by creating a specific group and membership with:
```
sudo mkdir -p /run/runc
sudo addgroup runc
sudo chown root:runc /run/runc
sudo chmod g+rwx /run/runc
sudo adduser $(id -u -n) runc
```
Is there something obvious I'm doing wrong here?

```
piers@dragon:~/code/docker$ runc --version
runc version 1.0.0-rc3
commit: 2daa11574b12d2dd7f6dad3ffaa302871f21bd12
spec: 1.0.0-rc5
piers@dragon:~/code/docker$ uname -a
Linux dragon.local.net 4.10.0-21-generic #23-Ubuntu SMP Fri Apr 28 16:14:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
# Ubuntu 17.04
```

Thanks,
Piers.

**Comment by teddyking** [comment]
Rather than creating new groups and setting permissions etc. you could instead pass the `--root` flag to runc. There's a section in the README about running rootless containers with some more info about it: https://github.com/opencontainers/runc#rootless-containers.

**Comment by piersharding** [comment]
Hi @teddyking -
thanks for pointing this out, I missed that feature.
While this solves the immediate problem of access to the container runtime state,  I guess I was looking (hoping) for a more generic solution similar to the permissions hack I did (something multiple users in a shared environment would not need to think about).  As a bit of background, I'm researching alternatives to http://singularity.lbl.gov/, and runC rootless seems like a very promising direction.
Thanks,
Piers.

**Comment by cyphar** [comment]
@piersharding 

> I guess I was looking (hoping) for a more generic solution similar to the permissions hack I did (something multiple users in a shared environment would not need to think about)

You could create a state directory in `/tmp` and set up sticky bits and the whole thing to make this work. The reason the state directories aren't world-writeable in the "default install" is because of security concerns (`runc` is run as root in most cases and I would be concerned about tricking `runc` into messing around with non-container processes).

> As a bit of background, I'm researching alternatives to http://singularity.lbl.gov/, and runC rootless seems like a very promising direction.

As an aside, it would really be nice if people stopped using singularity (it is trivially insecure and uses poorly audited `setuid` binaries to set everything up). I'm also fairly sure they use `chroot` rather than `pivot_root` and mount namespaces (which is bad).

**Comment by cyphar** [comment]
You could just get users to do `--root $HOME/.runc` or something like that, which would just "transparently" work.

**Comment by piersharding** [comment]
Hi @cyphar -
Thanks for the idea about ${HOME}/.runc - that would work nicely.

You are right about Singularity and chroot() - https://github.com/singularityware/singularity/blob/master/src/lib/rootfs/rootfs.c#L252 and with respect to mount namespaces I think this is what you mean - https://github.com/singularityware/singularity/blob/master/src/lib/ns/mnt/mnt.c#L46 .

I think that in order to replace Singularity, there needs to be a viable alternative that deals with the HPC use case (the niche that Singularity is going after) that does enable HPC cluster shell access to researchers with reasonable security guarantees for the admins that have to look after it, and that also trivially integrates with common requirements like integration with OpenMPI and Slurm.
Why Singularity was not based on runC, I don't understand - it seems like it would have all the upside of the Docker eco-system to draw on, and none of the down side of having to reinvent a lot of these things again (or maintain them).

Once again, thanks for your help.
Cheers,
Piers Harding.

**Comment by cyphar** [comment]
I mean they have a function called `singularity_priv_escalate`... What the hell.

**Comment by AkihiroSuda** [comment]
Should have been fixed on recent version
