### ISSUE TITLE
can't get this lib in windows machine

### ISSUE THREAD

**Issue by jiang1095** [opencontainers/runc#1458]
When I run `go get github.com/opencontainers/runc` in windows machine, It got error below:
```
# github.com/opencontainers/runc/libcontainer
github.com\opencontainers\runc\libcontainer\console_windows.go:5: cannot use windowsConsole literal (type *windowsConsole) as type Console in return argument:
        *windowsConsole does not implement Console (missing File method)
```

**Comment by cyphar** [comment]
runc only implements GNU/Linux containers. Honestly we should just delete all of the `_windows` code because we aren't ever going to support non-Linux platforms.
