### ISSUE TITLE
Unable to use setuidgid inside runc container

### ISSUE THREAD

**Issue by robinmonjo** [opencontainers/runc#146]
I can't run `setuidgid` inside a `runc` container. Here are the steps to reproduce:

* Pull an image with setuidgid and bash installed
* Use this config:

````json
{
	"version": "pre-draft",
	"platform": {
		"os": "linux",
		"arch": "amd64"
	},
	"process": {
		"terminal": true,
		"user": {
			"uid": 0,
			"gid": 0,
			"additionalGids": null
		},
		"args": [
			"bash"
		],
		"env": [
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"TERM=xterm"
		],
		"cwd": ""
	},
	"root": {
		"path": ".",
		"readonly": false
	},
	"hostname": "shell",
	"mounts": [
		{
			"type": "proc",
			"source": "proc",
			"destination": "/proc",
			"options": ""
		},
		{
			"type": "tmpfs",
			"source": "tmpfs",
			"destination": "/dev",
			"options": "nosuid,strictatime,mode=755,size=65536k"
		},
		{
			"type": "devpts",
			"source": "devpts",
			"destination": "/dev/pts",
			"options": "nosuid,noexec,newinstance,ptmxmode=0666,mode=0620,gid=5"
		},
		{
			"type": "tmpfs",
			"source": "shm",
			"destination": "/dev/shm",
			"options": "nosuid,noexec,nodev,mode=1777,size=65536k"
		},
		{
			"type": "mqueue",
			"source": "mqueue",
			"destination": "/dev/mqueue",
			"options": "nosuid,noexec,nodev"
		},
		{
			"type": "sysfs",
			"source": "sysfs",
			"destination": "/sys",
			"options": "nosuid,noexec,nodev"
		},
		{
			"type": "cgroup",
			"source": "cgroup",
			"destination": "/sys/fs/cgroup",
			"options": "nosuid,noexec,nodev,relatime,ro"
		}
	],
	"linux": {
		"uidMappings": null,
		"gidMappings": null,
		"rlimits": null,
		"sysctl": null,
		"resources": {
			"disableOOMKiller": false,
			"memory": {
				"limit": 0,
				"reservation": 0,
				"swap": 0,
				"kernel": 0,
				"swappiness": -1
			},
			"cpu": {
				"shares": 0,
				"quota": 0,
				"period": 0,
				"realtimeRuntime": 0,
				"realtimePeriod": 0,
				"cpus": "",
				"mems": ""
			},
			"blockIO": {
				"blkioWeight": 0,
				"blkioWeightDevice": "",
				"blkioThrottleReadBpsDevice": "",
				"blkioThrottleWriteBpsDevice": "",
				"blkioThrottleReadIopsDevice": "",
				"blkioThrottleWriteIopsDevice": ""
			},
			"hugepageLimits": null,
			"network": {
				"classId": "",
				"priorities": null
			}
		},
		"namespaces": [
			{
				"type": "process",
				"path": ""
			},
			{
				"type": "network",
				"path": ""
			},
			{
				"type": "ipc",
				"path": ""
			},
			{
				"type": "uts",
				"path": ""
			},
			{
				"type": "mount",
				"path": ""
			}
		],
		"capabilities": [
			"CHOWN",
			"DAC_OVERRIDE",
			"FSETID",
			"FOWNER",
			"MKNOD",
			"NET_RAW",
			"SETGID",
			"SETUID",
			"SETFCAP",
			"SETPCAP",
			"NET_BIND_SERVICE",
			"SYS_CHROOT",
			"KILL",
			"AUDIT_WRITE"
		],
		"devices": [
			"null",
			"random",
			"full",
			"tty",
			"zero",
			"urandom"
		]
	}
}
````

* start `runc` this will start bash as root
* create a group: `addgroup --quiet --gid 7999 u7999`
* add the user:

````bash
adduser --shell /bin/bash --disabled-password --force-badname --no-create-home --uid 7999 --gid 7999 --gecos '' --quiet  u7999
````

* start bash as the new user: `setuidgid u7999 /bin/bash`

This will output the error: `setuidgid: fatal: unable to run /bin/bash: access denied`

This is working with docker but not with `runc`. I have had a look a the [default libcontainer config of docker](https://github.com/docker/docker/blob/master/daemon/execdriver/native/template/default_template.go), and it looks similar to the config I'm using here.

**Comment by rajasec** [comment]
With full capabilities in config.json, I'm able to do the setuidgid
setuidgid u7999 /bin/bash
bash: /root/.bashrc: Permission denied ---> 
u7999@shell:~$ pwd
/root

I've added the full capabilities for testing purpose
                      "AUDIT_WRITE",
                        "KILL",
                        "SETPCAP",
                        "SYS_MODULE",
                        "SYS_RAWIO",
                        "SYS_PACCT",
                        "SYS_ADMIN",
                        "SYS_NICE",
                        "SYS_RESOURCE",
                        "SYS_TIME",
                        "SYS_TTY_CONFIG",
                        "MKNOD",
                        "AUDIT_CONTROL",
                        "MAC_OVERRIDE",
                        "MAC_ADMIN",
                        "NET_ADMIN",
                        "SYSLOG",
                        "CHOWN",
                        "NET_RAW",
                        "DAC_OVERRIDE",
                        "FOWNER",
                        "DAC_READ_SEARCH",
                        "FSETID",
                        "SETGID",
                        "SETUID",
                        "LINUX_IMMUTABLE",
                        "NET_BIND_SERVICE",
                        "NET_BROADCAST",
                        "IPC_LOCK",
                        "IPC_OWNER",
                        "SYS_CHROOT"

**Comment by robinmonjo** [comment]
Thank you for your answer, turned out I was using `runc` on a rootfs that was mounted with overlay, and my mount was badly configured.
