### ISSUE TITLE
json: cannot unmarshal number -1 into Go value of type uint64

### ISSUE THREAD

**Issue by xiajohnnyxia** [opencontainers/runc#1465]
/runc/vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go 

       func (l *LinuxFactory) loadState(root, id string) (*State, error)
                      
                       json.NewDecoder(f).Decode(&state)

In this type : State.BaseState.Config.Cgroups.Resources,there are serval unit64 type field . And their json value is number.
How can i fix this error?

```

            "memory": 0,
            "memory_reservation": 0,
            "memory_swap": 0,
            "kernel_memory": 0,
            "kernel_memory_tcp": 0,
            "cpu_shares": 0,
            "cpu_quota": 0,
            "cpu_period": 0,
            "cpu_rt_quota": 0,
            "cpu_rt_period": 0,
            "cpuset_cpus": "",
            "cpuset_mems": "",
```

```
// Memory limit (in bytes)
	Memory uint64 `json:"memory"`

	// Memory reservation or soft_limit (in bytes)
	MemoryReservation uint64 `json:"memory_reservation"`

	// Total memory usage (memory + swap); set `-1` to enable unlimited swap
	MemorySwap uint64 `json:"memory_swap"`

	// Kernel memory limit (in bytes)
	KernelMemory uint64 `json:"kernel_memory"`

	// Kernel memory limit for TCP use (in bytes)
	KernelMemoryTCP uint64 `json:"kernel_memory_tcp"`

	// CPU shares (relative weight vs. other containers)
	CpuShares uint64 `json:"cpu_shares"`

	// CPU hardcap limit (in usecs). Allowed cpu time in a given period.
	CpuQuota int64 `json:"cpu_quota"`

	// CPU period to be used for hardcapping (in usecs). 0 to use system default.
	CpuPeriod uint64 `json:"cpu_period"`

	// How many time CPU will use in realtime scheduling (in usecs).
	CpuRtRuntime int64 `json:"cpu_rt_quota"`

	// CPU period to be used for realtime scheduling (in usecs).
	CpuRtPeriod uint64 `json:"cpu_rt_period"`
```

**Comment by justincormack** [comment]
Yes that looks like a bug in the types, they should be `int64` not `uint64`. Reserving over 2^63 bytes of memory is meaningless anyway.

**Comment by justincormack** [comment]
Can you open the issue on https://github.com/opencontainers/runtime-spec as that is where the specification is set.

**Comment by xiajohnnyxia** [comment]
ok, i just see you commented.i will do this.

**Comment by xiajohnnyxia** [comment]
Have anyway to let it transform to `uint64`?It is cited in much places.

**Comment by cyphar** [comment]
@justincormack It's because they have the wrong version of `config.json` for their version of `runc`. We changed this recently IIRC.

**Comment by xiajohnnyxia** [comment]
My docker's version is "17.03.1-ce, build c6d412e".And the runc what i used is the latest source code.

**Comment by cyphar** [comment]
@xiajohnnyxia There's your problem. Docker requires very specific versions of runc (you'll have to check the source code to figure out what git commit you need). If your distribution has packages for Docker, please just use them.

**Comment by xiajohnnyxia** [comment]
@cyphar How can i find the corresponding version of runc.Which file record that.

**Comment by cyphar** [comment]
They change it quite often, but for `v17.03` you can see it in [this file](https://github.com/moby/moby/blob/v17.03.0-ce/hack/dockerfile/binaries-commits#L6).

**Comment by xiajohnnyxia** [comment]
@cyphar How to decrypt?

**Comment by xiajohnnyxia** [comment]
@cyphar why is the `*string` will appear` invalid operation: d.Type != nil (mismatched types string and nil)` or 
`invalid indirect of d.Type (type string)`.

**Comment by cyphar** [comment]
I don't understand your question.

**Comment by xiajohnnyxia** [comment]
I find the official version version.And it's int64.Thank you.
