### ISSUE TITLE
USER namespaces aren't enabled in the kernel

### ISSUE THREAD

**Issue by vinnitu** [opencontainers/runc#1472]
```
$ runc --root $(pwd) run one
USER namespaces aren't enabled in the kernel
```

**Comment by williammartin** [comment]
Hi @vinnitu,

This error comes from https://github.com/opencontainers/runc/blob/13a8c5d140b66e2c6372a70bd513a85584a33ffb/libcontainer/configs/validate/validator.go#L105

Is there some reason to think that you are receiving this message incorrectly? What kernel version do you have?

**Comment by marcosps** [comment]
@vinnitu you can also run https://raw.githubusercontent.com/opencontainers/runc/master/script/check-config.sh and check if the user namespace is disabled. If the userns is in fact disabled, you should try a different kernel, or maybe enable it if your distribution allows it.

**Comment by marcosps** [comment]
The line correspondent to user namespace is CONFIG_USER_NS, so check this line in the output of the script.
