### ISSUE TITLE
runc: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zenabamin** [opencontainers/runc#1486]
what to do??

**Comment by cyphar** [comment]
Options:

a) Recompile `runc` with apparmor disabled.
b) Install the apparmor library.
c) Use a statically compiled binary (like the ones we publish).

If you got the binary from a distribution, that distribution aren't handling dependencies properly so open a bug in their bug tracker.

**Comment by zenabamin** [comment]
how to  Recompile runc with apparmor disabled????

b) Install the apparmor library.
c) Use a statically compiled binary (like the ones we publish).

**Comment by cyphar** [comment]
Get the source code, run `make`. You need to have a Go development environment set up.

**Comment by zenabamin** [comment]
Error: while executing make test


 PASS
ok      github.com/opencontainers/runc/libcontainer/xattr       0.016s
Makefile:91: recipe for target 'localunittest' failed
make: *** [localunittest] Error 1
make[1]: *** [unittest] Error 2
make[1]: Leaving directory `/root/go/src/github.com/opencontainers/runc'
make: *** [test] Error 2

**Comment by AkihiroSuda** [comment]
https://github.com/opencontainers/runc/pull/1675 dropped the dependency
