### ISSUE TITLE
Error: while executing make test  PASS ok github.com/opencontainers/runc/libcontainer/xattr 0.016s Makefile:91: recipe for target 'localunittest' failed make: *** [localunittest] Error 1 make[1]: *** [unittest] Error 2 make[1]: Leaving directory `/root/go/src/github.com/opencontainers/runc' make: *** [test] Error 2

### ISSUE THREAD

**Issue by zenabamin** [opencontainers/runc#1487]
Error: while executing make test

PASS
ok github.com/opencontainers/runc/libcontainer/xattr 0.016s
Makefile:91: recipe for target 'localunittest' failed
make: *** [localunittest] Error 1
make[1]: *** [unittest] Error 2
make[1]: Leaving directory `/root/go/src/github.com/opencontainers/runc'
make: *** [test] Error 2

**Comment by cyphar** [comment]
There's no need to open a new issue each time you create a comment on #1486. Closing.
