### ISSUE TITLE
Missing SPEC

### ISSUE THREAD

**Issue by lgs** [opencontainers/runc#15]
In your [OPEN CONTAINER PROJECT](http://www.opencontainers.org/) homepage, you say:

<pre>The specification will be available at https://github.com/opencontainers/specs.</pre>

but that is still missing.

**Comment by wking** [comment]
On Tue, Jun 23, 2015 at 02:14:49AM -0700, Luca G. Soave wrote:
> In your [OPEN CONTAINER PROJECT](http://www.opencontainers.org/)
> homepage, you say:
> 
> <pre>The specification will be available at
> https://github.com/opencontainers/specs.</pre>
> 
> but that is missing.

The rest of that paragraph is:

  The newly expanded team of maintainers … are busy preparing the
  first draft of the specification, and intend to release it in 2-3
  weeks.

So I'd expect the repo is already there and will become public by
mid-July.  Until then, I'd guess some union of [1,2] isn't *too* far
from what it will look like.

[1]: https://github.com/appc/spec
[2]: https://github.com/opencontainers/runc/blob/master/libcontainer/SPEC.md

**Comment by estesp** [comment]
As @wking notes, the work is underway to prepare a draft specification, but based on the working group meeting today, it was decided to expose the repo immediately.  I think this issue can be closed now as the specs repo is public as of this afternoon.

**Comment by rjnagal** [comment]
spec is public now, closing.
