### ISSUE TITLE
Unable to find/checkout commit 2d41c04

### ISSUE THREAD

**Issue by flaccid** [opencontainers/runc#1503]
Not sure if this is pebkac or something is foo'd.

This particular commit https://github.com/opencontainers/runc/commit/2d41c047c83e09a6d61d464906feb2a2f3c52aa4.

```
$ git clone https://github.com/opencontainers/runc.git
Cloning into 'runc'...
remote: Counting objects: 16398, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 16398 (delta 2), reused 6 (delta 1), pack-reused 16389
Receiving objects: 100% (16398/16398), 5.18 MiB | 305.00 KiB/s, done.
Resolving deltas: 100% (10537/10537), done.
$ cd runc
$ git checkout 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
fatal: reference is not a tree: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
$ git branch --contains 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
error: no such commit 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
```

Need this to work for building using https://github.com/moby/moby/commit/a5e83836a49547b2add871bb52cbd8bfedb57114#diff-705886959f75f158a6230aaa994d6d2cR6.

**Comment by crosbymichael** [comment]
@flaccid Its probably in this repo for the moby build

https://github.com/docker/runc

**Comment by cyphar** [comment]
Yeah, it's in the `docker/runc` repo: https://github.com/docker/runc/commit/2d41c047c83e09a6d61d464906feb2a2f3c52aa4.

**Comment by flaccid** [comment]
Hmm how come I can see it on GitHub with the link.  https://github.com/opencontainers/runc/commit/2d41c047c83e09a6d61d464906feb2a2f3c52aa4  ? *Perplexed*

**Comment by cyphar** [comment]
I think GitHub might allow links like that to cross into forks. It's definitely not in this repo.

**Comment by flaccid** [comment]
Will close out. A request though - for these cherry pick commits be nice to also list the current repo home for each somewhere (or did I miss that?).

**Comment by cyphar** [comment]
@flaccid The Docker source code mentions the repository, if that's what you mean (it used to be more clear):

```
% grep 'github.com.*runc' hack/dockerfile/install-binaries.sh
        git clone https://github.com/docker/runc.git "$GOPATH/src/github.com/opencontainers/runc"
        cd "$GOPATH/src/github.com/opencontainers/runc"
```

If you're talking about referencing where a commit comes from, you would have to ask @crosbymichael about how they handle cherry-picks (personally when I backport patches for openSUSE I modify the descriptions heavily to add references to upstream).

**Comment by flaccid** [comment]
Kind of, but to package, need it in shell env or something sourceable like that.
Its done for cli here https://github.com/moby/moby/blob/master/hack/dockerfile/binaries-commits#L13-L14 - perhaps we should be employing this for each repo e.g. runc?

**Comment by cyphar** [comment]
That is done in the same file you linked (https://github.com/moby/moby/blob/master/hack/dockerfile/binaries-commits#L6).

I will give you a friendly warning, as someone who helps package [Docker for openSUSE](https://build.opensuse.org/package/show/Virtualization:containers/docker), you're **really** not going to have a fun time if you want to create packages for Docker. We've had a **lot** of issues in getting our packages to work.

**Comment by flaccid** [comment]
The repo source not the commit..

I think I am doing fine 😎 https://aur.archlinux.org/packages/docker-git/
