### ISSUE TITLE
Make is failed

### ISSUE THREAD

**Issue by Devendrabhat** [opencontainers/runc#1508]
go build -i  -ldflags "-X main.gitCommit="3a5b963f2f0a924e1f0b81dc3b0a31249af92ed1" -X main.version=1.0.0-rc3 " -tags "seccomp" -o runc .
events.go:12:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/lib/go-1.6/src/github.com/Sirupsen/logrus (from $GOROOT)
	($GOPATH not set)
utils_linux.go:14:2: cannot find package "github.com/coreos/go-systemd/activation" in any of:
	/usr/lib/go-1.6/src/github.com/coreos/go-systemd/activation (from $GOROOT)
	($GOPATH not set)
tty.go:11:2: cannot find package "github.com/docker/docker/pkg/term" in any of:
	/usr/lib/go-1.6/src/github.com/docker/docker/pkg/term (from $GOROOT)
	($GOPATH not set)
update.go:11:2: cannot find package "github.com/docker/go-units" in any of:
	/usr/lib/go-1.6/src/github.com/docker/go-units (from $GOROOT)
	($GOPATH not set)
checkpoint.go:10:2: cannot find package "github.com/opencontainers/runc/libcontainer" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer (from $GOROOT)
	($GOPATH not set)
events.go:14:2: cannot find package "github.com/opencontainers/runc/libcontainer/cgroups" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer/cgroups (from $GOROOT)
	($GOPATH not set)
utils_linux.go:16:2: cannot find package "github.com/opencontainers/runc/libcontainer/cgroups/systemd" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd (from $GOROOT)
	($GOPATH not set)
spec.go:11:2: cannot find package "github.com/opencontainers/runc/libcontainer/configs" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer/configs (from $GOROOT)
	($GOPATH not set)
init.go:8:2: cannot find package "github.com/opencontainers/runc/libcontainer/nsenter" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer/nsenter (from $GOROOT)
	($GOPATH not set)
spec.go:12:2: cannot find package "github.com/opencontainers/runc/libcontainer/specconv" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer/specconv (from $GOROOT)
	($GOPATH not set)
signals.go:12:2: cannot find package "github.com/opencontainers/runc/libcontainer/system" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer/system (from $GOROOT)
	($GOPATH not set)
list.go:17:2: cannot find package "github.com/opencontainers/runc/libcontainer/user" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer/user (from $GOROOT)
	($GOPATH not set)
exec.go:13:2: cannot find package "github.com/opencontainers/runc/libcontainer/utils" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer/utils (from $GOROOT)
	($GOPATH not set)
checkpoint.go:11:2: cannot find package "github.com/opencontainers/runtime-spec/specs-go" in any of:
	/usr/lib/go-1.6/src/github.com/opencontainers/runtime-spec/specs-go (from $GOROOT)
	($GOPATH not set)
checkpoint.go:12:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/lib/go-1.6/src/github.com/urfave/cli (from $GOROOT)
	($GOPATH not set)
checkpoint.go:14:2: cannot find package "golang.org/x/sys/unix" in any of:
	/usr/lib/go-1.6/src/golang.org/x/sys/unix (from $GOROOT)
	($GOPATH not set)
Makefile:30: recipe for target 'runc' failed
make: *** [runc] Error 1

**Comment by cyphar** [comment]
You need to have a proper `GOPATH` setup, which is part of having a proper `go` development environment. Here's the sparknotes version:

```bash
echo 'export GOPATH=$HOME/go' >> ~/.profile
. ~/.profile
mkdir -p $GOPATH/src/github.com/opencontainers/
git clone https://github.com/opencontainers/runc $GOPATH/src/github.com/opencontainers/
cd $GOPATH/src/github.com/opencontainers/
make
```
