### ISSUE TITLE
"cannot unmarshal array" error with runc 1.0.0-rc3

### ISSUE THREAD

**Issue by azadi** [opencontainers/runc#1512]
Hi,

I am getting the error `json: cannot unmarshal array into Go value of type specs.LinuxCapabilities` when trying to create and start a container.

```
runc version 1.0.0-rc3
commit: 3a5b963f2f0a924e1f0b81dc3b0a31249af92ed1
spec: 1.0.0-rc5-dev
```
This on Ubuntu 16.04.2.

```
$ sudo runc run 539336ef2f50f3b5858684df6
json: cannot unmarshal array into Go value of type specs.LinuxCapabilities
```
The directory structure is:
```
total 8
-rw-rw-r--  1 sukhbir sukhbir 2581 Jul  7 00:02 config.json
drwxrwxr-x 22 sukhbir sukhbir 4096 Jul  7 00:00 rootfs
```
Searching for this error doesn't tell me much. 

Apologies for missing something obvious (I am new to runC) and happy to provide any other information. Thanks.

**Comment by crosbymichael** [comment]
@azadi you have a newer `runc` with an older spec.  You have to update your config.json for the latest changes

**Comment by azadi** [comment]
@crosbymichael: Ah OK, thank you. Closing this.
