### ISSUE TITLE
runc list missing username (!?) incorrectly (!?) casts uid (int) to string

### ISSUE THREAD

**Issue by DazWilkin** [opencontainers/runc#1515]
### Summary
In the following the `owner` value is rendered as `𰨅` (U+30A05 == 199173).  This only happens on one (Ubuntu) workstation and does not arise on a second (Ubuntu) machine. I raise it because, while there appears to be several issues, at least one appears to be manifest by `runc`.

### Issues
On the problematic instance, the `owner` value is rendered by `runc list` as `𰨅`:
- `𰨅` corresponds to `U+30A05` == `199173`
- 199173 is the uid of the user account logged-in to the instance
- however the `runc` commands are being run as `root` (sudo) not the user
- `runc` appears to fail in looking up the username of the 199173 user (not root?)
- this results in `runc` `owner.Name` string value of `"\U00030a05"`
- which appears to be then rendered by `runc list` as if it were a character (`𰨅`) not the string

### Observation
consistently across `runc list --format`

```
sudo ./runc list --format table

ID          PID         STATUS      BUNDLE                                                                                                              CREATED                          OWNER
daz01       23235       running     [[OBFUSCASTED]]/go/src/github.com/opencontainers/runc/mycontainer   2017-07-10T22:09:45.474632798Z   𰨅
```
```
sudo ./runc list --format json

[{"ociVersion":"1.0.0-rc5-dev","id":"container01","pid":23235,"status":"running","bundle":"[[OBFUSCATED]]/go/src/github.com/opencontainers/runc/mycontainer","rootfs":"[[OBFUSCATED]]/go/src/github.com/opencontainers/runc/mycontainer/rootfs","created":"2017-07-10T22:09:45.474632798Z","owner":"𰨅"}]
```
### Exploration

I don't understand how this is arising but this uid corresponds to the logged in user's uid even though the `runc` commands are being run as `root`:

`os.Geteuid()` == `unix.Getuid()` == `199173`

Subsequently, the `owner.Name` is assigned a Unicoded encoded string value of `"\U00030a05"` (==199173) and then this is incorrectly interpreted as a character and rendered as `𰨅`

This appears to arise during `lookup.go` attempt to determine username from `/etc/passwd`

list.go:136
```
github.com/opencontainers/runc/libcontainer/user.User {Name: "", Pass: "", Uid: 0, Gid: 0, Gecos: "", Home: "", Shell: ""}
```

`user.LookupUid` is returning an err (`delve` isn't surfacing this to me) and so...

list.go:138
```
github.com/opencontainers/runc/libcontainer/user.User {Name: "\U00030a05", Pass: "", Uid: 0, Gid: 0, Gecos: "", Home: "", Shell: ""}
```

**Comment by cyphar** [comment]
Can you give us the relevant line from `/etc/passwd`?

**Comment by DazWilkin** [comment]
Wow! You're responsive :-)

Apologies, I omitted an important point, the user corresponding to uid `199173` is *not* listed in the workstation's `/etc/passwd`. It is a corporate workstation.

So, this would explain why any lookup for it in `/etc/passwd` is failing, but [rhetorical]:

-- why is this `uid` being sought if `runc` is run as `sudo`?
-- why does `runc` convert the `uid` to a unicode value as a string? perhaps `unknown`?
-- why then does `runc list` convert the unicode value in a string to a character?

**Comment by DazWilkin** [comment]
...and I'm motivated to help resolve this issue if you're willing to persevere with me.

If you need me to, I can edit sources, debug|trace specific functions etc.

`delve` is awesome but I'm finding that it's not always able to evaluate variables I expect to be in context and it's not possible to use it to evaluate functions.

**Comment by cyphar** [comment]
> -- why is this uid being sought if runc is run as sudo?

I just tried doing `runc run` and `runc list` on my machine and it looks like we're using `os.Getuid` rather than `os.Geteuid` to figure out what user to set as the owner of the corresponding `/run/runc/$id` directory (which is where that `uid` comes from). So I reckon it's just a matter of making sure that the code which sets that doesn't do the wrong thing. I'll take a look at this now.

> -- why does runc convert the uid to a unicode value as a string? perhaps unknown?
> -- why then does runc list convert the unicode value in a string to a character?

Yeah, that's my fault. I was casting `user.UID` to `string` rather than doing `fmt.Sprintf`. This patch should fix *that* aspect of this bug.

```
From 57ddfe79d44632dbe57d4c71e3ddfb669f3255c1 Mon Sep 17 00:00:00 2001
From: Aleksa Sarai <asarai@suse.de>
Date: Wed, 12 Jul 2017 05:53:38 +1000
Subject: [PATCH] list: stop casting unknown UIDs to their unicode values

If a container is owned by a UID that is not listed in /etc/passwd,
previously we would cast the UID to a string which contained a character
with the unicode value of the UID. This is clearly wrong, switch to
using fmt.Sprintf as intended.

Signed-off-by: Aleksa Sarai <asarai@suse.de>
---
 list.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/list.go b/list.go
index 1c3b9aa8..43f076dd 100644
--- a/list.go
+++ b/list.go
@@ -135,7 +135,7 @@ func getContainers(context *cli.Context) ([]containerState, error) {
 			stat := item.Sys().(*syscall.Stat_t)
 			owner, err := user.LookupUid(int(stat.Uid))
 			if err != nil {
-				owner.Name = string(stat.Uid)
+				owner.Name = fmt.Sprintf("%d", stat.Uid)
 			}
 
 			container, err := factory.Load(item.Name())
-- 
2.13.2
```

**Comment by cyphar** [comment]
Ah my above explanation was wrong. The reason for the owner being non-root is because we set the owner to be the root inside the container. After some tests, I'm convinced that this is actually not correct.

I've opened #1516 which should fix the problems. PTAL.

**Comment by DazWilkin** [comment]
I applied your changes in #1516 against my existing sources and it works for me!!

```
sudo ./runc list --format=json

[{"ociVersion":"1.0.0-rc5-dev","id":"mybusybox","pid":25636,"status":"running","bundle":"[[OBFUSCASTED]]/go/src/github.com/opencontainers/runc/mycontainer.busybox","rootfs":"[[OBFUSCASTED]]/go/src/github.com/opencontainers/runc/mycontainer.busybox/rootfs","created":"2017-07-11T02:35:09.93474615Z","owner":"#199173"}]
```

```
sudo ./runc --debug --log ./log.$(date +"%H%M") list --format=table
ID          PID         STATUS      BUNDLE                                                                                                                      CREATED                         OWNER
mybusybox   25636       running    [[OBFUSCASTED]]/go/src/github.com/opencontainers/runc/mycontainer.busybox   2017-07-11T02:35:09.93474615Z   #199173
```

Thanks very much and I am impressed by your responsiveness.

**Comment by cyphar** [comment]
No problem. We'll close this when the fix is merged.
