### ISSUE TITLE
integration tests do not run when criu is not found

### ISSUE THREAD

**Issue by karstengr** [opencontainers/runc#1520]
On my system the integration tests did not run at all, no error, no output.
Finally the reason was the following line in tests/integration/helpers.bash:

CRIU="$(which criu)"

I have no criu executable, so the 'which' seems to fail, helpers.bash aborts, and bats exits.

Should be easily reproducible on any system.

**Comment by cyphar** [comment]
I believe that this was actually going to be fixed in #1245 but @WeiZhang555 closed the PR last week. @WeiZhang555 did you want me to carry #1245?

**Comment by cyphar** [comment]
Sorry for ignoring it for so long, it went off the end of my backlog :wink:. I'll review it now.

**Comment by hqhq** [comment]
@WeiZhang555 We've merged it, nobody response only because people are too busy, please keep pinging and don't give up on us :)

**Comment by hqhq** [comment]
@karstengr Thanks for reporting, the fix is merged.

**Comment by WeiZhang555** [comment]
@hqhq All right, I got it! :wink:

**Comment by karstengr** [comment]
Thanks for your support!
