### ISSUE TITLE
runc spec --rootless does not generate a config.json file

### ISSUE THREAD

**Issue by c4milo** [opencontainers/runc#1531]
As advertised in the README. It prints the help instead. 

spec: 1.0.0-rc5

**Comment by cyphar** [comment]
Are you using the latest `runc` from `master`? We haven't had a release since rootless containers were merged in #774, so if you're using a release it won't work.

**Comment by c4milo** [comment]
I need to deploy a binary without having to build it. I took the latest release indeed.

**Comment by cyphar** [comment]
Yeah, we will need to create a new release soon anyway (since #1527 was merged). I'm going to close this, since it is fixed by master and I'll send a mail to the ML to start work on a new release.

**Comment by c4milo** [comment]
👍
