### ISSUE TITLE
Cannot build on 32bit or ARM Scaleway server (ARM 32bit, armv7l)

### ISSUE THREAD

**Issue by DieterReuter** [opencontainers/runc#155]
see https://github.com/docker/docker/issues/15053

Seems that `seccomp` currently supports `linux/amd64` only right now. There is only a file [jump_amd64.go](https://github.com/opencontainers/runc/blob/master/libcontainer/seccomp/jump_amd64.go), and no `jump_386.go`, `jump_arm.go` nor `jump_arm64.go`.

Any plans to support `linux/386`, `linux/arm` and `linux/arm64` soon?

**Comment by hqhq** [comment]
I think they have #70 working on, so no need to fix this jump_xxx.go right now, @LK4D4 @crosbymichael is that settled? Otherwise I can help make seccomp support on multiple arch.

**Comment by LK4D4** [comment]
@hqhq yup, we'll merge it I think. IBM guys helping in libseccomp repo with their arch, you can try to help with yours.

**Comment by vbatts** [comment]
ah. Cross-linking the issue https://github.com/docker/docker/issues/15120 I just opened.

**Comment by jperrin** [comment]
This seems to be hitting us for linux/arm64 as well. bumping for interest.

**Comment by StefanScherer** [comment]
I can confirm that #70 fixes this problem at least for `linux/arm`. After applying the PR docker builds works fine again on a Raspberry Pi.

**Comment by pavanpalaksha** [comment]
New to git and docker. what's the right way to patch #70 to my existing codebase(docker)? I have cloned docker/docker in my 32bit workstation. From my understanding, I have to clone runc and replace runc directory under docker-1.8.1/vendor/src/github.com/opencontainers/
