### ISSUE TITLE
when should prestart hooks be called

### ISSUE THREAD

**Issue by hqhq** [opencontainers/runc#1574]
It's a copy from https://github.com/opencontainers/runtime-spec/issues/909

I just realized that we define [prestart hooks MUST be called after the start operation is called](https://github.com/opencontainers/runtime-spec/blob/v1.0.0/config.md#prestart), it's been there since we restore hook language removed by create/start split in #532 , but we actually call prestart hooks in create operation which before start operation in runc, and this should be the right approach in practice, should we amend language in runtime-spec or should we reconsider implementation in runc?

**Comment by cyphar** [comment]
Closing this in favour of #1710 (since it's basically the same issue).
