### ISSUE TITLE
Error while creating containers i.e. "runc create"

### ISSUE THREAD

**Issue by LalatenduMohanty** [opencontainers/runc#1580]
Creating containers is giving `cannot allocate tty if runc will detach without setting console socket` error
Version:
```
$ runc --version
runc version spec: 1.0.0
```

**Output:**
```
$ mkdir busybox
$ cd busybox
$ mkdir rootfs
$ export $(docker create busybox) | tar -C rootfs -xvf -

$ runc spec

$ sudo runc run busyboxid
/ # 
/ # hostname
runc
/ # exit
$ sudo runc create busyboxid
cannot allocate tty if runc will detach without setting console socket
```
As `rootless`

```
$ runc spec --rootless

$ runc --root $HOME/.runc run busybox
/ # hostname
runc
/ # 
/ # exit

$ runc --root $HOME/.runc create busybox
cannot allocate tty if runc will detach without setting console socket
```

```

**Comment by vrothberg** [comment]
> $ sudo runc create busyboxid
cannot allocate tty if runc will detach without setting console socket

It's happening because the spec file has `"terminal": true`, but it must be set to false in this case. Or you use `runc create --console-socket ...`.

**Comment by LalatenduMohanty** [comment]
@vrothberg thanks, it worked for me. I think we should add it to the documentation.

**Comment by hqhq** [comment]
@LalatenduMohanty We already have this documented, see https://github.com/opencontainers/runc/blob/v1.0.0-rc4/README.md#running-containers if it's not clear enough for you, contribution is always welcome.

I think this issue can be closed.
