### ISSUE TITLE
compliance with runtime spec problem 

### ISSUE THREAD

**Issue by Mashimiao** [opencontainers/runc#1584]
Currently, when use runc to create container, we need option `--bundle` to specify bundle path.
But, in runtime spec, it definitely says `create <container-id> <path-to-bundle>`, bundle path should be a arg. More information please refer to  [runtime.md](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md)
So, will runc change the format of command `create` to be compliant of spec?

**Comment by hqhq** [comment]
@Mashimiao Which part of spec confuses you? I don't get it.

Note that there's notes about operation definitions in runtime-spec

```
Note: these operations are not specifying any command-line APIs, and the parameters are inputs for general operations.
```

**Comment by Mashimiao** [comment]
Ah,  sorry. I didn't notice that note.  We are trying to implement runtime validation in runtime-tools, and we test based on `create <container-id> <path-to-bundle>`, and then found runc is not compliant. when reading runtime.md,  the first impression it gives me is the spec rules create format and runc does not follow it.

**Comment by hqhq** [comment]
There's no cli definition in runtime-spec, In my memory the conclusion is runtime-tools implements a harness to handle that.

**Comment by Mashimiao** [comment]
On 09/12/2017 12:11 PM, Qiang Huang wrote:
> There's no cli definition in runtime-spec, In my memory the conclusion is runtime-tools implements a harness to handle that.

I have no idea about that.

**Comment by hqhq** [comment]
@Mashimiao I double checked, it's not that runtime-tools implements a harness, but depends on runtimes to implement harnesses who want to use runtime-tools for compliance validation. See conclusion in https://github.com/opencontainers/runtime-spec/pull/513#issuecomment-278550496 and there's already a PR in runtime-tools https://github.com/opencontainers/runtime-tools/pull/321 .

**Comment by Mashimiao** [comment]
On 09/12/2017 02:21 PM, Qiang Huang wrote:
> @Mashimiao <https://github.com/mashimiao> I double checked, it's not that runtime-tools implements a harness, but depends on runtimes to implement harnesses who want to use runtime-tools for compliance validation. See conclusion in opencontainers/runtime-spec#513 (comment) <https://github.com/opencontainers/runtime-spec/pull/513#issuecomment-278550496> and there's already a PR in runtime-tools opencontainers/runtime-tools#321 <https://github.com/opencontainers/runtime-tools/pull/321> .

Got it, thanks

**Comment by cyphar** [comment]
Yeah, there was a huge discussion about this a while ago. We wanted to create a CLI spec as well as the semantic one, but after quite a lot of discussion we decided that it would cause a lot of issues (as well as not being well-defined in cases were a runtime doesn't have a CLI interface). So basically the way it should be done is that you need to tell us what the harness should look like and we write it (and it'll probably just be a few shell scripts).

**Comment by williammartin** [comment]
Just as a note of interest, although we know there isn't a CLI spec, we've been treating it roughly as such with [winc](https://github.com/cloudfoundry-incubator/winc), the containeriser for Cloud Foundry on Windows. This allowed us to support windows with minor changes in the Garden code, since the commands and args could be treated the same (with winc ignoring a couple of flags).
