### ISSUE TITLE
runc list failure

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#1592]
Started the fedora container with docker version 
Server Version: 17.03.1-ce

In another directory, I have used the latest master runc to run an ubuntu container.
When I tried to do runc list
load container cee99b245cd41f1aa266dfab142acd5d9cecfad8e30dec17a1a8ac92add00a16: json: cannot unmarshal string into Go struct field State.init_process_start of type uint64

This is because state.json of fedora container created by docker is having string type for field init_process_start.  Recently in runc it got changed to uint64 as per this commit
75d98b26b7acb0023b990a7305a2553c6dbc12d4

**Comment by cyphar** [comment]
Yeah, that's because you have two `runc` versions that are sharing incompatible state. That's not really a supported configuration (though we should be more friendly about not bailing when an error occurs).
