### ISSUE TITLE
libcontainer: Potential infinite loop when setting freezer cgroup state

### ISSUE THREAD

**Issue by sboeuf** [opencontainers/runc#1609]
When using libcontainer library, we can end up calling into signalAllProcesses which leads to the following call chain:
https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go#L335
==>https://github.com/opencontainers/runc/blob/master/libcontainer/init_linux.go#L473
==> https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/apply_raw.go#L224
==> https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/freezer.go#L29

This can potentially lead to a deadlock by running in an infinite loop if the state never gets the one that is expected (FREEZING instead of FROZEN).

This code needs two things:
- Call into `writeFile()` everytime we don't get the expected state, because reading from the doc here: https://www.kernel.org/doc/Documentation/cgroup-v1/freezer-subsystem.txt, it appears that if a new task pops up, it will set the state to FREEZING instead of FROZEN. We have to set FROZEN again to make sure the new task is set to FROZEN state too.
- Add a timeout. After some time, we might want to consider this loop as failing instead of waiting forever.

**Comment by sboeuf** [comment]
@crosbymichael @cyphar @mrunalp any thoughts about this ?

**Comment by crosbymichael** [comment]
SGTM
