### ISSUE TITLE
glide get failed

### ISSUE THREAD

**Issue by xujianhai** [opencontainers/runc#1611]
I want to use the go package, but when I run command `glide get github.com/opencontainers/runc` on my terminal, I get the failed info: 

[INFO]	Preparing to install 1 package.
[INFO]	Attempting to get package github.com/opencontainers/runc
[INFO]	--> Gathering release information for github.com/opencontainers/runc
[INFO]	--> Adding github.com/opencontainers/runc to your configuration
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching github.com/opencontainers/runc.
[INFO]	--> Fetching updates for github.com/vishvananda/netlink.
[WARN]	Unable to checkout github.com/opencontainers/runc
[ERROR]	Update failed for github.com/opencontainers/runc: Unable to get repository
[WARN]	Download failed.
[ERROR]	Update failed for github.com/vishvananda/netlink: Unable to update repository
[ERROR]	Failed to checkout packages: Unable to get repository
Unable to update repository

so what I should do to aviod the fail get ?

**Comment by crosbymichael** [comment]
We don't' use glide for vendoring, you use `vndr` and the go vendor work dont in like 1.7+.

You just clone the repo with go get and run `make`
