### ISSUE TITLE
[runc] make failed in Centos 7

### ISSUE THREAD

**Issue by jithinjk** [opencontainers/runc#1617]
Facing similar issue here on Centos 7:

> [root@home runc]# cat /etc/centos-release
> CentOS Linux release 7.4.1708 (Core)
> 
> [root@home runc]# go env
> GOARCH="amd64"
> GOBIN=""
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/root/buildah"
> GORACE=""
> GOROOT="/usr/local/go"
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build173567046=/tmp/go-build -gno-record-gcc-switches"
> CXX="g++"
> CGO_ENABLED="1"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> 
> [root@home runc]# make
> go build -buildmode=pie  -ldflags "-X main.gitCommit="c05f6368afaf7f720c10b1207a51e40fccf05295" -X main.version=1.0.0-rc4+dev " -tags "seccomp" -o runc .
> \# internal/poll
> /usr/local/go/src/internal/poll/fd_mutex.go:194:6: missing function body for "runtime_Semacquire"
> /usr/local/go/src/internal/poll/fd_mutex.go:195:6: missing function body for "runtime_Semrelease"
> /usr/local/go/src/internal/poll/fd_poll_runtime.go:17:6: missing function body for "runtimeNano"
> /usr/local/go/src/internal/poll/fd_poll_runtime.go:19:6: missing function body for "runtime_pollServerInit"
> /usr/local/go/src/internal/poll/fd_poll_runtime.go:20:6: missing function body for "runtime_pollServerDescriptor"
> /usr/local/go/src/internal/poll/fd_poll_runtime.go:21:6: missing function body for "runtime_pollOpen"
> /usr/local/go/src/internal/poll/fd_poll_runtime.go:22:6: missing function body for "runtime_pollClose"
> /usr/local/go/src/internal/poll/fd_poll_runtime.go:23:6: missing function body for "runtime_pollWait"
> /usr/local/go/src/internal/poll/fd_poll_runtime.go:24:6: missing function body for "runtime_pollWaitCanceled"
> /usr/local/go/src/internal/poll/fd_poll_runtime.go:25:6: missing function body for "runtime_pollReset"
> /usr/local/go/src/internal/poll/fd_poll_runtime.go:25:6: too many errors
> make: *** [runc] Error 2

**Comment by cyphar** [comment]
Looks like the `go` package is broken -- what version of `Go` do you have?

**Comment by jithinjk** [comment]
> [root@home runc]# go version
> go version go1.9 linux/amd64
>

**Comment by cyphar** [comment]
Looks like a bug in the CentOS package for `go` -- something we can't really help you with. All of the `runtime_...` errors are because the source package in `/usr/local/go/src/` is broken somehow. Please report the bug to your distribution. I'd double check whether you can compile _any_ packages.

**Comment by jithinjk** [comment]
I think that was an $GOPATH issue. I was running it under a different location. Not an issue anymore.

**Comment by cyphar** [comment]
Alright, cool.
