### ISSUE TITLE
`runc exec` can't specify no-tty unless changing config.json or creating process.json

### ISSUE THREAD

**Issue by qingyunha** [opencontainers/runc#1627]
```golang
    // set the tty
    if context.IsSet("tty") {
        p.Terminal = context.Bool("tty")
    }
```

**Comment by kolyshkin** [comment]
What the bug reporter means is, if a container's config.json specifies `"terminal": true"` (in `process` section), there is no ability to have terminal-less `runc exec`.

In addition to that, `runc exec` does not create a proper terminal using /dev/ptmx, but reuses fd 0. This, combined with `runc exec ... < /dev/null`, leads to 

> ERRO[0000] exec failed: provided file is not a console

**Comment by kolyshkin** [comment]
A few possible solutions are:

1. Do not derive terminal boolean property from config.json (it is for the container start/run, not for exec). This is the way crun does it.

2. If a terminal is requested, create a pty pair using /dev/ptmx (or `"github.com/containerd/console".NewPty`). This is also the way crun does it.

I'm going to implement 1 for now.
