### ISSUE TITLE
Failed to build runc  with command "make release"

### ISSUE THREAD

**Issue by foreverpersist** [opencontainers/runc#1630]
I tried to build release runc from source. This is what I did:
``` bash
$ make release
```
  Here is the output message:
```
script/release.sh -r release/1.0.0-rc4+dev -v 1.0.0-rc4+dev
[*] creating runc release in 'release/1.0.0-rc4+dev'
[*]   version: 1.0.0-rc4+dev
[*]    commit: HEAD
[*]       key: DEFAULT
[*]      hash: sha256sum
+ rm -rf release/1.0.0-rc4+dev
+ mkdir -p release/1.0.0-rc4+dev
+ build_project release/1.0.0-rc4+dev/runc.amd64
++ dirname release/1.0.0-rc4+dev/runc.amd64
+ builddir=release/1.0.0-rc4+dev
+ make -C /go/src/github.com/opencontainers/runc COMMIT_NO= 'BUILDTAGS=seccomp selinux apparmor' static
make[1]: Entering directory '/go/src/github.com/opencontainers/runc'
CGO_ENABLED=1 go build  -tags "seccomp selinux apparmor netgo cgo static_build" -installsuffix netgo -ldflags "-w -extldflags -static -X main.gitCommit="" -X main.version=1.0.0-rc4+dev " -o runc .
# github.com/opencontainers/runc/libcontainer/apparmor
libcontainer/apparmor/apparmor.go:6:27: fatal error: sys/apparmor.h: No such file or directory
 // #include <sys/apparmor.h>
                           ^
compilation terminated.
Makefile:42: recipe for target 'static' failed
make[1]: *** [static] Error 2
make[1]: Leaving directory '/go/src/github.com/opencontainers/runc'
Makefile:46: recipe for target 'release' failed
make: *** [release] Error 2

```

  Comand "make" and "make static" work well. But why command "make release" failed?

  How can I build release runc?

**Comment by cyphar** [comment]
`make release` statically compiles all of the possible build options into a final binary. The error signifies that you don't have the necessary `apparmor-devel` (or whatever it's called in your distro) package. You'll also need `libseccomp-devel`. And you have to have the `-static` versions, if your distro has separate static versions.

If you just want the binaries, we provide them [in releases](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc4) along with detached signatures (signed by me) and some other "reproducible builds" information to make sure you can reproduce our binaries.
