### ISSUE TITLE
container_linux.go:296: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"mountpoint for devices not found\""

### ISSUE THREAD

**Issue by foreverpersist** [opencontainers/runc#1631]
I checked cgroup had been mounted at /sys/fs/cgroup.

**Comment by teddyking** [comment]
This error indicates that the `devices` cgroup wasn't mounted. Could you check the `/proc/self/mountinfo` file to see if it's listed in there?

**Comment by foreverpersist** [comment]
Thank you! 
  I checked `/proc/self/mountinfo`. Only memory cgroup is here. I mounted other cgroup subsystems, then the error dismissed.
