### ISSUE TITLE
Docker Cross-repo dependencies

### ISSUE THREAD

**Issue by cpuguy83** [opencontainers/runc#1638]
Working on some stuff for moby/moby I noticed that runc is pulling in two packages causing a cross-repo dep (moby depends on runc, runc depends on moby):

- github.com/docker/docker/pkg/mount
- github.com/docker/docker/pkg/symlink

I wonder if we should consider moving these?
For the mount package at least just the lower level items being used (mount table parsing). There is some higher level stuff in there that may not be strictly needed here.

ping @crosbymichael

**Comment by caniszczyk** [comment]
If you want to move these into OCI, we can definitely start the process for that to happen

**Comment by tianon** [comment]
Regarding `pkg/symlink` at least, @vdemeester is already on it: https://github.com/opencontainers/runc/pull/1622

**Comment by vdemeester** [comment]
- [x] pkg/symlink #1622 
- [ ] pkg/mount #1644

**Comment by cyphar** [comment]
This has been fixed since both #1622 and #1644 have been merged.
