### ISSUE TITLE
Parent process is killed when container is destroyed

### ISSUE THREAD

**Issue by Freeaqingme** [opencontainers/runc#1672]
Hi,

I'm using the libcontainer as part of a larger project. For every incoming connection I spawn a new container. My project handles all signals. When SIGINT is received, it will loop over all running containers, and Destroy() them gracefully.

The problem I faced was that whenever my container was destroyed, the parent process got killed as well, hindering a proper clean up of some other stuff.

This was fixed by this commit: https://github.com/Freeaqingme/opencontainers-runc/commit/08bbfcb2672119263cb097ec1828ff4de77edb6d

I could definitely file that as a pull request, but I figured it was put there for a reason, and will probably serve its purposes in other situations. Given how I also didn't see an easy way of making this configurable without muddling the existing interface, I figured I'd create an issue first.

**Comment by crosbymichael** [comment]
You should call Kill first, forwarding the signals to the containers before calling destroy.  Destroy forcefully kills and removes.  

Just forward signals like TERM to the container before deleting them and you will be good to go.
