### ISSUE TITLE
Not able to run runc from Java processbuilder

### ISSUE THREAD

**Issue by frezbo** [opencontainers/runc#1681]
```time="2018-01-04T19:04:33+05:30" level=error msg="Failed to remove paths: map[devices:/sys/fs/cgroup/devices/user/1001.user/c2.session/test cpuacct:/sys/fs/cgroup/cpuacct/user/1001.user/c2.session/test perf_event:/sys/fs/cgroup/perf_event/user/1001.user/c2.session/test memory:/sys/fs/cgroup/memory/user/1001.user/c2.session/test cpu:/sys/fs/cgroup/cpu/user/1001.user/c2.session/test blkio:/sys/fs/cgroup/blkio/user/1001.user/c2.session/test hugetlb:/sys/fs/cgroup/hugetlb/user/1001.user/c2.session/test freezer:/sys/fs/cgroup/freezer/user/1001.user/c2.session/test name=systemd:/sys/fs/cgroup/systemd/user/1001.user/c2.session/test]"```

@cyphar Any idea on this issue? The same runc command works when running from terminal.

**Comment by cyphar** [comment]
This is a little odd, but I feel it might be because the cgroup has processes still left in it (which is odd, because `runc` creates its own cgroups by default). Is there anything odd about your configuration?

```
// RemovePaths iterates over the provided paths removing them.
// We trying to remove all paths five times with increasing delay between tries.
// If after all there are not removed cgroups - appropriate error will be
// returned.
func RemovePaths(paths map[string]string) (err error) {
	delay := 10 * time.Millisecond
	for i := 0; i < 5; i++ {
		if i != 0 {
			time.Sleep(delay)
			delay *= 2
		}
		for s, p := range paths {
			os.RemoveAll(p)
			// TODO: here probably should be logging
			_, err := os.Stat(p)
			// We need this strange way of checking cgroups existence because
			// RemoveAll almost always returns error, even on already removed
			// cgroups
			if os.IsNotExist(err) {
				delete(paths, s)
			}
		}
		if len(paths) == 0 {
			return nil
		}
	}
	return fmt.Errorf("Failed to remove paths: %v", paths)
}
```

**Comment by frezbo** [comment]
@cyphar this was due to an old kernel issue. The system on which my colleague tried was having 3.10, once upgraded the error went away, had to disable tty  as per https://github.com/opencontainers/runc/issues/202. I'm closing this issue. Thanks for the help.
