### ISSUE TITLE
Container "Annotations" cannot be read from stdin by (prestart) hook

### ISSUE THREAD

**Issue by FlorianOtel** [opencontainers/runc#1686]
Caveat emptor: Being relatively new to this, I'm not sure if I'm doing something wrong or this is a genuine bug / missing feature. TIA for your guidance.

Description: 

Inspired by https://github.com/jessfraz/netns/blob/master/interface.go#L215-#L231 I wrote a little piece of code that -- when run as a (prestart) hook -- reads the container state from stdin. 

The code is here: https://github.com/OpenPlatformSDN/nuage-oci-plugin/blob/master/runc/runc.go 

The problem: The hook does read the correct information, _except_ Annotations -- which is the part I am interested in. 

On the other hand `runc state <container_ID>` does list the correct annotations. 

The "config.json" for the container -- containing the hook and Annotations is (partly) shown here: https://gist.github.com/FlorianOtel/dc12ae370b87f3d51527af5dcdeee797 

The difference on how the hook reads the data vs how `runc state ...` lists it is shown here: https://gist.github.com/FlorianOtel/73707cd372309ca0d566daabd9120e52 

As can be read from the last gist, the hook data reads annotations as `Annotations:map[string]string(nil) ` i.e. nothing can be read from stdin. 

Please advise if this is an issue with my code, a missing feature or a bug. 

Thanks,

/Florian

P.S. Forgot to mention the runc version: 

`
runc version 1.0.0-rc4
spec: 1.0.0
`
 
If this is a bug / missing feature that was fixed in subsequent versions, please advise.

**Comment by runcom** [comment]
I'm looking at this, will a patch shortly
