### ISSUE TITLE
runc build fails in Ubuntu 14.04 (go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64)

### ISSUE THREAD

**Issue by ajayaa** [opencontainers/runc#17]
make
====
go get github.com/tools/godep                                                  
unexpected fault address 0x2b2a00000011                                        
fatal error: fault                                                             
[signal 0xb code=0x1 addr=0x2b2a00000011]                                      
                                                                               
goroutine 5 [running]:                                                         
                                                                               
    :0                                                                         
                                                                               
    :0                                                                         
                                                                               
    :0                                                                         
                                                                               
    :0                                                                         
                                                                               
    :0                                                                         
                                                                               
    :0                                                                         
                                                                               
    :0                                                                         
goroutine 1 [select]:                                                          
main.$nested27                                                                 
    /build/buildd/gccgo-go-1.2.1/src/cmd/go/http.go:57                         
main.httpsOrHTTP                                                               
    /build/buildd/gccgo-go-1.2.1/src/cmd/go/http.go:65                         
main.repoRootForImportDynamic                                                  
    /build/buildd/gccgo-go-1.2.1/src/cmd/go/vcs.go:468                         
main.repoRootForImportPath                                                     
    /build/buildd/gccgo-go-1.2.1/src/cmd/go/vcs.go:362                         
main.downloadPackage                                                           
    /build/buildd/gccgo-go-1.2.1/src/cmd/go/get.go:269                         
main.download                                                                  
    /build/buildd/gccgo-go-1.2.1/src/cmd/go/get.go:166                         
main.download                                                                  
    /build/buildd/gccgo-go-1.2.1/src/cmd/go/get.go:232                         
main.runGet                                                                    
    /build/buildd/gccgo-go-1.2.1/src/cmd/go/get.go:72                          
main.main                                                                      
    /build/buildd/gccgo-go-1.2.1/src/cmd/go/main.go:161                        
                                                                               
goroutine 3 [syscall]:                                                         
    goroutine in C code; stack unavailable
make: *** [all] Error 2

**Comment by carmark** [comment]
It looks like you need to update your go from 1.2 to latest version.

**Comment by maxkueng** [comment]
Seems like the Makefile has some issues.I've also had problems on Arch Linux and also inside a `golang:latest` Docker container. It just failed. Then I saw this in [another issue](https://github.com/opencontainers/runc/issues/9#issuecomment-114420633) and it works for me. 

```sh
GOPATH=$PWD PATH=$PWD/bin:$PATH  make
#wait for it to fail, fixup dependencies
mkdir -p src/github.com/opencontainers/runc/
ln -sf $PWD/libcontainer src/github.com/opencontainers/runc/
GOPATH=$PWD PATH=$PWD/bin:$PATH  make
#works now
```
