### ISSUE TITLE
runc : tags/1.0.0-rc4 does not build

### ISSUE THREAD

**Issue by pracplayopen** [opencontainers/runc#1719]
fyi:

```
opencontainers/runc$git clean -f
opencontainers/runc$ git describe
v1.0.0-rc4
opencontainers/runc$ make
go build -i  -ldflags "-X main.gitCommit="2e7cfe036e2c6dc51ccca6eb7fa3ee6b63976dcd" -X main.version=1.0.0-rc4 " -tags "seccomp" -o runc .
# opencontainers/runc ./tty.go:17:12: undefined: libcontainer.Console
make: *** [Makefile:30: runc] Error 2
```

**Comment by pracplayopen** [comment]
v1.0.0-rc3 also failed with same error above.
v.10.0-rc2 built successfully.

**Comment by cyphar** [comment]
What is your `$GOPATH`, and do you have your Go environment set up properly (is the directory you're trying to build `runc` in inside `$GOPATH/src/github.com/opencontainers/runc`)?

**Comment by pracplayopen** [comment]
new to go dependencies here but did try all of following before reporting: 
GOPATH=$HOME,GOPATH=$(pwd), GOPATH=$HOME:$(pwd),GOPATH=$(pwd):$HOME 

same compile error regardless of GOPATH setting.

rc2 built as promised with default GOPATH.

**Comment by AkihiroSuda** [comment]
Closing as outdated
