### ISSUE TITLE
runc on MacOS

### ISSUE THREAD

**Issue by nqbao** [opencontainers/runc#1733]
Hi,

I know `runc` can run on Windows and Linux. I wonder if we can run `runc` on MacOS.

Thanks!

**Comment by cyphar** [comment]
`runc` only runs on Linux, it doesn't run on Windows nor MacOS. Docker's (or rather contained's) container support on Windows uses `hcsshim` -- which is a Windows-specific VM-like thing.

**Comment by nqbao** [comment]
Oh right, for some reason i have the impression that runc can also run on windows. I must have drunken too much coffee ...  Thanks for your quick reply!

**Comment by cyphar** [comment]
All good! :smile_cat:
