### ISSUE TITLE
Significance of rbind when type:bind is removed

### ISSUE THREAD

**Issue by Nabarun** [opencontainers/runc#1744]
Hi I don't want to bind my /tmp inside the container to my host system.
Currently my config.json was as follows      
{
            "destination": "/tmp",
            "type": "bind",
            "source": "/tmp",
            "options": ["rbind","rw"]
        }

I removed the "type" : "bind" from this node still I see the bindings in the host system. I thought that removal of type:bind will be preventing me to create the bind. Is that not the case here?
{
            "destination": "/tmp",
            "source": "/tmp",
            "options": ["rbind","rw"]
        }

**Comment by wking** [comment]
If you don't want to bind `/tmp` into your container, just drop the whole entry.  As long as it contains `rbind` in `options`, you'll get a bind mount.

**Comment by Nabarun** [comment]
Thanks for confirming that
