### ISSUE TITLE
Get error building runc

### ISSUE THREAD

**Issue by Dutchdoc** [opencontainers/runc#1761]
I got the latest runc sources and tried to build it (with go-1.6) by running make:
This is the output (and error message) I get:

`
make
go build -buildmode=pie  -ldflags "-X main.gitCommit="69663f0bd4b60df09991c08812a60108003fa340" -X main.version=1.0.0-rc5+dev " -tags "seccomp" -o runc .

<span>#</span> github.com/opencontainers/runc/libcontainer/user
libcontainer/user/user.go:64: undefined: user.Group
Makefile:32: recipe for target 'runc' failed
make: *** [runc] Error 2
`

Any ideas or suggestions?

**Comment by cyphar** [comment]
You need a Go version that includes golang/go@42f07ff2679d3 -- which is Go 1.7 or later.

**Comment by Dutchdoc** [comment]
Thanks! Using go 1.10 did it!
