### ISSUE TITLE
Unable to stop containers running systemd with SIGRTMIN+3

### ISSUE THREAD

**Issue by sajones** [opencontainers/runc#1766]
The version of runc provided by CentOS, based on RC4 it appears, returns `unknown signal "RTMIN+3"` or `unknown signal "37"` when I attempt it send the systemd prescribed shutdown signal. The earlier version of runc I have available is based on RC2-dev commit c91b5bea4830a57eac7882d7455d59518cdf70ec and does not exhibit this issue. The older version did not accept the signal by name, however it did allow sending the signal by its number, `37`, instead.

**Comment by crosbymichael** [comment]
Are you using `runc kill` for this?

**Comment by sajones** [comment]
`runc kill <container-name> 37` works on RC2 and breaks in RC3 and later. `runc kill <container-name> RTMIN+3` does not work in any version.

**Comment by sajones** [comment]
After more commit testing it appears the issue was introduced with a367e4b95c9f25e684dd7bd6f1a33aaf7b807087 and resolved by 7ac503d1a2135dcf985677a0f8ea6950d9935e9e. While sending raw signal numbers to `runc kill` it appears to be the only way using runc to stop a container started by runc that uses systemd as the container PID 1. Since 7ac503d1a2135dcf985677a0f8ea6950d9935e9e is part of RC5 will close this issue.
