### ISSUE TITLE
exec failed: starting container process

### ISSUE THREAD

**Issue by andrewrynhard** [opencontainers/runc#1783]
I am attempting to use `runc` with [CRI-O](https://cri-o.io) in a Kubernetes cluster. I'm running this in a [custom distro](https://github.com/autonomy/dianemo) I am building for the sole purpose of running Kubernetes. Almost everything works, except `exec`'ing into an existing pod container.

I can create the container initially just fine:
```bash
$ kubectl run --rm -it --image=alpine --restart=Never test -- sh
If you don't see a command prompt, try pressing enter.
/ # 
```

Now, attempting to `exec` into the newly created container:

```bash
$ kubectl exec -it test -- sh
exec failed: container_linux.go:348: starting container process caused "open /dev/ptmx: no such file or directory"
```
 Which I don't understand because (executed from within the above container):

```bash
/ #ls -l /dev/ptmx
lrwxrwxrwx    1 root     root             8 Apr 15 23:05 /dev/ptmx -> pts/ptmx
/ # ls -l /dev/pts
total 0
crw--w----    1 root     tty       136,   0 Apr 15 23:12 0
crw-rw-rw-    1 root     root        5,   2 Apr 15 23:12 ptmx
```

Dropping the `-t` flag throws a different error:

```bash
kubectl exec -i test -- sh
exec failed: container_linux.go:348: starting container process caused "open /proc/self/fd: no such file or directory"
command terminated with exit code 1
```

Again, this is confusing because (executed from within the above container):

```bash
/ # ls -l /proc/self/fd
total 0
lrwx------    1 root     root            64 Apr 15 23:18 0 -> /dev/pts/0
lrwx------    1 root     root            64 Apr 15 23:18 1 -> /dev/pts/0
lrwx------    1 root     root            64 Apr 15 23:18 2 -> /dev/pts/0
ls: /proc/self/fd/3: cannot read link: No such file or directory
lr-x------    1 root     root            64 Apr 15 23:18 3
/ #
```

There seems to be a few issues created around this

- https://github.com/docker/cli/issues/297
- https://github.com/docker/for-linux/issues/105
- https://what.thedailywtf.com/topic/24206/docker-shim-error-open-dev-ptmx/11

I have spent a lot of time attempting to track down the root cause, but I keep going in circles. Any kind of guidance would be appreciated if it is an error on my end, but I have done just about all I *think* I can to get it working.

Here is some info that might be helpful:

```bash
$ runc --version
runc version 1.0.0-rc5
spec: 1.0.0
```

```bash
/ # uname -r
4.15.13-dianemo
```

Kernel configs related to PTY:
```
CONFIG_UNIX98_PTYS=y
# CONFIG_LEGACY_PTYS is not set
```

Mount info (from within the container):
```bash
/ # mount
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/containers/storage/overlay/l/EDHGG3O3NIUU2DXR5N7KS2GMCP,upperdir=/var/lib/containers/storage/overlay/96eb0dc702ea59f0b0a68a6efb4293a303b08fab5c6257d289a9bc79485aa449/diff,workdir=/var/lib/containers/storage/overlay/96eb0dc702ea59f0b0a68a6efb4293a303b08fab5c6257d289a9bc79485aa449/work)
proc on /proc type proc (rw,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)
defaults on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,hugetlb,pids)
shm on /etc/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
tmpfs on /etc/resolv.conf type tmpfs (rw,relatime)
tmpfs on /etc/hostname type tmpfs (rw,relatime)
/dev/sda2 on /etc/hosts type xfs (rw,noatime,attr2,inode64,noquota)
/dev/sda2 on /dev/termination-log type xfs (rw,noatime,attr2,inode64,noquota)
tmpfs on /run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,relatime)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
proc on /proc/asound type proc (ro,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime)
tmpfs on /sys/firmware type tmpfs (ro,relatime)
```

```bash
/ # cat /proc/sys/kernel/pty/max
4096
/ # cat /proc/sys/kernel/pty/reserve
1024
/ # cat /proc/sys/kernel/pty/nr
1
```

FWIW I see the same error when attempting the above with Docker instead of CRI-O.

**Comment by andrewrynhard** [comment]
Digging into it with delve:

`github.com/kubernetes-incubator/cri-tools/vendor/k8s.io/client-go/tools/remotecommand/v2.go:152`
```
(dlv) bp
Breakpoint unrecovered-panic at 0x42bc50 for runtime.startpanic() .usr/local/go/src/runtime/panic.go:577 (0)
	print runtime.curg._panic.arg
Breakpoint 1 at 0xaa603f for github.com/kubernetes-incubator/cri-tools/vendor/k8s.io/client-go/tools/remotecommand.(*streamProtocolV2).copyStderr() .go/src/github.com/kubernetes-incubator/cri-tools/vendor/k8s.io/client-go/tools/remotecommand/v2.go:152 (0)
(dlv) c
> github.com/kubernetes-incubator/cri-tools/vendor/k8s.io/client-go/tools/remotecommand.(*streamProtocolV2).copyStderr() .go/src/github.com/kubernetes-incubator/cri-tools/vendor/k8s.io/client-go/tools/remotecommand/v2.go:152 (hits goroutine(1):1 total:1) (PC: 0xaa603f)
Warning: debugging optimized function
(dlv) n
> github.com/kubernetes-incubator/cri-tools/vendor/k8s.io/client-go/tools/remotecommand.(*streamProtocolV2).copyStderr() .go/src/github.com/kubernetes-incubator/cri-tools/vendor/k8s.io/client-go/tools/remotecommand/v2.go:153 (PC: 0xaa6052)
Warning: debugging optimized function
(dlv)
exec failed: container_linux.go:348: starting container process caused "open /dev/ptmx: no such file or directory"
> github.com/kubernetes-incubator/cri-tools/vendor/k8s.io/client-go/tools/remotecommand.(*streamProtocolV2).copyStderr() .go/src/github.com/kubernetes-incubator/cri-tools/vendor/k8s.io/client-go/tools/remotecommand/v2.go:154 (PC: 0xaa6063)
Warning: debugging optimized function
(dlv)
```

**Comment by andrewrynhard** [comment]
Same error with kernel `4.14.34-dianemo`

**Comment by andrewrynhard** [comment]
So it turns out that my code was not performing `switch_root` properly. Sorry for the noise.

**Comment by Ybt-1** [comment]
I also had the same issue, please how did you solve it. 
docker exec -it myubuntu /bin/bash
OCI runtime exec failed: exec failed: unable to start container process: error closing exec fds: open /proc/self/fd: no such file or directory: unknown
Go version:        go1.21.9                                                    
 Git commit:        9714adc                                                     
 Built:             Mon Apr 22 17:07:13 2024                                    
 OS/Arch:           linux/arm64                                                 
 Context:           default                                                     
                                                                                
Server: Docker Engine - Community                                               
 Engine:                                                                        
  Version:          26.1.0                                                      
  API version:      1.45 (minimum version 1.24)                                 
  Go version:       go1.21.9                                                    
  Git commit:       c8af8eb                                                     
  Built:            Mon Apr 22 17:07:13 2024                                    
  OS/Arch:          linux/arm64                                                 
  Experimental:     false                                                       
 containerd:                                                                    
  Version:          1.6.31                                                      
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521                    
 nvidia:                                                                        
  Version:          1.1.0-0ubuntu1~20.04.1                                      
  GitCommit:        ddeeca392c7bd8b33d0a66400b77af7a97e16cef                    
 docker-init:                                                                   
  Version:          0.19.0                                                      
  GitCommit:        de40ad0
