### ISSUE TITLE
why do you hide File/Path not exist error when calling mem.GetStats?

### ISSUE THREAD

**Issue by qudongfang** [opencontainers/runc#1789]
why do you hide File/Path not exist error when calling [mem.GetStats](https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/memory.go#L208)?

```golang
func (s *MemoryGroup) GetStats(path string, stats *cgroups.Stats) error {
	// Set stats from memory.stat.
	statsFile, err := os.Open(filepath.Join(path, "memory.stat"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	defer statsFile.Close()
   
       // ...
}
```

I found it was merge by this [pull request](https://github.com/docker/libcontainer/pull/75) by @vmarmol 

Does anybody can help me to understand ?

I think that it should return PathError to caller.

**Comment by cyphar** [comment]
It's because `memory.stat` wasn't supported on all older kernels. If there is no `memory.stat` file then the kernel is too old to support it, and rather than erroring out we just ignore it and move on (and the stat struct doesn't get filled).

**Comment by qudongfang** [comment]
why not return some `NOT_SUPPORTED_ERROR` ? 
how can we tell `NOT_SUPPORTED` from `memory.Stat` all zero value?

**Comment by qudongfang** [comment]
ping @crosbymichael

**Comment by crosbymichael** [comment]
@qudongfang I don't think we ever meant for runc's cgroup package to be used outside of runc.  It handles things our runc's usecase.

If you are looking for a general purpose cgroups lib in Go, containerd has https://github.com/containerd/cgroups which is really nice and has good support. It allows you to handle errors on the Stat collection, you can ignore, return, etc.

**Comment by qudongfang** [comment]
OK, thanks for spotting this. I'll close this issue and turn to use[ cgroups from containerd](https://github.com/containerd/cgroups).
