### ISSUE TITLE
docker-runc init child process hangs indefinitely

### ISSUE THREAD

**Issue by justcsdr** [opencontainers/runc#1804]
As I said in the subject, after a few re-creating of a container, docker-runc init child process hangs. The only output of strace (for the child) is:
getpid()                                = 31982
close(6)                                = 0
prctl(PR_SET_NAME, "runc:[1:CHILD]\0r") = 0
unshare(CLONE_NEWNS|CLONE_NEWUTS|CLONE_NEWIPC|CLONE_NEWPID|CLONE_NEWNET

And the only way to proceed is to restart the entire host.
My host OS is CentOS7 with kernel 4.16.0-1.el7.
Current Docker version is 18.03.0-ce, build 0520e24 (but the older 17.12 did the same thing)

**Comment by cyphar** [comment]
This is very likely to be a kernel bug, if `unshare` is not completing.

**Comment by justcsdr** [comment]
Thanks for the info. I was hopping that I did something wrong, but the /usr/bin/unshare command is doing the same thing.
