### ISSUE TITLE
FTBFS on [mips, mips64el, mipsel]: cannot use devNumber (type uint32) as type uint64

### ISSUE THREAD

**Issue by onlyjob** [opencontainers/runc#1823]
[mips](https://buildd.debian.org/status/fetch.php?pkg=runc&arch=mips&ver=1.0.0%7Erc5%2Bdfsg1-2&stamp=1529155516&raw=0), [mips64el](https://buildd.debian.org/status/fetch.php?pkg=runc&arch=mips64el&ver=1.0.0%7Erc5%2Bdfsg1-2&stamp=1529160601&raw=0) and [mipsel](https://buildd.debian.org/status/fetch.php?pkg=runc&arch=mipsel&ver=1.0.0%7Erc5%2Bdfsg1-2&stamp=1529158764&raw=0) exhibit the following FTBFS:

~~~~
# github.com/opencontainers/runc/libcontainer/devices
src/github.com/opencontainers/runc/libcontainer/devices/devices.go:34:25: cannot use devNumber (type uint32) as type uint64 in argument to unix.Major
src/github.com/opencontainers/runc/libcontainer/devices/devices.go:54:32: cannot use devNumber (type uint32) as type uint64 in argument to unix.Minor
~~~~

https://buildd.debian.org/status/package.php?p=runc&suite=unstable

Wrapping `devNumber` as `uint64(devNumber)` should help.

Affected lines:

https://github.com/opencontainers/runc/blob/master/libcontainer/devices/devices.go#L34
https://github.com/opencontainers/runc/blob/master/libcontainer/devices/devices.go#L54

**Comment by cyphar** [comment]
Out of interest what does FTBFS stand for?

**Comment by onlyjob** [comment]
[FTBFS](https://wiki.debian.org/FTBFS) stands for _Fails To Build From Source_. :)

Thanks for working on this problem.

**Comment by onlyjob** [comment]
Confirming: #1824 fixed the problem. Thanks.
