### ISSUE TITLE
go get github.com/opencontainers/runc fails with undefined: user.Group

### ISSUE THREAD

**Issue by kagehisa** [opencontainers/runc#1828]
I tried to install runc via the go get method stated in the documentation.
GOPATH is set correctly to ~/go. 
But all I get is:
`> go get github.com/opencontainers/runc
github.com/opencontainers/runc/libcontainer/user
/usr/lib/go-1.6/src/github.com/opencontainers/runc/libcontainer/user/user.go:64: undefined: user.Group
`

Is there a way to get more information to what exactly is going wrong?

**Comment by AkihiroSuda** [comment]
1.6 is unsupported

**Comment by kagehisa** [comment]
Ok, I switched to 1.10 and did it again. The warning remains the same but the fetch works and directory as well as the data are present. Thanks.
