### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [opencontainers/runc#1842]
Hello @crosbymichael 

I wanted to contribute and i designed a logo for runc. Inspired by the OpenContainers logo. What do you think?

![runc](https://user-images.githubusercontent.com/36298335/42680962-204dd0d0-868f-11e8-99f1-14261e9733de.jpg)

**Comment by rhatdan** [comment]
You spelt Opencontainer wrong.

**Comment by crosbymichael** [comment]
@reallinfo That looks really good.  Thanks!  

Since @caniszczyk runs OCI, lets see what he thinks and what the process is for contributing a logo for a project.  

Thanks again @reallinfo

**Comment by caniszczyk** [comment]
cool! if you state on this github that you're willing to donate the logo to the OCI under CC0 (https://creativecommons.org/publicdomain/zero/1.0/) we will gladly take it if the other @opencontainers/runc-maintainers are OK with it

**Comment by reallinfo** [comment]
Sure! I will donate you the logo. What do you think about this license? 

https://creativecommons.org/licenses/by/4.0/

Where should I send Pr?

**Comment by reallinfo** [comment]
I prepared the logos as in the oci file and i sent a pr. Please check it and if there is a problem tell me. So I can make the necessary arrangements.

https://github.com/opencontainers/artwork/pull/5

**Comment by reallinfo** [comment]
Hey @caniszczyk Also, I updated the readme file. Please check it.

https://github.com/opencontainers/runc/pull/1843

**Comment by kolyshkin** [comment]
This can be closed I think.
