### ISSUE TITLE
checkpoint/restore broken

### ISSUE THREAD

**Issue by qiancai** [opencontainers/runc#1853]
Since commit 8187fb740c202f5d29f1717bb933143c10dae8a1

Easy to reproduce using this config.json,

http://people.redhat.com/qcai/tmp/config.json

<console #1> # runc run root

<console #2> rm -rf /tmp/root; mkdir /tmp/root
<console #2> runc checkpoint --image-path /tmp/root/ --work-path /tmp/root/ root
<console #2> runc restore --image-path /tmp/root/ --work-path /tmp/root/ root
criu failed: type NOTIFY errno 0
log file: /tmp/root/restore.log

http://people.redhat.com/qcai/tmp/restore.log

@avagin

**Comment by avagin** [comment]
What version of criu do you use?

**Comment by qiancai** [comment]
criu-3.5

**Comment by avagin** [comment]
@qiancai I think this is a dup of https://github.com/checkpoint-restore/criu/issues/314. Could you try to update criu?

**Comment by qiancai** [comment]
Yes, using the latest upstream criu works fine.

**Comment by avagin** [comment]
@qiancai could you close this issue?
