### ISSUE TITLE
Running 'make test' TestCheckpoint Fails. [8] System error: mountpoint for cgroup not found.

### ISSUE THREAD

**Issue by markkelloggjr** [opencontainers/runc#186]
When I'm running "make test", I run into failing tests during integration/checkpoint_test.go TestCheckpoint (among others, all with the same error). 

See below for an example of one of the errors.

When I look at the config that is being used for container.start(&pconfig) it does not have cgroups designated under mounts. Should that exist in the test config being passed in or is there something I am missing for my environment? I cloned the repo at commit 9be9157fc5cd9cf59c155fe194a0acc5f1e6f926

**Test output below**
=== RUN TestCheckpoint
time="2015-08-06T20:44:48Z" level=warning msg="signal: killed" 
:make: *** [localtest] Error 1
make: *** [test] Error 2
--- FAIL: TestCheckpoint (0.14s)
        checkpoint_test.go:99: [8] System error: mountpoint for cgroup not found

**Comment by LK4D4** [comment]
@markkelloggjr It's actually works for me. Seems like you can miss some cgroup on your host. Would you mind to provide output of `mount` command?

**Comment by markkelloggjr** [comment]
This is on the output of the mount command from my dev machine.

sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=635061,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,relatime,size=1019664k,mode=755)
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=509832k,mode=700,uid=1000,gid=1000)
tmpfs on /tmp/libcontainer092097685 type tmpfs (rw,relatime)
tmpfs on /tmp/libcontainer606459216 type tmpfs (rw,relatime)
tmpfs on /tmp/libcontainer805033813 type tmpfs (rw,relatime)
tmpfs on /tmp/libcontainer746908320 type tmpfs (rw,relatime)
tmpfs on /tmp/libcontainer642187764 type tmpfs (rw,relatime)

**Comment by LK4D4** [comment]
@markkelloggjr You have no memory cgroup, this might be an issue.

**Comment by wking** [comment]
On Thu, Aug 06, 2015 at 02:42:39PM -0700, Alexander Morozov wrote:
> @markkelloggjr You have no memory cgroup, this might be an issue.

To make it easy to diagnose things like this, it might be worth
pulling [1] over from Docker, or splitting it out into a separate
project so we can easily test for runC requirement (e.g. MEMCG) while
Docker can still layer on Docker-specific requirements
(IP_NF_TARGET_MASQUERADE?).

Alternatively, maybe we just need better error messages in runC?

[1]: https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by markkelloggjr** [comment]
@LK4D4 I *believe* I added the memory cgroup (have not messed around with them before). It does show in the output at least.

I am still getting the same error when I try to run make test with this update.



Here is the new output from my mount command

sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=635061,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,relatime,size=1019664k,mode=755)
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
tmpfs on /run/user/117 type tmpfs (rw,nosuid,nodev,relatime,size=509832k,mode=700,uid=117,gid=124)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=509832k,mode=700,uid=1000,gid=1000)

**Comment by markkelloggjr** [comment]
@wking I think I understand. It looks like I am also missing the cpu cgroup from the file you linked. I will try that. Thanks

**Comment by LK4D4** [comment]
@markkelloggjr Actually you have `cpu,cpuacct` it should be enough. What version of docker do you use? I think `make test` might require at least 1.8-rc2 :/

**Comment by markkelloggjr** [comment]
@LK4D4 I am using:
Client version: 1.6.2
Client API version: 1.18

I will try and update that.

**Comment by marcosnils** [comment]
@LK4D4 it was working with 1.7.1 the last time I checked. Seems like the runc_test docker image doesn't have the corresponding cgroups mountpoints. Ideas?

**Comment by wking** [comment]
On Thu, Aug 06, 2015 at 03:49:21PM -0700, Marcos Nils wrote:
> Seems like the runc_test docker image doesn't have the corresponding
> cgroups mountpoints. Ideas?

Write an OCI bundle for the runC tests?  It would be nice if runC
tests were self-hosting.

**Comment by marcosnils** [comment]
@wking that's a good idea. The thing about testing with docker is that it's very easy to setup images through the dockerfile with the corresponding env settings (go / mountpoints / etc). If we use a bundle then the rootfs should be hosted somewhere in order to test.

**Comment by markkelloggjr** [comment]
Thank you for the help. I am pretty sure updating to 1.8 fixed the issue that I was previously getting. 

I believe all but 1 test pass now. I am currently running 'make test' with heightened permissions but the file it's looking for does not exist. Maybe it's an issue with how I set up the cgroup for memory.

TestRunWithKernelMemory (0.15s)
	exec_test.go:554: runContainer failed with kernel memory limit: [8] System error: open /sys/fs/cgroup/memory/integration/test/memory.kmem.limit_in_bytes: permission denied

**Comment by wking** [comment]
On Thu, Aug 06, 2015 at 04:04:36PM -0700, Marcos Nils wrote:
> … it's very easy to setup images through the dockerfile with the
> corresponding env settings (go / mountpoints / etc).

Doing environment-variable replacement on a template config is easy.
For example, see [1,2,3].

> If we use a bundle then the rootfs should be hosted somewhere in
> order to test.

That's probably enough of a reason to not bother testing directly in
runC now ;).  Tarballs in a submodule seem like too annoying a hoop.

[1]: http://linux.die.net/man/1/envsubst
[2]: http://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html
[3]: https://github.com/wking/dockerfile/blob/269a64f1f54b8f5077bbf27d6b93eabffdb4fa9b/build.sh#L219-L228

**Comment by marcosnils** [comment]
@wking thanks for the env replacement info. I'm still wondering why tests don't work in 1.7.1 when they used to.

**Comment by LK4D4** [comment]
@marcosnils it requires mounting cgroups inside container

**Comment by marcosnils** [comment]
@LK4D4 it was working before for me in 1.7.1. I believe cgroups were mounted before..

**Comment by LK4D4** [comment]
@marcosnils It's not about docker, it's about docker + runc test image. Before we mount cgroups inside container with script, not it's done by docker(runc now mounts them too).

**Comment by hqhq** [comment]
@marcosnils It used to work on 1.7.1 because runc test used dind and dind will mount cgroup in container, after #164 , runc removed dind, so it depends on docker to mount cgroup in container, and that's only supported after 1.8.0-rc2.

I added some docs about testing in #237 , I think this issue can be closed once that's merged.

**Comment by runcom** [comment]
I've hit the same problem, after debug, with latest docker (1.8.2 and master), turns out that when the installed docker on host is running w/o the native driver but with LXC, tests in runc are failing with this error because LXC isn't mounting cgroups inside the contianer for test.
I also think this issue can be closed now

**Comment by crosbymichael** [comment]
This appears  not to be an issue anymore.  Closing. Thanks!
