### ISSUE TITLE
 hard coded constants outside 'int' range on 32-bit platforms

### ISSUE THREAD

**Issue by andreasbaumann** [opencontainers/runc#1885]
Building on 32-bit Intel results in:

```
# github.com/projectatomic/buildah/vendor/github.com/opencontainers/runc/libcontainer/system
vendor/github.com/opencontainers/runc/libcontainer/system/linux.go:119:89: constant 4294967295 overflows int
```

int and uint are platform-dependent, as you can check with a test program like
in https://gist.github.com/petergloor/1eacd3ebcfc3e09ed578dd0d4f80cabe

on 32-bit:

```
Integer range on this computer
MinUint: 0
MaxUint: 4294967295
MinInt: -2147483648
MaxInt: 2147483647
```

I hacked the sources with:

```
  find . -type f -exec sed -i 's/4294967295/2147483647/g' {} \;
```

but this feels - well hacky :-)

**Comment by AkihiroSuda** [comment]
Yes, using `MaxUint32` makes sense, but I suppose the issue has been fixed in #1819

**Comment by cyphar** [comment]
I believe this issue was fixed in the past -- we build `runc` on 32-bit machines for openSUSE and we don't have this issue (unless it was regressed recently). But let me see what happens when I test it.

**Comment by rhatdan** [comment]
Is this issue still ongoing?

**Comment by rhatdan** [comment]
Any update on this issue?

**Comment by AkihiroSuda** [comment]
Wasn't it fixed in https://github.com/opencontainers/runc/pull/1819 ?

**Comment by cyphar** [comment]
Yes, I think it was.

**Comment by cyphar** [comment]
We also do a `make cross` as part of CI so we should catch it in the future.
