### ISSUE TITLE
Pushing discussion to the mailing list first: reword maintainer guide

### ISSUE THREAD

**Issue by wking** [opencontainers/runc#189]
In opencontainers/specs#102, @vbatts [pointed me towards the 2015-08-05 meeting][1] for notes about discussing things on the mailing list.  Looking through the [minutes][2] and [video][3] (after 26:02), it sounds like the new policy is to push discusion-worthy topics to the mailing list first, so they get broader exposure in a medium that's easier to archive than GitHub's inline comments.  I'm not sure if that discussion is just about the spec, or if it also extends to runC.  But as far as I can tell (see opencontainers/web#5), runC's maintainer list and guide currently apply to all OCI projects, including the spec.  In any case, if the list-first approach was intendend to cover runC, I'd suggest adapting the [language in the maintainer guide][4], which is currently pushing pull-requests for all discussion.

In the minutes, @vbatts was taking point for documenting the list-first approach, but I thought I'd file an issue about the guide's wording to help remember that it may also need updating.

[1]: https://github.com/opencontainers/specs/pull/102#issuecomment-129048348
[2]: https://docs.google.com/document/d/1a5UW7MRLVaUDEjuQmRudYMZcPV0bBtPD2QEOLT_3zi0/edit?usp=sharing
[3]: https://plus.google.com/events/cqfpicicbnra9mv6kvpj0mb24u4
[4]: https://github.com/opencontainers/runc/blob/9be9157fc5cd9cf59c155fe194a0acc5f1e6f926/MAINTAINERS_GUIDE.md#how-are-decisions-made

**Comment by wking** [comment]
opencontainers/specs#104 landed three weeks ago pushing spec discussion to the mailing list.  I still have the scope of that decision, but if it is intended to apply to this repository we still need to adjust the [language in the maintainer guide][1] to shift initial discussion from pull-requests to the mailing list.

[1]: https://github.com/opencontainers/runc/blob/b1e704195757ff759c3260b0a578c75c6eb17da5/MAINTAINERS_GUIDE.md#how-are-decisions-made

**Comment by crosbymichael** [comment]
this is not a runc issue.  closing
