### ISSUE TITLE
Panic if `config.json` is missing "linux" configuration.  Should fail gracefully instead.

### ISSUE THREAD

**Issue by marler8997** [opencontainers/runc#1890]
Here's the stacktrace, but the fix would likely be checking that spec.Linux is not nil before dereferenceing it in https://github.com/opencontainers/runc/blob/master/libcontainer/specconv/spec_linux.go#L260

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x558fe4aac809]

goroutine 1 [running]:
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0xc00018b890)
	/home/marler8997/go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x23c
panic(0x558fe4dfba80, 0x558fe507dda0)
	/home/marler8997/go/src/runtime/panic.go:513 +0x1bd
github.com/opencontainers/runc/libcontainer/specconv.CreateLibcontainerConfig(0xc00018b2b0, 0x558fe4ade782, 0xe, 0x0)
	/home/marler8997/go/src/github.com/opencontainers/runc/libcontainer/specconv/spec_linux.go:260 +0x7e9
main.createContainer(0xc00017e140, 0x7ffe97d3cb61, 0xb, 0xc000162150, 0xb, 0x0, 0x558fe48222d3, 0x0)
	/home/marler8997/go/src/github.com/opencontainers/runc/utils_linux.go:253 +0x146
main.startContainer(0xc00017e140, 0xc000162150, 0x2, 0x0, 0x0, 0xc000128600, 0x8)
	/home/marler8997/go/src/github.com/opencontainers/runc/utils_linux.go:426 +0x10c
main.glob..func13(0xc00017e140, 0x0, 0x0)
	/home/marler8997/go/src/github.com/opencontainers/runc/run.go:76 +0xb0
reflect.Value.call(0x558fe4de72c0, 0x558fe4e578d0, 0x13, 0x558fe4adb2ec, 0x4, 0xc0000e1850, 0x1, 0x1, 0xc0000840c0, 0xc00013e680, ...)
	/home/marler8997/go/src/reflect/value.go:447 +0x44b
reflect.Value.Call(0x558fe4de72c0, 0x558fe4e578d0, 0x13, 0xc0000e1850, 0x1, 0x1, 0xc0000e1830, 0x558fe4aa1eb8, 0x558fe4adb42c)
	/home/marler8997/go/src/reflect/value.go:308 +0xa6
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x558fe4de72c0, 0x558fe4e578d0, 0xc00017e140, 0x0, 0x0)
	/home/marler8997/go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x1fa
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x558fe4adb1ee, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x558fe4ae335e, 0x1a, 0x0, ...)
	/home/marler8997/go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0x908
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0xc000154180, 0xc000010090, 0x3, 0x3, 0x0, 0x0)
	/home/marler8997/go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x530
main.main()
	/home/marler8997/go/src/github.com/opencontainers/runc/main.go:165 +0xae7

**Comment by cyphar** [comment]
We already do an `if spec.Linux != nil` check earlier in the same function -- the code should've been in that block in the first place. Would you mind submitting a patch for it?

**Comment by marler8997** [comment]
I created a PR a couple weeks ago but it's not been looked at yet (#1890).  Is this normal for this repository?

**Comment by mikebrow** [comment]
I just reviewed it. Looks good but the repo has a requirement that commits be signed. Please sign and push -f it back up :-)
