### ISSUE TITLE
Documentation license - version

### ISSUE THREAD

**Issue by juliaszegedi** [opencontainers/runc#1902]
Hello,

Could you please help me with some additional information about the documentation license? The README.md file contains only the below mentioned details, without clarifying the version of the Creative Commons license. 

"Code and documentation copyright 2014 Docker, inc. Code released under the Apache 2.0 license. Docs released under Creative commons."

Thanks a lot in advance!

Best regards, 
Julia

**Comment by caniszczyk** [comment]
We need to update that blurb, it's left over from the initial contribution by Docker.

The terms are specified in the charter in section 8: https://www.opencontainers.org/about/governance

"a. All new inbound contributions to OCI will be made under the Apache License, Version 2.0 (available at http://www.apache.org/licenses/LICENSE-2.0) accompanied by a Developer Certificate of Origin sign-off (http://developercertificate.org). All contributions by Member employees will bind their employers in accordance with this policy, including the patent and copyright license grants in the Apache License, Version 2.0.

b. All outbound code and documentation will be made available under the Apache License, Version 2.0."

**Comment by juliaszegedi** [comment]
Thank you very much for the quick answer!

**Comment by cyphar** [comment]
#1903 has been merged.
