### ISSUE TITLE
rootless mode should ignore unwritable cgroupsPath

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#1927]
As of b1068fb9258d2cc5aa59505fbb703d914120013d , rootless runc (both non-root-in-the-initial-namespace and root-in-unprivileged-userns) fails when `cgroupsPath` is set to `/does/not/exist`

```
container_linux.go:337: starting container process caused "process_linux.go:280: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/cpuset/does/not/exist: permission denied\""
```

The current workaround is to just remove `cgroupsPath` (https://github.com/rootless-containers/usernetes/blob/a720bed2b08f34d9027c7afac04e53b9faa32bf0/build/patches/moby/0002-allow-running-dockerd-in-an-unprivileged-user-namesp.patch#L764), but it would be good to allow rootless runc to ignore unwritable cgroupsPath

**Comment by williammartin** [comment]
Hey @AkihiroSuda, what do you mean by "ignore unwritable cgroupsPath"? Silently carry on without applying cgroup constraints?

**Comment by AkihiroSuda** [comment]
Yes, as in the current other cgroup-related code.

But I'm wondering it might be inconsistent with the runtime spec https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#cgroups-path

> If the value is specified, the runtime MUST consistently attach to the same place in the cgroups hierarchy given the same value of cgroupsPath.

**Comment by williammartin** [comment]
It's been such a long time since I looked at runc I'm not sure I have useful context anymore, but it seems dangerous to silently not constrain containers?

**Comment by cyphar** [comment]
One of the big concerns I had over cgroup handling in rootless containers was that we mustn't silently ignore constraints, because that's just a CVE waiting to happen. Ignoring cgroupPath silently would do precisely this. NACK.

**Comment by AkihiroSuda** [comment]
Closing for now.

Probably instead we should provide some common `func IsCgroupPathSettable(string) (bool, error)` pkg in some repo that can be vendored by moby/containerd/crio/podman/buildah/....
