### ISSUE TITLE
 "args" in config.json can't have a parameter

### ISSUE THREAD

**Issue by liugenping** [opencontainers/runc#195]
when config.json's args like this, runc  will give a error.   
 "args": [
      "/bin/ps -a"
    ],

**Comment by rajasec** [comment]
exec.Lookpath in linux.go searches for search as complete string as exe "ps -a". so it will fail to look out for this exe in $PATH

**Comment by lizf-os** [comment]
The correct config is

"args": [
    "/bin/ps",
    "-a"
],

**Comment by liugenping** [comment]
Thanks ,   and I also have a doubt.  I use command "/bin/readlink  /proc/*/ns/*" is ok on  host,  but config in config.json and run return nothing.
"args": [
"/bin/readlink",
"/proc/*/ns/*"
],

**Comment by mrunalp** [comment]
@liugenping It is usually /proc/<pid>/ns, you could try /proc/self/ns or /proc/1/ns

**Comment by ashwani29** [comment]
@mrunalp , how can i run a custom cpp file or python program in runc ? what changes should I have to make in config.json if my cpp file is present inside root in the rootfs folder?
