### ISSUE TITLE
compile runc on arm64 centos 7 but hits unexpected directory layout error

### ISSUE THREAD

**Issue by ranchothu** [opencontainers/runc#1969]
i compile runc on centos golang 1.8.3 as follow:
`cd runc 
mkdir -p .gopath/src/github.com/opencontainers 
export GOPATH=$(pwd)/.gopath/ 
ln -sf $(pwd) .gopath/src/github.com/opencontainers/runc 
cd .gopath/src/github.com/opencontainers/runc 
make 'BUILDTAGS=seccomp selinux' static 
rm .gopath/src/github.com/opencontainers/runc 
rm -rf .gopath` 

and i get the follow error, go version is 1.8.3 
`make 
go build -i -ldflags "-X main.gitCommit="a638cc43f759f7fdb719f9c241c095f23e62c046" -X main.version=1.0.0-rc3" -tags "seccomp" -o runc . 
unexpected directory layout: 
        import path: github.com/Sirupsen/logrus 
        root: /home/cgl/docker_codehub/runc_v1.0.0_rc3/.gopath/src 
        dir: /home/cgl/docker_codehub/runc_v1.0.0_rc3/.gopath/src/github.com/opencontainers/runc/vendor/github.com/Sirupsen/logrus 
        expand root: /home/cgl/docker_codehub/runc_v1.0.0_rc3/.gopath/src 
        expand dir: /home/cgl/docker_codehub/runc_v1.0.0_rc3/vendor/github.com/Sirupsen/logrus 
        separator: / 
make: *** [runc] Error 1 
`

Anyone knows why? THKS

**Comment by renkam** [comment]
This is from logrus issues: https://github.com/sirupsen/logrus/issues/1041

**Comment by cyphar** [comment]
This is a really old issue, but you were trying to build 1.0.0-rc3 which is very old and used an older version of logrus where the import path was different.
