### ISSUE TITLE
Not able to use the native IP address for runc apache web server container.

### ISSUE THREAD

**Issue by ivinpolosony** [opencontainers/runc#198]
I am trying to checkpoint an apache webserver I did the following steps:
1) docker export apache > apache.tar 
2) untared to rootfs 
3) Used this config for native network.
https://gist.github.com/ivinpolosony/3fdbe2a93235099420cc
4) I am able to sh into the container.
but i am not able to do a curl like 127.0.0.1:8080 
What other changes should be made to the config file? 

When i am checkpointing it gives me 
 sudo runc checkpoint 
criu failed: type DUMP errno 0

**Comment by crosbymichael** [comment]
you can look at the dump logs in `/run/oci/<container_id>/criu.work/dump.log`

**Comment by boucher** [comment]
Maybe we should print the path of the log file on failure? The criu failed message is pretty useless on its own.

**Comment by crosbymichael** [comment]
Ya, that sounds like a good idea @boucher .  Either that or read out the log in `--debug` mode for the operation.

**Comment by boucher** [comment]
The log can be pretty big since we run in verbose mode always I think, but
we could print the tail. I'll try and write a PR for this today.

**Comment by ivinpolosony** [comment]
Got the checkpoint working. Thanks guys. How do u do port forwarding though. Mine is 80. Do i need to keep both the port same? i am trying to do something like docker run -p 80:8000
