### ISSUE TITLE
Separate linux-specific config from os-independent config

### ISSUE THREAD

**Issue by shykes** [opencontainers/runc#2]
As discussed, we like the idea of having 2 different kinds of configuration in the manifest: 1) os-specific config (for example: `create a new pid namespace`, or `set cgroup foo to bar`, or `drop CAP_SYSADMIN`), and 2) os-independent config (for example: `execute /bin/bash`, or `set environment DEBUG to 1`).

Currently these 2 different kinds of configs are mixed in the manifest. We should segment them more clearly, to make more visible the tradeoff between control and portability, and to allow for new sections to be created for other OSes - Windows, Solaris, FreeBSD etc.

**Comment by crosbymichael** [comment]
Closing this as we moved this work into https://github.com/opencontainers/specs/issues/7 and have made the separation.
