### ISSUE TITLE
Freezer in rootless containers

### ISSUE THREAD

**Issue by lfield** [opencontainers/runc#2003]
On Ubuntu 18.10 with runc 1.0.0 I am trying to pause a rootless container.
`runc --root state pause <id>`
but am getting the following error message: 
`no such directory for freezer.state`

**Comment by lifubang** [comment]
If you don't have the full access to cgroups, you'll get such error.

**Comment by lfield** [comment]
How do I get full access? I tried running the command as root and got the same error.

**Comment by lifubang** [comment]
> How do I get full access?
You can grant the access to the rootless user first. Please refer to:
https://github.com/opencontainers/runc/blob/master/tests/rootless.sh#L64-L85

> I tried running the command as root and got the same error.
Please provide your config.json, and rootfs.

**Comment by lfield** [comment]
ls rootfs/
bin  cvmfs  dev  home  lib  lib64  opt  proc  root  sbin  shared  srv  sys  tmp  usr  var

[config.json.txt](https://github.com/opencontainers/runc/files/2941475/config.json.txt)

**Comment by lifubang** [comment]
> I tried running the command as root and got the same error.

With your provided config.json, I can't reproduce your problem. I have no idea about there is an error when pause a container with root user. Sorry. I can't help you. Maybe other people can help you.
```
root@test:/opt/busybox# runc list
ID          PID         STATUS      BUNDLE                                            CREATED                          OWNER
test        20046       paused      /opt/busybox   2019-03-07T14:51:13.278691917Z   root
```

**Comment by lifubang** [comment]
> I tried running the command as root and got the same error.

One more question. You just only run `runc pause id` with root user? But the container is still a rootless container? In other words, you want to try to pause a rootless container with the root user?

**Comment by lfield** [comment]
Yes, if I start the container as root I can pause it.

**Comment by lifubang** [comment]
So, it's not the problem of runc. Because runc will ignore cgroup permission errors in container creating phase if you don't have the full access to cgroups. So, even you pause a rootless container with the root user, runc always can't find the cgroup path.
So , you can create rootless container with full access of cgroup path. Please refer to https://github.com/opencontainers/runc/blob/master/tests/rootless.sh#L64-L85

**Comment by lifubang** [comment]
> runc will ignore cgroup permission errors in container creating phase if you don't have the full access to cgroups.

And I think if runc can print these errors to user, it will be better.

**Comment by lfield** [comment]
I gave access to the cgroup path as indicated in the code [snippet](https://github.com/opencontainers/runc/blob/master/tests/rootless.sh#L64-L85).  I now get the following message running as both root and non-root user.
```
 runc  --root state pause <id>
failed to write FROZEN to freezer.state: open /sys/fs/cgroup/freezer/freezer.state: permission denied
```
This error message seems more meaningful.

**Comment by lfield** [comment]
I used that code snippet to create a cgroup boinc and would expect it to use the file:
`/sys/fs/cgroup/freezer/boinc/freezer.state`
but as you can see from the error message it is not using that location. How do you tell runc to use that cgroup?

**Comment by lifubang** [comment]
You should add `"cgroupsPath": "/runc-cgroups-integration-test/boinc"` in linux section in config.json

**Comment by lfield** [comment]
Thanks. It is working now. I guess the two issues are that the original error message ` no such directory for freezer.state` didn't help me to understand the issue and that certain features need a cgroup when using rootless containers.

**Comment by lifubang** [comment]
You can force runc don't ignore the cgroup error with `--rootless=false`. For example:
```
test@iZ2ze1o61blvco5p5ducnnZ:~/busybox$ runc --root ./runc --rootless=false create test2
container_linux.go:345: starting container process caused "process_linux.go:276: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/cpuset/test2: permission denied\""
```

If you have any other questions, I think this issue can be closed.

**Comment by lifubang** [comment]
You can use `runc --help` to view the usage of `--rootless`.

**Comment by lfield** [comment]
I think the issue is that the message ` no such directory for freezer.state` did not help to understand the problem. Feel free to close this issue but others may also be confused.
