### ISSUE TITLE
Fatal error: 'sys/statfs.h' file not found

### ISSUE THREAD

**Issue by jxub** [opencontainers/runc#2011]
While running `go get -v github.com/opencontainers/runc` on MacOS 10.14 with Golang 1.12 I get the following output and `go get` fails:
```
github.com/opencontainers/runc (download)
github.com/opencontainers/runc/libcontainer/nsenter
github.com/opencontainers/runc/vendor/golang.org/x/sys/unix
github.com/opencontainers/runc/libcontainer/stacktrace
github.com/opencontainers/runc/vendor/github.com/opencontainers/runtime-spec/specs-go
github.com/opencontainers/runc/vendor/github.com/sirupsen/logrus
github.com/opencontainers/runc/vendor/github.com/urfave/cli
github.com/opencontainers/runc/libcontainer/configs
# github.com/opencontainers/runc/libcontainer/configs
/Users/jakub/go/src/github.com/opencontainers/runc/libcontainer/configs/config.go:128:11: undefined: Cgroup
github.com/opencontainers/runc/libcontainer/utils
# github.com/opencontainers/runc/libcontainer/utils
/Users/jakub/go/src/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go:39:62: undefined: unix.SOCK_CLOEXEC
# github.com/opencontainers/runc/libcontainer/nsenter
cloned_binary.c:30:10: fatal error: 'sys/statfs.h' file not found
```
Could someone shed some light on that? I guess it's related to some headers missing on my system.
The one in question is here: https://github.com/opencontainers/runc/blob/master/libcontainer/nsenter/cloned_binary.c#L30

I found someone had the same issue with a different project: https://github.com/jbenet/go-fuse-version/issues/1

**Comment by cyphar** [comment]
We don't support `runc` for OS X, because OS X doesn't have kernel support for any of the features we need -- so it's unsurprising there are a bunch of compilation errors, since it's a target we simply cannot support.

**Comment by jxub** [comment]
Thanks for the explanation @cyphar and sorry for not noticing that (just seen it's in the README) 👍
