### ISSUE TITLE
Can runc take its configuration on stdin?

### ISSUE THREAD

**Issue by stuartpb** [opencontainers/runc#202]
It would be nice if there is a way to run `runc` with a configuration specified via stdin (for those of us with systems that build their container commands on the fly, although we'd prefer command-line overrides). If you're set on using `runc` to parse `config.json` in the working directory, then I'd settle for `runc -` to read the configuration from stdin.

**Comment by wking** [comment]
On Fri, Aug 14, 2015 at 09:49:08AM -0700, Stuart P. Bentley wrote:
> It would be nice if there is a way to run `runc` with a
> configuration specified via stdin (for those of us with systems that
> build their container commands on the fly, although we'd prefer
> command-line overrides). If you're set on using `runc` to parse
> `config.json` in the working directory, then I'd settle for `runc -`
> to read the configuration from stdin.

I expected /dev/stdin to work here, but for some reason it doesn't:

  # runc /dev/stdin <config.json
  FATA[0000] Container start failed: inappropriate ioctl for device 

That's with a build of v0.0.3 anyway.

**Comment by laijs** [comment]
@wking /dev/stdin actually works, and it works well.

```
# runc /dev/stdin <config.json
FATA[0000] Container start failed: inappropriate ioctl for device
```
The failure reason is that the container needs the terminal, but the /dev/stdin in not the terminal.
After the config.json is changed (```"terminal": false,```), the command ```runc /dev/stdin <config.json```

So @stuartpb can disable the terminal of the container and use the way as @wking suggested

**Comment by wking** [comment]
On Tue, Aug 18, 2015 at 07:22:55PM -0700, Lai Jiangshan wrote:
> The failure reason is that the container needs the terminal, but the
> /dev/stdin in not the terminal.

Ah, thanks for clearing me up.  I should have straced it ;), but we
might want to catch this and return a more specific error in this
case.

**Comment by laijs** [comment]
Yep, the runc should check the fd/0 fd/1 fd/2 before running the container if terminal==true
I add this to my todo list

**Comment by crosbymichael** [comment]
@stuartpb i don't know if this would be a good idea to pass configs via stdin because runc will use it's current STDIO as the containers IO.  So if we pass the config via STDIN you couldn't do things like `cat hello | runc`

to cat something into the container's process.

**Comment by wking** [comment]
On Fri, Aug 21, 2015 at 11:36:51AM -0700, Michael Crosby wrote:
> i don't know if this would be a good idea to pass configs via stdin
> because runc will use it's current STDIO as the containers IO.

You currently use ‘runc config.json’ if you want to explicitly specify
your config path.  With #210 that will become ‘runc start
config.json’, and @duglin [1] and I [2] both hope to see ‘runc
--config config.json COMMAND’ at some point.

But that doesn't mean that you shouldn't be able to use stdin for that
purpose if it's more convenient for you (e.g. your shell doesn't
support process substitution and you don't care about consuming the
container's stdin before the application is launched).

[1]: https://github.com/opencontainers/runc/pull/210#issuecomment-132265820
[2]: https://github.com/opencontainers/runc/pull/210#issuecomment-132265217

**Comment by tv42** [comment]
So use an fd that isn't stdin!

```console
$ echo foo >bar
$ sh -x -c 'cat $0' /dev/fd/6 6<bar
+ cat /dev/fd/6
foo
$ 
```

**Comment by crosbymichael** [comment]
I think we can close this one now.  In the latest spec updates we have more than one configuration and we want that to be more immutable so accepting something on stdin does not help this.  Like my previous comment since we dup the runc stdio this will cause issues for other use cases.
