### ISSUE TITLE
runc fails with "invalid argument" on Travis as of commit dd22a84

### ISSUE THREAD

**Issue by reidpr** [opencontainers/runc#2024]
We have some Travis builds that use `runc`. Today they started failing with ([e.g.](https://travis-ci.org/hpc/charliecloud/jobs/509482581), line 460):

```
   error running container: error creating container for [/bin/sh -c apk add --no-cache bc]: container_linux.go:345: starting container process caused "set process label: write /proc/self/task/1/attr/exec: invalid argument"
```

We install via the Project Atomic PPA, which I believe is a pretty light autobuild of this GitHub source. I'm pretty sure this happened when the Debian package provided by the Project Atomic PPA changed from version `1.0.0-rc6-1~ubuntu16.04.2~ppa72` (commit f56b4cb) to `1.0.0-rc6-1~ubuntu16.04.2~ppa73` (commit dd22a84).

Normally I would not report packaged bug upstream, but I'm seeing a similar-looking issue in your own tests: https://travis-ci.org/opencontainers/runc/jobs/509259627

Thanks for your hard work on runc. Please let me know how I can help.

**Comment by reidpr** [comment]
Possible duplicate of #2030?

**Comment by thaJeztah** [comment]
If it's the same, the SELinux dependency was updated in https://github.com/moby/moby/issues/38997

**Comment by reidpr** [comment]
So now I have a different error in our Travis build (package version `1.0.0-rc6-1~ubuntu16.04.2~ppa77`, commit 029124d):

```
error running container: error creating container for [/bin/sh -c apk add --no-cache bc]: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"sysfs\\\" to rootfs \\\"/tmp/buildah161887079/mnt/rootfs\\\" at \\\"/sys\\\" caused \\\"operation not permitted\\\"\""
```

That one sounds more like some sort of configuration or user error. It did used to work though. I'll investigate further.

Feel free to close this issue if you feel that's appropriate.

**Comment by reidpr** [comment]
Adding the following environment variables did the trick:

```
export BUILDAH_ISOLATION=rootless
export STORAGE_DRIVER=vfs
```

Closing.
