### ISSUE TITLE
Forgot to bump version in v0.0.3

### ISSUE THREAD

**Issue by wking** [opencontainers/runc#203]
Both the [current master][1] and the [tagged v0.0.3][2] have `0.2` as their version.  Is that value intended to match the runC tag?

[1]: https://github.com/opencontainers/runc/blob/744a6b0e7bd3aa1d2985060170040392be3e94e3/main.go#L11
[2]: https://github.com/opencontainers/runc/blob/v0.0.3/main.go#L11

**Comment by LK4D4** [comment]
@wking It wasn't intented, we use tags only for libcontainer now. Though I think that hardcoding versions is bad, it should be set on build from commit.

**Comment by wking** [comment]
On Fri, Aug 14, 2015 at 11:06:40AM -0700, Alexander Morozov wrote:
> @wking It wasn't intented, we use tags only for libcontainer
> now.

Are libcontainer and runC going to be versioned independently?  That
seems awkward if both are in the same repository.

> Though I think that hardcoding versions is bad, it should be
> set on build from commit.

+1 for that.

**Comment by wking** [comment]
On Fri, Nov 20, 2015 at 01:45:57PM -0800, Alexander Morozov wrote:
> Closed #203 via #410.

Hmm, #410 took this (the runC version number?) from 0.3 to 0.0.5.
Does that mean the plan going forward is to version libcontainer and
runC as a single entity?  I think that makes more sense with them in
the same repo [1], but it sounded like the previous plan was for
independent versioning [2].

[1]: https://github.com/opencontainers/runc/issues/203#issuecomment-131200247
[2]: https://github.com/opencontainers/runc/issues/203#issuecomment-131196853

**Comment by tianon** [comment]
Yeah, this whole repo really has to have a single version number -- nothing
else even could make sense IMO unless libcontainer gets its own repository
again.
