### ISSUE TITLE
500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout:

### ISSUE THREAD

**Issue by RohitJain88** [opencontainers/runc#2053]
While trying to run the docker container I am facing 500 Internal Server Error

**Comment by RohitJain88** [comment]
HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.40/containers/8a3fb46d6e69bd8da34a8928035cadd9622f937a67ba9c2f2d0964aa0952484d/start

**Comment by cyphar** [comment]
Please submit this to the Docker bug-tracker (https://github.com/moby/moby).

**Comment by cyphar** [comment]
Oh wait, I didn't notice you changed the title. Docker doesn't usually use hooks -- are you on a RedHat machine (they have a bunch of OCI hooks set up to run underneath Docker)? If so, submit a bug report to Red Hat.

**Comment by RohitJain88** [comment]
Thanks for the reply. I am using Ubuntu Data Science Virtual Machine provided by Microsoft Azure to run the docker container using python. Let me know if you need any further details.
