### ISSUE TITLE
Is runc root required to be on tmpfs?

### ISSUE THREAD

**Issue by danail-branekov** [opencontainers/runc#2054]
Hi runc,

According to `runc --help`

```
--root value        root directory for storage of container state (this should be located in tmpfs) (default: "/run/runc")
```

It seems that this comment has been available in runc since the beginning. We are wondering whether having the root on tmpfs is a nice place to have things (because of e.g. performance considerations), or this is a runc functional requirement. Should we expect any problems (besides performance degradation) if we
switched to a directory that is not on tmpfs?

cc @crosbymichael @Callisto13

**Comment by cyphar** [comment]
We don't require it to be on a `tmpfs` (in fact the default setup on most distributions is such that `/run/runc` is actually on the `/` filesystem). It's mostly a performance thing, as well as avoiding people running `runc` with the root being on NFS or something similarly bad.

**Comment by danail-branekov** [comment]
Thanks, @cyphar , that is good to know. 
Closing as question is now answered
