### ISSUE TITLE
Runc + podman|cri-o + systemd issue with stderr

### ISSUE THREAD

**Issue by alitvak69** [opencontainers/runc#2056]
Runc cannot open stderr 

open /dev/stderr: no such device or address

Issue is tracked in 
https://github.com/kubernetes/kubernetes/issues/77615

Devs of kubernetes think it is a runc issue, so I thought reference it here for you to take a look.

**Comment by giuseppe** [comment]
it is a regression introduced by: a1460818288b8addfe9b70c8931da83864251f7a
