### ISSUE TITLE
could not ensure we are a cloned binary: Device or resource busy

### ISSUE THREAD

**Issue by tonistiigi** [opencontainers/runc#2059]
Getting reports on buildkit about this error showing up occasionally.

```
nsenter: could not ensure we are a cloned binary: Device or resource busy
container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\""
```

https://github.com/moby/buildkit/files/3184283/exit_code1_1.log
https://github.com/moby/buildkit/files/3184284/exit_code1_2.log
https://github.com/moby/buildkit/issues/991

Runc version in current BuildKit: 6635b4f0c6af3810594d2770f662f34ddc15b40d

Note that the way runc is invoked in buildkit is with `runc run`, not `runc create/start`. May or may not be significant.

**Comment by tonistiigi** [comment]
@cyphar @crosbymichael @msg555

**Comment by msg555** [comment]
Currently this issue happens during buildkit runs on an AWS r4.large machine running Ubuntu 16.04. Here's some basic info about the machine:

```
$ uname -a
Linux awsrunner7 4.4.0-1079-aws #89-Ubuntu SMP Tue Mar 26 15:25:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -c
Codename:    xenial
$ df -Th / /olympus
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/xvda1     ext4  7.7G  4.0G  3.8G  52% /
/dev/xvdb      ext4  394G  166G  211G  44% /olympus
$ docker --version
Docker version 18.03.1-ce, build 9ee9f40
```

runc is being invoked from a docker container based on the `moby/buildkit:v0.5.1` image started with the `--privileged` flag.

**Comment by cyphar** [comment]
You should update to v1.0.0-rc8. There were a lot of changes made to the `cloned_binary` code in order to work around a bunch of other issues.

**Comment by msg555** [comment]
It seems like updating the runc version did address the problem we were seeing.

**Comment by thaJeztah** [comment]
I'm guessing this was resolved now; let me close
