### ISSUE TITLE
Unable to mount nfs with config.json

### ISSUE THREAD

**Issue by vmexit** [opencontainers/runc#2060]
Hi runc, 

After I have started the container, I can do 
"mount -t nfs4 nfs_server:/nfs_server nfs_client" to mount 
a remote nfs directory. 

However, I cannot specify the nfs mnt with the config.json. 
After adding the following to the mount section of config.json:
                {
                        "destination": "/nfs_client",
                        "type": "nfs4",
                        "source": "nfs_server:nfs_server"
                }

When the container starts, it complains: 

container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"nfs_server:/nfs_server\\" to rootfs \\\"/root/container/rootfs\\\" at \\\"/root/container/rootfs/nfs_client\\\" caused \\\"invalid argument\\\"\""

Any idea what's going on? And is there anything I can do to get additional 
debugging information? 

Thanks in advance for your help!

**Comment by cyphar** [comment]
I looked into this, and it seems that internally `mount(1)` does a bunch of resolution and then includes a few additional mount options that are required in order for the share to be mounted.

```
% strace -s 4096 mount -t nfs deku.dot.cyphar.com:/megalos /media/megalos
[pid 30330] mount("deku.dot.cyphar.com:/megalos", "/media/megalos", "nfs", 0, "vers=4.2,addr=10.42.10.128,clientaddr=10.42.20.109") = 0
```

So you need to include those options in order for it to work (though I'm not sure how `clientaddr` should work with containers). It should also be noted that `mount(1)` also makes a few other changes (such as adding an entry to `/run/mount/utab`) which `runc` won't do.

**Comment by vmexit** [comment]
@cyphar Thank
