### ISSUE TITLE
localunittest error

### ISSUE THREAD

**Issue by zhlhahaha** [opencontainers/runc#2083]
Recently I ran make localunittest on host and met following error:

`checkpoint_test.go:70: copy error "exit status 1": "cp: cannot stat '/busybox/*': No such file or directory\n"
=== RUN   TestCheckpoint
--- FAIL: TestCheckpoint (0.01s)
    checkpoint_test.go:70: copy error "exit status 1": "cp: cannot stat '/busybox/*': No such file or directory\n"
=== RUN   TestExecPS
--- FAIL: TestExecPS (0.01s)
    utils_test.go:55: exec_test.go:40: unexpected error: copy error "exit status 1": "cp: cannot stat '/busybox/*': No such file or directory\n"

=== RUN   TestUsernsExecPS
--- FAIL: TestUsernsExecPS (0.01s)
    utils_test.go:55: exec_test.go:40: unexpected error: copy error "exit status 1": "cp: cannot stat '/busybox/*': No such file or directory\n"

=== RUN   TestIPCPrivate
--- FAIL: TestIPCPrivate (0.01s)
    utils_test.go:55: exec_test.go:73: unexpected error: copy error "exit status 1": "cp: cannot stat '/busybox/*': No such file or directory\n"

=== RUN   TestIPCHost
--- FAIL: TestIPCHost (0.01s)
    utils_test.go:55: exec_test.go:98: unexpected error: copy error "exit status 1": "cp: cannot stat '/busybox/*': No such file or directory\n"`

It causes by missing /buxybox. I found the busybox environment is only built in Dockfile, which means if we ran localunittest on the host directly, this error will appear.

I am not sure if it is necessary to add an patch on it.

**Comment by cyphar** [comment]
Yeah, this is how our tests are written -- maybe it would be nice to make it neater, but none of us really have time to fix it up. If you would like to, feel free to send a patch.
