### ISSUE TITLE
Test suite showing errors: TestUsernsCheckpoint

### ISSUE THREAD

**Issue by GinesGarcia** [opencontainers/runc#2092]
Hi,
I found some of the tests in a failed status. The steps I followed to compile runc and tests are the following: 
```
make clean
make BUILDTAGS='seccomp apparmor'
sudo make install
sudo make test
```

Attached you can also find the complete log of the tests.

[tests.log](https://github.com/opencontainers/runc/files/3446253/tests.log)

Do you know where the problem could be? is there any way of getting a more complete log when executing the test suite?

Moreover, I'm trying to play a little bit with seccomp profiles and open containers. I've been following [this](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#seccomp) part of the documentation but I'm not able to corretly "limit" the syscalls that appears in the example. I can run a simple container with all the seccomp rules added to config.json but they have no effect.

Thanks in advance,
Ginés.

**Comment by AkihiroSuda** [comment]
Is this still an issue on master?
