### ISSUE TITLE
Optimize writeFile function usage in libcontainer/cgroups/fs

### ISSUE THREAD

**Issue by fristonio** [opencontainers/runc#2115]
There are a lot of places in `libcontainer/cgroups/fs` where the usage of `writeFile` function can be optimised. For example here https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/blkio.go#L44-L51
the function call to `writeFile` is made for each entry in the slice `BlkioWeightDevice`, which in turn opens and closes file for each entry. This can be optimised by joining all the strings and then writing only once.
I haven't looked around much but this might be the case at other places too.

PS: Let me know if you need help with this, I will be happy to send a Pull Request.

**Comment by mattbonnell** [comment]
I can take a stab at this, will work on a PR

**Comment by kolyshkin** [comment]
> This can be optimised by joining all the strings and then writing only once.

Joining the strings might result in increased memory footprint. It might be better to find a solution to write a set of strings to a file in some way, or just do usual open / for ... write / close

**Comment by mattbonnell** [comment]
> or just do usual open / for ... write / close

This is the approach I’m taking, yeah.

**Comment by mattbonnell** [comment]
In light of @cyphar's investigations into the kernel source, it seems these interfaces can only accept one entry at a time, anyways. I think this issue can be closed.

**Comment by kolyshkin** [comment]
Closing as per https://github.com/opencontainers/runc/pull/2568#issuecomment-682472705
