### ISSUE TITLE
runc nginx issues -- portmapping

### ISSUE THREAD

**Issue by chenliu1993** [opencontainers/runc#2127]
Hi all,
    I am using runc to run a nginx:latest container rootfs using commnd "runc run --no-pivot nginx-1" and I can get the output of "runc list" showing that ngin-1 is running. But I cannot access the welcome page for nginx. It always gives me a connection refused failure. I try to change the port in rootfs/etc/nginx/conf.d/default.conf, but it did not help. 
    I noticed that there is one issue about port mapping in runc. I follow the instruction and remove the "network" ns in config.json. Besides I add hosts and resolv.conf file. Still doesn't take effect. While Pinging the IP of container from inside and outside are both OK
    How can I access the page?
    But When I using Docker, Welcome page is OK to see.
    My env is Ubuntu 18.09 VM 
   Linux ubuntu 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
  Tell me if you need more info.

**Comment by chenliu1993** [comment]
Sorry, I found the problem

**Comment by jedrekdomanski** [comment]
@chenliu1993 Can you share how you solved your problem? :)

**Comment by chenliu1993** [comment]
> @chenliu1993 Can you share how you solved your problem? :)

Hi sorry for the late reply. But it has been too long... I cannot remeber either how I fixed this issue.
