### ISSUE TITLE
OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \\\"process_linux.go:396: setting cgroup config for procHooks process caused \\\\\\\"failed to write 100000 to cpu.cfs_period_us

### ISSUE THREAD

**Issue by etcshad0vv** [opencontainers/runc#2142]
Hello,

I am facing below error on my environment, and doesn't seem to be somehow reproducible. 

`Oct 16 14:24:19 agnsrlnicp1n10 hyperkube[1421]: E1016 14:24:19.003982    1421 kuberuntime_manager.go:744] container start failed: RunContainerError: failed to start container "a52afb440febae5ffc83430349aa38b801bbf4de331dcd124af4d63695f72b5a": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"process_linux.go:396: setting cgroup config for procHooks process caused \\\"failed to write 100000 to cpu.cfs_period_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods/pod248fb7bf-f05b-11e9-8ad1-005056b7990b/a52afb440febae5ffc83430349aa38b801bbf4de331dcd124af4d63695f72b5a/cpu.cfs_period_us: invalid argument\\\"\"": unknown
Oct 16 14:24:19 agnsrlnicp1n10 hyperkube[1421]: E1016 14:24:19.004037    1421 pod_workers.go:186] Error syncing pod 248fb7bf-f05b-11e9-8ad1-005056b7990b ("sla-collector-77cbd9cbb9-9q88h_sladev(248fb7bf-f05b-11e9-8ad1-005056b7990b)"), skipping: failed to "StartContainer" for "collector" with RunContainerError: "failed to start container \"a52afb440febae5ffc83430349aa38b801bbf4de331dcd124af4d63695f72b5a\": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \\\"process_linux.go:396: setting cgroup config for procHooks process caused \\\\\\\"failed to write 100000 to cpu.cfs_period_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods/pod248fb7bf-f05b-11e9-8ad1-005056b7990b/a52afb440febae5ffc83430349aa38b801bbf4de331dcd124af4d63695f72b5a/cpu.cfs_period_us: invalid argument\\\\\\\"\\\"\": unknown"`

**docker info**
```
Client:
 Debug Mode: false

Server:
 Containers: 98
  Running: 64
  Paused: 0
  Stopped: 34
 Images: 136
 Server Version: 18.09.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-164-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 62.9GiB
 Name: agnsrlnicp1n09
 ID: F23N:UDME:KMLU:U4UB:ZUA4:4Y2A:N7RU:6X5M:EO57:KOOA:D57P:RYT5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://100.64.69.4:8080/
 HTTPS Proxy: http://100.64.69.4:8080/
 No Proxy: localhost,127.0.0.1,local,local:8500
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

root@agnsrlnicp1n09:~# runc --version
runc version 1.0.0-rc8
commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
spec: 1.0.1-dev
root@agnsrlnicp1n09:~# docker info
Client:
 Debug Mode: false

Server:
 Containers: 98
  Running: 64
  Paused: 0
  Stopped: 34
 Images: 136
 Server Version: 18.09.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-164-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 62.9GiB
 Name: agnsrlnicp1n09
 ID: F23N:UDME:KMLU:U4UB:ZUA4:4Y2A:N7RU:6X5M:EO57:KOOA:D57P:RYT5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://100.64.69.4:8080/
 HTTPS Proxy: http://100.64.69.4:8080/
 No Proxy: localhost,127.0.0.1,local,local:8500
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

Distribution: **Ubuntu 16.04**
Kernel Version: **4.4.0-164-generic**
```
runc --version
runc version 1.0.0-rc8
commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
spec: 1.0.1-dev
```

**Comment by shqear93** [comment]
Any updates here? !

**Comment by ezamorad** [comment]
Hi. 
I have been experiencing this issue for some weeks now.
I'd appreciate some related information and fix.

**Comment by cyphar** [comment]
Can you provide some more information -- such as how often this happens, what type of workload you're trying to run, and so on. It's a bit difficult to figure out the root cause of an issue where the bug report says that the problem isn't reproducible.

In the hopes of finding something out, I checked where you can get an `EINVAL` from when setting `cfs_period_us` but it didn't really help too much:

* If the `cfs_period_us` value would overflow a u64 when represented in nanoseconds -- which isn't true for `100000`.
  ```
	if ((u64)cfs_period_us > U64_MAX / NSEC_PER_USEC)
		return -EINVAL;
  ```

* If the cgroup being set is the root cgroup, which definitely isn't true
  ```
	if (tg == &root_task_group)
		return -EINVAL;
  ```

* If the period is smaller than `min_cfs_quota_period` (`1ms`) -- but `100000us` is `100ms`.
  ```
	/*
	 * Ensure we have at some amount of bandwidth every period.  This is
	 * to prevent reaching a state of large arrears when throttled via
	 * entity_tick() resulting in prolonged exit starvation.
	 */
	if (quota < min_cfs_quota_period || period < min_cfs_quota_period)
		return -EINVAL;
  ```

* If the period is larger than `max_cfs_quota_period` (`1s`) -- but `100000us` is `100ms`.
  ```
	/*
	 * Likewise, bound things on the otherside by preventing insane quota
	 * periods.  This also allows us to normalize in computing quota
	 * feasibility.
	 */
	if (period > max_cfs_quota_period)
		return -EINVAL;
  ```

And that's it. All the other `EINVAL`s within the `cpu` cgroup code are unrelated to setting `cfs_period_us`. So given that I can't tell what error path might be being hit, there's not much I can do without any more information. This could be a kernel bug for all I know.

**Comment by etcshad0vv** [comment]
@cyphar thanks for your response, could this be related to https://github.com/kubernetes/kubernetes/issues/72878 ? Unfortunately the patch of the kernel is not backported and I will not be able to test this kernel.

**Comment by etcshad0vv** [comment]
Closing the issue, after kernel was patched. Issue no longer exists.
