### ISSUE TITLE
cgroup2: eBPF device controller

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2144]
https://github.com/AkihiroSuda/runc/commits/ebpf

I'm trying to port over [`libcrun/ebpf.c` from crun v0.10.2](https://github.com/containers/crun/blob/0.10.2/src/libcrun/ebpf.c), which is licensed under LGPL3 (or later) and incompatible with Apache License 2.0

@giuseppe Do you think my code should be treated as a derivative of your C code? If so, any chance to relicense `ebpf.c` and `cgroup.c` as Apache License 2.0?

**Comment by giuseppe** [comment]
I am fine to relicense these two files under the Apache License 2.0 license

**Comment by AkihiroSuda** [comment]
thanks!

**Comment by AkihiroSuda** [comment]
PR: https://github.com/opencontainers/runc/pull/2145
