### ISSUE TITLE
sharing glibc and ld /ldconfig with container to run busybox

### ISSUE THREAD

**Issue by mtayyab01** [opencontainers/runc#2153]
On my desktop machine I built busybox docker image and exported its rootfs for runc. runc could successfully start the container. 
I exported the rootfs to an embedded platform running Linux Kernel 3.18 (compiled with all of the needed flags). runc could not start container and complained about "no such file and directory" . 
After a while, the issue was related to missing libc and ld on container rootfs. After copying those libraries from host to the container rootfs, it worked.

My question is that how could we share these basic host libraries with runc Container to even start the execution of container? Or while building OCI image, those libraries should be packed inside it?

**Comment by AkihiroSuda** [comment]
> Or while building OCI image, those libraries should be packed inside it?

Yes.

You may also try bind-mounting, but not the standard way to solve this issue.
