### ISSUE TITLE
README.md: add repo deps

### ISSUE THREAD

**Issue by apparluk** [opencontainers/runc#2162]
hadn't read the entirety of the README.md

mark as irrelevant

closed

**Comment by tianon** [comment]
I'm confused, isn't that the point of the existing `vendor.conf` file?

**Comment by apparluk** [comment]
under [Releases](https://github.com/opencontainers/runc#releases) appears a hyperlink to a sibling repository

under [Dependencies Management](https://github.com/opencontainers/runc#dependencies-management) appears a reference to vndr, _i.e._, vendor.conf

the misdirection on my end would perhaps not have been encountered

had **Releases** and **Security** been placed below **License**

you might add a hyperlink as in the following line

you will need to install [libseccomp](https://github.com/seccomp/libseccomp) on your platform

on a side note the Linux distro I run doesn't use systemd

**Comment by apparluk** [comment]
T. Gravi

owing to my misdirection, you're welcome to close
