### ISSUE TITLE
cgroup2: systemd manager uses deprecated options

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2164]
https://github.com/opencontainers/runc/blob/e57a774066af2f0adc76ffb6201588091cd872d5/libcontainer/cgroups/systemd/unified_hierarchy.go#L99-L132

According to [`systemd.resource-control(5)`](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html), `CPUShares`, `MemoryLimit`, and `BlockIOWeight` are deprecated

**Comment by AkihiroSuda** [comment]
cc @filbranden

**Comment by AkihiroSuda** [comment]
I think unified manager can depend on recent version of systemd (v242-v243). RHEL 7 doesn't support unified mode.

**Comment by filbranden** [comment]
Yes! Definitely agree with that for "unified" driver.

**Comment by rhatdan** [comment]
RHEL7 will never support cgroups V2, so that makes sense.
