### ISSUE TITLE
Consider switching to go modules

### ISSUE THREAD

**Issue by saschagrunert** [opencontainers/runc#2171]
Hey, I see no open issue related to a go module migration yet. I would like to propose the update of go-systemd/v22 inside this repository, but It seems that vndr does not support versioned import paths like `github.com/coreos/go-systemd/v22`.

One way to solve this would be switching to go modules. WDYT?

Refers to https://github.com/kubernetes/kubernetes/pull/85097

**Comment by odinuge** [comment]
Also ref. https://github.com/opencontainers/runc/pull/2073

**Comment by AkihiroSuda** [comment]
done
