### ISSUE TITLE
nginx webserver starts but it doesn't work

### ISSUE THREAD

**Issue by farso92** [opencontainers/runc#2178]
i'm trying to create a webserver with runC and nginx but even if the container is started it doesn't work. I can't reach it on my browser. I run this command:
```
mkdir -p /containers/webserver1/rootfs
cd /containers/webserver1
docker create --name webserver -p 32788:80 nginx
docker export webserver > temp.tar
tar -xvf temp.tar -C rootfs/
rm temp.tar
runc spec
nano config.json
///////////// i made this changes: "terminal" : false and "args": ["sleep", "300"]
runc create webserver1
runc start webserver1
```
the containers starts but i can't reach it on localhost:32788
what m i doing wrong?
thank you

**Comment by AkihiroSuda** [comment]
You need to either remove `"type": "network"` from `.linux.namespaces` (insecure) or set up port forwarder.
