### ISSUE TITLE
Restoring a container with host network brings down the host's network

### ISSUE THREAD

**Issue by vincent-163** [opencontainers/runc#2181]
I performed the following steps:
1. Run `runc spec` to create a default configuration file, remove `"type": "network"` entry in `linux.namespaces`, set rootfs to a Linux image.
2. Run `runc run x` to run the container, verify that the network configuration is exactly the same as the host. `ip link` and `ip addr` show identical results with the host, and commands that use network works.
3. Run `runc checkpoint x` to checkpoint the container. The container gets killed.
4. Run `runc restore x` to restore the container. The processes in the container work fine, but the host's network becomes inaccessible. `ping` shows the error `ping: sendmsg: Operation not permitted`, and all TCP connections timeout (even on loopback).

Expected behavior: The host's network should continue to work.

**Comment by adrianreber** [comment]
This is probably related to CRIU locking the network. However, I remember this being fixed in CRIU for some time. Which CRIU version are you using? Please try it with the latest version.

**Comment by vincent-163** [comment]
Indeed. I was using criu 3.6 from the Ubuntu repository, and by building criu-3.13 from source the problem went away. Thanks!
