### ISSUE TITLE
armv7 code build errors 

### ISSUE THREAD

**Issue by vastchen** [opencontainers/runc#2194]
in armv7 gentoo build runc error

>>> Compiling source in /var/tmp/portage/app-emulation/runc-1.0.0_rc9/work/runc-1.0.0_rc9 ...
make -j5 'BUILDTAGS=ambient seccomp' -C src/github.com/opencontainers/runc
make: Entering directory '/var/tmp/portage/app-emulation/runc-1.0.0_rc9/work/runc-1.0.0_rc9/src/github.com/opencontainers/runc'
fatal: not a git repository (or any of the parent directories): .git
go build -buildmode=pie  -ldflags "-X main.gitCommit="" -X main.version=1.0.0-rc9 " -tags "ambient seccomp" -o runc .
import cycle not allowed
package github.com/opencontainers/runc
        imports bytes
        imports errors
        imports internal/reflectlite
        imports runtime
        imports internal/bytealg
        imports internal/cpu
        imports runtime
make: *** [Makefile:30: runc] Error 1
make: Leaving directory '/var/tmp/portage/app-emulation/runc-1.0.0_rc9/work/runc-1.0.0_rc9/src/github.com/opencontainers/runc'
 * ERROR: app-emulation/runc-1.0.0_rc9::gentoo failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=app-emulation/runc-1.0.0_rc9::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/runc-1.0.0_rc9::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/app-emulation/runc-1.0.0_rc9/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/runc-1.0.0_rc9/temp/environment'.
 * Working directory: '/var/tmp/portage/app-emulation/runc-1.0.0_rc9/work/runc-1.0.0_rc9'
 * S: '/var/tmp/portage/app-emulation/runc-1.0.0_rc9/work/runc-1.0.0_rc9'

how to slow?

**Comment by cyphar** [comment]
That import cycle is happening within the Go stdlib. Can you compile this program:

```
import "bytes"

func main() {
    buf := bytes.NewBuffer(nil)
}
```

If you can't, then there's something wrong with the standard library on `armv7` and you should either report it to the Gentoo folks, or to the Golang folks.

**Comment by cyphar** [comment]
Also I would suggest reporting these kinds of issues to Gentoo directly -- I'm not a Gentoo user and so I can't really help you all that much. If the Gentoo package maintainer thinks that we need to fix something, they can always open an issue.

**Comment by vastchen** [comment]
slow it is longtime ago set local golang so can't get really version.
