### ISSUE TITLE
cgroup2: TODO list

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2209]
# EDIT: this tracker was superseded by https://github.com/opencontainers/runc/issues/2315

**Comment by AkihiroSuda** [comment]
Attempting to implement support for systemd user instances, but godbus seems to require extra `dbus-launch` binary, which is included in `dbus-x11` dpkg on Ubuntu :cry: https://github.com/godbus/dbus/blob/06fc4b473149e499166adbb9e31c7365a8ea146f/conn_other.go#L20

**Comment by AkihiroSuda** [comment]
Trying to implement the support for rootless systemd, but still got stuck because godbus doesn't seem to support user namespaces :sob:

https://github.com/AkihiroSuda/runc/commit/1f642d92d5008f1264eec7e9ab8f3ac81e4f2f9a
https://github.com/godbus/dbus/blob/v5.0.3/auth.go#L56-L57

cc @giuseppe

**Comment by kolyshkin** [comment]
>￼ CI: enable integration test (rootful)

This is addressed by #2295 (we still need more tests though)

**Comment by AkihiroSuda** [comment]
this tracker was superseded by https://github.com/opencontainers/runc/issues/2315
