### ISSUE TITLE
Can #2132 be cherry-picked to the latest release version?

### ISSUE THREAD

**Issue by skilxn-go** [opencontainers/runc#2216]
It's a tiny pr, but currently, every third-party repo that depanding on RunC can hardly work in our environment. I don't know how to fix it quickly, maybe cherry-pick it to the lastest release version, or just waiting for the next version?
Thanks.
FYI: #2132

**Comment by cyphar** [comment]
It'll be in the next release. The only blocker at the moment is a security fix being merged (#2207).

**Comment by skilxn-go** [comment]
Thanks, I will keep waiting
