### ISSUE TITLE
Checkpoint and restore runc container while running sysbench and redis benchmark

### ISSUE THREAD

**Issue by chandrabvv** [opencontainers/runc#2227]
Checkpoint and restoration of runc container fails when running sysbench (CPU test: sh -c 'sysbench --test=cpu --cpu-max-prime=20000 run') and Redis (redis-benchmark) workload inside runc container. But, I am able to checkpoint and restore successfully when using docker container while running above mentioned workloads.  I am able to checkpoint and restore successfully when running command "/bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done' " inside runc container. I am not sure that where i am doing mistake in sysbench and redis workload.

**Comment by adrianreber** [comment]
@chandrabvv What errors do you get? Do you get an error from CRIU? Any log files?

**Comment by kolyshkin** [comment]
No response from the reporter; I guess this can be closed.

@chandrabvv feel free to file a new bug if you're still having issues.
