### ISSUE TITLE
chmod on read-only tmpfs

### ISSUE THREAD

**Issue by zhangyoufu** [opencontainers/runc#2246]
# How to reproduce
```
# docker run --rm -it --tmpfs /mnt:ro alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"tmpfs\\\" to rootfs \\\"/var/lib/docker/overlay2/ee05948a3c3d2007ac920c0e8a7dcfdaed59a85fcaa59ff9eb791f5151dc92bf/merged\\\" at \\\"/mnt\\\" caused \\\"chmod /var/lib/docker/overlay2/ee05948a3c3d2007ac920c0e8a7dcfdaed59a85fcaa59ff9eb791f5151dc92bf/merged/mnt: read-only file system\\\"\"": unknown.
```
Tested on docker 19.03.2 with runc 1.0.1-dev.

# Related code
https://github.com/opencontainers/runc/blob/fc5759cf4fcf3f9c77c5973a24d37188dbcc92ee/libcontainer/rootfs_linux.go#L331-L377

# Use case
I'm using `registry:2` with s3 storage backend, thus `/var/lib/registry` mountpoint is useless for my setup. If I didn't specify a bind mount or tmpfs for this path, an anonymous volume would be created. I don't want to keep an empty folder for bind-mounting to `/var/lib/registry`, nor do I want a writable tmpfs. So I tried `--tmpfs /var/lib/registry:ro`, but failed.

My best effort without read-only tmpfs is `--tmpfs /var/lib/registry:nr_blocks=1,nr_inodes=2`.

**Comment by vikramcse** [comment]
@AkihiroSuda I would like to work on this issue (As my first contribution).

I read about `tmpfs` bind mounts, from which I understood that there are cases where we have to run a container in `—read-only` mode for security reasons, but there are some images (eg. postgres) which need a write access to a directory to make it run, in this use case we can use the `tmpfs` to mount as a write directory.
Am I missing something? can you help me a little to resolve this issue.

Thanks

**Comment by zhangyoufu** [comment]
@vikramcse This issue is not about `--read-only` container. A `tmpfs` mount in `--read-only` container is writable by default. The use case you metioned (read-only postgres container with tmpfs mount) is not affected by this issue.

**Comment by cyphar** [comment]
Indeed, the issue appears to be one of operation ordering -- a tmpfs mounted as `ro` results in us trying to `chmod` it (even though it's read-only). I'll take a look at this on Monday.

**Comment by vikramcse** [comment]
@cyphar is there anything I could do to resolve this issue?

**Comment by cyphar** [comment]
The issue should be fairly easy to reproduce, so you could take a look at changing the section of `rootfs_linux.go` that is mentioned in the issue description (from a quick look, @zhangyoufu is correct about the source of the issue) so that we don't try to `Chmod` a read-only mount. As I mentioned, a good solution might be to first mount the filesystem read-write, then chmod, then re-mount it as read-only.

**Comment by EduardoVega** [comment]
Hi  @cyphar, I would like to work on this, if it is still required.
