### ISSUE TITLE
Need to add integration test suite for resource limitation (especially for devices)

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2249]
https://github.com/opencontainers/runc/blob/master/tests/integration/cgroups.bats

The current test suite doesn't cover resource limitation stuff except `memory.kernel`.

**Comment by AkihiroSuda** [comment]
We could extend the current bats suite to cover them, but we should also consider port over https://github.com/containers/crun/tree/master/tests (Python) for ease of json manipulation.
(The current crun suite seems to cover PID limits, but doesn't seem to cover cpu and memory anyway.)

cc @giuseppe

**Comment by ahmedaabouzied** [comment]
I can work on that

**Comment by AkihiroSuda** [comment]
Thanks, please feel free to open PR

**Comment by kolyshkin** [comment]
> The current test suite doesn't cover resource limitation stuff except memory.kernel.

There's also https://github.com/opencontainers/runc/blob/master/tests/integration/update.bats which tests many other controllers.

@AkihiroSuda what kind of tests do you have in mind?

**Comment by AkihiroSuda** [comment]
I think we need to add tests for devices (if we don't have yet)

**Comment by ahmedaabouzied** [comment]
> I think we need to add tests for devices (if we don't have yet)

@AkihiroSuda, could you explain more or maybe provide an example of tests for devices?

**Comment by AkihiroSuda** [comment]
Like this but as integration tests 
https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go

**Comment by AkihiroSuda** [comment]
@ahmedaabouzied Are you still working on this?

**Comment by ahmedaabouzied** [comment]
Actually, I couldn't get any far with this.

**Comment by EduardoVega** [comment]
@AkihiroSuda I would like to work on this one if it is still required.

**Comment by AkihiroSuda** [comment]
Yes please, thanks
