### ISSUE TITLE
Missing package apparmor in Makefile

### ISSUE THREAD

**Issue by jiatongw** [opencontainers/runc#2250]
Hi team,

I built `runc` from the latest release (`rc-10`) and tried to bootstrap a k8s cluster, but it failed to work:

```skipping: failed to "StartContainer" for "kube-apiserver" with RunContainerError: "failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \\\"apply apparmor profile: apparmor: config provided but apparmor not supported\\\"\": unknown" ```

It shows that `apply apparmor profile: apparmor: config provided but apparmor not supported`, then I checked Makefile and found 
```
BUILDTAGS ?= seccomp
```
I guess it is missing `apparmor`.

**Comment by AkihiroSuda** [comment]
It is likely that your host OS distro (or CRI runtime) just doesn't support apparmor.

**Comment by mikebrow** [comment]
FYI... when we build runc for containerd & cri testing packaging etc... we use BUILDTAGS:-seccomp apparmor

https://github.com/containerd/cri/blob/master/hack/install/utils.sh#L35
https://github.com/containerd/containerd/blob/master/script/setup/install-runc#L29

**Comment by mikebrow** [comment]
https://github.com/opencontainers/runc#build-tags

**Comment by jiatongw** [comment]
Thanks @mikebrow . 

It's inconvenience that we manually modify the Makefile to add build tags each time when we build. Is it possible to add `apparmor` officially in Makefile?

**Comment by mikebrow** [comment]
I'd would not modify `makefile` I'd make a build script for calling make BUILDTAGS='apparmor seccomp'  .. or see if make cri-release .... https://github.com/opencontainers/runc/blob/master/script/release.sh#L30
somehow works for your workflow.

**Comment by AkihiroSuda** [comment]
https://github.com/opencontainers/runc/pull/2254 fixes this
