### ISSUE TITLE
Container is not destroyed with pre-dump

### ISSUE THREAD

**Issue by levanthanh3005** [opencontainers/runc#2253]
Hi,
Could you please help me to check the error with runc:
My steps are:
mkdir /mycontainer
cd /mycontainer
mkdir rootfs
docker export $(docker create busybox) | tar -C rootfs -xvf -

runc spec

Then change config.json : as the example in github https://github.com/opencontainers/runc
"terminal": false,
"user": {
"uid": 0,
"gid": 0
},
"args": [
"sleep", "50000"
],

Then go to mycontainer
runc run -d busybox &> /dev/null < /dev/null
runc checkpoint --image-path cp busybox => it works

I reproduce the steps to make the busybox run again, and then run
runc checkpoint --pre-dump --image-path cp busybox
=> ERRO[0000] container is not destroyed

criu version is 3.13
runc version 1.0.0-rc9+dev
commit: c4d8e1688c816a8cef632a3b44a38611511b7140
spec: 1.0.1-dev

**Comment by levanthanh3005** [comment]
Hi @adrianreber 
My complaining is about the behavior, 
"container is not destroyed" is correct, but it should not make any errors, I also try with other service with tcp connection and it makes the same error

**Comment by adrianreber** [comment]
I will have a look at what is up with the message during checkpointing.
