### ISSUE TITLE
Error occurs when build the newest version runc (since commit e7663a673efe0da696ea87eaa7695ec2e604dd76)

### ISSUE THREAD

**Issue by wangkirin** [opencontainers/runc#226]
I pull the newest version of runc and execute `make` command in the `/runc` folder , but it occurs the following error :
``` 
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp.go:25:22: fatal error: seccomp.h: No such file or directory
 // #include <seccomp.h>
                      ^
compilation terminated.
make: *** [all] error 2
```
and when I reset the runc to commit
```
commit 6d0f60bb94b4d09d2777f814b1cf4c1d4c8d709b
Merge: 90e6d37 47f294d
Author: Mrunal Patel <mrunal@me.com>
Date:   Fri Aug 21 10:45:28 2015 -0700

    Merge pull request #205 from tonistiigi/exec
    
    Add exec command
```
 , the error information disappear and the runc can run normally

I think the error may be cause by the `Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp.go` because some dependency problem

**Comment by marcosnils** [comment]
@wangkirin this is not an issue. You need libseccom-dev libraries in order to build runc with seccomp capabilities. You can still disable this through go build flags.

**Comment by wangkirin** [comment]
@marcosnils  thank you very much, how about update the README.md to make other developers known

**Comment by runcom** [comment]
PR is here #220
