### ISSUE TITLE
cgroupv2 checkpoint/restore is not working

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#2328]
One reason it is not working is cgroupv2 mount (and BTW cgroupv1 mounts in case `--cgroupns` is used) should not be treated like (presented to criu as) external bind mount(s).

* cgroupv1 + cgroupns mounts are real mounts (having `fstype` of `cgroup`)
* cgroupv2 mount is a real mount (`fstype` is `cgroup2`)

There might be other bugs, too.

**Comment by kolyshkin** [comment]
I already have a patch to fix this, just need more time to create a PR

**Comment by adrianreber** [comment]
When I implemented the freezer CRIU cgroup2 changes for runc and CRIU it was still working. That was a few weeks ago.

The integration tests are actually running checkpoint/restore using vagrant-fedora-31 with cgroup2 in the container and outside of the container: https://github.com/opencontainers/runc/blob/master/libcontainer/integration/checkpoint_test.go#L86

I am certain I do not understand the whole cgroup details as good as you, just wanted to mention that some checkpoint/restore tests using cgroup2 are working.

**Comment by kolyshkin** [comment]
@adrianreber I'll take a closer look at it, but I think I found (and fixed) a genuine bug, please see #2335. The reason it works in your case is that you explicitly set `Device` to `"cgroup2"`, while in case of runc run/checkpoint/restore it says `"cgroup"` since it is taken right from contig.json.

Maybe I need to redo my fix differently, changing "cgroup" to "cgroupv2" in case we're using v2 unified hierarchy, but let's discuss it in #2335
