### ISSUE TITLE
failed to remove cgroup paths

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#234]
While tried to exit the container I got the following messages
ERRO[0001] Failed to remove paths: map[cpuset:/sys/fs/cgroup/cpuset/user.slice/user-1000.slice/session-c2.scope/runc memory:/sys/fs/cgroup/memory/user.slice/user-1000.slice/session-c2.scope/runc cpu:/sys/fs/cgroup/cpu,cpuacct/user.slice/user-1000.slice/session-c2.scope/runc hugetlb:/sys/fs/cgroup/hugetlb/user.slice/user-1000.slice/session-c2.scope/runc net_cls:/sys/fs/cgroup/net_cls,net_prio/user.slice/user-1000.slice/session-c2.scope/runc perf_event:/sys/fs/cgroup/perf_event/user.slice/user-1000.slice/session-c2.scope/runc cpuacct:/sys/fs/cgroup/cpu,cpuacct/user.slice/user-1000.slice/session-c2.scope/runc devices:/sys/fs/cgroup/devices/user.slice/user-1000.slice/session-c2.scope/runc blkio:/sys/fs/cgroup/blkio/user.slice/user-1000.slice/session-c2.scope/runc net_prio:/sys/fs/cgroup/net_cls,net_prio/user.slice/user-1000.slice/session-c2.scope/runc freezer:/sys/fs/cgroup/freezer/user.slice/user-1000.slice/session-c2.scope/runc]

I could login to container and exit, but every time if I exit the container, got the above message.
Until I reboot the system, the message did not disappear.

**Comment by hqhq** [comment]
How did you start the container? Can you reproduce this issue?

**Comment by crosbymichael** [comment]
Closing as we don't have information for a reproducible case and it is probably working fine now ;)
