### ISSUE TITLE
Enable travis to run arm64, ppc64le and s390x

### ISSUE THREAD

**Issue by alicefr** [opencontainers/runc#2383]
It might be useful to test runc for non-x86 architectures. Travis has the support for arm64, ppc64le and s390x. We can simply enable to run the tests also for other arches.

**Comment by alicefr** [comment]
Here the travis blog how to enable multiple cpu architectures: https://docs.travis-ci.com/user/multi-cpu-architectures/

**Comment by XiaodongLoong** [comment]
@alicefr 
I have raised a PR (https://github.com/opencontainers/runc/pull/2508) to run runc integration test on more CPU architecture.  Does travis support for mips64le?

**Comment by alicefr** [comment]
@XiaodongLoong not sure, the best would be to try :). You can add the additional arch in the travis yaml on your branch and see if the job gets triggered.

**Comment by alicefr** [comment]
@AkihiroSuda I'm changing job, so I don't have time to finish my PR. The tests are still failing for s390x, ppc64le and arm64. Not sure what is going wrong since when I run them directly on s390x, everything is successful. My latest updates can be found here https://github.com/alicefr/runc/tree/travis-multi-arch. I'm closing this issue since I'm not working on this anymore.
