### ISSUE TITLE
The name of this project is unfortunate.

### ISSUE THREAD

**Issue by haf** [opencontainers/runc#24]
We live in an international world.

In the part of the world called Sweden, your project is named *masturbation*. C on its own in Swedish is pronounced k, and:

![screen shot 2015-06-27 at 20 55 27](https://cloud.githubusercontent.com/assets/193115/8393431/f56cfde2-1d0e-11e5-8737-3572488061f2.png)

The sells in the enterprises might not come. And then it would be over prematurely.

Just thought you wanted to know. ;)

**Comment by shykes** [comment]
Ha ;) Well that's unfortunate. I think it could help if you spell it run-C with a dash maybe?

Also, it's ok if it's not an "enterprise-ready" name, it's meant to be low-level plumbing to power the internals of Docker. Enterprises care about Docker - and they will leave the plumbers alone to do the low-level coding here :)

**Comment by keis** [comment]
if it's "run-see" that would get around the problem and anyway we learned to live with pull(a)

**Comment by badbug0101** [comment]
@haf lol

**Comment by rymohr** [comment]
Haha, some follow up commentary in an HN thread: https://news.ycombinator.com/item?id=9788058

**Comment by errordeveloper** [comment]
What about a shorter reverse version `cr`?

**Comment by omeid** [comment]
+1 for cr.

**Comment by CameronNemo** [comment]
cr is too short, likely to conflict with something else.

**Comment by errordeveloper** [comment]
I've checked, and it doesn't look like there's a command that is commonly found on Linux installations. There used to be one, but looks like it's [long gone](http://www.unix.com/man-page/debian/1/cr/), as the man page is dated to 1996 and is not like a POSIX command or anything.

**Comment by errordeveloper** [comment]
It may be worth noting that `docker` command has conflicted with another from the start and we all got over it.

**Comment by senlog** [comment]
how about "stevedore" or "wharfie" ?

**Comment by crosbymichael** [comment]
I think we can close this issue now ;)
