### ISSUE TITLE
Use xhyve to facilitate native execution in OSX

### ISSUE THREAD

**Issue by booyaa** [opencontainers/runc#241]
I appreciate you're trying to achieve stability on the Linux platform, but it would be nice to do this on OS X (and in theory *BSD) too.

Rather than starting from scratch, perhaps code could be reused/purposed from [xhyve](https://github.com/mist64/xhyve) project?

**Comment by c4milo** [comment]
What you are asking is difficult to achieve as runC relies entirely on the Linux Kernel. However, 
you can still use xhyve and runC through a linux VM. For instance: https://github.com/coreos/coreos-xhyve.

**Comment by booyaa** [comment]
Of course the hint is the  **L**XC :) apologies for the daft question.
