### ISSUE TITLE
tests: stop using sed for manipulating JSON

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2417]
https://github.com/opencontainers/runc/blob/f369199ff61bafdb91b5308d8b30cb4c18270bd9/tests/integration/helpers.bash#L155-L158

The current sed scripts are hard to maintain, should be substituted with `jq` as in: https://github.com/opencontainers/runc/blob/f369199ff61bafdb91b5308d8b30cb4c18270bd9/tests/integration/helpers.bash#L87-L95

**Comment by JFHwang** [comment]
Hello, I'm interested in taking on this issue. Is it alright for me to start?

**Comment by AkihiroSuda** [comment]
Yes please, thanks

**Comment by kolyshkin** [comment]
Been meaning to address that, too, but for some reason it did not went well for me (don't remember any details now).

**Comment by kolyshkin** [comment]
> Hello, I'm interested in taking on this issue. Is it alright for me to start?

@JFHwang sure. The things we're looking for are
 - use `jq` for config.json manipulation
 - move common stuff into helper functions
 - increase code readability
