### ISSUE TITLE
Is there a way to identify if the container was started as a privileged one using runc list -f json or runc state

### ISSUE THREAD

**Issue by DevasiaThomas** [opencontainers/runc#2421]
I had a similar question in crio https://github.com/cri-o/cri-o/issues/3769 and they don't support it right now, but the PR is on the way, I wanted to know if I could Identify if a container was privileged at the runc layer.

**Comment by DevasiaThomas** [comment]
Even if it is some other way, I hope so. Since docker did support showing that info, I'm expecting runc to have it. just don't know where to look.

**Comment by AkihiroSuda** [comment]
There is no single "privileged" boolean in OCI Runtime Spec

**Comment by DevasiaThomas** [comment]
Okay, if a docker created container has privileged on it, how can I identify that from the runc layer?
Similarly k8s has securityContext which allows you to specify privileged in one word, how does that translate down to the runc layer?

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/containerd/blob/v1.4.0-beta.0/oci/spec_opts.go#L1127-L1137

**Comment by DevasiaThomas** [comment]
@AkihiroSuda Thanks for pointing out the privileges that are applied. Can these be queried for using the runc cli against a running container? I had a look at list and state and couldn't find them

**Comment by AkihiroSuda** [comment]
You need to query `config.json`

**Comment by DevasiaThomas** [comment]
So direct file interaction and not through the runc cli?

**Comment by AkihiroSuda** [comment]
Yes

**Comment by DevasiaThomas** [comment]
Thanks @AkihiroSuda . Anyway you can add this to runc state or somewhere relevant? the way crio is adding to inspect? I know you mentioned that its not in the Spec(crio did too - but they have a PR now), but from a user perspective that wants to introspect if the "privileged" context they applied in their yml file has been applied to the container, wouldn't it be easier if there was a key privileged which either had true or false as a value?

**Comment by AkihiroSuda** [comment]
No, should be handled by crio

**Comment by DevasiaThomas** [comment]
Cool alright. Thanks :)
