### ISSUE TITLE
Cannot run SCHED_FIFO process inside runc

### ISSUE THREAD

**Issue by jedichen121** [opencontainers/runc#2431]
I was trying to run a SCHED_FIFO process inside the container. I was able to achieve that by adding "CAP_SYS_NICE" to the capabilities in config.json file on my XPS 13 laptop running ubuntu 18.04. However, I did the same on Raspberry Pi 3B running Raspbian stretch 4.14. But here inside runc it does not have the permission to set real-time scheduler for the process. I tried to use "CAP_SYS_ADMIN" but it didn't work either. 

Here's how I set the container up:
```
docker export $(docker create ubuntu:18.04) | tar -C rootfs -xvf -
cp fifo_process rootfs
runc spec
# add CAP_SYS_NICE to config.json file
sudo runc run mycontainer
```
I did meet some problems trying to install runc on Raspberry Pi. Instead of following the normal make procedure, I have to give up some build tag so that it can build successfully. And when using `sudo make install` for runc, it will install but report `make: go: Command not found` though golang is definitely installed. 

```
go get github.com/opencontainers/runc
cd $GOPATH/src/github.com/opencontainers/runc
make BUILDTAGS=""
sudo make install
```
I tried to build runc the same way without build tags on my laptop and it didn't affect it's ability to run fifo process. 

Any help is appreciated. Thank you.

**Comment by cyphar** [comment]
You probably need to set `cpu.rt_period_us` and `cpu.rt_runtime_us` settings in your `config.json`. Depending on the host configuration, RT processes (such as your `SCHED_FIFO` process) need to explicitly have time allocated to their cgroup. You might want to check what the sysctl values of `kernel.sched_rt_runtime_us` and `kernel.sched_autogroup_enabled` are. If autogroup is disabled (but `kernel.sched_rt_runtime_us` is enabled) then you need to explicitly specify how much runtime to give the container.

**Comment by jedichen121** [comment]
Thank you for the reply. I think you mean the settings in `proc/sys/kernel/sched_rt_runtime_us` and `proc/sys/kernel/sched_autogroup_enabled`? I checked but the settings are the same on two machines. `sched_autogroup_enabled` is enabled and `sched_rt_runtime_us` is set to 950000. But you reminded me that I have `CONFIG_RT_GROUP_SCHED` turned on on the Raspberry pi but not the laptop. This seems to be the cause. After adding the `resources.cpu.realtimePeriod` and `resources.cpu.realtimeRuntime` in `config.json` the program can run. Thank you for the help.

**Comment by cyphar** [comment]
Ah right, all of my comment was assuming you had `rt_cgroup` (`CONFIG_RT_GROUP_SCHED`) enabled on both machines (given it's enabled by most distribution kernels). Having `rt_cgroup` disabled means that all of the realtime cgroup-related rules aren't applied.
