### ISSUE TITLE
runc exec -u 0 <containerID> sh -c "ps ax"

### ISSUE THREAD

**Issue by DevasiaThomas** [opencontainers/runc#2432]
I'm having trouble getting the output from the above command across environments
I execute the above in 2 different envs
The First:
```
openshift v4.2
https://www.openshift.com/learn/courses/playground/
runc VERSION:
   spec: 1.0.1-dev
```
Executing the above has no output
The Second:
```
crio on k8s 1.16
runc VERSION:
   1.0.0-rc10
commit: 50d5773810ff80bea305931897920daa58a6a769
spec: 1.0.1-dev
```
Executing the above command returns expected output

Am I doing something wrong? Or was this a bug? Anyway I can get around this?

**Comment by AkihiroSuda** [comment]
Should be asked to Red Hat support

**Comment by DevasiaThomas** [comment]
@AkihiroSuda I was trying to execute runc from within a privileged container, and turns out it needed some SELinux label adjustments. from container_t to spc_t, the pipes were being denied
