### ISSUE TITLE
Add Vagrant CI for several distros (e.g. CentOS 7)

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2444]
- [X] Ubuntu 18.04 (Travis)
- [X] Fedora 32 (Vagrant on Travis)
- [x] CentOS 7 (Vagrant on Travis): https://github.com/opencontainers/runc/pull/2453

**Comment by kolyshkin** [comment]
We might also need to add a semi-recent Ubuntu, as I recently found out we're not running the tests on a system with no mem+swap limit (https://github.com/opencontainers/runc/pull/2439).

Note that CentOS 7 has this controller (see e.g. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/resource_management_guide/sec-modifying_control_groups)

**Comment by AkihiroSuda** [comment]
@kolyshkin 
GH actions seems supporting Ubuntu 20.04 (as well as 18.04 and 16.04) without nesting: https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
