### ISSUE TITLE
master: TestDockerSuite/TestRunInvalidCPUShares fails

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2462]
moby/moby@3aac5f0 + opencontainers/runc@1b97c04 doesn't pass Moby's `TestDockerSuite/TestRunInvalidCPUShares`

```
=== RUN   TestDockerSuite/TestRunInvalidCPUShares
    --- FAIL: TestDockerSuite/TestRunInvalidCPUShares (0.50s)
        docker_cli_run_unix_test.go:769: assertion failed: expression is false: strings.Contains(out, expected)
```
https://github.com/moby/moby/pull/41025#issuecomment-641114413

This was working two weeks ago: https://github.com/moby/moby/pull/41025#issuecomment-634309258

**Comment by kolyshkin** [comment]
This is because the error message was lowercased in 3249e2379 (PR #2441).

Fix belongs to moby: https://github.com/moby/moby/pull/41085
