### ISSUE TITLE
systemdVersion parsing failure causes extra output

### ISSUE THREAD

**Issue by haircommander** [opencontainers/runc#2480]
this issue has two parts to it. The first is that runc is logging warning messages even though `--debug` is not specified:
```
2020-06-17T19:54:10.907080297+00:00 stderr F time="2020-06-17T19:54:10Z" level=warning msg="systemdVersion: can't parse version \"219\""
# 2020-06-17T19:54:10.907080297+00:00 stderr F time="2020-06-17T19:54:10Z" level=warning msg="systemdVersion: can't parse version \"219\""
```
it seems it defaults to at least Warn level. Other projects allow a finer grained specification for `--log-level`, but without that, logrus output shouldn't come unless it's error level or `--debug` is specified

I'm opening an issue to allow the maintainers decide what should be logged by default.

The second part is I believe the systemd version parsing should succeed in cases where just the version number is given, as now. I have added this case in [this](https://github.com/opencontainers/runc/pull/2479) PR

[breaking PR](https://github.com/opencontainers/runc/pull/2466)

Note: I noticed this because the change has broken CRI-O CI, as we have a test that matches against output, and runc output is counted for the container's:
https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/3868/test_pull_request_crio_integration_rhel/13239/artifacts/testout.txt

**Comment by AkihiroSuda** [comment]
solved in https://github.com/opencontainers/runc/pull/2479
