### ISSUE TITLE
Proposal: Set up Dependabot

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2536]
[Dependabot](https://github.com/marketplace/dependabot-preview) seems very useful to update go.mod dependencies automatically. 

Dependabot PR will look like this: https://github.com/containers/podman/pull/7045

I suggest setting up Dependabot to open PRs weekly (or monthly) on this repo.

**Comment by AkihiroSuda** [comment]
Note: it doesn't support updating `vendor` currently: https://github.com/dependabot/dependabot-core/issues/670

So a maintainer will need to amend the PR to run `go mod vendor`..

**Comment by AkihiroSuda** [comment]
@cyphar @thaJeztah WDYT?

**Comment by thaJeztah** [comment]
Given that the PR's won't be mergeable (so always require manual action to make them mergeable), it'd mostly be to "notify" maintainers that a newer version is available for a dependency.

Perhaps that's ok, not sure; would it instead be an option to have (e.g.) a GitHub action that opens a ticket (weekly?) with an overview of dependencies that have new versions available? (should it include dependencies that don't have tagged releases?)

**Comment by AkihiroSuda** [comment]
>  would it instead be an option to have (e.g.) a GitHub action that opens a ticket

SGTM, not sure there is an existing tool

**Comment by thaJeztah** [comment]
I see someone implemented it in gh actions; https://github.com/vmware-tanzu/octant/blob/master/.github/workflows/dependabot-gomod.yaml

example; https://github.com/GoComply/metaschema/pull/3

Not sure how the legal side of things are with a bot doing a `signed-off-by`
