### ISSUE TITLE
[AliOS] nsenter: failed to unshare namespaces: Invalid argument container_linux.go:262: starting container process caused "process_linux.go:247: running exec setns process for init caused \"exit status 34\""

### ISSUE THREAD

**Issue by sjc2870** [opencontainers/runc#2544]
I I occasionally encounter this error when I start the container, every time I encounter it when restarting the container several times continuously. Do you have any suggestions?
`uname -a
Linux e03g04255.eu6sqa 3.10.0-327.ali2013.alios7.x86_64`
`unshare  --user sh
unshare: unshare failed: Invalid argument`
I seems kernel dosen't supports CLONE_NEWUSER.But mostly I can start container normally and just encounter this problem occasionally.And this is why?

**Comment by sjc2870** [comment]
This is my runc version:`docker-runc --version
runc version 1.0.0-rc3
commit: b0917904e049873e6fe70520b9a049b8cb3a9ea2
spec: 1.0.0-rc5`

**Comment by sjc2870** [comment]
And this is dockerd log when restart normally:
![image](https://user-images.githubusercontent.com/51011799/89601755-d301e700-d897-11ea-8c8f-deb651ef8572.png)

**Comment by kolyshkin** [comment]
> docker-runc --version runc version 1.0.0-rc3

This runc version is very old and I guess is only supported by Docker, so I guess you should file a bug to Docker.

In case you are not using Docker, but bare runc, feel free to reproduce this using a recent runc release and reopen this (or file a new issue with a reference to this one).

**Comment by xuegege5290** [comment]
> And this is dockerd log when restart normally: ![image](https://user-images.githubusercontent.com/51011799/89601755-d301e700-d897-11ea-8c8f-deb651ef8572.png)

hi，i meet the same question. failed to unshare namespaces:can't allocate memory......do you solve the problem?(same version of runc)
