### ISSUE TITLE
Spec status

### ISSUE THREAD

**Issue by c4milo** [opencontainers/runc#255]
Readme says spec v1 was supposed to come out on  ~July 2015. Did it happen?

**Comment by wking** [comment]
On Tue, Sep 08, 2015 at 01:56:47PM -0700, Camilo Aguilar wrote:
> Readme says spec v1 was supposed to come out on ~July 2015. Did it
> happen?

No.  There should be a v0.1.0 release cut in the next day or two
(opencontainers/specs#151), but I'm not aware of a timeline for 1.0.

**Comment by vbatts** [comment]
https://github.com/opencontainers/specs/releases/tag/v0.1.1 is tagged now, and https://github.com/opencontainers/specs/blob/f6ec7a75c65cd58322ec120f651ccdf465af7973/version.go reflects it.
There is presently no timeline for a v1.0.0
