### ISSUE TITLE
Makefile: DESTDIR is not added to PREFIX if PREFIX is manually given

### ISSUE THREAD

**Issue by nanonyme** [opencontainers/runc#2571]
When used with packaging, we might want prefix to point to /usr and collect package artifacts into /staging-dir. In this case we would set PREFIX=/usr and DESTDIR=/staging-dir. This results in make actually installing files under /usr (which might not be mutable) instead of under /staging-dir/usr.

**Comment by kolyshkin** [comment]
Thanks for reporting, proposed fix is https://github.com/opencontainers/runc/pull/2578
