### ISSUE TITLE
runc is unable to kill the conatiner

### ISSUE THREAD

**Issue by gitsvm** [opencontainers/runc#2572]
While It is able to pause the running container, it is unable to kill the container. Why is this happening and what should i do to make this work?

**Comment by cyphar** [comment]
It's a bit hard to figure out why it's not working if you haven't even told us what the error is. For future reference, please tell us as much information as you can about your setup.

**Comment by gitsvm** [comment]
It doesn't produce any error, the command `sudo runc kill <cid>` doesn't print anything, instead i'm being prompted to run another command as usual.

**Comment by gitsvm** [comment]
this is config.json file for the container:
```
{
	"ociVersion": "1.0.2-dev",
	"process": {
		"terminal": true,
		"user": {
			"uid": 0,
			"gid": 0
		},
		"args": [
			"/hello"
		],
		"env": [
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"TERM=xterm"
		],
		"cwd": "/",
		"capabilities": {
			"bounding": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"effective": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"inheritable": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"permitted": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			],
			"ambient": [
				"CAP_AUDIT_WRITE",
				"CAP_KILL",
				"CAP_NET_BIND_SERVICE"
			]
		},
		"rlimits": [
			{
				"type": "RLIMIT_NOFILE",
				"hard": 1024,
				"soft": 1024
			}
		],
		"noNewPrivileges": true
	},
	"root": {
		"path": "rootfs",
		"readonly": true
	},
	"hostname": "runc",
	"mounts": [
		{
			"destination": "/proc",
			"type": "proc",
			"source": "proc"
		},
		{
			"destination": "/dev",
			"type": "tmpfs",
			"source": "tmpfs",
			"options": [
				"nosuid",
				"strictatime",
				"mode=755",
				"size=65536k"
			]
		},
		{
			"destination": "/dev/pts",
			"type": "devpts",
			"source": "devpts",
			"options": [
				"nosuid",
				"noexec",
				"newinstance",
				"ptmxmode=0666",
				"mode=0620",
				"gid=5"
			]
		},
		{
			"destination": "/dev/shm",
			"type": "tmpfs",
			"source": "shm",
			"options": [
				"nosuid",
				"noexec",
				"nodev",
				"mode=1777",
				"size=65536k"
			]
		},
		{
			"destination": "/dev/mqueue",
			"type": "mqueue",
			"source": "mqueue",
			"options": [
				"nosuid",
				"noexec",
				"nodev"
			]
		},
		{
			"destination": "/sys",
			"type": "sysfs",
			"source": "sysfs",
			"options": [
				"nosuid",
				"noexec",
				"nodev",
				"ro"
			]
		},
		{
			"destination": "/sys/fs/cgroup",
			"type": "cgroup",
			"source": "cgroup",
			"options": [
				"nosuid",
				"noexec",
				"nodev",
				"relatime",
				"ro"
			]
		}
	],
	"linux": {
		"resources": {
			"devices": [
				{
					"allow": false,
					"access": "rwm"
				}
			]
		},
		"namespaces": [
			{
				"type": "pid"
			},
			{
				"type": "network"
			},
			{
				"type": "ipc"
			},
			{
				"type": "uts"
			},
			{
				"type": "mount"
			}
		],
		"maskedPaths": [
			"/proc/acpi",
			"/proc/asound",
			"/proc/kcore",
			"/proc/keys",
			"/proc/latency_stats",
			"/proc/timer_list",
			"/proc/timer_stats",
			"/proc/sched_debug",
			"/sys/firmware",
			"/proc/scsi"
		],
		"readonlyPaths": [
			"/proc/bus",
			"/proc/fs",
			"/proc/irq",
			"/proc/sys",
			"/proc/sysrq-trigger"
		]
	}
}
```

**Comment by cyphar** [comment]
Does `runc kill` have a non-zero error code (in other words, did it actually have an error of some kind)? Is your container already paused when you do `runc kill`? If you try to kill a container while it is paused, the container will receive the kill signal but won't do anything until you unpause it (this is a limitation of cgroupv1's freezer cgroup).

**Comment by gitsvm** [comment]
I also tried to run runc kill after resuming the container but it still doesn't work.

**Comment by gitsvm** [comment]
no `runc kill` doesn't have any zero error code

**Comment by gitsvm** [comment]
and by the way how can i run processes as root inside the container?

**Comment by cyphar** [comment]
Processes run as root by default inside the container (run `id` inside the container to see what user you are running as) -- this is controlled by the `process.uid` and `process.gid` options in `config.json`.

**Comment by cyphar** [comment]
> no runc kill doesn't have any zero error code

Ah okay, that means that the signal was sent successfully it just didn't do anything. I guess you just did `runc kill container` -- the issue is that the default signal (`SIGTERM`) is ignored by most programs when run inside the container as PID 1. If you do `runc kill container KILL` it will send `SIGKILL` which cannot be ignored by programs and will immediately terminate the container.

**Comment by gitsvm** [comment]
> 
> Ah okay, that means that the signal was sent successfully it just didn't do anything. I guess you just did `runc kill container` -- the issue is that the default signal (`SIGTERM`) is ignored by most programs when run inside the container as PID 1. If you do `runc kill container KILL` it will send `SIGKILL` which cannot be ignored by programs and will immediately terminate the container.

Thanks it's working, now i'm able to kill all the processes. but there is another problem which i'm not able to figure out , this is slightly different from the question, when i'm doing nsenter it shows `nsenter: error: Unable to access PID: [Errno 22] EINVAL` error. I used below commands:

`sudo nsenter --target 16627 --all ps aux`
`sudo nsenter --target 16627 --mnt --uts --ipc --net --pid ps aux`
both giving same error. 

but when i remove sudo it says `nsenter: error: Unable to access PID: [Errno 13] Permission denied: '/proc/16627/ns/user'`
so if it is able to the directory then why does it say `unable to acces PID`, and how can i solve this? earlier i was using the same command for other containers and it worked fine but now it is giving this error when i downloaded `ubuntu` as a `rootfs` rather than `busybox` for the current container.

**Comment by gitsvm** [comment]
@cyphar ? i still couldn't do it. what might be the case here.
