### ISSUE TITLE
Failures when running statically linked binary in scratch container

### ISSUE THREAD

**Issue by Sigurthorb** [opencontainers/runc#2577]
I am trying to execute a statically linked binary inside a scratch container where I am encountering 2 failures. I've tried both docker version 18.06.1-ce and 19.03.6-ce, build 369ce74

#### Example 1:
when executing a statically linked binary as entrypoint in a scratch container, I encounter this error:

    standard_init_linux.go:190: exec user process caused "no such file or directory"

You can reproduce this issue with the following dockerfile:
```
FROM golang:1.15.1 as build-env
WORKDIR /go/src/main

RUN echo "package main;import \"fmt\";func main() {fmt.Println(\"Simple Example\")}" > main.go
RUN GOOS=linux go build  -ldflags "-linkmode=internal -s -w" -buildmode=pie -o /mainProc main.go

FROM scratch

COPY --from=build-env /mainProc /mainProc

CMD ["/mainProc"]
```

Then execute these commands:

    docker build -t example . && docker run -it example

#### Example 2:
when executing a statically linked binary using docker exec inside a scratch container, I encounter this error:

    OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "no such file or directory": unknown

You can reproduce this issue with the following dockerfile:

```
FROM golang:1.15.1 as build-env
WORKDIR /go/src/main

RUN echo "package main;import \"fmt\";func main() {fmt.Println(\"Simple Example\")}" > main.go
RUN GOOS=linux go build  -ldflags "-linkmode=internal -s -w" -buildmode=pie -o /mainProc main.go

RUN echo "package main;import \"time\";func main() {time.Sleep(time.Hour)}" > main.go
RUN GOOS=linux go build -o /sleep main.go

RUN ldd /sleep || exit 0
RUN ldd /mainProc || exit 0

FROM scratch

COPY --from=build-env /sleep /sleep
COPY --from=build-env /mainProc /mainProc

CMD ["/sleep"]
```

Then execute this command in terminal 1:

    docker build -t example . && docker run -it --name container_example example

Execute this command in terminal 2:

    docker exec -it container_example /mainProc

If mainProc is compiled without pie and linkmode internal, this works fine. I am however trying to find a solution where PIE can be enabled for security purposes so my attempt was to use the linkmode internal.

Is there any workaround I can use here? In the sort term I am trying to get example 2 working but in the long term I need to be able to enable example 1 as well.

**Comment by Sigurthorb** [comment]
I'm not sure why this is being labeled as a question when I am providing 2 concrete failure examples. Are you saying this is expected behaviour?

**Comment by cyphar** [comment]
Neither of the binaries you described building are actually statically linked as far as I can tell (so the error you're getting is a stock-standard link-loader error -- there are no shared libraries in `scratch`):

```shell
% echo "package main;import \"fmt\";func main() {fmt.Println(\"Simple Example\")}" > main.go
% GOOS=linux go build  -ldflags "-linkmode=internal -s -w" -buildmode=pie -o mainProc main.go
% file mainProc
mainProc: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=8mM4GRs9zxgrVjDRg2Ch/efne9QJbJLpmKT6hRtJm/JWUYVr1m9OhJoV0v1uwq/1IZdDT8CvBOOywiI8eQq, stripped
```

I'm not sure how you to convince Go to produce static PIE binaries, but that's not really a question related to runc.

**Comment by Sigurthorb** [comment]
When I execute ```ldd``` on the binary it says statically linked:
```
% echo "package main;import \"fmt\";func main() {fmt.Println(\"Simple Example\")}" > main.go
% GOOS=linux go build  -ldflags "-linkmode=internal -s -w" -buildmode=pie -o mainProc main.go
% file mainProc
mainProc: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, stripped
% ldd mainProc
	statically linked
```

**Comment by Sigurthorb** [comment]
This issue was created because of incorrect understanding of Static, dynamic and dynamic statically linked. This does not belong in this repository
