### ISSUE TITLE
rootless+systemd should fail with human-friendly error when `dbus-user-session` is not installed

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2582]
On Debian 10, rootless runc (rc92) with `--systemd-cgroup` fails with a cryptic error when `DBUS_SESSION_BUS_ADDRESS` is not present in the result of `systemctl --user --no-pager show-environment`:

https://github.com/opencontainers/runc/blob/2b31437caa905b7b944a891aee613e7dd0a1f898/libcontainer/cgroups/systemd/user.go#L105

This error happens mostly when [dbus-user-session](https://packages.debian.org/bullseye/dbus-user-session) package is not installed, but it is hard for users to notice what they should do:

```console
$ sudo apt-get install -y dbus-user-session
$ systemctl --user start dbus
```

We should improve the error message and/or improve the document.

**Comment by aos** [comment]
Hey -- if you don't mind, I'm going to take this up!
