### ISSUE TITLE
network state when the container is paused

### ISSUE THREAD

**Issue by gitsvm** [opencontainers/runc#2585]
I don't get what happens to the network state of the container when it is paused, does the incoming packets are dropped ? or can they change the state of the container. if yes then how?

**Comment by gitsvm** [comment]
Help here @adrianreber , @cyphar

**Comment by cyphar** [comment]
The semantics are the same as `SIGSTOP` or when a program stops reading packets from a socket. Packets will be buffered until the buffer is full and then will be dropped. It would've probably been simpler to do a quick test with `netcat` than posting questions on the issue tracker.

**Comment by gitsvm** [comment]
Thanks.
