### ISSUE TITLE
RunC as a library?

### ISSUE THREAD

**Issue by mikesimons** [opencontainers/runc#260]
Are there any plans to provide a public interface to runc functionality such that it may be used by other go projects without shelling out?

**Comment by wking** [comment]
On Thu, Sep 10, 2015 at 01:50:46AM -0700, Mike Simons wrote:
> Are there any plans to provide a public interface to runc
> functionality…

Duplicate of #134?  Maybe this should be in a FAQ or something…

**Comment by mikesimons** [comment]
My bad on the dupe. I wasn't expecting a closed issue.

I am using libcontainer already but I'm duplicating (badly) a lot of what runc is already doing.

Take the libcontainer defaults for example. That structure is huge and debugging it is a pain in the ass. I dont need all the power libcontainer gives me, i just want to run a specified rootfs in a container.

**Comment by mikesimons** [comment]
Closing this off since it's just issue noise with no further input.
