### ISSUE TITLE
runc container cpu usage

### ISSUE THREAD

**Issue by gitsvm** [opencontainers/runc#2601]
Where to look for cpu usage for  a specific `runc` container? . 
There is no file present in `/proc/<cid>/`  (`<cid>` is the pid obtained from `runc list` command) by any cpu related name which gives `cpu usage` for that specific container. 
In `/sys/fs/cgroup`  there are files present under  `cpu`, `cpuacct`, `cpu,cpuacct` directories. I don't see if there's any way to extract cpu usage form those files for a specific container. 
Is there any way i can get this information?

**Comment by gitsvm** [comment]
@cyphar , @avagin . pls Help here.

**Comment by ashwani29** [comment]
I got the answer, we can look at `cpuacct.usage` file present under  `/sys/fs/cgroup/cpu,cpuacct/user.slice/<container_name>/cpuacct.usage` path. It will gives cpu usage cycles of the container `<container_name>` , It will always be in increasing order, so to get the correct usage, take the difference between successive intervals.

**Comment by gitsvm** [comment]
Thanks.
