### ISSUE TITLE
inconsistent relative --root behavior

### ISSUE THREAD

**Issue by najohnsn** [opencontainers/runc#2613]
A relative path can be specified for `--root`, but it is sometimes interpreted as relative to current directory and sometimes as relative to bundle directory:
```
> sudo find .
.
./mybundle
./mybundle/config.json
./myroot
> sudo runc --root myroot create --bundle mybundle a
> sudo find .
.
./mybundle
./mybundle/config.json
./mybundle/myroot
./mybundle/myroot/a
./mybundle/myroot/a/exec.fifo
./mybundle/myroot/a/state.json
./myroot
> sudo runc --root myroot state a
container "a" does not exist
> sudo runc --root mybundle/myroot state a
{
  "ociVersion": "1.0.0",
  "id": "a",
  "pid": 241,
  "status": "created",
...
```

This seems to be because commands like `create` change directory to the bundle before getting the absolute path to the root. And commands like `state` do _not_ change directory to the bundle before getting the absolute path to the root.

Possibly, there should be a `reviseRootDir` similar to the existing `revisePidFile`?

**Comment by cyphar** [comment]
Yeah `--root` should probably be relative to the current directory.

**Comment by knabben** [comment]
can I give it a try?

**Comment by kolyshkin** [comment]
> can I give it a try?

Sure, why not!
