### ISSUE TITLE
Mount propagation flags don't work

### ISSUE THREAD

**Issue by rhvgoyal** [opencontainers/runc#263]
Currently if I specify a mount propagation flag in "options", it does not take effect. For example  try following bind mount in config.json.

 {
  "type": "bind",
  "source": "/root/mnt-source",
  "destination": "/root/mnt-dest",
  "options": "rbind,shared"
}

And inside container check the properties of mount.

$ findmnt -o TARGET,PROPAGATION /root/mnt-dest
/root/mnt-dest                      private

It continues to be private, despite the fact user requested for it to be "shared".

**Comment by mrunalp** [comment]
Closing as #264 was merged.
