### ISSUE TITLE
Running a python file in the runC container

### ISSUE THREAD

**Issue by ashwani29** [opencontainers/runc#2637]
How can I run a python file in the runC container? I've exported `ubuntu` filesystem as `rootfs` instead of `busybox`, but still, it gives an error of `python3 not found`.

Even can't install it. it is unable to locate package.
```
# apt-get install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
W: Not using locking for read only lock file /var/lib/dpkg/lock-frontend
W: Not using locking for read only lock file /var/lib/dpkg/lock
E: Unable to locate package python3

```

Cannot use sudo, says `sudo: not found`.

**Comment by kolyshkin** [comment]
> # apt-get install python3

1. You have to run `apt-get update` first.

2. It might be called `python` not `python3`, depending on the distro.

3. This is not the right place to ask questions. This is a place to report runc bugs.

**Comment by ashwani29** [comment]
@kolyshkin  So where to ask these questions?
