### ISSUE TITLE
Can't install package via Go get

### ISSUE THREAD

**Issue by kenorb** [opencontainers/runc#2638]
```
$  go get github.com/opencontainers/runc
package github.com/opencontainers/runc
	imports github.com/opencontainers/runc/libcontainer/nsenter: C source files not allowed when not using cgo or SWIG: cloned_binary.c nsexec.c
```

Tested on macOS 10.15.7.

**Comment by cyphar** [comment]
runc doesn't support MacOS (it's a Linux-only program). `go get` does work on Linux, but I wouldn't recommend using it because we set several string constants when using `make` as well as several build tags.
