### ISSUE TITLE
Incremental checkpointing

### ISSUE THREAD

**Issue by gitsvm** [opencontainers/runc#2650]
Is it possible to do incremental checkpointing in `runc` with full `dumps`?
In criu, we can do incremental checkpoints by doing

```
criu dump --tree <pid> --images-dir <path-to-existing-directory-B> \
 --prev-images-dir <path-to-directory-A-relative-to-B> --leave-stopped --track-mem
```
from the help option of runc, it says we can use
`--parent-path value path for previous criu image files in pre-dump option` but in case of pre-dumps only, Is there similar thing in runc which can do incremental checkpointing with full dumps also?

**Comment by gitsvm** [comment]
I'm not able to even verify it , i'm doing incremental checkpoints using runc command
`sudo runc checkpoint --leave-running --parent-path images --image-path images2/ <ctr_id>`
and everytime the checkpoint size is same. so unable to verify whether it is doing checkpoints incrementally and that too with full dumps.

**Comment by gitsvm** [comment]
Is it like incremental checkpoints are possible in criu only not in runc?

> Is it possible to do incremental checkpointing in `runc` with full `dumps`?
> In criu, we can do incremental checkpoints by doing
> 
> ```
> criu dump --tree <pid> --images-dir <path-to-existing-directory-B> \
>  --prev-images-dir <path-to-directory-A-relative-to-B> --leave-stopped --track-mem
> ```
> 
> from the help option of runc, it says we can use
> `--parent-path value path for previous criu image files in pre-dump option` but in case of pre-dumps only, Is there similar thing in runc which can do incremental checkpointing with full dumps also?

**Comment by kolyshkin** [comment]
@adrianreber PTAL

**Comment by adrianreber** [comment]
This is exactly the same question as https://github.com/checkpoint-restore/criu/issues/1237: It does not work in `runc` and needs to be implemented if needed. Another possible solution would be using CRIU configuration files like mentioned in the CRIU issue. This can be closed.

**Comment by gitsvm** [comment]
Yes i think this will be helpful, will try those solutions mentioned in this issue.  Just one another question. is there any c/c++ or any other language library which can do checkpoints for `runc` container ?
> This is exactly the same question as [checkpoint-restore/criu#1237](https://github.com/checkpoint-restore/criu/issues/1237): It does not work in `runc` and needs to be implemented if needed. Another possible solution would be using CRIU configuration files like mentioned in the CRIU issue. This can be closed.

**Comment by adrianreber** [comment]
>  Just one another question. is there any c/c++ or any other language library which can do checkpoints for `runc` container ?

You could look at crun, which is in C and which also does checkpoints of containers using CRIU.

**Comment by gitsvm** [comment]
This is as powerful as `runc` right?
