### ISSUE TITLE
container_linux.go:345: starting container process caused "read init-p: connection reset by peer"

### ISSUE THREAD

**Issue by chenliu1993** [opencontainers/runc#2662]
Hi experts,
    I am execing a process inside archlinux container through libconatiner's Run(p) method.
    But I always got a err like the title said. The error is happening on container_linux.go's handleFifoResult() func and this func is called on https://github.com/opencontainers/runc/blob/07e35a7a409c14d665d06733c21aaae37810d63a/libcontainer/container_linux.go#L295 and https://github.com/opencontainers/runc/blob/07e35a7a409c14d665d06733c21aaae37810d63a/libcontainer/container_linux.go#L302.
From the err msg content, it seems 302 is not the problem.
I am confused here, what could be the reasons here?
And it seems this is a archlinux containier-specific problem.
Thanks in advance!

**Comment by chenliu1993** [comment]
And where this read-p comes from?

**Comment by AkihiroSuda** [comment]
Please provide a full reproducer of your issue

**Comment by chenliu1993** [comment]
Seems this maybe a bug of our own. Needs more debugging. closing this issue.
