### ISSUE TITLE
Move cgroup v2 out of experimental

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2663]
We have seen a lot of refactoring (thanks @kolyshkin ) for the cgroup drivers.

I think v1 and v2 now have same level of implementation quality, so I suggest moving cgroup v2 out of experimental.

`README.md` and `docs/cgroup-v2.md` need to be updated, but the code does not need to be updated.

**Comment by AkihiroSuda** [comment]
@kolyshkin @giuseppe @cyphar WDYT?

**Comment by kolyshkin** [comment]
Although not as production tested as cgroup v1, I think v2 in its current form is ready for prime time.

**Comment by mrunalp** [comment]
Sounds good to me :+1:

**Comment by AkihiroSuda** [comment]
PR https://github.com/opencontainers/runc/pull/2674
