### ISSUE TITLE
CI: switch to travis-ci.com github checks API

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#2670]
Currently, integration provided by travis-ci.org is "legacy", IOW it is not seen in "checks" tab on a PR page, and clicking a link leads directly to travis-ci page.

Travis-CI.com offers github checks API integration, meaning it will look like this: https://github.com/kolyshkin/runc/pull/4/checks

I propose moving to travis-ci.com (which still has free tier for open source projects) and enable this integration. For more details, see https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by kolyshkin** [comment]
OK, looks like it's imminent anyway, as travis-ci.org is closing down in December 2020, see https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by kolyshkin** [comment]
Going to proceed with the changes...

**Comment by kolyshkin** [comment]
I can't proceed -- I guess I need opencontainers org admin rights to add travis-ci from marketplace. @caniszczyk HALP

**Comment by kolyshkin** [comment]
Basically I need to add travis-ci to https://github.com/opencontainers/runc/settings/installations

**Comment by kolyshkin** [comment]
OK, I have migrated my fork of runc (i.e. github.com/kolyshkin/runc) to travis-ci.com last night and I already ran out of credits :confused:

So, I guess, it's not suitable unless @thelinuxfoundation pays for non-free tier.

(removing the rc93 milestone)

**Comment by kolyshkin** [comment]
OK, @caniszczyk suggested (https://twitter.com/cra/status/1324107650288832519) switching to github actions instead. Let's see if it is possible with all our Vagrant tricks etc.

**Comment by kolyshkin** [comment]
Alas, nested virtualization is not supported by GH actions (tried it as well as found found this: https://github.com/actions/virtual-environments/issues/183), and they only provide Ubuntu Images (we need Fedora 32 and CentOS 7).

Circle CI also only provides Ubuntu images, and apparently nested virtualization is not supported either (haven't tried it).

:thinking:

**Comment by cyphar** [comment]
In addition, my personal experience with GitHub Actions for CI is quite mixed. I was under the impression that travis-ci.com was free for FOSS projects forever? Or am I misunderstanding?

**Comment by adrianreber** [comment]
@kolyshkin Same happened to me yesterday. Trying to move CRIU to travis-ci.com and testing it on my account I ran out of Travis credits after half a day.

Using Cirrus CI I am able to boot a vagrant based Fedora 32 VM: https://cirrus-ci.com/task/5842008197562368

**Comment by kolyshkin** [comment]
> Using Cirrus CI I am able to boot a vagrant based Fedora 32 VM

Nice, thanks! Maybe it's time to switch to cirrus-ci (and still ask LF to pay for it)

**Comment by kolyshkin** [comment]
> I was under the impression that travis-ci.com was free for FOSS projects forever? Or am I misunderstanding?

So, this is what they say ("it's free and will always be free"). They also say that [travis-ci.org will be officially closed down completely on December 31st, 2020](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom), and that there is a free tier available on travis-ci.com. Problem is, free tier has a limited amount of per-month credits, which, given the amount of testing we do here, won't be enough for a day.

So it's not yet clear whether they will kill travis-ci.org, or when they will do it (probably not in December 2020 as I don't see any big red warnings on travis-ci.org), but I guess it's better to be prepared and have an alternative (paid travis, free circle-ci, paid circle-ci, free GH actions, something else...)

**Comment by cyphar** [comment]
Oh, I assumed "it's free and will always be free" means that for FOSS projects we basically get unlimited credit (as most other such CI and developer tooling sites work). Yeah we'll need to switch then...

**Comment by danger89** [comment]
Go to GitHub Actions.. or use GitLab.

**Comment by kolyshkin** [comment]
We are already using github actions for a few things, alas it is not yet suitable for everything we test (for one thing, we run CentOS 7 and Fedora 33 VMs to test old kernel and cgroupv2, respectively).

We won't be moving to travis-ci.com given the current situation of very limited credits given to opensource projects, so closing this.

**Comment by danger89** [comment]
FYI: You do know you are forced to move to Travis-ci.com if you don't taken any action this year?
