### ISSUE TITLE
cgroups/ebpf: switch to new cilium/ebpf API

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#2699]
`cilium/ebpf`'s `prog.{Attach,Detach}` API is now deprecated in favor of new link package (see  https://github.com/cilium/ebpf/pull/108/commits/5727d650c09d79ac987b3c2d4e5420e6393cd5c7 and https://github.com/cilium/ebpf/pull/110).

runc need to adopt.

```console
libcontainer/cgroups/ebpf/ebpf.go:35:12: SA1019: prog.Attach is deprecated: use link.RawAttachProgram instead.  (staticcheck)
	if err := prog.Attach(dirFD, ebpf.AttachCGroupDevice, unix.BPF_F_ALLOW_MULTI); err != nil {
	          ^
libcontainer/cgroups/ebpf/ebpf.go:39:13: SA1019: prog.Detach is deprecated: use link.RawDetachProgram instead.  (staticcheck)
		if err := prog.Detach(dirFD, ebpf.AttachCGroupDevice, unix.BPF_F_ALLOW_MULTI); err != nil {
		          ^
```

I don't know much about these matters; @cyphar mind to take a look?

**Comment by thaJeztah** [comment]
missed there was a tracking issue for this; I opened https://github.com/opencontainers/runc/pull/2903, which also revealed a potential bug in the closer (pls double-check that one)
