### ISSUE TITLE
Dockerfile of libcontainer contains wrong $GOPATH env

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#27]
Hi,

I've done the clone of runc repository from github

git clone https://github.com/opencontainers/runc

The Dockerfile contents of libcontainer
ENV GOPATH $GOPATH:/go/src/github.com/opencontainers/runc/libcontainer/vendor

Looks like there is no specific vendor inside libcontainer.

When I tried to build the makefile inside libcontainer, build fails.

Thanks

**Comment by crosbymichael** [comment]
This has been resolved by #44
