### ISSUE TITLE
Proposal: remove "apparmor" build tag

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2704]
The `apparmor` tag was introduced in a01ed80babebf1db6f303a64c871c04914456b18  (2014)  to make cgo dependency on libapparmor optional.

However, the cgo dependency was removed in db093f621f4e6d40feafbe6d7b89a9bee6f6ff85 (2017), so it doesn't seem meaningful to keep `apparmor` build tag. I suggest removing the build tag.

**Comment by cyphar** [comment]
Yeah I agree it's not needed anymore.

**Comment by kolyshkin** [comment]
:+1: makes total sense

**Comment by AkihiroSuda** [comment]
I'll open a PR after https://github.com/opencontainers/selinux/pull/132 gets merged, so that we can remove apparmor and selinux together at once.

**Comment by AkihiroSuda** [comment]
PR: https://github.com/opencontainers/runc/pull/2709
