### ISSUE TITLE
unable to run mysql and redis in a runc container

### ISSUE THREAD

**Issue by gitsvm** [opencontainers/runc#2713]
I have to evaluate the mysql and redis server application in a runc container. 
To set up mysql in a runc container i followed below steps:

- mkdir -p mysql_container/rootfs
- cd mysql_container
- docker export $(docker run -d mysql:latest) |tar -C rootfs -xvf -
- runc spec
- sudo runc run mysql_container

This throws the error: `sh: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`

Similary how can i set up a redis server in a runc container?  

config.json for mysql container:  [config.txt](https://github.com/opencontainers/runc/files/5719244/config.txt)

**Comment by kolyshkin** [comment]
Works for me. Maybe you need to forcefully `docker pull` the latest image.

In any case, this seems like a problem with the image, not runc, and this place is for runc issues.

**Comment by gitsvm** [comment]
If it works for you then it's definitely not the problem with image.  What is the proper way to run any service (which can be run with docker) with `runc` too? 
Which can automatically generate config.json file, many times I doubt whether config.json I've written is correct or not. 

How do you generate this file and please tell the steps you follow to run most of the applications with runc?
