### ISSUE TITLE
CI: avoid hitting Docker Hub limit

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2718]
```
not ok 55 runc run (hooks library tests)
# (from function `get_and_extract_debian' in file tests/integration/multi-arch.bash, line 35,
#  from function `setup_debian' in file tests/integration/helpers.bash, line 512,
#  from function `setup' in test file tests/integration/hooks.bats, line 16)
#   `setup_debian' failed
# time="2021-01-05T04:38:21Z" level=fatal msg="Error initializing source docker://amd64/debian:buster: Error reading manifest buster in docker.io/amd64/debian: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
```

saw in https://github.com/opencontainers/runc/pull/2715#issuecomment-754391045

Maybe we can use mirror.gcr.io or something else similar.

**Comment by kolyshkin** [comment]
So, most CI providers (including GH actions) have implemented proxies and other measures to fix this, so their users are saved from hitting rate limiter. Travis CI did not do this for some reason.

There are workarounds, like logging in to docker hub, but given the fact that travis-ci.org will be retired in a few weeks, and travis-ci.com is not suitable (not in it's "free for open source projects" tier) it probably does not make sense to try and fix it.

Seems like it's better to find an alternative to travis ci. Opened https://github.com/opencontainers/runc/issues/2720 to track it.

**Comment by kolyshkin** [comment]
Fixed by #2721 (github actions infra is supposed to use proxy to avoid hitting docker hub too much, so it should not happen)

**Comment by thaJeztah** [comment]
> github actions infra is supposed to use proxy to avoid hitting docker hub too much, so it should not happen

It may still happen on the macOS workers (IIRC), but authenticating to docker hub (can be using a "personal access token" with a dummy account; doesn't require privileges) can help to prevent being limited by IP-address. Let's keep an eye if it's still a problem; happy to help otherwise 👍

**Comment by dims** [comment]
we can request CNCF for the GCP account and store things we need there? (GCR)

**Comment by thaJeztah** [comment]
I think CI is only using the official images; if they would be images for the project itself, rate-limits for project-specific images can be removed (when applying for an open source account)
