### ISSUE TITLE
ci/gha: make the artefacts from make release available

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#2728]
We currently have a ci job that builds a static binary. It would be beneficial to have the binary (tarball) published somewhere so that whoever looks at PR can quickly test the result.

**Comment by tianon** [comment]
I've played with https://github.com/actions/upload-artifact and it's not awful, but IMO the Artifacts support in Actions leaves a lot to be desired; for example, downloading the artifacts requires you to be authenticated, which is fine when you click download from a browser, but makes it kind of annoying to try to download from GitHub Actions in a separate repo to do cross-repo testing (for which I ended up using https://github.com/dawidd6/action-download-artifact).
