### ISSUE TITLE
Container failed to start on seccomp not enabled

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#273]
With the latest runc, spec will generate the seccomp entries in runtime.json file, but I have disabled seccomp in Makefile,   Since the spec by default generates the seccomp entries. Container failed to start and gave the following message.
seccomp: config provided but seccomp not supported

I've removed the seccomp entries in config.json to start the container.

As per the current implementation
 if l.config.Config.Seccomp != nil {
                if err := seccomp.InitSeccomp(l.config.Config.Seccomp); err != nil {
                        return err
                }
Entry is available in config, but seccomp is disabled.
Not sure whether container start failure is expected in this case ?

**Comment by mheon** [comment]
This definitely looks like a bug. The "Seccomp disabled" error should be ignored in this case. I'll whip up a quick patch to do this.

**Comment by rajasec** [comment]
Thanks @mheon for getting the fix. Thinks like Selinux, apparmor comes as default spec value with empty value. It is up to the user to fill the right security profiles. I'm not sure about why seccomp comes with default values along with the spec itself.

I'm not expert in this area, but just an thought

1) Do not return err in case of "seccomp: config provided but seccomp not supported", so that container can start gracefully
2) Fill with "empty value" during the spec creation itself in runtime.json
3) Move the seccomp config file creation steps to different file, so that we can control via build tags

**Comment by rajasec** [comment]
@mheon 
Thanks for the fix.

**Comment by mheon** [comment]
@rajasec No problem. I want to investigate making the Seccomp config empty by default as well if support isn't compiled in, which will also eliminate the warning that will show up after that change.

**Comment by crosbymichael** [comment]
Why not just delete the seccomp section if you are not going to use it?  The `runc spec` command is meant to provide you a starting point and to see many of the options that you have available.  It's not meant to be the set in stone config values and more than likely you are going to edit this file after it's generated anyways.

**Comment by mheon** [comment]
That's definitely also a solution to this - I just feel like generating a config that fails in a non-obvious way out of the box is confusing. Users who don't know what seccomp is are going to have to hunt through the generated configs to find why they're getting strange errors or warnings.

Maybe it would be better to not generate a Seccomp config by default, requiring you to manually add it (and presumably know what you're doing).

**Comment by rajasec** [comment]
@mheon 
More similar to other security things like apparmor & selinux profiles. Let the user defines the syscall entries for seccomp

**Comment by crosbymichael** [comment]
@mheon @rajasec 

runc just generates a good default to get people started and tries to add everything so people know the options that they have available to them.  That is why the spec does not have `omitempty` on the struct fields so that people can see all options.

It's not meant for you to just `runc spec && runc start` and everything will be ok.  More likely than not you are going to edit those files and so it's not a burden to remove sections that you don't use.

**Comment by mrunalp** [comment]
I agree with @crosbymichael
