### ISSUE TITLE
cadvisor depends on public IntelRDTManager

### ISSUE THREAD

**Issue by ehashman** [opencontainers/runc#2733]
In https://github.com/opencontainers/runc/commit/933c4d31a77ac8b85982f960a09b7257fff51044 IntelRDTManager was made private.

However, cadvisor has a dependency on this interface: https://github.com/google/cadvisor/blob/c09d1abe244f5de5d0d547b366f434d8c0d87b1c/resctrl/collector.go#L25-L31

This means cadvisor cannot be bumped to the latest version of runc.

It's unclear to me if the fix is better suited for runc or cadvisor, but I ran into this when trying to bump runc in Kubernetes (https://github.com/kubernetes/kubernetes/pull/97992)

cc @bobbypage

**Comment by tianon** [comment]
Looks like @kolyshkin, @xiaochenshen, and @Creatone discussed this a bit in https://github.com/opencontainers/runc/pull/2653#issuecomment-723311584 :sweat_smile:

**Comment by ehashman** [comment]
Aha, I missed that in my quick scroll!

**Comment by ehashman** [comment]
I will close this -- if we want to bump to the latest runc in k8s, we should probably do it transitively via a cadvisor update first. For now, I'll try to just pick the most minimal runc diff that addresses the issue.
