### ISSUE TITLE
runc@master doesn't pass TestDockerSwarmSuite/TestServiceLogsTTY

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2742]
[`TestDockerSwarmSuite/TestServiceLogsTTY` of Moby v20.10.2](https://github.com/moby/moby/blob/v20.10.2/integration-cli/docker_cli_service_logs_test.go#L260-L296)  was passing with runc v1.0.0-rc92:
```bash
$ git clone https://github.com/docker/docker.git
$ cd docker
$ git checkout v20.10.2
$ TESTFLAGS='-test.run TestDockerSwarmSuite/TestServiceLogsTTY' DOCKER_BUILD_ARGS="--build-arg=RUNC_COMMIT=v1.0.0-rc92" make test-integration
```

The test is failing with the current master dbbe7e60c7b8c18cdf8a6e87d2dddcbfb24d7c90 (Jan 14)
```bash
$ TESTFLAGS='-test.run TestDockerSwarmSuite/TestServiceLogsTTY' DOCKER_BUILD_ARGS="--build-arg=RUNC_COMMIT=dbbe7e60c7b8c18cdf8a6e87d2dddcbfb24d7c90" make test-integration
...
=== FAIL: amd64.integration-cli TestDockerSwarmSuite/TestServiceLogsTTY (12.34s)
    --- FAIL: TestDockerSwarmSuite/TestServiceLogsTTY (12.34s)
        docker_cli_service_logs_test.go:295: assertion failed: 
            Command:  /usr/local/cli/docker --host unix:///tmp/docker-integration/dbd8f3b28537b.sock service logs --raw TestServiceLogsTTY
            ExitCode: 0
            Stdout:   out
            err
            
            Stderr:   
            
            Failures:
            Expected stdout to contain "out\r\nerr\r\n"
```

**Comment by AkihiroSuda** [comment]
Seems related to https://github.com/opencontainers/runc/pull/2723

Do we need to rollback to the rc92 behavior? Or can we just update Moby test to match the behavior of the current master?

**Comment by kolyshkin** [comment]
I think the new behavior is (more) correct, and the test need to be updated.

Even the test author was confused with `\r`, which, I _guess_, is another manifestation of the
race described in #2723 / #2425.

https://github.com/moby/moby/blob/8891c58a433a823ce0a65b57efff45f32ee9cb45/integration-cli/docker_cli_service_logs_test.go#L293-L295

**Comment by zhsj** [comment]
@AkihiroSuda Is there a moby issue related?

I'm not sure what I met is same as this.

Run with runc master with docker 20.10, I get a messed up termnial.

![image](https://user-images.githubusercontent.com/227180/104844790-28452880-590d-11eb-8267-c99329c9c5a3.png)

Git bisect points me to 24c05b71fa4fff0bf92c65240c7e22807717b3a4.

**Comment by AkihiroSuda** [comment]
Could you open a new issue? @zhsj

**Comment by zhsj** [comment]
> Could you open a new issue? @zhsj

https://github.com/opencontainers/runc/issues/2747

**Comment by AkihiroSuda** [comment]
The behavior will be rolled back in https://github.com/opencontainers/runc/pull/2749 (thanks @kolyshkin )
