### ISSUE TITLE
runc@master with docker 20.10.2 mess up the terminal

### ISSUE THREAD

**Issue by zhsj** [opencontainers/runc#2747]
```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:11:26 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92+dev
  GitCommit:        49cc2a22c30728a3686cbfe25794c6fa51b457e6
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

![image](https://user-images.githubusercontent.com/227180/104850017-b6c6a380-5927-11eb-9ecc-3d5b9f52b08f.png)

git bisect tells the regression is caused by https://github.com/opencontainers/runc/commit/24c05b71fa4fff0bf92c65240c7e22807717b3a4 (#2723)

**Comment by AkihiroSuda** [comment]
Is this issue specific to Docker/Moby?
I can reproduce this issue with Docker/Moby, but can't reproduce with nerdctl and Podman.

Do we need a fix on runc side or on Moby side?

**Comment by kolyshkin** [comment]
I have reproduced this with both docker and ctr, but can't repro with podman.

ctr repro:
``` console
// (1) replace runc with one from master
$ sudo mv /usr/bin/runc /usr/bin/runc.orig
$ sudo install runc /usr/bin/runc
$ which runc
/usr/bin/runc
$ runc --version
runc version 1.0.0-rc92+dev
commit: 49cc2a22c30728a3686cbfe25794c6fa51b457e6
spec: 1.0.2-dev
go: go1.15.6
libseccomp: 2.4.3

// (2) create a container
$ sudo ctr i pull docker.io/library/busybox:latest
$ sudo ctr run -d docker.io/library/busybox:latest bbb
// (3) run exec
$ sudo ctr t exec -t --exec-id=bbb-1 bbb ps | od -c
0000000   P   I   D               U   S   E   R                       T
0000020   I   M   E           C   O   M   M   A   N   D  \n            
0000040       1       r   o   o   t                           0   :   0
0000060   0       s   h  \n               1   3       r   o   o   t    
0000100                       0   :   0   0       p   s  \n
0000115
```

With stock runc, the last command gives:
```console
$ sudo ctr t exec -t --exec-id=bbb-2 bbb ps | od -c
0000000   P   I   D               U   S   E   R                       T
0000020   I   M   E           C   O   M   M   A   N   D  \r  \n        
0000040           1       r   o   o   t                           0   :
0000060   0   0       s   h  \r  \n               1   8       r   o   o
0000100   t                           0   :   0   0       p   s  \r  \n
0000120
```

Podman fixed this via https://github.com/cri-o/cri-o/pull/568 and https://github.com/containers/podman/pull/3143, with a test case added in https://github.com/containers/podman/pull/3986.

**Comment by AkihiroSuda** [comment]
Would it be possible to roll back to the previous behavior?

**Comment by cyphar** [comment]
From memory, we *did* revert the `ONCLR` behaviour of runc several years ago (I changed it during the `--console-socket` rewrite but it caused regressions)...

**Comment by kolyshkin** [comment]
So, it seems that docker cli can be fixed to set `opost onlcr` on a terminal, and (I still can't understand why) `ctr` is working fine without it. The comparison of straces between docker and ctr shows that ctr sets `opost` while docker doesn't.

I'm still very much lost, so going to partially revert the patch to restore the status quo. We can try this again once docker et at are fixed (to set `opost onlcr`).

Still don't know what to do with the flaky test case (https://github.com/opencontainers/runc/issues/2425).

**Comment by kolyshkin** [comment]
> Still don't know what to do with the flaky test case (#2425).

Current dumb idea is to make the test code look more like the code of tty.go (i.e. with `console.Epoller` etc) and see it it fixes the race.

**Comment by kolyshkin** [comment]
I'll take a fresh look tomorrow but for now it is https://github.com/opencontainers/runc/pull/2749
