### ISSUE TITLE
Go 1.16: TestHelperProcess: a test that calls os.Exit(0) during execution of a test function will now be considered to fail

### ISSUE THREAD

**Issue by eclipseo** [opencontainers/runc#2765]
In Go 1.16, the following change was added:

> 
> go test
> 
> When using go test, a test that calls os.Exit(0) during execution of a test function will now be considered to fail. This will help catch cases in which a test calls code that calls os.Exit(0) and thereby stops running all future tests. If a TestMain function calls os.Exit(0) that is still considered to be a passing test. 

See https://tip.golang.org/doc/go1.16#tools

This makes the following test fail:

https://github.com/opencontainers/runc/blob/c69ae759fbf5acf6e8ef805471b99feee8246c3c/libcontainer/configs/config_test.go#L203-L206

We are testing Go 1.16 beta 1 in Fedora Rawhide, so this error prevents us from successfully build the package.

**Comment by cyphar** [comment]
We'd be happy to take a one-line patch removing that (and any other examples you may have hit).

**Comment by eclipseo** [comment]
We can't simply remove `os.Exit(0)` otherwise it would break:

https://github.com/opencontainers/runc/blob/c69ae759fbf5acf6e8ef805471b99feee8246c3c/libcontainer/configs/config_test.go#L155-L177

TBH I don't know how to fix this.

**Comment by cyphar** [comment]
Ah okay. I'll take a look at fixing this sometime this week.

**Comment by kolyshkin** [comment]
This is actually fixed in https://github.com/opencontainers/runc/pull/2660

**Comment by eclipseo** [comment]
Thanks to all the persons involved!
