### ISSUE TITLE
getCgroupRoot doesn't return expected value when run within nested container

### ISSUE THREAD

**Issue by bduffany** [opencontainers/runc#2766]
I'm trying to run containerd inside a container, but when I try to spawn child containers, I'm getting the error:

```
ctr: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: no cgroup mount found in mountinfo: unknown
```

I dug into this a bit and found that `tryDefaultCgroupRoot` was returning `""`, since it hits the case where the `Dev` of `/sys/fs/cgroup` equals the `Dev` of `/sys/fs`: https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/fs.go#L88-L91

(I copied this Go function & its deps, added some print statements, and ran it inside the parent container in order to figure this out).

This seems unexpected because if I run a docker-on-docker container (e.g. `docker run -it docker sh`) -- which IIUC uses containerd / runc under the hood -- I can see that `/sys/fs/cgroup` exists, and I'm guessing this is the "cgroup root" that should be returned by that `tryDefaultCgroupRoot` func.

Is this a bug? And is there a workaround?

Here's the script I'm using (as well as the `main.go` for debug binary I mentioned above): https://gist.github.com/bduffany/b2c758c5e796f12ef657051e9fe141e7 (in this setup, I'm running a new instance of `containerd` within the parent container, to avoid having to mount `/run/containerd`, `/var/lib/containerd` etc. to the parent container)

(Pretty new to cgroups, namespaces etc. so I would super grateful if you could help correct any misunderstandings or incorrect assumptions I've made in any of the above.)

**Comment by bduffany** [comment]
@kolyshkin @vmarmol who wrote this originally

**Comment by kolyshkin** [comment]
The code of cgroup v1 fs driver expects individual cgroup mounts (i.e. those with fstype of `cgroup`) in /proc/self/mountinfo. It was doing that before my changes, iow `tryDefaultCgroupRoot` is just an optimization.

I guess your container misses those cgroup mounts. When I run a standard container with spec created by `runc spec` on a cgroup v1 host, I see the following mounts:

```
/ # cat /proc/self/mountinfo | grep cgroup
784 783 0:60 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,mode=755
785 784 0:31 / /sys/fs/cgroup/systemd ro,nosuid,nodev,noexec,relatime - cgroup systemd rw,xattr,name=systemd
786 784 0:35 / /sys/fs/cgroup/pids ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids
787 784 0:36 / /sys/fs/cgroup/freezer ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
788 784 0:37 / /sys/fs/cgroup/hugetlb ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,hugetlb
789 784 0:38 / /sys/fs/cgroup/perf_event ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event
790 784 0:39 / /sys/fs/cgroup/memory ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
791 784 0:40 / /sys/fs/cgroup/net_cls,net_prio ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls,net_prio
792 784 0:41 / /sys/fs/cgroup/devices ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
849 784 0:42 / /sys/fs/cgroup/blkio ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
856 784 0:43 / /sys/fs/cgroup/cpu,cpuacct ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu,cpuacct
857 784 0:44 / /sys/fs/cgroup/cpuset ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset
858 784 0:45 / /sys/fs/cgroup/rdma ro,nosuid,nodev,noexec,relatime - cgroup cgroup rw,rdma
```

Those are created because container's config.json has this:

```json
        "mounts": [
...
                {
                        "destination": "/sys/fs/cgroup",
                        "type": "cgroup",
                        "source": "cgroup",
                        "options": [
                                "nosuid",
                                "noexec",
                                "nodev",
                                "relatime",
                                "ro"
                        ]
                }
```

Your container apparently does not have it, or have it in some different way that precludes mounts to be shown in mountinfo as in my example above.

**Comment by kolyshkin** [comment]
In other words, this is not a bug in runc, but rather in your container configuration.

**Comment by bduffany** [comment]
Ah, interesting -- if I update my script to include `--mount src=cgroup,dst=/sys/fs/cgroup,type=cgroup,options=nosuid:noexec:nodev:relatime:ro` in the `ctr` command, then it works.

As a bit of feedback (probably more for `ctr` than for `runc`, really) -- it would have been easier if this was somehow done automatically, or if there was maybe a flag like `--enable-nested-containers` which sets up the necessary config. Although I imagine that most people don't have the use case of running nested containers, so I guess I was expecting to run into some friction.

Thank you! :smiley:
