### ISSUE TITLE
libcontainer/seccomp/patchbpf: build fails without cgo

### ISSUE THREAD

**Issue by thaJeztah** [opencontainers/runc#2778]
Didn't look too closely, but noticed this while trying to run golang-ci-lint locally;

```bash
docker run --rm -v $(pwd):/go/src/github.com/opencontainers/runc -w /go/src/github.com/opencontainers/runc golangci/golangci-lint:v1.35.2 golangci-lint run -v
```

...

```
level=warning msg="[runner] Can't run linter goanalysis_metalinter: S1018: failed prerequisites: 
[(inspect@github.com/opencontainers/runc/libcontainer/seccomp/patchbpf, isgenerated@github.com/opencontainers/runc/libcontainer/seccomp/patchbpf): analysis skipped:
errors in package: [/go/src/github.com/opencontainers/runc/libcontainer/seccomp/patchbpf/enosys_unsupported.go:10:13:
could not import github.com/seccomp/libseccomp-golang (/go/src/github.com/opencontainers/runc/vendor/github.com/seccomp/libseccomp-golang/seccomp.go:26:8:
could not import C (cgo preprocessing failed))]]"
```

https://github.com/opencontainers/runc/blob/c531a6f26aa2ee5ccf89b88d12b59d6152127ce3/libcontainer/seccomp/patchbpf/enosys_unsupported.go#L10-L13

**Comment by thaJeztah** [comment]
@cyphar @AkihiroSuda ptal

**Comment by cyphar** [comment]
Yeah this is problem I solved in CI by requiring `libseccomp-devel`. It seems that golang-ci can't handle cgo projects? I'm not sure how we could work around this because we need cgo in order to implement `patchbpf`...

**Comment by AkihiroSuda** [comment]
A quick workaround would be to just replace `*libseccomp.ScmpFilter` with `interface{}`, though it may look weird.

**Comment by thaJeztah** [comment]
>  I'm not sure how we could work around this because we need cgo in order to implement patchbpf...

Yup; the issue in this case is that it's in the `_unsupported.go` file, so in situations where seccomp or cgo are not enabled / supported.

> A quick workaround would be to just replace *libseccomp.ScmpFilter with interface{}, though it may look weird.

Perhaps not that bad it we add a comment; this file is just a "stub" if its not supported, so probably not too horrible.

**Comment by thaJeztah** [comment]
Actually wondering if `PatchAndLoad()` needs to have a stub at all, because `InitSeccomp` won't call it on situations that don't have seccomp; https://github.com/opencontainers/runc/blob/4d4d19ce528ac40cc357ef92cd3a6931dba19316/libcontainer/seccomp/seccomp_unsupported.go#L14-L19

**Comment by cyphar** [comment]
My only question is does this mean that golang-ci doesn't scan cgo package sources by default? In other words if you don't give it the right build tags will it not lint code? Or is there another reason it cares about build dependencies based on `-tags ""` builds?

**Comment by kolyshkin** [comment]
I think that `cgo` tag is enabled by default (if supported, and it is supported on where we run golangci-lint).

OTOH `seccomp` is not set when running golangci-lint and I think we should add it (or change the logic to have the functionality on by default, unless something like `disable_seccomp` is not set).

**Comment by kolyshkin** [comment]
>  I think we should add it

https://github.com/opencontainers/runc/pull/2782

(Note it only reports issues for the current PR; needs to be merged in order to run on master)
