### ISSUE TITLE
Setting cgroup config failed when nested inside LXC unprivileged container w/ pure cgroups v2 ("unified hierarchy")

### ISSUE THREAD

**Issue by PeterCxy** [opencontainers/runc#2792]
I am trying to run Docker inside an unprivileged LXC container on a host with pure cgroups v2 (systemd "unified hierarchy"), but with limited success with `runc` runtime. Before `runc 1.0-rc93`, the runtime fails in an attempt to use `systemd --user` even when it is the root user inside the unprivileged LXC container, which I believe is the same regression as described in #2724 and now fixed in #2725. However, now, on `1.0-rc93`, another new error emerges from `runc`:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: can't load program: operation not permitted: unknown.
```

For context, using `crun` as Docker's OCI runtime instead of `runc` works perfectly and I've had no issues with it so far.

**Comment by cyphar** [comment]
So we're getting `EPERM` while trying to inject the BPF rule for the devices cgroup... @giuseppe can you think of something we're doing that is substantially different to crun here?

**Comment by AkihiroSuda** [comment]
https://github.com/opencontainers/runc/blob/12644e614e25b05da6fd08a38ffa0cfe1903fdec/libcontainer/cgroups/fs2/devices.go#L31-L38

This function needs to return constantly true when we are in userNS

**Comment by cyphar** [comment]
Yeah I was thinking along the same lines -- I can cook up a quick patch for that.

**Comment by cyphar** [comment]
It should be noted our rule for this is actually a bit wrong IMHO -- crun now does what I think makes more sense (if there are any block rules we cannot ignore the error).
