### ISSUE TITLE
runc checkpoint not working 

### ISSUE THREAD

**Issue by devikrishnar** [opencontainers/runc#2811]
Hi, when I try to checkoint a runC busybox container using the command - 
`runc checkpoint --image-path images <container_name>`

I am getting the following error- 
```
ERRO[0000] container is not destroyed                   
ERRO[0000] read unixpacket @->@: EOF   
```

Here are some extracts from the config.json file -

```
        "ociVersion": "1.0.2-dev",
        "process": {
                "terminal": true,
                "user": {
                        "uid": 0,
                        "gid": 0
                },
                "args": [
                        "sh"
                ],
                "env": [
                        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                        "TERM=xterm"
                ],
......
        "root": {
                "path": "rootfs",
                "readonly": true
        },
```

I tried the same with an ubuntu container and I am getting the same failure. 
The pre-dump operation is working fine.
These are the versions of CRIU and runC I am using -
```
user@server:~# runc --version
runc version 1.0.0-rc93+dev
commit: f245a1d1edbf545549e5a16106cf1aec356a3c7d
spec: 1.0.2-dev
go: go1.13.8
libseccomp: 2.4.3
user@server:~# criu --version
Version: 3.12
GitID: v3.12-175-g3953b3332
```

When I try to checkpoint the container using CRIU, I get the following error - 
```
Error (criu/mount.c:945): mnt: Mount 1344 ./sys/fs/cgroup/cpuset (master_id: 25 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
Error (criu/cr-dump.c:2103): Dumping FAILED.
```

Can someone please provide an explanation and solution for this issue?

**Comment by kolyshkin** [comment]
> Version: 3.12

please retry with criu 3.15 (see https://criu.org/Packages to find packages for your distro, or compile it from source)

**Comment by kolyshkin** [comment]
> Mount 1344 ./sys/fs/cgroup/cpuset (master_id: 25 shared_id: 0) has unreachable sharing

Enabling cgroup namespace might also help (but try updated criu first).

**Comment by kolyshkin** [comment]
No reply from the original reporter, so I suggest we close this one.

**Comment by devikrishnar** [comment]
Thanks, will try with updated CRIU and see if the issue is resolved. Will get back if any other help is required.
