### ISSUE TITLE
proposal: add --no-delete to runc run

### ISSUE THREAD

**Issue by tonistiigi** [opencontainers/runc#2817]
`runc run` is much more simple to use than `create/start` async commands that are almost impossible to use safely without introducing a special shim-like binary to deal with `SIGCHLD` reaper issues.

One of the problems though is that when using `run` calling process can't get the full stats of the process because cgroups are already deleted when it returns. Could we consider adding `--no-delete` option that leaves cgroups and other resources in place so the caller can analyze them and then call `runc delete` to do the manual cleanup.

**Comment by lifubang** [comment]
+1

**Comment by kolyshkin** [comment]
Maybe `--keep-cgroups`? I'm not sure what are the other resources (except maybe intel RDT).

**Comment by lifubang** [comment]
> Maybe `--keep-cgroups`? I'm not sure what are the other resources (except maybe intel RDT).

Besides cgroup paths, we should keep runc state dir to allow us use `runc delete` to delete the cgroup paths, so I'd prefer to use `--no-delete`.

**Comment by lifubang** [comment]
It's very easy to implement. Please see #2825 .

**Comment by lifubang** [comment]
As described in https://github.com/opencontainers/runc/pull/2825#discussion_r584178754
We suggest change `--no-delete` to `--keep`.
