### ISSUE TITLE
Test failure on armhf - integer overflow

### ISSUE THREAD

**Issue by lucaskanashiro** [opencontainers/runc#2846]
I am trying to update the `runc` Ubuntu package to version `1.0-rc93` but the following test is failing on armhf (32 bits):

```
# github.com/opencontainers/runc/libcontainer/seccomp/patchbpf [github.com/opencontainers/runc/libcontainer/seccomp/patchbpf.test]
src/github.com/opencontainers/runc/libcontainer/seccomp/patchbpf/enosys_linux_test.go:180:20: constant 3735928559 overflows int
src/github.com/opencontainers/runc/libcontainer/seccomp/patchbpf/enosys_linux_test.go:204:19: constant 3735928559 overflows int
src/github.com/opencontainers/runc/libcontainer/seccomp/patchbpf/enosys_linux_test.go:227:25: constant 3735928559 overflows int
FAIL	github.com/opencontainers/runc/libcontainer/seccomp/patchbpf [build failed]
```

The new "special handling for seccomp profiles to avoid making new syscalls unusable for glibc" is exactly the feature that I am looking for, but this failure is a blocker. Full build log:

https://launchpadlibrarian.net/527223578/buildlog_ubuntu-hirsute-armhf.runc_1.0.0~rc93-0ubuntu1~ppa1_BUILDING.txt.gz

**Comment by tianon** [comment]
I think this was fixed in https://github.com/opencontainers/runc/pull/2768 (which isn't in the latest release yet). :sweat_smile:

**Comment by kolyshkin** [comment]
@lucaskanashiro please test the git tip (or grab the first commit from #2768) and report whether it fixes your issue.

If yes, guess we can close it as a duplicate fo https://github.com/opencontainers/runc/issues/2783.

**Comment by lucaskanashiro** [comment]
Ah I did not notice this fix, my bad. It indeed fixes my issue! Sorry for the noise, we can close this bug.
