### ISSUE TITLE
ERRO[0000] container_linux.go:367: starting container process caused: exec: "sleep": executable file not found in $PATH

### ISSUE THREAD

**Issue by aiaiai-czh** [opencontainers/runc#2856]
hello, today i use runc to run/create a container, but i meet a problem and don't know how to solve. First i use skopeo to copy the remote image to local and use oci-image-tool to create the bundle, the command is 
```
skopeo copy docker://hello-world oci:hello-world
oci-image-tool create --ref latest hello-world hello-world-bundle
```
but when i use runc to create the container, i meet the problem
```
ERRO[0000] container_linux.go:367: starting container process caused: exec: "sleep": executable file not found in $PATH
```
and this is my config.json, i use runc spec to create it and i update the args
```
{
  "ociVersion": "1.0.2-dev",
  "process": {
    "terminal": true,
    "user": {
      "uid": 0,
      "gid": 0
    },
    "args": [
      "sleep",
      "5"
    ],
    "env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "TERM=xterm"
    ],
    "cwd": "/",
    "capabilities": {
      "bounding": [
        "CAP_AUDIT_WRITE",
        "CAP_KILL",
        "CAP_NET_BIND_SERVICE"
      ],
      "effective": [
        "CAP_AUDIT_WRITE",
        "CAP_KILL",
        "CAP_NET_BIND_SERVICE"
      ],
      "inheritable": [
        "CAP_AUDIT_WRITE",
        "CAP_KILL",
        "CAP_NET_BIND_SERVICE"
      ],
      "permitted": [
        "CAP_AUDIT_WRITE",
        "CAP_KILL",
        "CAP_NET_BIND_SERVICE"
      ],
      "ambient": [
        "CAP_AUDIT_WRITE",
        "CAP_KILL",
        "CAP_NET_BIND_SERVICE"
      ]
    },
    "rlimits": [
      {
        "type": "RLIMIT_NOFILE",
        "hard": 1024,
        "soft": 1024
      }
    ],
    "noNewPrivileges": true
  },
  "root": {
    "path": "rootfs",
    "readonly": true
  },
  "hostname": "runc",
  "mounts": [
    {
      "destination": "/proc",
      "type": "proc",
      "source": "proc"
    },
    {
      "destination": "/dev",
      "type": "tmpfs",
      "source": "tmpfs",
      "options": [
        "nosuid",
        "strictatime",
        "mode=755",
        "size=65536k"
      ]
    },
    {
      "destination": "/dev/pts",
      "type": "devpts",
      "source": "devpts",
      "options": [
        "nosuid",
        "noexec",
        "newinstance",
        "ptmxmode=0666",
        "mode=0620",
        "gid=5"
      ]
    },
    {
      "destination": "/dev/shm",
      "type": "tmpfs",
      "source": "shm",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "mode=1777",
        "size=65536k"
      ]
    },
    {
      "destination": "/dev/mqueue",
      "type": "mqueue",
      "source": "mqueue",
      "options": [
        "nosuid",
        "noexec",
        "nodev"
      ]
    },
    {
      "destination": "/sys",
      "type": "sysfs",
      "source": "sysfs",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "ro"
      ]
    },
    {
      "destination": "/sys/fs/cgroup",
      "type": "cgroup",
      "source": "cgroup",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "relatime",
        "ro"
      ]
    }
  ],
  "linux": {
    "resources": {
      "devices": [
        {
          "allow": false,
          "access": "rwm"
        }
      ]
    },
    "namespaces": [
      {
        "type": "pid"
      },
      {
        "type": "network"
      },
      {
        "type": "ipc"
      },
      {
        "type": "uts"
      },
      {
        "type": "mount"
      }
    ],
    "maskedPaths": [
      "/proc/acpi",
      "/proc/asound",
      "/proc/kcore",
      "/proc/keys",
      "/proc/latency_stats",
      "/proc/timer_list",
      "/proc/timer_stats",
      "/proc/sched_debug",
      "/sys/firmware",
      "/proc/scsi"
    ],
    "readonlyPaths": [
      "/proc/bus",
      "/proc/fs",
      "/proc/irq",
      "/proc/sys",
      "/proc/sysrq-trigger"
    ]
  }
}
```
can you help me?

**Comment by aiaiai-czh** [comment]
> hello, today i use runc to run/create a container, but i meet a problem and don't know how to solve. First i use skopeo to copy the remote image to local and use oci-image-tool to create the bundle, the command is
> 
> ```
> skopeo copy docker://hello-world oci:hello-world
> oci-image-tool create --ref latest hello-world hello-world-bundle
> ```
> 
> but when i use runc to create the container, i meet the problem
> 
> ```
> ERRO[0000] container_linux.go:367: starting container process caused: exec: "sleep": executable file not found in $PATH
> ```
> 
> and this is my config.json, i use runc spec to create it and i update the args
> 
> ```
> {
>   "ociVersion": "1.0.2-dev",
>   "process": {
>     "terminal": true,
>     "user": {
>       "uid": 0,
>       "gid": 0
>     },
>     "args": [
>       "sleep",
>       "5"
>     ],
>     "env": [
>       "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>       "TERM=xterm"
>     ],
>     "cwd": "/",
>     "capabilities": {
>       "bounding": [
>         "CAP_AUDIT_WRITE",
>         "CAP_KILL",
>         "CAP_NET_BIND_SERVICE"
>       ],
>       "effective": [
>         "CAP_AUDIT_WRITE",
>         "CAP_KILL",
>         "CAP_NET_BIND_SERVICE"
>       ],
>       "inheritable": [
>         "CAP_AUDIT_WRITE",
>         "CAP_KILL",
>         "CAP_NET_BIND_SERVICE"
>       ],
>       "permitted": [
>         "CAP_AUDIT_WRITE",
>         "CAP_KILL",
>         "CAP_NET_BIND_SERVICE"
>       ],
>       "ambient": [
>         "CAP_AUDIT_WRITE",
>         "CAP_KILL",
>         "CAP_NET_BIND_SERVICE"
>       ]
>     },
>     "rlimits": [
>       {
>         "type": "RLIMIT_NOFILE",
>         "hard": 1024,
>         "soft": 1024
>       }
>     ],
>     "noNewPrivileges": true
>   },
>   "root": {
>     "path": "rootfs",
>     "readonly": true
>   },
>   "hostname": "runc",
>   "mounts": [
>     {
>       "destination": "/proc",
>       "type": "proc",
>       "source": "proc"
>     },
>     {
>       "destination": "/dev",
>       "type": "tmpfs",
>       "source": "tmpfs",
>       "options": [
>         "nosuid",
>         "strictatime",
>         "mode=755",
>         "size=65536k"
>       ]
>     },
>     {
>       "destination": "/dev/pts",
>       "type": "devpts",
>       "source": "devpts",
>       "options": [
>         "nosuid",
>         "noexec",
>         "newinstance",
>         "ptmxmode=0666",
>         "mode=0620",
>         "gid=5"
>       ]
>     },
>     {
>       "destination": "/dev/shm",
>       "type": "tmpfs",
>       "source": "shm",
>       "options": [
>         "nosuid",
>         "noexec",
>         "nodev",
>         "mode=1777",
>         "size=65536k"
>       ]
>     },
>     {
>       "destination": "/dev/mqueue",
>       "type": "mqueue",
>       "source": "mqueue",
>       "options": [
>         "nosuid",
>         "noexec",
>         "nodev"
>       ]
>     },
>     {
>       "destination": "/sys",
>       "type": "sysfs",
>       "source": "sysfs",
>       "options": [
>         "nosuid",
>         "noexec",
>         "nodev",
>         "ro"
>       ]
>     },
>     {
>       "destination": "/sys/fs/cgroup",
>       "type": "cgroup",
>       "source": "cgroup",
>       "options": [
>         "nosuid",
>         "noexec",
>         "nodev",
>         "relatime",
>         "ro"
>       ]
>     }
>   ],
>   "linux": {
>     "resources": {
>       "devices": [
>         {
>           "allow": false,
>           "access": "rwm"
>         }
>       ]
>     },
>     "namespaces": [
>       {
>         "type": "pid"
>       },
>       {
>         "type": "network"
>       },
>       {
>         "type": "ipc"
>       },
>       {
>         "type": "uts"
>       },
>       {
>         "type": "mount"
>       }
>     ],
>     "maskedPaths": [
>       "/proc/acpi",
>       "/proc/asound",
>       "/proc/kcore",
>       "/proc/keys",
>       "/proc/latency_stats",
>       "/proc/timer_list",
>       "/proc/timer_stats",
>       "/proc/sched_debug",
>       "/sys/firmware",
>       "/proc/scsi"
>     ],
>     "readonlyPaths": [
>       "/proc/bus",
>       "/proc/fs",
>       "/proc/irq",
>       "/proc/sys",
>       "/proc/sysrq-trigger"
>     ]
>   }
> }
> ```
> 
> can you help me?

**Comment by aiaiai-czh** [comment]
the kernel is 
Linux czh-virtual-machine 5.8.0-45-generic #51-Ubuntu SMP Fri Feb 19 13:24:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
the runc version is 
runc version 1.0.0-rc93+dev
commit: 249bca0a1316129dcd5bd38b5d75572274181cb5
spec: 1.0.2-dev
go: go1.14.2
libseccomp: 2.4.3

**Comment by AkihiroSuda** [comment]
Because "hello-world" image does not contain /bin/sleep.

Probably you want to try busybox image.
