### ISSUE TITLE
No checks for spec.Platform

### ISSUE THREAD

**Issue by zenlinTechnofreak** [opencontainers/runc#286]
There are no checks for spec.Platform before startContainer, 
when using the config.json as below, runc can start normally, I think it is not what we want.
``` json
{
  "version": "0.1.0",
  "platform": {
    "os": "osErr",
    "arch": "archErr"
  },

``` 
to my mind, may we have a check the platform before start the container.

So I new a PR Add detech of spec.Platform before star runc. #285, but it is auto tested failed, I think it is because of the err testcases?

Can anyone help me to fix it?

**Comment by hqhq** [comment]
I think these configs are supposed to be legal, confirmed by other tools like docker, and runc just take and use them, runc doesn't check every entries of config.

**Comment by crosbymichael** [comment]
yes, these fields are for information to the bundle author or user.  I'm not sure we want to validate these.
