### ISSUE TITLE
Audit active maintainers + call for new maintainers

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/runc#2891]
In regards to opencontainers/tob#95

If I do a quick audit of all of authors and last commit dates, i.e., git log --pretty=%an%x09%ad | awk -F$'\t' '!seen[$1]++'

I get this:

Kir Kolyshkin	Sat Apr 3 19:10:36 2021 -0700
Aleksa Sarai	Sat Apr 3 12:41:41 2021 +1100
Sebastiaan van Stijn	Sun Mar 14 19:41:55 2021 +0100
Mrunal Patel	Thu Apr 1 16:14:31 2021 -0700
Shiming Zhang	Thu Apr 1 20:54:13 2021 +0800
Akihiro Suda	Wed Mar 31 12:42:43 2021 +0900
Kieron Browne	Thu Mar 25 14:03:00 2021 +0000
Danail Branekov	Thu Mar 25 10:53:03 2021 +0000
Kenta Tada	Fri Mar 26 20:14:24 2021 +0900
AdamKorcz	Mon Mar 8 21:41:52 2021 +0000
Daniel Dao	Wed Feb 24 13:18:00 2021 +0000
Iceber Gu	Fri Feb 26 02:23:44 2021 +0800
Ryosuke Hanatsuka	Sat Feb 20 15:31:14 2021 +0900
Odin Ugedal	Mon Feb 22 08:44:49 2021 +0100
Adrian Reber	Mon Feb 8 13:20:02 2021 +0000
Vasiliy Ulyanov	Mon Feb 8 13:47:30 2021 +0100
Mauricio Vásquez	Wed Feb 3 16:06:32 2021 -0500
An Long	Sat Jan 30 00:45:52 2021 +0800
wangtianxia	Fri Jan 29 10:08:46 2021 +0800
Shengjing Zhu	Sat Jan 23 22:53:32 2021 +0800
acetang	Tue Jan 19 14:56:15 2021 +0800
Piotr Wagner	Fri Jul 31 09:08:52 2020 +0200
Peter Hunt	Thu Nov 19 09:38:05 2020 -0500
Paweł Szulik	Fri Dec 18 14:32:23 2020 +0100
Xiaochen Shen	Wed Dec 16 23:37:31 2020 +0800
Feng Sun	Fri Dec 11 12:22:04 2020 +0800
Michael Crosby	Tue Nov 10 10:47:32 2020 -0500
Giuseppe Scrivano	Fri Nov 6 11:36:45 2020 +0100
SataQiu	Sat Oct 17 13:14:55 2020 +0800
Cory Bennett	Mon Oct 5 22:18:21 2020 +0000
Chaitanya Bandi	Mon Oct 5 14:31:53 2020 -0700
Amim Knabben	Fri Oct 2 23:12:29 2020 -0400
Eduardo Vega	Fri Aug 28 16:06:23 2020 -0600
Aos Dabbagh	Fri Oct 2 22:17:38 2020 -0400
root	Sat Oct 3 01:59:33 2020 +0000
Ashok Pon Kumar	Fri Oct 2 00:36:58 2020 +0530
Wei Fu	Mon Sep 7 15:04:04 2020 +0800
Shukui Yang	Fri Jul 12 09:54:52 2019 +0800
Daniel J Walsh	Wed Aug 19 06:28:15 2020 -0400
Sascha Grunert	Sun Aug 16 14:28:50 2020 +0200
Xiaodong Liu	Mon Aug 10 10:25:53 2020 +0800
Cesar Talledo	Wed Jul 22 20:57:22 2020 -0700
Jeff Zvier	Sat Jul 25 23:15:07 2020 +0800
John Hwang	Tue Jul 28 12:46:06 2020 -0700
zvier	Mon Jul 20 22:37:36 2020 +0800
Xiaoyu Zhang	Sat Jul 11 16:36:32 2020 +0800
Lokesh Mandvekar	Wed Jul 8 09:20:03 2020 -0400
tjucoder	Sun Jul 5 12:10:47 2020 +0800
Manabu Sugimoto	Thu Jun 25 12:21:38 2020 +0900
Alban Crequy	Mon Jun 22 12:41:06 2020 +0200
Tianjia Zhang	Fri Jun 19 19:14:37 2020 +0800
Renaud Gaubert	Thu May 14 00:56:55 2020 +0000
Katarzyna Kujawa	Mon Jun 15 10:59:56 2020 +0200
Ted Yu	Sat Jun 6 15:10:45 2020 -0700
lifubang	Tue Jun 2 18:55:15 2020 +0800
Tianon Gravi	Tue May 19 09:44:06 2020 -0700
Pradyumna Agrawal	Mon May 11 13:38:14 2020 -0700
Alice Frosi	Fri May 8 07:09:25 2020 +0100
Chris Aniszczyk	Tue Apr 21 13:20:20 2020 -0500
iwankgb	Mon Mar 30 09:43:25 2020 +0200
Tobias Klauser	Fri Apr 3 21:09:43 2020 +0200
Yulia Nedyalkova	Tue Mar 31 15:52:20 2020 +0100
Qiang Huang	Fri Mar 27 11:21:41 2020 +0800
Mario Nitchev	Thu Mar 19 12:52:08 2020 +0200
SiYu Zhao	Tue Mar 17 11:26:46 2020 +0800
Boris Popovschi	Tue Mar 10 15:28:45 2020 +0200
l00397676	Sun Jun 17 20:42:04 2018 +0800
zyu	Mon Mar 9 09:29:03 2020 -0700
Brian Goff	Wed Feb 12 10:23:58 2020 -0800
Andrei Vagin	Sun Feb 9 22:32:56 2020 -0800
wanghuaiqing	Fri Feb 7 13:02:14 2020 +0800
Amye Scavarda Perrin	Fri Dec 20 15:53:32 2019 -0800
Kohei Ota	Sun Jan 26 23:03:13 2020 +0900
Jordan Liggitt	Wed Dec 18 15:20:53 2019 +0000
Julio Montes	Fri Dec 6 15:43:08 2019 +0000
James Peach	Sat Oct 26 08:24:14 2019 +1100
Radostin Stoyanov	Thu Oct 17 07:49:38 2019 +0100
Manuel Rüger	Tue Oct 1 10:04:23 2019 +0200
tianye15	Fri Sep 27 19:26:16 2019 +0800
Julia Nedialkova	Fri Sep 27 17:02:56 2019 +0300
blacktop	Thu Sep 26 11:03:03 2019 -0400
Jonathan Rudenberg	Wed Sep 11 17:02:43 2019 +0000
Carlos de Paula	Mon Aug 26 15:54:48 2019 -0300
Filipe Brandenburger	Thu Aug 22 21:53:24 2019 -0700
sashayakovtseva	Thu Aug 15 17:16:38 2019 +0300
Erik Sipsma	Sun Aug 11 00:27:34 2019 -0700
Andreas Stocker	Mon Jul 29 22:05:31 2019 +0200
Kurnia D Win	Thu Jul 18 05:57:23 2019 +0700
Howard Zhang	Sun Jul 7 19:08:30 2019 -0700
Julien Durillon	Tue Jun 11 13:15:00 2019 +0200
Joe Burianek	Tue May 7 11:28:49 2019 -0500
Georgi Sabev	Tue Apr 23 17:02:31 2019 +0300
Xiao YongBiao	Wed Apr 10 23:24:43 2019 +0800
Marco Vedovati	Fri Aug 10 11:23:30 2018 +0200
Alex Fang	Thu Mar 21 13:24:04 2019 +1100
Lifubang	Sat Mar 16 13:08:24 2019 +0800
Daniel, Dao Quang Minh	Fri Mar 15 10:49:13 2019 +0000
Justin Cormack	Thu Mar 14 10:58:10 2019 +0000
Vincent Batts	Sun Mar 3 15:00:09 2019 -0500
Christian Brauner	Thu Feb 14 15:56:26 2019 +0100
John Howard	Thu Feb 7 14:49:22 2019 -0800
JoeWrightss	Wed Dec 19 20:22:48 2018 +0800
Tom Godkin	Mon Dec 17 15:34:47 2018 +0000
Ace-Tang	Mon Dec 3 13:31:20 2018 +0800
Kevin Kelani	Thu Nov 15 21:37:23 2018 -0800
Lin Yang	Wed Nov 14 15:10:47 2018 -0800
W. Trevor King	Sun Feb 25 14:47:41 2018 -0800
Yuanhong Peng	Mon Nov 14 20:54:17 2016 +0800
Sergio Lopez	Wed Oct 24 17:20:27 2018 +0200
Harald Nordgren	Sat Oct 20 11:54:38 2018 +0200
Dominik Süß	Sat Oct 13 21:14:03 2018 +0200
Mike Brown	Fri Oct 12 09:22:35 2018 -0500
Jonathan Marler	Thu Oct 4 21:30:55 2018 -0600
Yan Zhu	Fri Sep 7 11:37:40 2018 +0800
ChangFeng	Thu Aug 30 21:23:35 2018 +0800
Jay Kamat	Tue Jul 31 19:42:49 2018 -0700
Dmitry Smirnov	Sun Jun 17 19:11:36 2018 +1000
Tibor Vass	Thu Jun 14 17:59:28 2018 +0000
Derek Carr	Tue May 22 23:39:19 2018 -0400
dlorenc	Tue Apr 17 10:42:04 2018 -0700
Bin Chen	Mon Apr 16 22:18:39 2018 +1000
Antonio Murdaca	Thu Apr 12 12:25:06 2018 +0200
Nalin Dahyabhai	Wed Apr 11 13:28:19 2018 -0400
Sebastien Boeuf	Fri Mar 30 09:29:18 2018 -0700
Tamal Saha	Wed Mar 21 20:50:24 2018 -0700
vikaschoudhary16	Wed Mar 7 00:31:41 2018 -0500
Denys Smirnov	Tue Mar 6 23:31:31 2018 +0100
Alex Glikson	Thu Mar 1 16:12:48 2018 -0500
ynirk	Mon Feb 26 11:47:15 2018 +0100
Allen Sun	Sat Feb 24 05:56:38 2018 +0800
vsoch	Wed Feb 21 12:54:14 2018 -0800
Peter Morjan	Wed Feb 21 09:45:28 2018 +0100
ravisantoshgudimetla	Sun Feb 18 20:54:46 2018 -0500
Taeung Song	Fri Feb 2 21:51:57 2018 +0900
Valentin Kulesh	Fri Jan 26 09:48:25 2018 +0300
Ed King	Tue Jan 23 10:46:31 2018 +0000
Will Martin	Mon Jan 22 17:03:02 2018 +0000
Ma Shimiao	Thu Dec 7 15:43:56 2017 +0800
Seth Jennings	Wed Nov 15 14:32:32 2017 -0600
Bin Lu	Mon Nov 6 18:36:56 2017 -0800
Vincent Demeester	Wed Nov 8 16:27:06 2017 +0100
Jianyong Wu	Fri Nov 3 16:42:29 2017 +0800
Lorenzo Fontana	Sat Oct 28 21:46:46 2017 +0200
Thomas Hipp	Thu Oct 26 19:48:52 2017 +0200
Matthew Heon	Mon Oct 16 16:27:40 2017 -0400
Petros Angelatos	Thu May 18 21:54:02 2017 -0700
Sumit Sanghrajka	Mon Feb 6 19:29:40 2017 -0800
Steven Hartland	Tue Jan 24 23:24:05 2017 +0000
Konstantinos Karampogias	Tue Sep 26 15:39:46 2017 +0200
Euan Kemp	Fri Sep 22 02:31:17 2017 -0700
leitwolf7	Thu Sep 21 22:25:58 2017 +0200
s7v7nislands	Fri Sep 22 04:21:02 2017 +0800
Yong Tang	Thu Aug 31 15:31:05 2017 +0000
Tycho Andersen	Thu Aug 24 16:20:19 2017 -0600
Nikolas Sepos	Fri Aug 18 16:19:21 2017 +0200
Kenfe-Mickael Laventure	Wed Aug 9 08:47:57 2017 -0700
yangshukui	Mon Jul 24 11:10:18 2017 +0800
Zhang Wei	Wed Dec 28 15:28:19 2016 +0800
Kang Liang	Fri Jun 9 18:47:05 2017 +0800
Vladimir Stefanovic	Fri Feb 17 23:17:11 2017 +0100
Christy Perez	Mon May 22 17:44:04 2017 -0500
Wentao Zhang	Tue Dec 20 06:21:10 2016 -0500
Valentin Rothberg	Tue May 16 13:45:21 2017 +0200
CuiHaozhi	Thu May 4 06:50:22 2017 -0400
Harshal Patil	Thu May 4 09:03:19 2017 +0530
Jonh Wendell	Thu Apr 27 10:52:31 2017 -0300
Tim Potter	Fri Apr 21 12:41:02 2017 +1000
chchliang	Wed Apr 19 16:28:03 2017 +0800
Craig Furman	Wed Mar 15 10:10:30 2017 +0000
Carlton-Semple	Wed Mar 8 10:25:10 2017 -0500
xuxinkun	Fri Feb 24 17:44:02 2017 +0800
Alexander Morozov	Wed Feb 22 23:02:13 2017 +0000
Máximo Cuadros	Mon Feb 20 13:15:58 2017 +0100
Ian Campbell	Tue Dec 13 16:21:36 2016 +0000
Mohammad Arab	Wed Oct 19 12:15:55 2016 +0200
Carlton Semple	Tue Feb 14 13:27:26 2017 -0500
Deng Guangxing	Wed Aug 24 17:48:56 2016 +0800
rainrambler	Mon Jan 23 14:37:16 2017 +0800
Wang Long	Wed Jan 18 17:18:22 2017 +0800
Lei Jitang	Mon Jan 9 01:56:14 2017 -0500
Xianglin Gao	Wed Jan 4 16:33:42 2017 +0800
Fengtu Wang	Wed Jan 4 16:06:21 2017 +0800
Michal Rostecki	Wed Dec 14 11:20:38 2016 +0100
Samuel Ortiz	Sat Dec 10 02:34:15 2016 +0100
Eric Paris	Tue Dec 6 13:38:07 2016 -0500
yupeng	Wed Nov 30 16:16:58 2016 +0800
Xianlu Bird	Thu Dec 1 15:23:58 2016 +0800
allencloud	Wed Nov 30 13:27:50 2016 +0800
Casey Callendrello	Mon Nov 21 20:20:14 2016 +0100
Daniel Martí	Thu Nov 17 11:51:24 2016 +0000
rajasec	Thu Nov 10 17:06:50 2016 +0530
Crazykev	Wed Nov 2 16:34:08 2016 +0800
Harry Zhang	Mon Oct 31 03:04:51 2016 -0400
Vivek Goyal	Tue Oct 25 11:15:11 2016 -0400
Ce Gao	Sat Oct 22 11:31:15 2016 +0800
Andrew Vagin	Tue Oct 18 23:56:48 2016 +0500
Dan Walsh	Mon Oct 17 16:56:42 2016 -0400
William Martin	Wed Sep 28 10:37:19 2016 +0000
Peng Gao	Tue Sep 27 23:36:57 2016 +0800
derekwaynecarr	Tue Sep 27 16:01:03 2016 -0400
Adam Thomason	Sun Sep 11 16:48:12 2016 -0700
Zhao Lei	Tue Sep 6 16:24:11 2016 +0800
Jiuyue Ma	Mon Sep 5 18:06:03 2016 +0800
Jonathan Boulle	Wed Aug 31 18:43:24 2016 +0200
Tristan Cacqueray	Sat Jun 11 17:46:47 2016 -0400
xiekeyang	Wed Aug 24 11:35:49 2016 +0800
Phil Estes	Sun Aug 21 18:15:18 2016 -0400
Carl Henrik Lunde	Tue Aug 16 22:45:26 2016 +0200
Serge Hallyn	Sun Aug 14 18:32:39 2016 -0500
Davanum Srinivas	Thu Aug 11 15:03:47 2016 -0400
Haiyan Meng	Mon Aug 8 12:26:59 2016 -0400
Buddha Prakash	Fri Jul 22 17:04:37 2016 -0700
Johnny Bieren	Thu Jul 14 12:03:09 2016 -0400
Guilherme Rezende	Sun Jul 24 19:41:57 2016 -0300
Yen-Lin Chen	Fri Jul 15 00:02:40 2016 -0700
Hushan Jia	Fri Jul 8 21:07:50 2016 +0800
Yang Hongyang	Wed Jul 6 09:58:30 2016 -0400
Vishnu kannan	Wed Jul 6 15:23:01 2016 -0700
Ben	Mon Jul 4 12:59:07 2016 +0100
ben	Tue May 31 09:01:04 2016 +0100
Petar Petrov	Fri Jun 10 10:35:13 2016 +0000
Joe Farrell	Fri Jun 3 18:05:34 2016 +0100
Michael Holzheu	Tue May 31 08:56:07 2016 -0400
Bhanu Valasa	Thu May 19 16:30:29 2016 -0400
Jim Berlage	Fri Apr 29 10:40:23 2016 -0500
Bryan Boreham	Fri Apr 29 12:59:58 2016 +0100
Tatsushi Inagaki	Mon Feb 29 17:22:45 2016 +0900
Natanael Copa	Tue Apr 19 10:43:00 2016 +0200
Amit Krishnan	Tue Apr 12 14:41:09 2016 -0700
Ido Yariv	Sat Apr 9 09:57:26 2016 -0400
Alberto Leal	Sun Apr 10 13:09:16 2016 +0000
George Lestaris	Wed Apr 6 16:57:59 2016 +0100
Marcos Lilljedahl	Sun Mar 27 01:53:01 2016 -0300
Matt Hartzler	Fri Mar 25 21:45:00 2016 -0500
Julian Friedman	Fri Mar 25 15:03:30 2016 +0000
Thomas Tanaka	Thu Mar 24 13:14:57 2016 -0700
Anusha Ragunathan	Thu Mar 24 10:40:16 2016 -0700
Tonis Tiigi	Tue Mar 22 15:41:49 2016 -0700
pankit thapar	Tue Mar 22 11:40:55 2016 -0400
Jessica Frazelle	Thu Mar 17 13:28:04 2016 -0700
Thomas LE ROUX	Thu Mar 17 18:23:12 2016 +0100
Rajasekaran	Mon Mar 7 23:06:14 2016 +0530
Andrey Vagin	Thu Mar 10 08:43:09 2016 -0500
Doug Davis	Thu Feb 11 10:42:28 2016 -0800
Ye Yin	Wed Mar 2 18:32:19 2016 +0800
Stefan Berger	Mon Feb 22 15:36:12 2016 -0500
Chun Chen	Tue Feb 16 15:59:27 2016 +0800
Andrew Fernandes	Fri Jan 29 20:37:10 2016 +0000
Marcos Nils	Fri Jan 22 16:44:52 2016 -0300
Alex Dadgar	Wed Jan 13 11:24:59 2016 -0800
Jimmi Dyson	Fri Jan 8 19:37:18 2016 +0000
Ahmet Alp Balkan	Thu Jan 7 23:44:01 2016 +0000
xlgao-zju	Thu Dec 17 10:28:38 2015 +0800
Kai Qiang WU(Kennan)	Wed Dec 30 00:30:53 2015 +0000
Ben Hall	Fri Dec 18 12:18:41 2015 +0100
David Calavera	Tue Dec 15 15:12:29 2015 -0500
Abin Shahab	Sun Oct 11 22:30:41 2015 +0000
Eric Myhre	Wed Oct 21 10:18:32 2015 -0500
Hui Kang	Thu Aug 6 15:14:59 2015 +0000
Bogdan Purcareata	Tue Oct 6 10:41:14 2015 +0000
Sami Wagiaalla	Sun Oct 4 19:02:30 2015 -0400
keloyang	Wed Sep 23 10:48:36 2015 +0800
Lai Jiangshan	Wed Sep 16 10:25:38 2015 +0800
Vishnu Kannan	Wed Aug 26 16:37:24 2015 -0700
Shishir Mahajan	Sat Aug 29 11:50:39 2015 -0400
Mark Sta Ana	Thu Aug 27 08:50:46 2015 +0100
boucher	Fri Aug 21 14:20:59 2015 -0700
Shijiang Wei	Sun Aug 16 12:19:44 2015 +0800
Michael Chase-Salerno	Thu Aug 13 17:52:47 2015 -0500
Fabio Kung	Mon Aug 10 16:22:49 2015 -0700
William Temple	Wed Aug 5 14:09:53 2015 -0400
Jin-Hwan Jeong	Fri Jul 24 11:19:25 2015 +0900
Rohit Jnagal	Mon Jul 20 17:09:11 2015 -0700
Zefan Li	Tue Jul 14 10:28:21 2015 +0800
Jessie Frazelle	Thu Jul 9 11:17:46 2015 -0700
zenlin	Wed Jul 8 19:10:22 2015 +0800
Raghavendra K T	Fri Jul 3 18:19:45 2015 +0530
Kenneth Lim	Mon Jun 29 08:47:00 2015 +0800
Marianna	Mon Jun 29 16:49:13 2015 -0700
Rodrigo	Mon Jun 29 03:08:16 2015 -0400
Blake La Pierre	Sat Jun 27 18:36:11 2015 -0700
mapk0y	Sat Jun 27 18:56:24 2015 +0900
Colin Walters	Fri Jun 26 14:07:00 2015 -0400
Michael Timbrook	Thu Jun 25 13:42:15 2015 -0700
Stephen Day	Wed Jun 24 18:21:26 2015 -0700
Lei Xue	Thu Jun 25 08:04:12 2015 +0800
unclejack	Wed Jun 24 01:55:02 2015 +0300
Jake Teton-Landis	Mon Jun 22 11:09:41 2015 -0700
Benoit Sigoure	Sat Jun 13 22:49:52 2015 -0700
Arnaud Porterie	Thu Jun 11 17:10:25 2015 -0700
Victor Marmol	Wed Jun 10 09:56:56 2015 -0400
Geoff Levand	Tue Jun 9 15:19:47 2015 -0700
Alexey Guskov	Fri Jun 5 14:23:32 2015 +0300
David Thompson	Sun May 31 17:57:07 2015 -0400
jianbosun	Tue May 26 16:39:35 2015 +0800
Saied Kazemi	Wed Mar 18 20:22:21 2015 -0700
Dmitri Shuralyov	Fri May 15 17:03:04 2015 -0700
Eric Windisch	Tue Apr 28 23:51:31 2015 -0400
sayuan	Sat Apr 18 16:42:48 2015 +0800
bin liu	Mon Apr 20 02:35:51 2015 +0000
tifayuki	Tue Apr 14 17:18:31 2015 +0200
Adam Conrad	Fri Apr 10 12:50:45 2015 -0600
Jörg Thalheim	Tue Mar 31 23:40:05 2015 +0200
wonderflow	Thu Apr 2 11:41:51 2015 +0800
Mathieu Lecarme	Wed Apr 1 21:43:45 2015 +0200
Brandon Philips	Tue Mar 24 20:41:17 2015 -0400
Pavel Tikhomirov	Fri Mar 20 15:01:55 2015 +0300
Yuan Sun	Fri Mar 20 07:54:05 2015 +0800
Andy Goldstein	Wed Mar 11 14:30:26 2015 -0400
Paul Morie	Fri Mar 6 13:23:55 2015 -0500
HuKeping	Sat Mar 7 02:30:55 2015 +0800
Mabin	Wed Mar 4 14:56:50 2015 +0800
Alexandr Morozov	Fri Feb 27 15:55:53 2015 -0800
Patrick Hemmer	Tue Jul 1 19:56:00 2014 -0400
guoxiuyan	Mon Jan 26 09:41:22 2015 +0800
Gary Berger	Fri Dec 12 09:18:30 2014 -0500
Ketouem	Fri Dec 12 11:31:47 2014 +0100
Milos Gajdos	Fri Nov 21 15:44:15 2014 +0000
Yohei Ueda	Fri Nov 21 14:18:48 2014 +0000
Donald Huang	Fri Nov 14 23:51:29 2014 +0000
Alexander Holler	Mon Nov 17 14:14:19 2014 +0100
Hans Rødtang	Fri Nov 14 05:49:50 2014 +0100
Albert Zhang	Thu Nov 6 15:58:07 2014 +0800
Luca Favatella	Sat Oct 25 13:15:28 2014 +0100
Harshavardhana	Fri Oct 24 01:19:17 2014 -0700
Alejandro Ojeda	Fri Oct 24 20:04:20 2014 +0200
Dave Tucker	Tue Oct 21 01:59:05 2014 +0100
Ian Main	Tue Oct 14 13:31:23 2014 -0700
Alexander Larsson	Mon Sep 22 18:01:58 2014 +0200
Malte Janduda	Tue Sep 30 00:33:12 2014 +0200
Hugo Duncan	Thu Sep 25 13:04:50 2014 -0400
Lewis Marshall	Thu Sep 18 01:16:37 2014 +0100
Steve Powell	Fri Sep 5 10:08:11 2014 -0700
Glyn Normington	Wed Sep 3 16:03:41 2014 -0700
Erik Hollensbe	Wed Sep 3 19:37:48 2014 -0700
Bernerd Schaefer	Fri Aug 29 16:17:22 2014 +0200
Johannes 'fish' Ziemke	Wed Aug 27 13:42:38 2014 +0200
Vish Kannan	Wed Aug 13 23:26:18 2014 -0700
Nicholas Weaver	Mon Aug 11 14:14:13 2014 -0700
Peter Bourgon	Wed Jul 30 15:20:51 2014 +0200
maebashi	Fri Jul 25 15:22:58 2014 +0900
Dhammika Pathirana	Wed Jul 23 22:19:26 2014 -0700
Tim Hockin	Tue Jul 15 00:50:54 2014 +0000
Victor Vieux	Fri Jul 11 00:23:05 2014 +0000
Lee Treveil	Tue Jul 8 23:32:46 2014 +0100
Timothy Hobbs	Thu Jun 12 16:07:31 2014 +0000
LK4D4	Thu Jun 12 09:52:31 2014 +0400
Solomon Hykes	Fri May 16 17:14:04 2014 -0700
William Thurston	Sat May 17 07:06:29 2014 +0000
Sridhar Ratnakumar	Thu May 15 21:36:15 2014 -0700
Guillaume J. Charmes	Tue May 13 11:59:27 2014 -0700
Jérôme Petazzoni	Wed Apr 30 18:00:42 2014 -0700
Eiichi Tsukata	Wed Apr 30 15:20:22 2014 +0900
Kato Kazuyoshi	Thu Apr 10 22:07:29 2014 +0900
Dan Stine	Mon Apr 7 22:09:15 2014 -0400
Michael Brown	Mon Apr 7 03:04:27 2014 -0400
Johan Euphrosine	Tue Mar 18 16:25:26 2014 -0700
srid	Mon Mar 10 16:50:29 2014 -0700
Sven Dowideit	Thu Feb 27 23:36:19 2014 -0800

**Comment by fuweid** [comment]
link comment here https://github.com/opencontainers/tob/issues/95#issuecomment-819192876 :)

**Comment by kolyshkin** [comment]
@fuweid we'd love to have more maintainers for sure -- I guess the first (second?) step for you is to be more active here -- review PRs, try to fix opened issues etc.

**Comment by fuweid** [comment]
@kolyshkin Yes! For sure. I will follow the common step to be more active in the repo :p

**Comment by metux** [comment]
How exactly is the term "maintainer" defined here ?

**Comment by cyphar** [comment]
> How exactly is the term "maintainer" defined here ?

Someone listed in the [`MAINTAINERS` file](https://github.com/opencontainers/runc/blob/master/MAINTAINERS) (which means you have the ability to merge and review PRs, manage the issue tracker, etc.)

**Comment by kolyshkin** [comment]
Perhaps the best way to do the active maintainers audit is to review maintainers activity in this repo, find out who was not active for a long period (say 1-2 years), and propose to move those people from MAINTAINERS to EMERITUS. The "activity" here is anything related to this repo -- PRs, reviews, issues etc.

Problem is, I don't know an easy way to overview the activity of a user in a repo. Maybe I'm missing something.

**Comment by kolyshkin** [comment]
I found one particular way to get the data -- github contributors graph can be limited by a date range. For example, here's the runc data for the last 3 years (2018-08-01 to 2021-08-01):

https://github.com/opencontainers/runc/graphs/contributors?from=2018-08-01&to=2021-08-01&type=c

The only problem is the above graph does not show the full picture, as it does not account for anything other than code changed in the master branch. For example, PR reviews and issues filed may still be a valuable contribution from a maintainer.

**Comment by cyphar** [comment]
I think it's clear we have a fairly healthy set of maintainers involved with this project, and we just added @thaJeztah recently. I reckon it's okay to close this for now.
