### ISSUE TITLE
terminal is broken on s390 (regression in rc93)

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#2896]
Initially reported in https://bugzilla.redhat.com/show_bug.cgi?id=1941815. On s390, runc run/exec can't open a terminal:

> ERRO[0000] exec failed: container_linux.go:367: starting container process caused: open /dev/pts/4294967296: no such file or directory 

This is a regression which has previously reported (https://github.com/moby/moby/issues/36467) and fixed (https://github.com/containerd/console/pull/20, https://github.com/opencontainers/runc/pull/1727).

Unfortunately, it has resurfaced. I think https://github.com/containerd/console/pull/42 and #2616 are the ones to blame, so this is a regression in rc93.

Fix for containerd/console is here: https://github.com/containerd/console/pull/51. Once in, we need to revendor it.

**Comment by Prashanth684** [comment]
with https://github.com/containerd/console/pull/51 being fixed, i guess we can revendor now?
