### ISSUE TITLE
runc returns with exit code 0 when poststop hook fails

### ISSUE THREAD

**Issue by jschwinger23** [opencontainers/runc#2905]
# 1. Reproduce Steps

### 1.1 create the container template

```
mkdir -p mycontainer/rootfs
cd mycontainer
docker export $(docker create busybox) | tar -C rootfs -xvf -
runc spec
```
### 1.2 add poststop hooks

change the command to `sleep` and disable the tty:

```
{
...
        "terminal": false,
        "args": [
            "sleep", "10000000"
        ],
...
}
```

add poststop hook which will 100% fail:

```
{
...
    "hooks": {
        "poststop": [
            {
                "path": "/bin/bash",
                "args": [
                    "bash",
                    "-c",
                    "ip net d 998e09fdf134"
                ]
            }
        ]
    },
...
}
```

### 1.3 run the container then stop && delete it

```
runc run -d mycontainerid
runc kill mycontainerid 9
runc delete mycontainerd
```

the last command will give back the errors but the exit code is still 0:

```
mycontainer$ s runc delete mycontainerid
ERRO[0000] Running hook #0:: error running hook: exit status 1, stdout: , stderr: Cannot remove namespace file "/run/netns/998e09fdf134": No such file or directory 
mycontainer $ echo $?
0
```

# 2. Expected behavior

My understanding is there is no specification regarding this situation: https://github.com/opencontainers/runtime-spec/blob/master/config.md#posix-platform-hooks

But it still gives me a feeling that it's the right behavior to return non-zero exit code when `poststop` hooks fail, isn't it?

**Comment by AkihiroSuda** [comment]
>  If any poststop hook fails, the runtime MUST log a warning, but the remaining hooks and lifecycle continue as if the hook had succeeded.

https://github.com/opencontainers/runtime-spec/blob/v1.0.2/runtime.md#lifecycle

So, this is excepted by design
