### ISSUE TITLE
runc@master failing with Moby CI: TestTemplatedConfig: Options:[rbind ro]}: mount destination templated_config not absolute: unknown

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2928]
```
--- FAIL: TestTemplatedConfig (61.70s)

[2021-05-01T17:09:25.901Z]     config_test.go:307: timeout hit after 1m0s: waiting for tasks to enter run state. task failed with error: starting container failed: failed to create shim: OCI runtime create failed: invalid mount {Destination:templated_config Type:bind Source:/go/src/github.com/docker/docker/bundles/test-integration/TestTemplatedConfig/d1fa52d447d48/root/containers/301097d0bae895342d137fd9217923474fddc25e6f06af4e3c3bd5a17cb5283c/mounts/secrets/l447q2mi60ayqntjg5bajt1hd Options:[rbind ro]}: mount destination templated_config not absolute: unknown
```

https://github.com/moby/moby/pull/42308
(moby/moby@59751bb23395a137253ca0b4fb99058ecec5a569 , runc @ d279ebd97d8832020e2c6f50cc3a11d0499a4690)

Regression in https://github.com/opencontainers/runc/pull/2917/commits/2192670a2430054c1e539ca7a3bf0ddc43b0bc3d  ( #2917 )
```
libct/configs/validate: validate mounts
    
Add a check that mount destination is absolute (as per OCI spec).
```

OCI spec: https://github.com/opencontainers/runtime-spec/blob/master/config.md#mounts

**Comment by AkihiroSuda** [comment]
- Option 1: revert #2917 and violate OCI spec
- Option 2: revert #2917, and modify OCI spec to allow slash-less relative path
- Option 3: modify Moby to avoid using relative paths

Option 3 is the most ideal, but may face compatibility issues.

cc @thaJeztah @tiborvass

**Comment by cyphar** [comment]
Yeah I agree option 3 is the best solution.

**Comment by AkihiroSuda** [comment]
Let's close this and proceed the release process.

**Comment by thaJeztah** [comment]
Generally, option 3 sounds good to me (actually surprised that this worked).

If we fix this in Moby/Docker, the only concern would be for existing versions of docker that would upgrade to a newer version of RunC.

Having a quick look, and it looks like regular bind-mounts already produce an error (on docker 20.10, runc rc93);

```bash
$ docker run -it --rm -w /app -v $(pwd):somewhere alpine sh
docker: Error response from daemon: invalid volume specification: '/host_mnt/Users/sebastiaan/go/src/github.com/docker/docker.github.io:somewhere': invalid mount config for type "bind": invalid mount path: 'somewhere' mount path must be absolute.
See 'docker run --help'.

$ docker run -it --rm -w /app --mount type=bind,src=$(pwd),target=somewhere alpine sh
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'somewhere' mount path must be absolute.
See 'docker run --help'.
```

I _think_ this would only affect swarm configs; for swarm _secrets_, the `/run/secrets/` path is prepended, but for configs, there is no default path (assumes `/`);


```bash
$ echo 'bla' | docker config create bla -
$ echo 'bla' | docker secret create bla -
$ docker service create \
   --name myservice \
   --config src=bla,target=configblatarget \
   --secret src=bla,target=secretblatarget \
   nginx:alpine
```

Above doesn't produce an error, and the config is mounted at `/configblatarget`, and the secret at `/run/secret/secretblatarget`

I think it's a bug, and it should either produce an error, or convert the path to be absolute (relative to `/` for configs)

**Comment by cpuguy83** [comment]
Reminder that moby is not the only project that uses runc.

**Comment by cpuguy83** [comment]
Basically, a configuration that worked before no longer works.
We should also test cri-containerd and cri-o.

**Comment by AkihiroSuda** [comment]
Cri-containerd is passing the tests with runc master https://github.com/containerd/containerd/pull/5442

**Comment by cpuguy83** [comment]
Right but are the tests testing this case?

**Comment by cpuguy83** [comment]
Applying through the normal flow seems to be ok in cri-containerd at least (it prepends a `/`).

**Comment by kolyshkin** [comment]
AFACS fixing in it higher-level software is straightforward (make the paths absolute).

At least some of cri-o tests are run against HEAD runc and we did not see failures (surely there might be no such test case)
