### ISSUE TITLE
CI seems skipping `cgroupv2 with rootless (systemd)`

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2942]
![image](https://user-images.githubusercontent.com/9248427/117261107-bb897600-ae8a-11eb-8093-52b1b5312fa8.png)
https://github.com/opencontainers/runc/runs/2512206353
https://github.com/opencontainers/runc/blob/2d38476c96e3407eba876e77b301880c6d7e5ccc/tests/integration/helpers.bash#L374

Most tests in `cgroupv2 with rootless (systemd)` seem skipped.

This is not a recent regression. The log from February has the same `skip` output. https://github.com/opencontainers/runc/runs/1867231647?check_suite_focus=true

**Comment by AkihiroSuda** [comment]
cc @kolyshkin

**Comment by kolyshkin** [comment]
Good catch, working on a fix

**Comment by kolyshkin** [comment]
Hmm, we're not in a very bad shape, the previously skipped tests only found 1 bug. PTAL https://github.com/opencontainers/runc/pull/2944.

**Comment by AkihiroSuda** [comment]
Thanks for fixing! 👍
