### ISSUE TITLE
Unable to run nvidia-container-toolkit with rootless runc

### ISSUE THREAD

**Issue by animesh-bhadouria** [opencontainers/runc#2952]
#### Description
Unable to run nvidia-container-toolkit with runC in rootless mode, the same configuration works as a root user. 
Container root user is a non-root user in HostOS and is added to the GPU group.
Trying to understand if its possible to run nvidia-container-toolkit in rootless mode and if so, then what configuration changes are required?

Kernel: Linux tegra-ubuntu 4.9.140 aarch64 aarch64 aarch64 GNU/Linux

runc version spec: 1.0.1-dev
nvidia-docker2_2.2.0
libnvidia-container0_0.9.0_beta
nvidia-container-runtime_3.1.0
nvidia-container-toolkit_1.0.1
libnvidia-container-tools_0.9.0_beta

#### Error Log
`WARN[0000] signal: killed`
`ERRO[0000] container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/dev/stderr configure --ldconfig=@/sbin/ldconfig.real --no-cgroups --device=all --utility --pid=19412 /data/container/test]\\\\nnvidia-container-cli: permission error: capability change failed: operation not permitted\\\\n\\\"\""`

`container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/dev/stderr configure --ldconfig=@/sbin/ldconfig.real --no-cgroups --device=all --utility --pid=19412 /data/container/test]\\\\nnvidia-container-cli: permission error: capability change failed: operation not permitted\\\\n\\\"\"" `

#### Steps to reproduce the issue
1. Install the nvidia toolkit, configure it to run with runC
2. Add GPU group from `/etc/group` as an additional gid.
3. Add the hook to config.
```     
"hooks": {
     "prestart": [
      {
        "path": "/usr/bin/nvidia-container-runtime-hook",
        "args": [
          "/usr/bin/nvidia-container-runtime-hook",
          "-debug",
	  "prestart"
        ]
      }
    ]
    },
```
4. Start a container using runC in rootless mode. 
`runc run test`

#### Additional Steps
Based on some suggestions on different threads, I have also tried setting "no-cgroups = true" in  in /etc/nvidia-container-runtime/config.toml but didn't fix the issue.
```
cat /etc/nvidia-container-runtime/config.toml
disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
#root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
debug = "/var/log/nvidia-container-toolkit.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false
no-cgroups = true
#user = "root:video"
ldconfig = "@/sbin/ldconfig.real"

[nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
debug = "/tmp/nvidia-container-runtime.log"
```

**Comment by metux** [comment]
It also wants to do other root-only things like loading kernel modules, creating device nodes, etc.
This thing is heavily tied to NVidia's broken-by-design binary-only drivers that compromise security.
Don't use it in production.
