### ISSUE TITLE
Capture number of IO operations performed with cgroup v2 hierarchy

### ISSUE THREAD

**Issue by iyashu** [opencontainers/runc#2967]
In cgroup v1, [GetStats](https://github.com/opencontainers/runc/blob/e005fee9d37f3ee35cfc6d4cfee687043656928f/libcontainer/cgroups/cgroups.go#L23) api captures the number of IO operations performed under `IoServicedRecursive` field of [BlkioStats](https://github.com/opencontainers/runc/blob/e005fee9d37f3ee35cfc6d4cfee687043656928f/libcontainer/cgroups/stats.go#L128-L138) struct. But the same stat is missing with cgroup v2 implementation. As you can see [here](https://github.com/opencontainers/runc/blob/e005fee9d37f3ee35cfc6d4cfee687043656928f/libcontainer/cgroups/fs2/io.go#L140), we never populate the `IoServicedRecursive` field for cgroup v2. This resulted in misleading zero valued metrics in kubelet and cadvisor for cgroup v2. As per the [cgroup v2 documentation](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#io-interface-files), io.stat file has `rios` and `wios` fields denoting the number of read and write operations performed on a device. Let me know if I can add these stats for cgroup v2 as well?

Original cAdvisor Issue - https://github.com/google/cadvisor/issues/2881

**Comment by iyashu** [comment]
cc/ @dims @mrunalp @AkihiroSuda

**Comment by dims** [comment]
@iyashu +1 to ensure the v2 impl faithfully reflects what we get in cgroup v1 impl.

**Comment by cyphar** [comment]
I will write a PR for this. Hopefully this will be the last thing PR for 1.0.0 (I was just getting ready to do the release).
