### ISSUE TITLE
[question] Is it compatible with the old version?

### ISSUE THREAD

**Issue by zhangguanzhang** [opencontainers/runc#2972]
Is it compatible with the old version, mainly using the new version of runc to replace the runc binary file in the old version of docker(such as `19.03.14`)

**Comment by cyphar** [comment]
In general, new releases of runc are compatible with old ones -- though it should be noted that if you use a different version of runc than the docker release was tested with, your configuration isn't as well-tested as the released configuration (in practice there haven't been significant issues for a few years, but it has happened in the past).

**Comment by zhangguanzhang** [comment]
thanks
