### ISSUE TITLE
"failed to call BPF_PROG_ATTACH (BPF_CGROUP_DEVICE, BPF_F_ALLOW_MULTI): can't attach program: invalid argument: unknown" (master, kernel 5.4, cgroup2)

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#3008]
`docker run` does not work at all with runc 4d6b9297 , cgroup v2, and kernel 5.4, due to the `failed to call BPF_PROG_ATTACH (BPF_CGROUP_DEVICE, BPF_F_ALLOW_MULTI): can't attach program: invalid argument: unknown.` error.

```console
$ docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to call BPF_PROG_ATTACH (BPF_CGROUP_DEVICE, BPF_F_ALLOW_MULTI): can't attach program: invalid argument: unknown.
ERRO[0000] error waiting for container: context canceled 
```

```console
$ docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95+dev
  GitCommit:        v1.0.0-rc95-89-g4d6b9297
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```console
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: v1.0.0-rc95-89-g4d6b9297
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.4.0-74-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.941GiB
 Name: ubuntu-focal
 ID: IXOP:CWWS:M7ET:LOFO:QI2Q:7KE6:BEMB:3SYU:WFTP:GHJF:RUID:YA53
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Found in https://github.com/moby/moby/pull/42450 , discussed in https://github.com/opencontainers/runc/pull/2986

**Comment by AkihiroSuda** [comment]
Probably `haveBpfProgReplace()` is not robust enough.
It should consistently return false for [kernel < 5.6](https://github.com/torvalds/linux/commit/7dd68b3279f1792103d12e69933db3128c6d416e).

**Comment by cyphar** [comment]
Yeah that explains it. I went through the source to figure out how they handle `BPF_F_REPLACE` not being supported, but somehow I missed that. We might need to use the syscall directly.

**Comment by cyphar** [comment]
Turns out they used `%w` for most errors, they just missed a handful. I've sent a PR to fix that on their side.

**Comment by chenhengqi** [comment]
@AkihiroSuda  I still have this issue on kernel 5.4 + cgroup v2.

```shell
$ ctr run --rm --gpus 0 -t docker.io/nvidia/cuda:11.0-base cuda-11.0-base nvidia-smi
ctr: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: failed to add device rules: unable to replace original device filters program with new one: failed to call BPF_PROG_ATTACH (BPF_CGROUP_DEVICE, BPF_F_ALLOW_MULTI): can't attach program: invalid argument: unknown
```
```shell
$ runc --version
runc version 1.0.3
commit: v1.0.3-0-gf46b6ba2c931
spec: 1.0.2-dev
go: go1.17.3
libseccomp: 2.5.1
```

**Comment by jmason** [comment]
This issue has just bit me on a system with a 5.4 kernel, using the released version of runc 1.2.2:

```
docker run hello-world
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to call BPF_PROG_ATTACH (BPF_CGROUP_DEVICE, BPF_F_ALLOW_MULTI): attach program: invalid argument: unknown.

sudo dpkg-query --listfiles containerd.io | grep runc
/usr/bin/containerd-shim-runc-v1
/usr/bin/containerd-shim-runc-v2
/usr/bin/runc

dpkg-query --show containerd.io
containerd.io   1.7.24-1

zless /usr/share/doc/containerd.io/changelog.Debian.gz

containerd.io (1.7.24-1) release; urgency=medium

  * Update containerd binary to v1.7.24
  * Update systemd unit to start containerd service after dbus.service
  * Update runc binary to v1.2.2

 -- Sebastiaan van Stijn <thajeztah@docker.com>  Thu, 21 Nov 2024 16:37:21 +0000
```

**Comment by cyphar** [comment]
It seems that `github.com/cilium/ebf` have effectively removed cilium/ebpf#320 and now return a different error in that case (`ErrNotSupported`). It seems we missed this in #4397.

**Comment by cyphar** [comment]
Okay, it seems that in #4397 the update to use Anchors (cilium/ebpf@417f8a264d2e691649ede9b995fb334e6c58ca71) didn't update the usage in `haveBpfProgReplace` and so we have been getting a different error (because we've been passing an invalid flag) but that was masked by how we checked the error value.

**Comment by kolyshkin** [comment]
@jmason what distro are you using? Asking because we don't hit this issue in CI.

It seems that the only possible way to have that is Ubuntu 20.04 LTS with
 - switched to cgroup v2 explicitly;
 - the kernel not being upgraded to the HWE one (5.15).

**Comment by jmason** [comment]
@kolyshkin it's an Ubuntu 22.04 LTS running on an Odroid SBC, using their vendor kernel (which is still 5.4.275-434), unfortunately.

**Comment by mtardy** [comment]
Hey I also bumped into this bug under 5.4 and 4.19 when using runc `v1.2.2`. Fortunately it seems that https://github.com/opencontainers/runc/pull/4551 and thus the `v1.2.3` [release](https://github.com/opencontainers/runc/releases/tag/v1.2.3) fixes it. Do you know when we can expect a new `containerd.io` Debian package? I'm using `bullseye/stable amd64` for my images and it's still shipping `v1.2.2` with:

```
$ apt show containerd.io
Package: containerd.io
Version: 1.7.24-1
Priority: optional
Section: devel
Maintainer: Containerd team <help@containerd.io>
Installed-Size: 121 MB
Provides: containerd, runc
Depends: libc6 (>= 2.14), libseccomp2 (>= 2.5.0)
Conflicts: containerd, runc
Replaces: containerd, runc
Homepage: https://containerd.io
Download-Size: 29.5 MB
APT-Manual-Installed: yes
APT-Sources: https://download.docker.com/linux/debian bullseye/stable amd64 Packages
Description: An open and reliable container runtime
```

Any chance we can get a new `containerd.io` package with runc `v1.2.3` inside?

**Comment by thaJeztah** [comment]
The containerd.io package at download.docker.com is not maintained by the runc project itself, but by Docker; containerd updated the version for the 1.7 releases in https://github.com/containerd/containerd/pull/11143, but it's not been included in a containerd release yet (which is usually when new packages will be built).

It looks like there's some patches pending to be released in that release branch, but not sure if there's a date set for it already (cc @dmcgowan) https://github.com/containerd/containerd/compare/v1.7.24...release/1.7

Some other patches have not been back ported yet, but not sure if there's any important ones in that list; https://github.com/containerd/containerd/pulls?q=is%3Apr+label%3Acherry-pick%2F1.7.x+is%3Aclosed
