### ISSUE TITLE
v1.x.x: enforce absolute paths for mounts again

### ISSUE THREAD

**Issue by thaJeztah** [opencontainers/runc#3020]
Commits 1f1e91b1a09b5b22eb414ba7e5ad8c3534526216 and 2192670a2430054c1e539ca7a3bf0ddc43b0bc3d (https://github.com/opencontainers/runc/pull/2917) added validation for mountpoints to be an absolute path, to match the OCI specs.

Unfortunately, the old behavior (accepting the path to be a relative path) has been around for a long time, and although "not according to the spec", various higher level runtimes rely on this behavior.

While higher level runtime have been updated to address this requirement, there will be a transition period before all runtimes are updated to carry these fixes.

PR https://github.com/opencontainers/runc/pull/3004 was merged to relax the validation, to generate a WARNING instead of failing, allowing runtimes to update (but allowing them to update runc to the current version, which includes security fixes).

We can remove this exception in a future patch release.

**Comment by kolyshkin** [comment]
I think this is implemented in https://github.com/opencontainers/runc/pull/3717

**Comment by lifubang** [comment]
According to #3971, reopen this one.

**Comment by lifubang** [comment]
!!! Anyone who wants to work on this in the future, please communicate with upsteam projects' maintainer first to check whethere it is safe or not. Thanks.

**Comment by rata** [comment]
I think we can close this issue. We decided to change the spec to allow them (mark them as deprecated): https://github.com/opencontainers/runtime-spec/pull/1225 . We relaxed it here in runc: https://github.com/opencontainers/runc/pull/4013

I've just opened a PR to remove an old comment related to this, but this should be done now, IMHO (https://github.com/opencontainers/runc/pull/4104).

**Comment by thaJeztah** [comment]
I agree, I think it's fine to close this one.


I'm still contemplating if having a `strict-mode` option would be possible somehow; such an option would potentially allow consumers to validate if no deprecated / not-recommended options are used.

That's a bit of a separate topic though, and probably better left for a separate discussion.


I'll go ahead and close this one for now 👍
