### ISSUE TITLE
open release-1.0 branch

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#3034]
It is practically impossible to bring new features and/or perform major refactoring without a possibility to introduce new bugs.

Thus I propose to have a `release-1.0` branch to backport bug fixes to and cut `1.0.z` patch releases from.

**Comment by kolyshkin** [comment]
I think PRs to release branches is the best option -- going through the same review process etc.

**Comment by cyphar** [comment]
Fair enough. I've opened the `release-1.0` branch so closing this.
