### ISSUE TITLE
[ARM64] `runc run` fails with `process_linux.go:722: waiting for init preliminary setup caused: unexpected 123 != 0`

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#3037]
```console
# mkdir rootfs
# curl -fsSL https://dl-cdn.alpinelinux.org/alpine/v3.14/releases/aarch64/alpine-minirootfs-3.14.0-aarch64.tar.gz | tar Cxz ./rootfs
# runc spec
# runc run foo
ERRO[0000] container_linux.go:380: starting container process caused: process_linux.go:722: waiting for init preliminary setup caused: unexpected 123 != 0
# runc --debug run foo
DEBU[0000]github.com/opencontainers/runc/libcontainer/logs/logs.go:69 github.com/opencontainers/runc/libcontainer/logs.processEntry() child process in init()                      
ERRO[0000]github.com/opencontainers/runc/utils.go:57 main.fatal() container_linux.go:380: starting container process caused: process_linux.go:722: waiting for init preliminary setup caused: unexpected 123 != 0 
DEBU[0000]github.com/opencontainers/runc/utils.go:59 main.fatal() container_linux.go:380: starting container process caused: process_linux.go:722: waiting for init preliminary setup caused: unexpected 123 != 0 
```

runc version:
```console
# runc --version
runc version 1.0.0
commit: v1.0.0-0-g84113eef
spec: 1.0.2-dev
go: go1.16.5
```

The runc binary is included in https://github.com/containerd/nerdctl/releases/download/v0.9.0/nerdctl-full-0.9.0-linux-arm64.tar.gz (https://github.com/containerd/nerdctl/blob/v0.9.0/Dockerfile#L43-L55)

Host OS: Ubuntu 21.04 on EC2 a1.large (`Linux ip-XXX-XXX-XXX-XXX 5.11.0-1011-aws #11-Ubuntu SMP Thu Jun 17 01:38:32 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`)

- - -
Originally reported by @idrissneumann (https://github.com/AkihiroSuda/lima/issues/79)

**Comment by AkihiroSuda** [comment]
`CGO_ENABLED=1` seems to solve the issue. We need more human-friendly error messages, though.

**Comment by tianon** [comment]
FWIW, I ran into a similar issue recently with the same exact root cause, and the 123 is `{`.

If you adjust https://github.com/opencontainers/runc/blob/1079288bef1261a22b74d49fdbfa5d380cab901b/libcontainer/process_linux.go#L710 to read more than just one byte and print the entire array as a string, it's a generic JSON error bubbling up from the container initialization code (which seeing in hindsight is what made me realize that `runc` without `cgo` can't possibly start containers properly :facepalm: :sweat_smile:).

**Comment by YanzhaoLi** [comment]
Hi, @AkihiroSuda, I ran into this issue on `kubernetes 1.22 + containerd 1.5.5`. Do you know how to add `CGO_ENABLED=1` in this case?
