### ISSUE TITLE
remove pkg/errors from vendor

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#3039]
In runc:
 * [x] PR #3011 (merged)

In vendored packages:
 * [x] https://github.com/cyphar/filepath-securejoin/pull/7
 * * [x] and https://github.com/cyphar/filepath-securejoin/issues/8
 * * [x] and https://github.com/opencontainers/runc/pull/3063
 * [x] https://github.com/containerd/console/pull/54
 * * [x] and https://github.com/containerd/console/issues/56
 * * [x] and https://github.com/opencontainers/runc/pull/3152
 * [x] https://github.com/opencontainers/selinux/pull/148
 * * [x] and cut a release https://github.com/opencontainers/selinux/releases/tag/v1.8.3
 * * [x] and https://github.com/opencontainers/runc/pull/3125

Once these three are merged and releases are tagged, we can remove pkg/errors from vendor as well.

**Comment by AkihiroSuda** [comment]
Is there an automation tool for migrating from pkg/errors to %w ?

**Comment by kolyshkin** [comment]
> Is there an automation tool for migrating from pkg/errors to %w ?

I am not aware of such a tool. I did it manually in the PRs referenced above (so it's basically done, the issue is mostly for tracking purposes).

**Comment by danishprakash** [comment]
for posterity: there's also the possibility of writing a dirty program which parses the source and makes the relevant changes using an AST.

ref: https://xdg.me/rewriting-go-with-ast-transformation/

**Comment by kolyshkin** [comment]
With https://github.com/opencontainers/runc/pull/3152 merged, this issue is finally fixed. Hooray!

**Comment by kolyshkin** [comment]
Whoops, I was writing a comment to close this one, and while I was doing it, the "close with comment" button became "reopen" 😃
