### ISSUE TITLE
Drop Go 1.13 support

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#3098]
Docker/Moby v20.10.8 will bump up Go requirement from 1.13 to 1.16: https://github.com/moby/moby/pull/42643

So we can safely drop support for Go 1.13.

https://github.com/opencontainers/runc/pull/2925

**Comment by thaJeztah** [comment]
👍 Note that containerd 1.4.x (which includes runc v1.0.0) is still on Go 1.15, so don't drop support for 1.15 yet

**Comment by kolyshkin** [comment]
> Note that containerd 1.4.x (which includes runc v1.0.0) is still on Go 1.15, so don't drop support for 1.15 yet

Go 1.15 is still supported (at least until go 1.17 is released) so it does not make sense to drop it yet.
