### ISSUE TITLE
specifying a spec file on cmd line?

### ISSUE THREAD

**Issue by duglin** [opencontainers/runc#310]
Per the OCF spec, the config file must be named `config.json` so its a bit odd that we allow people to specify a different name on the runc command line. I'm not sure a reference implementation should allow for deviations from the spec like this. I think it might make more sense to allow for the user to pass in the location of the bundle dir, in which are the config files and rootfs dirs though.

I'd be happy to open a PR for these but I wanted to see what people thought first.

**Comment by wking** [comment]
On Fri, Oct 02, 2015 at 08:47:35AM -0700, Doug Davis wrote:
> I'd be happy to open a PR for these but I wanted to see what people
> thought first.

Previous discussion in #202, and the /dev/fd/# approach [1] should
still work (although stdin is no longer enough by itself).  See also
#242, esp. [2,3].  And folks are still playing with the code (#270).

Personally, I'm in favor of allowing that flexibility for
runtime-callers, but bundle authors shouldn't rely on that
functionality.

[1]: https://github.com/opencontainers/runc/issues/202#issuecomment-136549629
[2]: https://github.com/opencontainers/runc/pull/242#issuecomment-139383519
[3]: https://github.com/opencontainers/runc/pull/242#issuecomment-139386227

**Comment by duglin** [comment]
The problem with allowing other variants in runc is that you are headed down the path of standardizing an extension and unless runc takes the "other" config.json (either from a different file or from stdin) and generates a config.json in the bundle dir, I think its fair to say that its running a non-compliant bundle and doing something in violation of the spec.

Or, put it another way, I think 'runc' as a reference implementation should enforce each "MUST" we see in the spec, and right now we say there MUST be a config.json and runconfig.json in the root of the bundle dir - how it gets there could be up an impl detail of runc, but in the end if the spec says it MUST be there, then runc needs to follow that rule.

**Comment by mrunalp** [comment]
I think it makes sense for runc to take a path to the bundle directory. @LK4D4 @crosbymichael WDYT?

**Comment by crosbymichael** [comment]
Path to bundle seems ok to me.  We would problem just chdir into it anyways so it's the same

**Comment by mikebrow** [comment]
#dibs

**Comment by mikebrow** [comment]
#close this issue pls...
