### ISSUE TITLE
How to set runc log path

### ISSUE THREAD

**Issue by shenshouer** [opencontainers/runc#3108]
Anyone who known how to set runc log path ?

**Comment by kailun-qin** [comment]
Hi @shenshouer, please kindly take a look at the runc cmdline options `--log` which sets the log file path and see if this is what you expect.

**Comment by shenshouer** [comment]
Yes, the flag can change log path of the runc.  Is there any way to change stdout log path  of container which run by runc ?

**Comment by kolyshkin** [comment]
@shenshouer This mostly depends on whether the app you run in container needs a terminal. Please see https://github.com/opencontainers/runc/blob/master/docs/terminals.md.
