### ISSUE TITLE
Installation failure on Slackware64 14.2 with sbopkg

### ISSUE THREAD

**Issue by John-Polo** [opencontainers/runc#3123]
Hi,
I tried an install via sbopkg. The requirements in Slackbuilds say: google-go-lang and libseccomp. They both were installed. I looked through the log and this seems like relevant information? 

`
...
Saving to: 'runc-1.0.0-rc92.tar.gz'

^Mrunc-1.0.0-rc92.tar     [<=>                 ]       0  --.-KB/s              
^Mrunc-1.0.0-rc92.tar     [ <=>                ] 443.74K  2.14MB/s               
^Mrunc-1.0.0-rc92.tar     [  <=>               ]   1.35M  3.36MB/s               
^Mrunc-1.0.0-rc92.tar     [   <=>              ]   1.97M  3.54MB/s    in 0.6s    

2021-08-01 14:29:49 (3.54 MB/s) - 'runc-1.0.0-rc92.tar.gz' saved [2061469]

Found runc-1.0.0-rc92.tar.gz in /var/cache/sbopkg.
Checking MD5SUM:
  MD5SUM check for runc-1.0.0-rc92.tar.gz ... OK
Building package for runc...

...
[many lines later]
go build "-mod=vendor" "-buildmode=pie"  -tags "seccomp" -ldflags "-X main.gitCo
mmit=ff819c7e9184c13b7c2607fe6c30ae19403a7aff -X main.version=1.0.0-rc92 " -o ru
nc .
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]

...
Makefile:32: recipe for target 'runc' failed
make: *** [runc] Error 2
`
Here is some info about my system:
`
Linux computer 4.4.276 #1 SMP Tue Jul 20 23:23:58 CDT 2021 x86_64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz GenuineIntel GNU/Linux
`
Please let me know if you need more information. 

Cheers,
John

**Comment by kolyshkin** [comment]
It seems that you're using
1. somewhat old version of runc (released a year ago) -- the latest version is 1.0.1;
2. very old version of go (looks like earlier than 1.11, which was released 3 years ago) -- the latest version is 1.16.x;

While 1 is not a problem per se, 2 is what results in compilation errors.

Finally, the errors like this should be reported to a distro vendor.

**Comment by John-Polo** [comment]
Okay, thanks.
