### ISSUE TITLE
Dependabot looks to be running on forks as well

### ISSUE THREAD

**Issue by thaJeztah** [opencontainers/runc#3127]
relates to https://github.com/opencontainers/runc/issues/2536 / https://github.com/opencontainers/runc/pull/2978

LOL, just noticed this; https://github.com/thaJeztah/runc/pulls

<img width="885" alt="Screenshot 2021-08-03 at 15 23 22" src="https://user-images.githubusercontent.com/1804568/128022893-fca7e5c3-9955-4474-a868-903cef018a59.png">

Looks like Depandabot may be a bit enthusiastic, and looks to be opening PRs against all(?) forks? Not sure if others see this as well. Hm... apparently they do; https://github.com/kolyshkin/runc/pulls?q=is%3Apr+is%3Aclosed 😂 

/cc @kolyshkin

**Comment by AkihiroSuda** [comment]
> PRs against all(?) forks?

Not for me 🤔 

https://github.com/AkihiroSuda/runc/pulls

**Comment by thaJeztah** [comment]
That's odd. Oh! Could it be because you don't keep your master branch in sync, so it doesn't have a gha files?

![49DDB707-606F-4B6F-9C09-CCE430E885F7](https://user-images.githubusercontent.com/1804568/128103615-255f2666-5612-4fb9-8899-dbe5ba8d13ee.jpeg)

**Comment by AkihiroSuda** [comment]
@thaJeztah Yes, probably.

The issue seems reported in https://github.com/dependabot/dependabot-core/issues/2804 but not solution

**Comment by thaJeztah** [comment]
> The issue seems reported in dependabot/dependabot-core#2804 and dependabot/dependabot-core#2198 but not solution

😞 that looks like a huge omission. I initially thought it was a regular GitHub action (which would allow it to be configured to only run on the main repo), but it isn't 😞 😞 😞

**Comment by kolyshkin** [comment]
The official docs say that dependabot is disabled on forks by default, and you need to explicitly enable it.

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates#enabling-version-updates-on-forks

Apparently, it is enabled on my fork, and I see no way to disable it :-\

**Comment by thaJeztah** [comment]
Could it be those docs may still be from the old implementation?

Perhaps it's possible to change access permissions on forks to deny the bot access 🤔

**Comment by AkihiroSuda** [comment]
Dependabot is now disabled for forks by default 
https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/

Configurable in https://github.com/USERNAME/runc/network/updates

**Comment by crazy-max** [comment]
@AkihiroSuda I think it's configurable through `https://github.com/USERNAME/runc/settings/security_analysis`:

![image](https://user-images.githubusercontent.com/1951866/200511887-b37aab0b-9516-46d0-ae61-e14e393629cf.png)
