### ISSUE TITLE
Support CFS bandwidth burst

### ISSUE THREAD

**Issue by kailun-qin** [opencontainers/runc#3145]
Burstable CFS controller is landed in Linux 5.14 [1], though the documentation is still WIP [2]. This helps with parallel workloads that might be bursty. They can get throttled even when their average utilization is under quota. And they may be latency sensitive at the same time so that throttling them is undesired.

This feature borrows time now against the future underrun, at the cost of increased interference against the other system users, by introducing cfs_burst_us into CFS bandwidth control to enact the cap on unused bandwidth accumulation, which will then used additionally for burst.

In general, it brings potential improvements on the efficiency of the CPU resource usage which may eventually help reduce the TCO and provide better QoS, which should be quite useful for many Cloud scenarios. It's great to have it supported in runc.

Drafted runtime-spec update: https://github.com/opencontainers/runtime-spec/pull/1120.

[1] torvalds/linux@f418371#diff-cc1a82129952a910fdc4292448c2a097a2ba538bebefcf3c06381e45639ae73e
[2] https://lore.kernel.org/lkml/20210730070956.44019-3-changhuaixin@linux.alibaba.com/T/

**Comment by m-yosefpor** [comment]
just adding runc PR link: https://github.com/opencontainers/runc/pull/3205

**Comment by AkihiroSuda** [comment]
Implemented in:
- https://github.com/opencontainers/runc/pull/3749
