### ISSUE TITLE
runc create: what is the default for terminal:?

### ISSUE THREAD

**Issue by dilyanpalauzov** [opencontainers/runc#3172]
https://github.com/opencontainers/runc/blob/master/docs/terminals.md says:

> By default, runc spec will create a configuration that will create a new terminal (terminal: true). However, if the terminal: ... line is not present in config.json then pass-through is the default.

This does not make sense.  The default is applied, when the parameter is not explicitly specified.

**Comment by kolyshkin** [comment]
> This does not make sense. The default is applied, when the parameter is not explicitly specified.

It does -- it's just `runc spec` default is to create a terminal, while `runc run/start` default is to use a pass-through mode.

Now, `runc run` default is actually dictated by the runtime-spec (see https://github.com/opencontainers/runtime-spec/blob/82ab996a5bf91804a440391bff43140b17bbadd4/config.md#process).

`runc spec` is merely providing an example spec. Usually container spec is created by some other tools.

Does this answer your question, @dilyanpalauzov?

**Comment by dilyanpalauzov** [comment]
After carefully re-reading the paragraph, I think it does make sense.

**Comment by cyphar** [comment]
Yeah the sentence is just explicitly spelling out that the default value of booleans in Go JSON if not specified is `false`, so in this case if you don't specify `terminal` it means you end up in pass-through mode (as if you'd set `terminal` to `false` explicitly).
