### ISSUE TITLE
Unable to load containers after devices.Type change

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#3179]
Just found this today:

[root@kir-rhat runc-tst]# ../runc/runc list
load container cc6: json: cannot unmarshal number into Go struct field Device.config.devices.type of type devices.Type
ID          PID         STATUS      BUNDLE      CREATED     OWNER

@thaJeztah not sure if there's a way to work around that -- if not, we may need to revert  https://github.com/opencontainers/runc/pull/3159

**Comment by cyphar** [comment]
Oh shit. Yeah if we changed the on-disk representation of the state we need to revert it. We caused a similar issue with `initProcessStartTime` a long time ago and it was incredibly painful to fix (it involved some truly awful hackery inside Docker to auto-migrate the on-disk state files). #3159 hasn't been in a release, right?

**Comment by thaJeztah** [comment]
Arf. Sorry for that.

> We really should add some kind of test to make sure that we can use runc on containers started with an older runc version

Perhaps we need some fixtures to Marshal/Unmarshal 🤔. I assumed failures in this area would indeed be caught by CI.


Also had a quick look if we could add a custom unmarshal to the `Type` type, but looks like Golang already errors out before it's hitting the custom function 😞

**Comment by cyphar** [comment]
> In this case, we would need to use two different runc versions in a single test (something like "use runc 1.0 to create a container, then use runc from git tip to list/update/delete it"), so we can test that config.json created by older runc can be parsed by newer runc.

Yeah we should do that.

> Yet another problem, perhaps even more complex, is backward compatibility. What if a user downgrades runc? Will older runc read config.json created by newer runc? Should we care about that scenario?

Purely from the on-disk-state perspective it should work fine, though in practice there's probably other issues we might hit doing that -- like if we add support for a new kernel feature and then older runc misconfigures it by accident. (Also the on-disk state isn't the same as config.json -- it's the internal libcontainer.Config generated by specconv.)
