### ISSUE TITLE
go get -u not working

### ISSUE THREAD

**Issue by gedw99** [opencontainers/runc#318]
i am just starting on this, so might be missing a few aspects, but on go run main.go i get:

/github.com/opencontainers/specs/config.go:25: undefined: User

**Comment by gedw99** [comment]
I am on OSX. It seems that OSX support is not ready yet even ?

**Comment by jfrazelle** [comment]
The primitives for creating linux namespaces do not exist on OS X so no

**Comment by jfrazelle** [comment]
I think this can be closed

**Comment by chengyuyang** [comment]
how to fix this issue?
I meet the same when I make go runc on mac

**Comment by marcosnils** [comment]
@chengyuyang @gedw99 The only way to run runC in OSX is to either use a VM or through docker. runC already supports running tests in a docker image with the `make test` command. If you need to build it, you can start from there and run it inside a docker container.
