### ISSUE TITLE
CI: relax commit message checker 'Subject too long (max 72)'

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#3187]
https://github.com/opencontainers/runc/blob/4d26c4a0a14e55fb71a3f7be2d3cd9f228523fff/.github/workflows/validate.yml#L121

This restriction seems too strict.
I suggest just dropping this check, or at least relaxing the constraint to 100 chars.

**Comment by kolyshkin** [comment]
I think the check makes sense and we should keep it. Whatever is not fitting in subject should go into commit description.
