### ISSUE TITLE
NOTIFY_SOCKET bind fails

### ISSUE THREAD

**Issue by cpuguy83** [opencontainers/runc#3202]
I started testing some things using runc in a systemd unit directly.
In this case it seems NOTIFY_SOCKET is always set, which triggers runc to bind-mount a socket into the container and proxy to the real socket (https://github.com/opencontainers/runc/blob/110bdb02e629aa3bd871d0c58a8f1e08c8cf48a6/notify_socket.go#L46-L56)

The issue with this is if the runc root (`/run/runc` by default) does not exist the bind fails.

**Comment by kolyshkin** [comment]
@cpuguy83 Do we want to create the directory (`/run/runc`) or skip the mount if it does not exist? I assume the former but I'm not quite sure.

**Comment by cpuguy83** [comment]
I think pre-create.
I noticed the code is currently just doing an Mkdir instead of MkdirAll and I wasn't sure if this was intentional.

**Comment by kolyshkin** [comment]
> I think pre-create. I noticed the code is currently just doing an Mkdir instead of MkdirAll and I wasn't sure if this was intentional.

I took a look at the code again, and it seems that "root" + id is always created by either "runc run" or "runc create". The work in a similar way:

```
-- startContainer
---- newNotifySocket
------ sets socketPath = root + id + "notify" + "notify.sock"
---- notifySocket.setupSpec
------ sets the mount with socketPath as source
---- createContainer
------ loadFactory
-------- gets the value of "root"
-------- makes an absolute path out of it (which is actually not necessary since #2629)
-------- libcontainer.New(root)
---------- os.MkdirAll(root, 0o700)
------ factory.Create
-------- makes sure root + id does not exist
-------- creates root + id
---- notifySocket.setupSocketDirectory
------ mkdir(pathDir(socketPath) (which is root + id + "notify")
```

Well, this should work, as root + id is created before calling `setupSocketDirectory` in `factory.Create`.

The only way how it might not work is `factory.Create` calls `secureJoin(root, id)` and in case there are some weird symlinks or something like that (frankly I can't imagine it), the path being created is different.

@cpuguy83 sorry for the late reply, but if you can still repro this, please share the steps to do so.

**Comment by cpuguy83** [comment]
I've been trying to force it to happen and can't seem to at this point. I don't recall what exact circumstances I was seeing this in. I'll go ahead and close this.
