### ISSUE TITLE
Investigate uses of cgroups.Manager.GetCgroups() (unused, perhaps can be deprecated)

### ISSUE THREAD

**Issue by thaJeztah** [opencontainers/runc#3221]
While reviewing https://github.com/opencontainers/runc/pull/3216, I noticed the manager interface has a `GetCgroups()`, which is unused in our codebase.

Looking at its history to see if it was used at some point, but "no longer" used, I found that it was contributed in https://github.com/opencontainers/runc/pull/2177 to be used by an external consumer. Digging further, that PR was linked to https://github.com/kata-containers/runtime/pull/2351, which is in a repository that has now been archived.

We should look if `GetCgroups()` is actively used by external consumers, and consider deprecating (and removing) it, if there are no uses.

**Comment by devimc** [comment]
please go ahead and deprecate it, we are using `github.com/containerd/cgroups` for cgroups management, thanks

**Comment by thaJeztah** [comment]
Thanks @devimc ! It's only a small bit of code, but I know we're looking at making more packages "internal" (as not all of them are really designed for external consumption), so this one caught my eye.

**Comment by kolyshkin** [comment]
This is used by kubernetes (see e.g. https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/kubelet/cm/container_manager_linux.go?L913:27#tab=references), maybe also cAdvisor, so we can't remove it.

One other thing, pretty big, which is not used by runc itself, is GetStats. We have lots of code and some tests for these methods, but never use them. The user is, again, kubernetes, and probably cAdvisor, too.

The way to solve it is to have a separate basic cgroup library which is used as a base by both runc and kubernetes. This is the subject of https://github.com/kubernetes/kubernetes/issues/104325, and it's a lot of work that has not been started yet (but I have it in mind).

(Feel free to reopen if I'm missing something)

**Comment by kolyshkin** [comment]
Ah, and the main reason why kubernetes use libcontainer is because no other cgroup library supports systemd (AFAIK).
