### ISSUE TITLE
When rootless runc exits, failed to remove cgroupv2 with sub-cgroup

### ISSUE THREAD

**Issue by chenk008** [opencontainers/runc#3225]
In case of rootless, cgroup2 mount into container `/sys/fs/cgroup`. After I created sub-cgroup `test`, and then exited. A error message shown
```
ERRO[0029] remove /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/user.slice/runc-foo.scope: device or resource busy
```

Reproduce:

```
runc spec --rootless
// add cgroupfs mount into config.json
{
      "destination": "/sys/fs/cgroup",
      "type": "cgroup",
      "source": "cgroup",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "relatime"
      ]
}
runc --systemd-cgroup run foo
// in the container
mkdir /sys/fs/cgroup/test
exit
```

systemd version: 239 (239-41.el8_3)
kernel version: 4.18.0-305.12.1.el8_4.x86_64
linux distro: centos 8

**Comment by chenk008** [comment]
I think it relates to https://github.com/opencontainers/runc/blob/e999e29a288630b5dfbfd8bc789975e5b94e6102/libcontainer/cgroups/systemd/v2.go#L305

**Comment by kolyshkin** [comment]
Ah, so you're using cgroup v2 on CentOS 8. We do not test this configuration, this is why we do not catch this bug.
