### ISSUE TITLE
I want to learn runc. I don't know how to compile and run runc on Mac? Can runc only be developed on Linux? I tried to install GoLand on the Mac and import the project, but I didn't know how to start or debug

### ISSUE THREAD

**Issue by zhangxsh** [opencontainers/runc#3247]
I want to learn runc. I don't know how to compile and run runc on Mac?
Can runc only be developed on Linux?
I tried to install GoLand on the Mac and import the project, but I didn't know how to start or debug

**Comment by cyphar** [comment]
runc is a Linux-only project. You probably can compile it on MacOS if you have the right cross-compilers installed (and you set `GOOS=linux`) but since in practice you need to have Linux on-hand in order to run it, it's probably simpler for you to create a Linux VM that you use for development.

**Comment by AkihiroSuda** [comment]
Cross-compiling cgo with libseccomp stuff is probably not straightforward.
I strongly suggest using Linux as the development env.
