### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/runc#3250]
This is listed under "Tier 1: Replace Immediately" in the Inclusive Naming Initiative:
https://inclusivenaming.org/word-lists/tier-1/#master

**Comment by cyphar** [comment]
I'm slightly more worried about some downstream using the word `master` explicitly in some script somewhere, but GitHub also appears to redirect `/blob/main/...` links as well so I guess this would only come to play if someone did `git clone` and explicitly tried to check out the `master` branch...

**Comment by jdolitsky** [comment]
@cyphar yes, correct (AFAIK). A simple `git clone` without specifying branch would use the "default" branch in GitHub settings. And if `master` explicitly specified on clone, it will have been renamed on server side and redirect to `main`.

**Comment by cyphar** [comment]
> And if master explicitly specified on clone, it will have been renamed on server side and redirect to main.

I just tried it, `git clone -b master --depth 1 https://github.com/opencontainers/umoci` doesn't get redirected (nor would I expect it to tbh).

**Comment by kolyshkin** [comment]
I say, let's do it after 1.1 release.

**Comment by kolyshkin** [comment]
Are we good to go? Unless there are any complains from @opencontainers/runc-maintainers, I am going to implement it in a week (next Tuesday or so).

**Comment by cyphar** [comment]
I'm not aware of any blockers. I'm sure folks will start screaming at us soon after if anything breaks (though thankfully GitHub does add redirects from the old branch name for most operations -- only local clones will be missing a "master" branch).

**Comment by thaJeztah** [comment]
No blockers from my side: GitHub itself will give some guidance after renames (with a link to instructions)

So, it's usually just my muscle memory that needs retraining

**Comment by kolyshkin** [comment]
Done!

For the reference, here are github-provided info about the rename (which includes what needs to be done locally)

> The default branch has been renamed!
> master is now named main
>
> If you have a local clone, you can update it by running the following commands.
>
> ```
> git branch -m master main
> git fetch origin
> git branch -u origin/main main
> git remote set-head origin -a
> ```

**Comment by kolyshkin** [comment]
@opencontainers/runc-maintainers You can also rename your forks by going to Settings / Branches (i.e. `https://github.com/<username>/runc/settings/branches`), at the top of the page is the form to rename.
