### ISSUE TITLE
cgroupv2: how can we collect cgroup stats after the process exits

### ISSUE THREAD

**Issue by darkyzhou** [opencontainers/runc#3255]
I am recently trying rootless libcontainer on Ubuntu 21.10 beta using cgroup v2 driven by systemd.

I found that when the init process in the container exits (even with code 0), the sub-cgroup folder gets immediately deleted automatically, which is kind of frustrating because I would like to collect some data from it such as cpu usage and memory usage.

Noticed that `Manager.Destroy()` in `cgroups.go` might be the cause, so I added a breakpoint before where it is called, but still the sub-cgroup gets deleted.

Are there any configurations or details I missed? Is it systemd that deletes the sub-cgroup? How can I access the sub-cgroup after the process exits? 

Any help would be greatly appreciated, thanks!

**Comment by kolyshkin** [comment]
Maybe `runc run --keep` will help? See #2817 / #2825

**Comment by darkyzhou** [comment]
> Maybe `runc run --keep` will help? See #2817 / #2825

Thanks for the suggestion but I am afraid it doesn't help.

It seems that the way libcontainer utilizes systemd to create a sub-cgroup folder, which is by creating a **transient scope unit**, makes systemd itself delete the folder once the process exits(therefore, runc/libcontainer itself cannot help).

After a detailed look into [the docs](https://systemd.io/CGROUP_DELEGATION/), I noticed that:

> The .scope unit type. This is very similar to .service. The main difference: the processes the units of this type encapsulate are forked off by some unrelated manager process, and that manager asked systemd to expose them as a unit.

Which might explain the reason: since libcontainer directly write the container process's pid into `cgroup.procs` file of the sub-cgroup folder, systemd will think it is the owner process of the transient scope unit, thus automatically clean up the sub-cgroup after the process exits.

And that:

> the unit itself is managed by systemd, i.e. all its attributes are managed exclusively by systemd, however your program may create/remove sub-cgroups _**inside it**_ freely, and those then become exclusive property of your program, systemd won’t touch them.

I guess if libcontainer write configuration into a new folder inside the sub-cgroup folder, we might be able to get around the problem. **So a decent solution could be that manually call dbus to create a transient unit file and create a new folder inside the sub-cgroup folder before calling libcontainer and tell it to use fs2 cgroup driver(instead of a systemd one) with the new folder.**

**Comment by kolyshkin** [comment]
@darkyzhou did you solve it? Care to share how?

**Comment by darkyzhou** [comment]
Sorry about being late, I was too sleepy when I was about to write this after closing the issue:

Hours ago I tried my idea:

> So a decent solution could be that manually call dbus to create a transient unit file and create a new folder inside the sub-cgroup folder before calling libcontainer and tell it to use fs2 cgroup driver(instead of a systemd one) with the new folder.

It worked and I was able to call `container.Stats()` to access cgroup statistics even after the container's process exits. But it turned out that I've got into another pitfall:

```
.../my-program.scope/runc-my-image$ cat cgroup.controllers
cpuset cpu pids

.../my-program.scope$ cat cgroup.subtree_control
cpuset cpu pids

.../my-program.scope$ cat cgroup.controllers
cpuset cpu io memory pids
```

Here `my-program.scope` is created by my program via systemd and `runc-my-image` is created by libcontainer. I found that even tough the parent cgroup(`my-program.scope`) enabled both `io` and `memory` controller, they were absent from the runc's. Which means that I cannot access any statistics about io and memory.

I noticed that in `CreateCgroupPath()` of `fs2/create.go`, libcontainer would iterate over every level of the specified cgroup path and try to write all available controllers' names into `cgroup.subtree_control`. And according to [the kernel docs](https://www.kernel.org/doc/Documentation/cgroup-v2.txt):

> A domain cgroup is turned into a threaded domain when one of its child
> cgroup becomes threaded or threaded controllers are enabled in the
> "cgroup.subtree_control" file while there are processes in the cgroup.
> A threaded domain reverts to a normal domain when the conditions
> clear.

When libcontainer tries to write `+cpu` into `my-program.scope/cgroup.subtree_control`, due to the cgroup already containing my program(`cgroup.procs` being non-empty), it becomes a threaded one:

```
.../my-program.scope$ cat cgroup.type
domain threaded
```

In this case, when libcontainer makes `runc-my-image` folder, the sub-cgroup's type will be defaulted to `domain invalid`, and libcontainer will set it to `threaded` since it is the only valid transition. As a result, both `io` and `memory` controllers are unavailable because they are not threaded controllers but domain ones.

I thought systemd should have some options that enable all controllers for `cgroup.subtree_control` when initializing `my-program.scope`, in which case libcontainer would not accidentally create a threaded controller. But I could hardly find any documents from systemd and it turned out that there might be no such options available. So I am depressed again, maybe I should submit another issue for systemd :(

**Comment by darkyzhou** [comment]
I checked systemd's source code: https://github.com/systemd/systemd/blob/main/src/core/scope.c#L383-L388

It seems that systemd just simply create the cgroup folder and then write the pid into `cgroup.procs`. Nothing I could do...

**Comment by darkyzhou** [comment]
Finally I came up with a workaround which seemed to be working nicely:

1. My program call dbus to create a scope, putting itself into the scope. Notice that current user(who runs my program) owns the cgroup folder of the scope.
2. At this time, when my program call libcontainer, the libcontainer would create the init process, and that process would be in the cgroup create by 1.
3. **My program call dbus again to create a slice,** it will be created in the `user@1000.service` folder so current user still have access to it. (My program might also need to manually write controller names to `cgroup.subtree_control`)
4. My program passes a newly created folder in the cgroup folder created by slice, eg. `my-program.slice/runc-test`, to libcontainer and asks it to use fs2 cgroup driver to do initialization things.
5. Libcontainer will succeeed because the init process of the container are originally at a cgroup owned my current user, so it is ok to move the process into a new cgroup that is also owned by current user. (It will not be the case if we don't do 1 and 2, because by default the init process will be in a cgroup owned by root).
6. **The `my-program.slice/runc-test` cgroup has every controller available and type being `domain`, thus I can access every type of statistics, voila!**
