### ISSUE TITLE
Add `runc --version-json` and print the implemented mount option strings

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#3274]
A high-level container application may want to obtain the list of the mount option strings supported by runc, because runc just ignores unimplemented mount option strings.

However, there is no way to obtain the list of the implemented mount option strings other than manually inspecting the code:
https://github.com/opencontainers/runc/blob/c1103d986faa82e9e6af7868b15e9904bbfd6fa6/libcontainer/specconv/spec_linux.go#L771-L824

I suggest adding `runc --version-json` command to print the machine-readable list of the implemented mount option strings.
We can put other info in this JSON eventually, too.

```console
$ runc --version-json
{
  "version": "X.Y.Z+dev",
  "commit": "vX.Y.Z-XXX-gXXXXXXXX",
  "spec": "X.Y.Z",
  "go": "goX.Y.Z",
  "libseccomp": "X.Y.Z",
  "supportedMountOptions": ["ro", "rw", "private", "rprivate", ..., "tmpcopyup"]
}
```

Relates to : 
- https://github.com/opencontainers/runc/pull/3272

**Comment by AkihiroSuda** [comment]
cc @giuseppe (runc and crun should share the same convention for this)

**Comment by kolyshkin** [comment]
The `--version-json` seems to be misleading, as it does not really shows version info.

Can we have something like `runc features` instead, which will produce output similar to the above, maybe slightly more generalized. For example
```console
$ runc features
{
  "version": "X.Y.Z+dev",
  "commit": "vX.Y.Z-XXX-gXXXXXXXX",
  .....
  "features": [
     "seccomp",
     .....
     "mount-rro"
  ]
}
```

JSON can certainly be different, I'm mostly talking about the command name (and command vs option).

**Comment by AkihiroSuda** [comment]
We should also print the known cap names in the json
https://github.com/containerd/nerdctl/issues/567#issuecomment-978958504

**Comment by AkihiroSuda** [comment]
PR: https://github.com/opencontainers/runc/pull/3296
