### ISSUE TITLE
How tracing telemetry fit in runc to capture performance and behavior metrics (in DEBUG mode)

### ISSUE THREAD

**Issue by Dentrax** [opencontainers/runc#3307]
While traversing around the issues, I noticed an issue #3181. And one of the notes that pointed in there is: `figure out why the difference is so high`.

So, I thought that how could we trace performance and behavior more easily for single command in DEBUG mode? There are some kinds of tracing methods:
* [OpenTelemetry](https://opentelemetry.io/)
* [OpenCensus](https://opencensus.io/)
* [OpenTracing](https://opentracing.io/)

I think tracing can be easily handled by higher level runtimes [^1]. Such as `CreateContainer`, `KillContainer`, etc. are high level metrics which we do not know what's happening in deeper levels.

Would it be a bit overengineering to trace syscalls, IO operaions, etc.? Do we already have a tracing strategy? Since we already have benchmark strategies, having a tracing method in entire runtime really worthy? Waiting your thoughts.

cc: @dashpole @kolyshkin

[^1]: https://github.com/containerd/containerd/issues/3057

**Comment by kolyshkin** [comment]
> Do we already have a tracing strategy?

I am mostly using strace, and have played with Go's [pkg/trace](https://pkg.go.dev/runtime/trace) (together with `go tool trace`).

I'm not sure we need distributed tracing in runc, and the projects you refer to are all about distributed tracing AFAICS.
