### ISSUE TITLE
 mounting "devpts" to rootfs at "/dev/pts" caused: mount through procfs: invalid argument

### ISSUE THREAD

**Issue by jennydaman** [opencontainers/runc#3317]
https://github.com/cri-o/cri-o/issues/5348

Hello,

I am trying to create a container via `runc` but I am getting the error with steps to reproduce from the linked issue above.

With the release of `runc` version 1.0.3, I tried the following:

```shell
cd /bin
wget -O real_runc https://github.com/opencontainers/runc/releases/download/v1.0.3/runc.amd64

cat > runc << EOF
#!/bin/bash
echo "$@" >> /tmp/runc.log
exec /bin/real_runc "$@"
EOF

chmod +x real_runc runc
```

Trying to create the container produces this in `/tmp/runc.log`:

```
--systemd-cgroup --root=/run/runc create --bundle /run/containers/storage/overlay-containers/eb38910e58361e6e10dc85d6963ca0eec29f2c72c71a7ebfec8c606d37f3ba8b/userdata --pid-file /run/containers/storage/overlay-containers/eb38910e58361e6e10dc85d6963ca0eec29f2c72c71a7ebfec8c606d37f3ba8b/userdata/pidfile eb38910e58361e6e10dc85d6963ca0eec29f2c72c71a7ebfec8c606d37f3ba8b
```

Does anyone have advice on how to investigate further?

**Comment by AkihiroSuda** [comment]
https://github.com/cri-o/cri-o/issues/5348#issuecomment-990742839

You have to map 65536 UIDs and GIDs, at least.
