### ISSUE TITLE
Rootless containers: How to run a process as a non-root user

### ISSUE THREAD

**Issue by darkyzhou** [opencontainers/runc#3321]
As many articles suggest, for better security, we can run the container's process as a non-root user even in a rootless container.

Container implementations like podman [has a `--user` flag to achieve that](https://www.redhat.com/sysadmin/user-flag-rootless-containers), which seems to do the following uid/gid mappings:

```
Container    |       Host
0                    1000
1                  100001
...                   ...
```

I am trying the same thing using runc. Following is a `config.json`.

```json5
{
    "ociVersion": "1.0.0",
    "process": {
        "user": {
            "uid": 1000,
            "gid": 1000
        },
        // ...
    },
    // ...
    "linux": {
        "uidMappings": [
            {
                "containerID": 0,
                "hostID": 1000,   // the uid of my user in the host
                "size": 1
            },
            {
                "containerID": 1,
                "hostID": 100000,
                "size": 65536
            }
        ],
        "gidMappings": [
            {
                "containerID": 0,
                "hostID": 1000,   // the gid of my user in the host
                "size": 1
            },
            {
                "containerID": 1,
                "hostID": 100000,
                "size": 65536
            }
        ],
        "namespaces": [
            {
                "type": "user"
            }
            // ...
        ]
    }
}
```

When I run `runc run test-container`, I got this:

```
FATA[0000] nsexec-0[952842]: failed to use newuid map on 952845: Operation not permitted
FATA[0000] nsexec-1[952845]: failed to sync with parent: read(SYNC_USERMAP_ACK): Success
ERRO[0000] container_linux.go:380: starting container process caused: process_linux.go:402: getting the final child's pid from pipe caused: EOF
```

It seems that nsexec called `newuidmap` executable but got the following output. But I don't understand why.

```
newuidmap: write to uid_map failed: Operation not permitted
```

I checked [man7.org](https://man7.org/linux/man-pages/man7/user_namespaces.7.html):

>  In order for a process to write to the /proc/[pid]/uid_map
       (/proc/[pid]/gid_map) file, all of the following permission
       requirements must be met:
> ...

But didn't find anything useful:

The capability of `newuidmap` seems to be right:

```
$ getcap /usr/bin/newuidmap
/usr/bin/newuidmap cap_setuid=ep
```

So does the content of `/etc/subuid`:

```
$ cat /etc/subuid
darkyzhou:100000:65536
```

Other backgrounds:

```
$ uname -a
Linux dev 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
$ runc --version
runc version 1.0.2
commit: v1.0.2-0-g52b36a2
spec: 1.0.2-dev
go: go1.16.10
libseccomp: 2.5.1
```

Are there any details I missed? Any help would be greatly appreciated, thanks!

**Comment by AlexeyPerevalov** [comment]
I can guess you are running runc as non-root user, in this case runc binary should have setuid capabilities too. As well as additional capabilities e.g. cap_sys_admin for unshare.

**Comment by AkihiroSuda** [comment]
> I can guess you are running runc as non-root user, in this case runc binary should have setuid capabilities too.

No

**Comment by AkihiroSuda** [comment]
@darkyzhou Does `runc spec --rootless` work?

**Comment by darkyzhou** [comment]
> @darkyzhou Does `runc spec --rootless` work?

The `config.json` created by the command works, but as soon as I add:
```json
{
    "containerID": 1,
    "hostID": 100000,
    "size": 65536
}
```

It fails with the exact same output.

**Comment by darkyzhou** [comment]
I reinstall the `uidmap` package and the problem got solved. Pretty strange tho :/

**Comment by cyphar** [comment]
I wonder if the capabilities are sufficient -- on openSUSE, they have setuid instead of setcaps.

**Comment by darkyzhou** [comment]
> I wonder if the capabilities are sufficient -- on openSUSE, they have setuid instead of setcaps.

After reinstalling `uidmap` in my Ubuntu 21.10:

```
$ ls -al /usr/bin/newuidmap
-rwsr-xr-x 1 root root 28136 Jun 17 19:35 /usr/bin/newuidmap
$ getcap /usr/bin/newuidmap
// empty output!
$
```

It seems that in my case the file capabilities are not relevant.

However, as soon as I run `sudo setcap cap_setuid+ep /usr/bin/newuidmap`, same error occurs again. And running `sudo setcap cap_setuid-ep /usr/bin/newuidmap` does not help:

```
$ sudo setcap cap_setuid-ep /usr/bin/newuidmap
$ getcap /usr/bin/newuidmap
/usr/bin/newuidmap =
$ runc run test
// still error
```

Even adding `cap_setfcap,cap_setpcap` does not help too. Maybe the way `uidmap` works is different from other distributions.

**Comment by AkihiroSuda** [comment]
Probably your newuidmap is not compiled with libcap

**Comment by darkyzhou** [comment]
> Probably your newuidmap is not compiled with libcap

What will it cause? My `newuidmap` seems to be dynamically linked with `libcap-ng`:

```
$ ldd $(which newuidmap)
	// ...
	libcap-ng.so.0 => /lib/x86_64-linux-gnu/libcap-ng.so.0 (0x00007ffaeef88000)
	// ...
```

**Comment by cyphar** [comment]
Does setcap cause the setuid bit to be dropped?

**Comment by darkyzhou** [comment]
> Does setcap cause the setuid bit to be dropped?

Wow, it does! Didn't expect that.

And it seems setcap(8) page on man7.org doesn't mention that behavior.
