### ISSUE TITLE
PGP Signature Issue

### ISSUE THREAD

**Issue by ntdash** [opencontainers/runc#3327]
During the installation of docker on Archlinux, I got the following error :
```log
error: runc: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
:: File /var/cache/pacman/pkg/runc-1.0.3-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```
Can someone help me resolve this issue since it preventing me from installing docker  ?

**Comment by cyphar** [comment]
I don't know who Frederik Schwan. It seems like you're using Arch Linux, and this is an error from pacman installing the Arch Linux package. Please report this to Arch Linux. Closing.
