### ISSUE TITLE
Incompatibility of bootstrapData() and newContainerInit()

### ISSUE THREAD

**Issue by andree182** [opencontainers/runc#3330]
I'm trying to make the version v1.0.0-rc93 work on (basically LFS) linux, but it fails as below.
When using go 1.12, even v1.0.0-rc90 works. With go 1.16, v1.0.0-rc9 fails already.

To reproduce, I used +- the commands from README:

> mkdir /mycontainer
> cd /mycontainer
> mkdir rootfs
> tar c /bin/busybox /bin/sh /lib/l*.so* | tar -C rootfs -xvf -
> runc spec
> runc run mycontainerid

> ERRO[0010] container_linux.go:367: starting container process caused: process_linux.go:365: getting pipe fds for pid 0 caused: readlink /proc/0/fd/0: no such file or director

The function process_linux.go::bootstrapData() appears to generate some binary data (apparently some netlink stuff), using strace I see something like this:

> \0\0\0000\362\1\0\1\0\0\0\0\0\0\0\10\0\221j\0\0\2l\10\0\227j\0\0\0\0

However, this gets later consumed in init_linux.go::newContainerInit(), by

> if err := json.NewDecoder(pipe).Decode(&config); err != nil {

and fails, since obviously it's not JSON. Should it be somehow chewed through the kernel, first? Am I missing some kernel config maybe?

This results in {"type":"procError"} being returned in the pipe. This time the parent doesn't parse that properly, and instead of printing the above error, after it tries to do readlinkat(AT_FDCWD, "/proc/0/fd/0"...), which is similar to #2707 .

Could you provide some hints if the evaluation is correct and/or what to check?

Note: I also tried master version, there I'm instead getting:

> ERRO[0001] runc run failed: unable to start container process: waiting for init preliminary setup: unexpected 123 != 0

**Comment by kolyshkin** [comment]
The way `runc` talks to `runc init` is somewhat complicated and involves both json and netlink-like packets. Netlink data is consumed by `libcontainer/nsenter/nsexec.c`, JSON comes earlier.

I can not debug this further without exact steps to repro, not can I recall a bug like this.

> getting pipe fds for pid 0 caused

This tells us that PID was not properly initialized. Must be a consequence of earlier failure(s).

In general, I suggest using the latest released version (either 1.0.3 or 1.1.0-rc1) together with a supported golang version (1.16 for 1.0.x, 1.17 for 1.1.x), as rc9 is quite old and was only tested with golang 1.11 and 1.12, and rc93 was barely tested with go 1.16.

If you can repro this with e.g. 1.0.3, and have steps to repro, feel free to report it here.

**Comment by kolyshkin** [comment]
> Note: I also tried master version, there I'm instead getting:
> 
> > ERRO[0001] runc run failed: unable to start container process: waiting for init preliminary setup: unexpected 123 != 0

This is more interesting. The code in master expects 0 to be sent by this code in nsexec.c:

https://github.com/opencontainers/runc/blob/00f56786bb220b55b41748231880ba0e6380519a/libcontainer/nsenter/nsexec.c#L867-L874

The fact that we get 123 (which is `{`, which is usually the first character in JSON message) instead of `0` means that something is very wrong.

Can you repro this with a release binary provided by us?

**Comment by andree182** [comment]
> The way `runc` talks to `runc init` is somewhat complicated and involves both json and netlink-like packets. Netlink data is consumed by `libcontainer/nsenter/nsexec.c`, JSON comes earlier.
> 

Okay, this probably leads somewhere! So gccgo is used here, which I didn't know. I'll have to dig into it, check if it uses cross-compiler correctly. Strangely it worked with v1.0.0-rc6 version and go 1.12, though the nsenter stuff looks similar.

So ultimately, the problem could be, that the nsenter stuff is not compiled in runc binary (at least I cannot see the strings, but I see them in your released binaries), and it somehow just skips that part during init.

> In general, I suggest using the latest released version (either 1.0.3 or 1.1.0-rc1) together with a supported golang version (1.16 for 1.0.x, 1.17 for 1.1.x), as rc9 is quite old and was only tested with golang 1.11 and 1.12, and rc93 was barely tested with go 1.16.

The released 1.0.3 appears to work in my env, so it's 99% the problem of my incorrect compilation. Unfortunately it failed silently, it seems :-/

**Comment by andree182** [comment]
So apparently with cross-compilation CGO_ENABLED=0 by default ( https://pkg.go.dev/cmd/cgo ). So the nsenter.go file didn't result into the *.c files compiled in (no gccgo in my env), which still somehow linked, but ultimately didn't work.

I'd suggest adding some safegard for this into the Makefile (or if possible, some assert into some go file).

In either case, it's solved for me - thanks for the pointer with nsenter!

**Comment by kolyshkin** [comment]
> I'd suggest adding some safegard for this into the Makefile (or if possible, some assert into some go file).

Thanks, totally makes sense, implemented in https://github.com/opencontainers/runc/pull/3331
