### ISSUE TITLE
libcontainer/README.md is out of date

### ISSUE THREAD

**Issue by mengqiy** [opencontainers/runc#3348]
The example used in https://github.com/opencontainers/runc/blob/master/libcontainer/README.md#using-libcontainer is out-of-date.

**Comment by kolyshkin** [comment]
I was just looking at it yesterday. This is being fixed as part of https://github.com/opencontainers/runc/pull/3316 (which I am going to split into smaller PRs). For now, you can see if its first commit addresses your concerns, @mengqiy .
