### ISSUE TITLE
v2 cgroup delegation fails: memory.oom.group: no such file or directory

### ISSUE THREAD

**Issue by dkadioglu** [opencontainers/runc#3387]
After the update of runc from 1.0.3 to 1.1.0, one of my containers doesn't start anymore and errors out with the following message:
```Error response from daemon: Cannot restart container dkhm: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: chown /sys/fs/cgroup/system.slice/docker-77a1ac22d8bfb1658e9bb8430d7dd8c75e8fad69b4e3b389f8d25a09fde26d21.scope/memory.oom.group: no such file or directory: unknown``` Downgrading to 1.0.3 fixes it and the container starts again.

My 16 other containers run as before.

My host:
- RPi 4B 8G
- Arch Linux ARM fully updated

I have no clue where to start searching for the culprit of all this. Is there any further info, which might help to investigate this?

**Comment by kolyshkin** [comment]
Thanks for reporting this!

Looks like a regression from #3057. The workaround for you would be to NOT mount /sys/fs/cgroup read-write.

The proposed fix is https://github.com/opencontainers/runc/pull/3389. You can test it by using a pre-built binary for your arch (arm64 I guess) from the zip archive at the very bottom of this page: https://github.com/opencontainers/runc/actions/runs/1877860537

**Comment by dkadioglu** [comment]
Thank you very much for looking into this! And for providing a fix so fast!
I rebuilt runc 1.1.0 including the mentioned patch and so far it seems to work again, i.e. the respective containers starts and runs now. Perfect!
Just to mention: I am still on armv7h.
