### ISSUE TITLE
runC should allow launching conainers from within user namespaced containers

### ISSUE THREAD

**Issue by ashahab-altiscale** [opencontainers/runc#350]
We at Altiscale are running Hadoop schedulers in user namespaced docker containers. The schedulers launch tasks that also need to be containerized. Therefore we need to be able launch child containers from user namespaced containers.

**Comment by cyphar** [comment]
This is almost certainly related to #774 -- the only difference being that the `Rootless` flag should depend on whether runC is being run inside a user namespace.

**Comment by cyphar** [comment]
Yes, the changes @AkihiroSuda worked on should have fixed this.
