### ISSUE TITLE
runc cannot write weight devices to io.bfq.weight

### ISSUE THREAD

**Issue by cdoern** [opencontainers/runc#3529]
runc, when used in comtainers/podman and containers/common can successfuly write values like `blkio-weight` to `io.bfq.weight` but something is wrong with the logic for writing `blkio-weight-device`:

```
[charliedoern@fedora podman]$  sudo bin/podman --cgroup-manager=cgroupfs pod create --blkio-weight=123 --blkio-weight-device=/dev/loop22:123
Error: setting device weight "7:22 123": write /sys/fs/cgroup/libpod_parent/ef9c967f4c0a9e4436aba5a195b7a468612941e0695728843b4d1f217097910a/io.bfq.weight: operation not supported

[charliedoern@fedora podman]$ cat /sys/fs/cgroup/libpod_parent/ef9c967f4c0a9e4436aba5a195b7a468612941e0695728843b4d1f217097910a/io.bfq.weight
default 123
```

this has been followed to:

https://github.com/opencontainers/runc/blob/93ad6a8513791784a081fc3f8444ebaf4b665995/libcontainer/cgroups/fs2/io.go#L70-L76

and the cat proves that blkio-weight works so io.bfq.weight is supported. But something is wrong with the way io-weight-devices are being written.

**Comment by cdoern** [comment]
@kolyshkin PTAL

**Comment by cdoern** [comment]
@AkihiroSuda @kolyshkin any thoughts on this? might be worthwhile to add a statement here to fallback on io.weight.

**Comment by cdoern** [comment]
ping @kolyshkin  @AkihiroSuda

**Comment by kolyshkin** [comment]
> and the cat proves that blkio-weight works so io.bfq.weight is supported

The `cat` only proves that the file exists, and that the file should support writing per-device weights (the feature was added in kernel v5.4, commit 795fe54c2a8). Alas, you don't say what kernel are you using.

It's the kernel that returns EOPNOTSUPP error.

Here's a repro without runc:
```console
[kir@kir-rhat linux]$ uname -a
Linux kir-rhat 5.17.14-300.fc36.x86_64 #1 SMP PREEMPT Thu Jun 9 13:41:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[kir@kir-rhat linux]$ cat /proc/self/cgroup 
0::/user.slice/user-1000.slice/user@1000.service/app.slice/vte-spawn-982fffdb-c573-41c0-a6d8-88cf21a25e22.scope
[kir@kir-rhat linux]$ cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/vte-spawn-982fffdb-c573-41c0-a6d8-88cf21a25e22.scope/io.bfq.weight 
default 100
[kir@kir-rhat linux]$ echo "7:3 99" > /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/vte-spawn-982fffdb-c573-41c0-a6d8-88cf21a25e22.scope/io.bfq.weight 
bash: echo: write error: Operation not supported
```

> might be worthwhile to add a statement here to fallback on io.weight.

Alas,

```console
[kir@kir-rhat linux]$ echo "7:3 99" > /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/vte-spawn-982fffdb-c573-41c0-a6d8-88cf21a25e22.scope/io.weight 
bash: echo: write error: Operation not supported
```

**Comment by kolyshkin** [comment]
I think this happens because:
```
[kir@kir-rhat linux]$ cat /sys/block/loop5/queue/scheduler 
[none] mq-deadline kyber bfq 
```

As you can see, current scheduler is `none`.

Indeed,

```console
$ echo bfq | sudo tee -a /sys/block/loop3/queue/scheduler 
[sudo] password for kir: 
bfq

[kir@kir-rhat linux]$ cat /sys/block/loop3/queue/scheduler 
mq-deadline kyber [bfq] none

[kir@kir-rhat linux]$ echo "7:3 99" > /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/vte-spawn-982fffdb-c573-41c0-a6d8-88cf21a25e22.scope/io.bfq.weight 

[kir@kir-rhat linux]$ cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/vte-spawn-982fffdb-c573-41c0-a6d8-88cf21a25e22.scope/io.bfq.weight
default 100
7:3 99
```

Currently, we do not have a way to set a per-device IO scheduler. If required, this should be added into runtime-spec.
