### ISSUE TITLE
Add check for CONFIG_CGROUP_BPF in check-config.sh

### ISSUE THREAD

**Issue by fmoessbauer** [opencontainers/runc#3547]
The kernel config option `CONFIG_CGROUP_BPF=y` is required to be able to inject the BPF program of type `BPF_PROG_TYPE_CGROUP_DEVICE`.

If this option is not set, no containers can be started with `runc` (BTW: the same holds for `crun`).

Currently, the `check-config.sh` script does not test for this option, leading to all-green results for kernels where runc fails to start a container.

**Comment by kolyshkin** [comment]
@fmoessbauer thanks for reporting, feel free to open a PR!

**Comment by dharmicksai** [comment]
Hello, 
I would like to take up this issue
is it okay if I create the pr?

**Comment by fmoessbauer** [comment]
> Hello, I would like to take up this issue is it okay if I create the pr?

Sure. Thanks for taking over.
