### ISSUE TITLE
Why do we produce some gotest code to test runc cli, the bats script is more complicated to use

### ISSUE THREAD

**Issue by kamizjw** [opencontainers/runc#3576]

**Comment by kolyshkin** [comment]
Can you please elaborate?

**Comment by kamizjw** [comment]
I use runc in linux, and I don't know how to run bats. The go language itself supports test case writing, why not write some test cases directly to call the container lifecycle command interface to complete the runc command test coverage。
like if i want to test the runc runc command，i will write
 TestRunFun（）{
...
exec.command("runc", "run", "-b /tmp/mycontainer", "nginx")
}
maybe exec.command interface is not suitable to use in this situation, but I just wanted to express the meaning

**Comment by kolyshkin** [comment]
Thank you for your explanation.

For one thing, we do have many tests written in Go. Those are unit tests, and tests in libcontainer/integration.

For tests that execute runc we use bats. Surely, the same thing can be achieved by writing tests in Golang, or in C, or in Perl, or in Python (in fact, many crun tests are written in Python). I can't really say why we are using bats, but I don't see why we should not use it.

> I don't know how to run bats.

This is not a good enough reason to not use bats.

The other reason you give is from this issue subject:

> the bats script is more complicated to use

That is also questionable. Here's a bats test that checks a program foo can accept the flag --bar:

```bash
@test "foo accepts --bar" {
    foo --bar
}
```

and here's the same code using Go testing:
```go
package main

import ( 
        "os/exec"
        "testing"
)

func TestFooAcceptsBar(t *testing.T) { 
        out, err := exec.Command("foo", "--bar").CombinedOutput()
        if err != nil { 
                t.Fatalf("want nil, got %v (output: %s)", err, out)
        } 
}
```

Now, which one do you find more complicated?

Having said that, if you want to rewrite all bats tests in Go, you can certainly give it a try.

**Comment by cyphar** [comment]
bats tests mean that we have proper e2e tests of the CLI (which is what everyone else uses), and in principle you end up with scripts that also act as examples. Writing scripts in other programming languages is much more annoying (no matter what wrappers you write to make it "nicer") than in sh/bash -- that's what it was designed for.

> I use runc in linux, and I don't know how to run bats.

`make test`? In most cases `bats` just works, but for runc's tests (and this would be the case no matter which testing framework we use) we require more setup and logic which means you just want to use the wrapper scripts we've already written.

Docker uses Go for their tests and I personally have always found it an enormous pain to work with when you want to write a simple test.

**Comment by kamizjw** [comment]
ok,I see what you mean, I will try to write some CLI test commands with go test privately, if it works, I will make a PR
