### ISSUE TITLE
runc path

### ISSUE THREAD

**Issue by sohnaeo** [opencontainers/runc#3589]
If runc is installed under any custom path eg /app/bin/runc , containerd can't find runc and throw the below error

`ctr: failed to create shim: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/default/cont1/log.json: no such file or directory): exec: "runc": executable file not found in $PATH: <nil>: unknown`

I cant find anything in config.toml where I can define the custom runc path. Is it current limitation ?

Can someone help in this regard?

**Comment by sohnaeo** [comment]
I believe I found a solution for this, I used the below line in /etc/containerd/config.toml

[plugins."io.containerd.internal.v1.opt"]
path = "/opendata"

By default, containerd looks /usr/bin or /opt/containerd to find the runc command so if runc in different location, containerd need to know about it, no need to provide the "bin" into path. Example ,if runc binary is installed under /opendata/bin so below line into /etc/containerd/confg.toml at the end would fix the issue

[plugins."io.containerd.internal.v1.opt"]
path = "/opendata"

I believe documentation should address this issue. If user is installing binaries installed into different location, users should be aware of this setup.

**Comment by kolyshkin** [comment]
Not sure why you file this to runc, as the process of finding the runc binary is clearly out of scope for runc itself.

In general, `$PATH` is used on UNIX systems (including Linux) as a mechanism to find binaries; the alternative is specifying the absolute path to a binary. All this is in no way specific to finding the runc binary (or containerd, for that matter).

I guess what you can do at most is send a PR to amend containerd documentation (if it doesn't mention this).
