### ISSUE TITLE
ms_dispatch fn_monstore process error

### ISSUE THREAD

**Issue by clcc2019** [opencontainers/runc#3668]
kernel:
Linux ecs-c5b9-0002 4.19.90-2003.4.0.0036.oe1.x86_64 #1 SMP Mon Mar 23 19:10:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

os:
NAME="openEuler"
VERSION="20.03 (LTS)"
ID="openEuler"
VERSION_ID="20.03"
PRETTY_NAME="openEuler 20.03 (LTS)"
ANSI_COLOR="0;31"

other:

https://github.com/rook/rook/issues/10110

**Comment by clcc2019** [comment]
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d1
spec: 1.0.2-dev
go: go1.17.10
libseccomp: 2.5.4

**Comment by AkihiroSuda** [comment]
What's this?
