### ISSUE TITLE
question: does runc support pass metadata to env?

### ISSUE THREAD

**Issue by Howie59** [opencontainers/runc#3673]
like this: https://stackoverflow.com/questions/30746888/how-to-know-a-pods-own-ip-address-from-inside-a-container-in-the-pod

how can i pass it to container env?

**Comment by AkihiroSuda** [comment]
Metadata of what?

**Comment by Howie59** [comment]
like status.podIP, hostip related

**Comment by AkihiroSuda** [comment]
Not runc's scope.
