### ISSUE TITLE
question: runc run test and get `no such file or directory`

### ISSUE THREAD

**Issue by Howie59** [opencontainers/runc#3676]
i use command `docker export $(docker create busybox) | tar -C rootfs -xvf -` expose rootfs

file tree is:
```bash
[root@host test]# ll
total 8.0K
-rw-r--r--  1 root root 2.6K Dec  3 17:11 config.json
drwxr-xr-x 18 root root 4.0K Dec  3 17:09 rootfs

```

in the same directory, i run `runc spec` create `config.json`

i add this code
```json
"args": [
     "sleep", "100"
 ],

```
and run `runc run -d test`

but i got this
```
[root@host test]# runc run -d o
exec /usr/bin/sleep: no such file or directory
```
i add /usr/bin/sleep to roofs directory manually, and got the same result

but in fact, the  file lies in `rootfs/usr/bin`
```
[root@host test]# ll rootfs/usr/bin/
total 1.2M
-rwxrwxrwx 1 root root 1.2M Dec  3 17:09 bash
-rw-r--r-- 1 root root  19K Dec  3 17:09 getconf
-rw-r--r-- 1 root root  11K Dec  3 17:09 ldd
-rwxrwxrwx 1 root root  39K Dec  3 17:09 sleep
```

**runc version:**
```
[root@host test]# runc --version
runc version 1.1.4
commit: 5cfec3d-dirty
spec: 1.0.2-dev
go: go1.19.3
libseccomp: 2.5.4
```

**Comment by Howie59** [comment]
and if i mount one executable file into rootfs, i got same result, and the file exists  in rootfs directory but file size is zero(content is empty)

**Comment by Howie59** [comment]
i use one running containerd layer rootfs as root path, it start normally.
any wrong step i use? or rootfs has any fixed requirement?

**Comment by leiqi96** [comment]
Can you upload your runc binary?  Then I can test runc in  my environment.

I get runc  from https://github.com/opencontainers/runc/releases/download/v1.1.4/runc.amd64.
` ./runc.amd64  --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d1
spec: 1.0.2-dev
go: go1.17.10
libseccomp: 2.5.4`

then test runc with your step, and it works well.

`# runc list
ID          PID         STATUS      BUNDLE                             CREATED                          OWNER
o           854580      running     /root/code/container/mycontainer   2022-12-04T06:53:19.216610794Z   root`

**Comment by Howie59** [comment]
> Can you upload your runc binary? Then I can test runc in my environment.
> 
> I get runc from https://github.com/opencontainers/runc/releases/download/v1.1.4/runc.amd64.
> 
> ```
> ./runc.amd64  --version
> runc version 1.1.4
> commit: v1.1.4-0-g5fd4c4d1
> spec: 1.0.2-dev
> go: go1.17.10
> libseccomp: 2.5.4
> ```
> 
> then test runc with your step, and it works well.

sry，the binary is in Intranet.

**Comment by Howie59** [comment]
temporary resolved, so close

**Comment by HeroicKatora** [comment]
If anyone encounters this, check if the binaries to be ran are in fact statically linked. And if not, whether all require link dependencies are also available in the system at the specified path. Both the dynamic linker (e.g. `/lib64/ld-linux-x86-64.so.2`) will resolve these before actually dispatching into 'your' executable. When even the file of linker itself is missing then you probably get an issue with the error message as shown.
