### ISSUE TITLE
Runc reports an error after upgrading the patch (from runc 1.0.0-rc3): `two checks on same syscall argument`

### ISSUE THREAD

**Issue by kamizjw** [opencontainers/runc#3692]
I am based on the 1.0.0-rc3 version and want to incorporate the patch https://github.com/opencontainers/runc/commit/7a8d7162f9d72f20d83eaa36aeb5426deecd58f2，After integration, the error message "libcontainer: container start initialization failed: two checks on same syscall argument container_linux.go:330: starting container process caused "two checks on same syscall argument"" was reported.

**Comment by kamizjw** [comment]
I found that the error code is in the function addRuleGeneric，the difference between the two versions is 1.0.0-rc3 is one by one addRule and other is addRule with array.
1.0.0-rc3:
`		for _, cond := range conds {
			cmpStruct := C.make_struct_arg_cmp(C.uint(cond.Argument), cond.Op.toNative(), C.uint64_t(cond.Operand1), C.uint64_t(cond.Operand2))
			defer C.free(cmpStruct)

			if err := f.addRuleWrapper(call, action, exact, C.scmp_cast_t(cmpStruct)); err != nil {
				return err
			}
		}`
the patch code：
`                argsArr := C.make_arg_cmp_array(C.uint(len(conds)))
                if argsArr == nil {
                        return fmt.Errorf("error allocating memory for conditions")
                }
                defer C.free(argsArr)

                for i, cond := range conds {
                        C.add_struct_arg_cmp(C.scmp_cast_t(argsArr), C.uint(i),
                                C.uint(cond.Argument), cond.Op.toNative(),
                                C.uint64_t(cond.Operand1), C.uint64_t(cond.Operand2))
                }

                if err := f.addRuleWrapper(call, action, exact, C.uint(len(conds)), C.scmp_cast_t(argsArr)); err != nil {
                        return err
                }
`

**Comment by AkihiroSuda** [comment]
The rc3 was a premature version, so upgrading from rc3 is not supported.
