### ISSUE TITLE
CI: `404  Failed to get https://github.com/docker-library/busybox/raw/dist-amd64/stable/glibc/busybox.tar.xz`

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#3699]
```
panic: getImages error exit status 1 (output: curl: (22) The requested URL returned error: 404 
Failed to get https://github.com/docker-library/busybox/raw/dist-amd64/stable/glibc/busybox.tar.xz
)

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer/integration.init.1()
	/home/runner/work/runc/runc/libcontainer/integration/utils_test.go:37 +0x2c5
FAIL	github.com/opencontainers/runc/libcontainer/integration	0.133s
```

https://github.com/opencontainers/runc/actions/runs/3896184715/jobs/6652404118

Thanks to @egernst for finding this in https://github.com/opencontainers/runc/pull/3698

**Comment by tianon** [comment]
Doh, this is my fault -- swap `stable` for `latest` and it should work again.

**Comment by tianon** [comment]
(I'm not entirely sure what the test is for, but it might be worth adjusting the test to pull the tarball from the registry instead, since that'll be more stable, or pinning specific commits :see_no_evil:)
