### ISSUE TITLE
Uncheck `Dismiss stale pull request approvals when new commits are pushed`

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#3706]
We have been often slow to merge PRs.
Maybe I've suggested before, but I'd like to uncheck the `Dismiss stale pull request approvals when new commits are pushed` checkbox in https://github.com/opencontainers/runc/settings/branches to facilitate merging PRs that are waiting for another two LGTMs.

Maintainers must still review the final commit before merging.

**Comment by kolyshkin** [comment]
I concur. It's better to move faster and occasionally break things, than be stuck for months.

@opencontainers/runc-maintainers WDYT?

**Comment by thaJeztah** [comment]
Agreed. I think we can trust maintainers to give another "ping" in situations where they made changes in between pushes that require a new review (and a clean / standard rebase should not require that).

**Comment by AkihiroSuda** [comment]
Done

**Comment by hqhq** [comment]
Sounds good to me.
