### ISSUE TITLE
RunC with CRIU : fails to clean up

### ISSUE THREAD

**Issue by wenhuizhang** [opencontainers/runc#3726]
When restore fails at post-resume, the process hangs there, if we kill the process, cgroup environment won't be cleaned。

**Comment by kolyshkin** [comment]
I am very sorry, but a one line description is not enough. Please describe what you do (in a way so a developer can reproduce your steps), what is the results that you see, and what did you expected to see.

**Comment by wenhuizhang** [comment]
> I am very sorry, but a one line description is not enough. Please describe what you do (in a way so a developer can reproduce your steps), what is the results that you see, and what did you expected to see.

It happened once, and could not reproduced at this moment, since did not find some container process hang , and did not force kill the process afterwards.
