### ISSUE TITLE
CI flaky test on centos-9: TestPodSkipDevicesUpdate stderr broken pipe

### ISSUE THREAD

**Issue by rata** [opencontainers/runc#3741]
On centos-9 I've seen this error:

```
=== RUN   TestPodSkipDevicesUpdate
    systemd_test.go:114: container stderr not empty: error writing "stdout": broken pipe
            while executing
        "puts stdout {test 0 = 1;}"
            (procedure "renderFalse" line 17)
            invoked from within
        "renderFalse"
            invoked from within
        "if {[catch {
           # parse all command-line arguments before doing any action, no output is
           # made during argument parse to wait for potential paging ..."
            (file "/usr/share/Modules/libexec/modulecmd.tcl" line 14687)
--- FAIL: TestPodSkipDevicesUpdate (0.13s)
```

**Comment by kolyshkin** [comment]
This is a tcl script which is part of `environment-modules` package, which we do not ever use directly. Must be something about centos-stream...

**Comment by rata** [comment]
@kolyshkin oh, maybe that was used from the basrc too? So maybe this https://github.com/opencontainers/runc/pull/3740 already fixed this one too? Let's see if it happens rebasing on main now

**Comment by rata** [comment]
After merging that PR, I haven't seen this happen again. Closing this

Please re-open @kolyshkin if you have hit this recently
