### ISSUE TITLE
make error on CentOS 7

### ISSUE THREAD

**Issue by AdoHe** [opencontainers/runc#378]
FYI. I downloaded the latest 0.0.4, and try to `make` on Linux host, but just get this error: `undefined: capability.List undefined: mount.Info`, it seems the libcontainer throws this error.

**Comment by gitido** [comment]
@AdoHe Are you building from within your GOPATH, or some other directory?

**Comment by AdoHe** [comment]
@gitido I think some other directory. Maybe you are right I should build from within my GOPATH. I will give a try.

**Comment by AdoHe** [comment]
@gitido you are right, I should build from with my GOPATH. thanks :)

**Comment by hqhq** [comment]
@AdoHe You can try this patch: #328
