### ISSUE TITLE
Create a private fork repo for privately running CI

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#3793]
GitHub Security Advisory's private PRs do not seem to support CI, so we failed to find a CI failure #3792 before merging GHSA-m8cg-xc2p-r3fc .

Can we create a private fork repo (`opencontainers/runc-private`) so as to run the CI for GHSA patches?

**Comment by AkihiroSuda** [comment]
cc @caniszczyk @amye @cyphar 🙏

**Comment by kolyshkin** [comment]
@caniszczyk @amye very please :pray:

 The current github process (of creating a draft security advisory and a private fork) does not allow us to run CI, which is a major issue.

Basically what we need here is a private repo (e.g. `opencontainers/runc-private`) which can only be accessed by runc maintainers, and on which we can run GHA CI. We would like to use that repo for running CI on runc with security fixes we might be working on from time to time.

**Comment by amye** [comment]
Cirrus CI work? (I just used the project template to give us somewhere to go with this - it might need to be recalibrated.)

**Comment by kolyshkin** [comment]
Yes, everything is working fine, thank you, we can consider this done
