### ISSUE TITLE
list all containers with runc

### ISSUE THREAD

**Issue by AdoHe** [opencontainers/runc#380]
FYI. I think we should have a command which can list all of the containers started by `runc`

**Comment by hqhq** [comment]
ping @crosbymichael @LK4D4 @mrunalp Do you think we need this?
If positive, I can help doing this feature.

**Comment by mikebrow** [comment]
I can help on this one as well.  ATM many of the runc commands require you to know what is running and from which bundle (directory) it was run from before you can successfully use a runc command. Seems like a ps like list is a necessary evil.

**Comment by mikebrow** [comment]
Might want to make the '-bundle / -b' command universal as well or at least add it to all of the bundle context sensitive commands.  I think that would go well with the listing the bundle directories for the running containers.. Then you could enter 'runc pause -b directory' to pause a running container.

**Comment by marcosnils** [comment]
I like the idea, runC already knows how to parse the state.json file, so doing something which traverses the /opencontainers/containers directory and print container statuses in a fashion way shouldn't be too intrusive. 

Maybe `runc ps` can emerge of this?

**Comment by AdoHe** [comment]
@mikebrow @marcosnils exactly, this feature shouldn't be too intrusive, `runc ps` is a good option.

**Comment by mikebrow** [comment]
#dibs

**Comment by crosbymichael** [comment]
This has been fixed in master now.

**Comment by AdoHe** [comment]
@crosbymichael cool :+1:
