### ISSUE TITLE
Runc build problem

### ISSUE THREAD

**Issue by abdasgupta** [opencontainers/runc#383]
Following are the errors when I build runc according to the instructions given here:

go build -tags "seccomp" -o runc .
checkpoint.go:11:2: cannot find package "github.com/opencontainers/runc/libcontainer" in any of:
	/usr/src/github.com/opencontainers/runc/libcontainer (from $GOROOT)
	/home/abhishek/go/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer (from $GOPATH)
	/home/abhishek/go/src/github.com/opencontainers/runc/libcontainer
spec.go:18:2: cannot find package "github.com/opencontainers/runc/libcontainer/cgroups" in any of:
	/usr/src/github.com/opencontainers/runc/libcontainer/cgroups (from $GOROOT)
	/home/abhishek/go/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/cgroups (from $GOPATH)
	/home/abhishek/go/src/github.com/opencontainers/runc/libcontainer/cgroups
restore.go:13:2: cannot find package "github.com/opencontainers/runc/libcontainer/configs" in any of:
	/usr/src/github.com/opencontainers/runc/libcontainer/configs (from $GOROOT)
	/home/abhishek/go/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/configs (from $GOPATH)
	/home/abhishek/go/src/github.com/opencontainers/runc/libcontainer/configs
main_unix.go:5:8: cannot find package "github.com/opencontainers/runc/libcontainer/nsenter" in any of:
	/usr/src/github.com/opencontainers/runc/libcontainer/nsenter (from $GOROOT)
	/home/abhishek/go/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/nsenter (from $GOPATH)
	/home/abhishek/go/src/github.com/opencontainers/runc/libcontainer/nsenter
spec.go:20:2: cannot find package "github.com/opencontainers/runc/libcontainer/seccomp" in any of:
	/usr/src/github.com/opencontainers/runc/libcontainer/seccomp (from $GOROOT)
	/home/abhishek/go/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/seccomp (from $GOPATH)
	/home/abhishek/go/src/github.com/opencontainers/runc/libcontainer/seccomp
signals.go:12:2: cannot find package "github.com/opencontainers/runc/libcontainer/utils" in any of:
	/usr/src/github.com/opencontainers/runc/libcontainer/utils (from $GOROOT)
	/home/abhishek/go/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/utils (from $GOPATH)
	/home/abhishek/go/src/github.com/opencontainers/runc/libcontainer/utils
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 1

Please, help me to resolve this issue.

**Comment by hqhq** [comment]
See: #378

**Comment by crosbymichael** [comment]
You need to clone the repo into your GOPATH and then use the makefile and not go build because of the way we vendor dependencies .

Thanks!
