### ISSUE TITLE
RFC: drop -a from `runc kill`

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#3864]
Option `-a` for `runc kill` is only usable when we are trying to `kill -9` the container which does not have its own PID namespace. All other use cases (like sending SIGTERM to _all_ container processes) are questionable to say at least.

I propose we deprecate `-a`, and handle the above use case (sending SIGKILL to init of the container which does not have its own pidns) automatically (in fact, this is already done in libcontainer, but not in runc binary).

The deprecation can be done in steps:
1. In runc 1.2, emit a warning when `-a` is used with `runc kill`.
2. In runc 1.3 (or later version), upgrade the warning to error.
3. In runc 1.4, drop the flag.

**Comment by kolyshkin** [comment]
@giuseppe @cyphar @AkihiroSuda WDYT?

**Comment by AkihiroSuda** [comment]
> automatically

Probably this is fine but we might need to add another flag to disable it

> drop the flag

For compatibility sake, the flag will have to remain as a NOP flag

**Comment by kolyshkin** [comment]
> > automatically
> 
> Probably this is fine but we might need to add another flag to disable it

libcontainer works this way since 2005:

https://github.com/opencontainers/runc/blob/268511680f4a72b4a0595497a37e4d6a7da0215c/libcontainer/process_linux.go#L617-L622

(Yes, the other peculiarity here is we call `kill` from `wait` which is counterintuitive to say at least).

For some reason, runc kill doesn't work this way, thus the need for `-a`.

I don't think we need a flag to disable this behavior -- there is no use case when you want to `kill -9` container init but leave all other processes around.

> 
> > drop the flag
> 
> For compatibility sake, the flag will have to remain as a NOP flag

Sure

**Comment by giuseppe** [comment]
> @giuseppe @cyphar @AkihiroSuda WDYT?

LGTM
