### ISSUE TITLE
Proposal: introduce testRequirement to runC

### ISSUE THREAD

**Issue by hqhq** [opencontainers/runc#387]
I got an error when doing integration test on a new machine:

```
=== RUN TestRunWithKernelMemory
time="2015-11-05T09:03:15Z" level=warning msg="signal: killed"
--- FAIL: TestRunWithKernelMemory (0.26s)
        exec_test.go:555: runContainer failed with kernel memory limit: [8] System error: open /sys/fs/cgroup/memory/integration/test/memory.kmem.limit_in_bytes: permission denied
```

Because I don't have kmem limit support, want to propose before doing this. Do we want something like testRequirement in runC?

**Comment by cyphar** [comment]
I did something like this for the pids cgroup. We can refactor this out to be a general `testRequirement` thing.

**Comment by crosbymichael** [comment]
We resolved this issues in the cgroups code and how values are set.
