### ISSUE TITLE
runc mounts wrong rootfs than specified in config.json

### ISSUE THREAD

**Issue by TomasTomecek** [opencontainers/runc#390]
I'm trying to setup a haproxy runc container for my presentation at conference tomorrow and am hitting weird behavior (probably caused by my lack of knowledge).

runc mounts my **host's** root filesystem as root of my container, and not the bundle I'm specifying.

this is what `mount` says inside my runc container:

```
/dev/sdb2 on / type btrfs (rw,noatime,seclabel,ssd,discard,space_cache,subvolid=257,subvol=/top)
```

(my host root filesystem is btrfs and `/` is actually a subvolume as you can see)

My container's FS bundle sits in:

```
/opt/containers/haproxy
```

And the rootfs is in directory `r` (actually it's in `rootfs` too):
```
$ ls -lha /opt/containers/haproxy/r/
total 20K
lrwxrwxrwx. 1 root root    7 Aug 16  2014 bin -> usr/bin
dr-xr-xr-x. 1 root root    0 Aug 16  2014 boot
drwxr-xr-x. 1 root root   26 Nov  6 11:26 dev
drwxr-xr-x. 1 root root 1.9K Nov  6 11:26 etc
-rw-rw-r--. 1 root root 3.7K Nov  6 11:01 ha.cfg
drwxr-xr-x. 1 root root    0 May 22 01:59 home
lrwxrwxrwx. 1 root root    7 Aug 16  2014 lib -> usr/lib
lrwxrwxrwx. 1 root root    9 Aug 16  2014 lib64 -> usr/lib64
drwx------. 1 root root    0 May 22 01:58 lost+found
drwxr-xr-x. 1 root root    0 Aug 16  2014 media
drwxr-xr-x. 1 root root    0 Aug 16  2014 mnt
drwxr-xr-x. 1 root root    0 Aug 16  2014 opt
drwxr-xr-x. 1 root root    0 May 22 01:58 proc
dr-xr-x---. 1 root root  128 Nov  6 11:26 root
drwxr-xr-x. 1 root root   14 Nov  6 11:26 run
lrwxrwxrwx. 1 root root    8 Aug 16  2014 sbin -> usr/sbin
drwxr-xr-x. 1 root root    0 Aug 16  2014 srv
drwxr-xr-x. 1 root root    0 May 22 01:58 sys
drwxrwxrwt. 1 root root  160 May 22 01:59 tmp
drwxr-xr-x. 1 root root  100 May 22 01:58 usr
drwxr-xr-x. 1 root root  160 May 22 01:58 var
```

Snippet of my config.json:

```
"root": {
    "path": "/opt/containers/haproxy/r",
    "readonly": false
},
```

I have mount namespace specified:

```
{
    "type": "mount",
    "path": ""
}
```

I've tried two different machines and runc in versions `git master`, `0.0.4`, `0.0.2`; same behavior everywhere.

What am I doing wrong?

**Comment by crosbymichael** [comment]
I have no clue what could be happening here.  Could be some issue with btrfs subvolumes but its hard to tell.

**Comment by TomasTomecek** [comment]
I think we can close this. As far as I remember, the issue was with `config.json` itself -- I copied one from readme instead of bootstrapping one with runc itself.
