### ISSUE TITLE
tmpfs mounts with pre-existing dir (effecitvely) ignores mode options

### ISSUE THREAD

**Issue by cpuguy83** [opencontainers/runc#3911]
### Description

Lets say you have a tmpfs mount like so:

```json
{ "destination": "/tmp/test", "type": "tmpfs", "source": "tmpfs", "options": ["mode=0444"] }
```

If a directory already exists in the rootfs for the destination the mode set during mount is overwritten by the original mode on that directory.
This seems to be cause here: https://github.com/opencontainers/runc/blob/bcaee38a9a1d1d13b274a569008067321dcf9c70/libcontainer/rootfs_linux.go#L446-L468

Where a `stat` is called, if the stat does not fail at the end, after mount, a `chmod` is performed.
Where this is particularly problematic is when re-using the same rootfs (e.g. restarting a container) because it also does an `mkdir(dest, 0755)`. So the next time a container is started with that rootfs the stat call will succeed and any mode set by the mount is overwritten.

### Steps to reproduce the issue

Using ctr for simplicity of getting a rootfs:

```console
$ mkdir -p /tmp/test/rootfs
$ sudo ctr image mount docker.io/library/busybox:latest /tmp/test/rootfs
$ sudo runc spec --bundle /tmp/test # creates a default runc spec
$ sudo mv /tmp/test/config.json /tmp/test/config.json.orig
$ sudo jq '.process += { "args": ["stat", "-c", "%a", "/tmp/test"]} | .mounts += [{ "destination": "/tmp/test", "type": "tmpfs", "source": "tmpfs", "options": ["mode=0444"] }]' /tmp/test/config.json.orig > /tmp/test/config.json
$ sudo runc run --bundle /tmp/test
444
$ sudo runc run --bundle /tmp/test
755
```

### Describe the results you received and expected

The target directory mode is set to the pre-existing directory's mode rather than the mode set in the mount.
After a container restart the mode actually changes in the above example which is highly unexpected.

I suspect this could be fixed by looking for a mode option and using that when doing the mkdir, though technically this is only a partial fix because the same rootfs could technically be used with different mount options.
Alternatively I guess `chmod` could be skipped if `mode` is set in the options.

### What version of runc are you using?
```
runc version 1.1.7
commit: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
spec: 1.0.2-dev
go: go1.19.10
libseccomp: 2.5.3
```

### Host OS information

```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Host kernel information

```
Linux dev2 5.15.0-1040-azure #47-Ubuntu SMP Thu Jun 1 19:38:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

ref: https://github.com/docker/for-linux/issues/138

**Comment by cpuguy83** [comment]
@corhere pointed out that we should be able to skip the chmod and prepend the stat'ed mode to the mount options.
This will set the mode at the mount level but if there is a user-provided mode that will win.

**Comment by cpuguy83** [comment]
```
$ mkdir -p test
$ stat -c %a /tmp/test
755
$ sudo mount -t tmpfs tmpfs -o mode=0755,mode=0444 /tmp/test
$ sudo stat -c %a /tmp/test
444
```

**Comment by thaJeztah** [comment]
- related https://github.com/moby/moby/issues/40881
