### ISSUE TITLE
Define documented const for magic `-1` file-descriptor

### ISSUE THREAD

**Issue by thaJeztah** [opencontainers/runc#3934]
The -1 to a var can work (although unsure which would be a good var name :-D). But yes, it touches way other func than this PR, so I agree it should be in another PR. I'm on the fence if just keeping -1 is okay, though, it is pretty widely used...

relates to https://github.com/opencontainers/runc/pull/3717#discussion_r1259780818_

**Comment by rata** [comment]
@thaJeztah I think we can close this now that #3939 is merged. Can you close (I can't, sorry :))

**Comment by kolyshkin** [comment]
Yes, we no longer use -1 in that code.
