### ISSUE TITLE
Cirrus-CI won't work in September

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#3964]
### Description

It seems that runc freeride on cirrus-ci is over: https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/

**Comment by cyphar** [comment]
It seems that they're "just" adding a compute cap. Do we know how much CPU time we are using monthly today?

Alternatively, I can take a look at whether it's possible to set up a CentOS VM inside a GitHub Action (such as with LXD)...

**Comment by kolyshkin** [comment]
@caniszczyk is there something that can be done?

**Comment by AkihiroSuda** [comment]
FYI: containerd and Lima are switching to "larger" instances of GHA paid by CNCF for running nested virt workloads
- https://github.com/containerd/containerd/pull/8919
- https://github.com/lima-vm/lima/pull/1723

**Comment by kolyshkin** [comment]
It looks like we're using 60-75 credits a month (May/June/July), which is not much more than their future limit of 50. What strikes me though is August usage is already 70.

I think if we can move the KVM (Fedora) out of cirrus-ci, this alone will make our usage below the limit. It seems that fedora image for GCP is available from https://alt.fedoraproject.org/cloud/, alas I can't find a public GCP fedora image.

**Comment by kolyshkin** [comment]
> FYI: containerd and Lima are switching to "larger" instances of GHA paid by CNCF for running nested virt workloads
> 
> * [CI: move Vagrant tests to GitHub Actions (larger runners) containerd/containerd#8919](https://github.com/containerd/containerd/pull/8919)
> * [CI: move Cirrus tests to GHA (larger instances) lima-vm/lima#1723](https://github.com/lima-vm/lima/pull/1723)

@caniszczyk can we do the same?

**Comment by kolyshkin** [comment]
@opencontainers/runc-maintainers does anyone know how can we contact OCI about this issue?

**Comment by amye** [comment]
I'm following, but I'm not sure if I'm following what the issue is. Help me out here?

**Comment by lifubang** [comment]
Yes, thanks.
I think there are two ways to solve this issue:

1. Use Compute Credits Auto Pay in cirrus CI.
https://cirrus-ci.com/settings/github/opencontainers
By enabling Auto Pay your repositories will be able to use compute credits in advance. You'll be billed in the end of each month for the amount of compute credits that your repositories used that month.

2. Use Github hosted large runners.
https://github.com/organizations/opencontainers/settings/actions/runners
We need to become a paid team or upgrade to Enterprise Plans.

**Comment by kolyshkin** [comment]
Fixed for now (we now use paid-for credits in Cirrus CI).

@caniszczyk is looking into using large runners.
