### ISSUE TITLE
[Refactor] Reduce runc-dmz binary size

### ISSUE THREAD

**Issue by lifubang** [opencontainers/runc#4027]
Now, the size of runc-dmz binary is more than 700kb, there is a sapce to reduce its size to reduce more memory when the container starting.
There are to ways could be considered:
1. try to remove libc dependency.
2. use asm

-----
I guess we can optimize the binary footprint by eliminating glibc and executing “syscall” instruction directly, but that may happen in follow-up PRs
Rewriting this in asm will be much easier than complicating libc dependency
original posted by @AkihiroSuda 
https://github.com/opencontainers/runc/pull/3983#discussion_r1295216177

The [kernel's nolibc](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/include/nolibc?h=v6.5) can be easily used and produces a very small binary. It seems only ppc is not supported, so we can fallback to stdlib in that case. We can just vendor it and no need to have anything installed on the distro building it.
A quick test shows that the binary can be 8K:
original posted by @rata 
https://github.com/opencontainers/runc/pull/3987#discussion_r1318670253

https://gist.github.com/Zheaoli/f37bc1fb04917fdfac36d644ee69f7e9
I made a demo for amd64. The binary file size is 4.9k.
original posted by @Zheaoli 
https://github.com/opencontainers/runc/pull/3983#discussion_r1307724677

Here is my contribution for arm64:
original posted by @eiffel-fl 
https://github.com/opencontainers/runc/pull/3983#discussion_r1310105876

**Comment by AkihiroSuda** [comment]
PRs:
- https://github.com/opencontainers/runc/pull/4024
- https://github.com/opencontainers/runc/pull/4026

**Comment by cyphar** [comment]
This is fixed with #4024. With nolibc, `runc-dmz` is 4.7kB on my machine.
