### ISSUE TITLE
[CI] not ok 135 runc run with tmpfs perms

### ISSUE THREAD

**Issue by lifubang** [opencontainers/runc#4029]
ci / test (ubuntu-20.04, 1.21.x, rootless, -race) (pull_request) Failing after 3m
```
not ok 135 runc run with tmpfs perms
# (in test file tests/integration/run.bats, line 119)
#   `[ "$output" = "710" ]' failed
# runc spec --rootless (status=0):
#
# runc run test_tmpfs (status=0):
# 444
# runc run test_tmpfs (status=0):
# 444
# runc run test_tmpfs (status=0):
# 710
```

**Comment by lifubang** [comment]
https://github.com/opencontainers/runc/actions/runs/6639817702/job/18038954312
It happended again. I have seen it several times.

ok 139 runc run with tmpfs # skip test requires root
not ok 140 runc run with tmpfs perms
# (in test file tests/integration/run.bats, line 104)
#   `[ "$output" = "444" ]' failed
# runc spec --rootless (status=0):
#
# runc run test_tmpfs (status=0):
# 444

**Comment by kolyshkin** [comment]
I think this is a manifestation of the same issue as in #2425 (a race in runc tty driver). I tried to solve it a few years ago (see #2723), albeit unsuccessfully (see #2749).

Maybe someone else can untangle this knot; I really tried.

As for the test case, a fix is simple, see https://github.com/opencontainers/runc/pull/4095.

**Comment by kolyshkin** [comment]
> I think this is a manifestation of the same issue as in #2425 (a race in runc tty driver). I tried to solve it a few years ago (see #2723), albeit unsuccessfully (see #2749).
> 
> Maybe someone else can untangle this knot; I really tried.

@lifubang if you want to give it a try, the repro is really simple:
1. Remove the `t.Skip` from the `TestExecInTTY`:
```diff
diff --git a/libcontainer/integration/execin_test.go b/libcontainer/integration/execin_test.go
index c5c32413..43eebeaf 100644
--- a/libcontainer/integration/execin_test.go
+++ b/libcontainer/integration/execin_test.go
@@ -234,7 +234,7 @@ func TestExecInTTY(t *testing.T) {
        if testing.Short() {
                return
        }
-       t.Skip("racy; see https://github.com/opencontainers/runc/issues/2425")
+       //      t.Skip("racy; see https://github.com/opencontainers/runc/issues/2425")
        config := newTemplateConfig(t, nil)
        container, err := newContainer(t, config)
        ok(t, err)
```
2. Run the test many times:
```console
$ cd libcontainer/integration
$ go test -v -count 1000 -exec sudo -run ExecInTTY
```

You will see it failing.

**Comment by kolyshkin** [comment]
Another manifestation of the same bug: #4074
