### ISSUE TITLE
Mirror site of criu is broken

### ISSUE THREAD

**Issue by lifubang** [opencontainers/runc#4088]
### Description

The following packages will be upgraded:
  criu
1 upgraded, 3 newly installed, 0 to remove and 23 not upgraded.
Need to get 1059 kB of archives.
After this operation, 1361 kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libnftables1 amd64 0.9.3-2 [229 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libseccomp-dev amd64 2.5.1-1ubuntu1~20.04.2 [83.6 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 sshfs amd64 3.6.0+repack+really2.10-0ubuntu1 [43.5 kB]
Get:5 https://downloadcontentcdn.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_20.04  criu 3.18-1 [703 kB]
Err:5 https://downloadcontentcdn.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_20.04  criu 3.18-1
  File has unexpected size (697812 != 703076). Mirror sync in progress? [IP: 146.75.105.91 443]
  Hashes of expected file:
   - SHA256:8dfa7f95fd1e3d860bd4352dc000a79aafd5b9c09a1aeeda5e4a5952449c1de6
   - SHA1:7a98b1a0430c236bbb245115d8051947a2dbca15 [weak]
   - MD5Sum:a022fc[57](https://github.com/opencontainers/runc/actions/runs/6608593038/job/17947521273?pr=4087#step:3:58)bd8af3945edbef4b4112625f [weak]
   - Filesize:703076 [weak]
Fetched 356 kB in 2s (230 kB/s)
E: Failed to fetch https://downloadcontentcdn.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_20.04/amd64/criu_3.18-1_amd64.deb  File has unexpected size (697812 != 703076). Mirror sync in progress? [IP: 146.75.105.91 443]
   Hashes of expected file:
    - SHA256:8dfa7f95fd1e3d860bd4352dc000a79aafd5b9c09a1aeeda5e4a[59](https://github.com/opencontainers/runc/actions/runs/6608593038/job/17947521273?pr=4087#step:3:60)52449c1de6
    - SHA1:7a98b1a0430c236bbb245115d8051947a2dbca15 [weak]
    - MD5Sum:a022fc57bd8af3945edbef4b4112[62](https://github.com/opencontainers/runc/actions/runs/6608593038/job/17947521273?pr=4087#step:3:63)5f [weak]
    - Filesize:[70](https://github.com/opencontainers/runc/actions/runs/6608593038/job/17947521273?pr=4087#step:3:71)30[76](https://github.com/opencontainers/runc/actions/runs/6608593038/job/17947521273?pr=4087#step:3:77) [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

Update criu successfuly.

### What version of runc are you using?

the main branch

**Comment by kolyshkin** [comment]
They say it was a temp issue (https://github.com/checkpoint-restore/criu/issues/2287#issuecomment-1773583776), as mirrors need some time to update. Anyway, we no longer see it so closing.
