### ISSUE TITLE
v0.0.5?

### ISSUE THREAD

**Issue by tianon** [opencontainers/runc#409]
There's been a fair amount of changes since the last `runc` release -- any thoughts on whether a new one is warranted? :smile: (https://github.com/opencontainers/runc/compare/v0.0.4...master)

**Comment by LK4D4** [comment]
@tianon I don't know, seems like it doesn't bother anyone, so I just stopped to do new :)

**Comment by tianon** [comment]
It bothers me!  I'd love to switch Docker to using an actual release tag,
and Debian (and likely other distros too) are using them for packaging:
https://packages.debian.org/sid/runc

**Comment by LK4D4** [comment]
@tianon How about then we will tag version which will be merged to release? For example on 1.10 we'll tag 0.0.5. and on 1.11 we'll tag 0.0.5.1?

**Comment by tianon** [comment]
Well, right now, 1.9 doesn't even compile with 0.0.4, so I'd rather we do 0.0.5 for 1.9 and then bump for 1.10, but yeah, I can definitely get behind that kind of cadence. :+1:

**Comment by tianon** [comment]
Happy to help do the work necessary for creating release tags too, if that's part of the blocker.

**Comment by LK4D4** [comment]
@tianon now in docker used "special" version of runc, we can tag it 0.0.5 anyway if you want. Or I don't know how it is supposed to be :/

**Comment by runcom** [comment]
I'm fixing docker to be able to use latest runc/libcontainer :)

**Comment by tianon** [comment]
If you want to do that, then I don't mind if you tag current latest as
0.0.5 and I'll just backport your patch to 1.9 for Debian (and happy to
share the rebased patch with any other packager interested). :smile:

**Comment by tianon** [comment]
Then your Docker patch could switch to v0.0.5 instead of just picking
some random new commit. :smile:

**Comment by runcom** [comment]
Indeed yes

**Comment by runcom** [comment]
Right now I'm just using the latest commit hash

**Comment by LK4D4** [comment]
@tianon If it's ok to do 0.0.5 right now on master, let's do it.

**Comment by LK4D4** [comment]
https://github.com/opencontainers/runc/releases/tag/v0.0.5

**Comment by tianon** [comment]
:heart: !
