### ISSUE TITLE
How to deal with the Configuration Conflict for user ns

### ISSUE THREAD

**Issue by lifubang** [opencontainers/runc#4132]
### Description

Nowadays, when we let the container to join an existing `user` or `time` namespace, we should not provide `uidMappings`, `gidMappings`, and `timeOffsets` configurations. But if these configurations are provided, how to deal with it? Error it out, or warn it out?

### Steps to reproduce the issue

Please see https://github.com/opencontainers/runc/pull/3985#pullrequestreview-1765313165

### Describe the results you received and expected

Let most upstream projects work fine.

### What version of runc are you using?

The main branch

**Comment by cyphar** [comment]
Ah, I opened #4133 already and #4134 which fixes the issue. Closing in favour of #4133.
