### ISSUE TITLE
Seems like a typo, the .PHONY label has no purpose this way

### ISSUE THREAD

**Issue by santidhammo** [opencontainers/runc#4204]
https://github.com/opencontainers/runc/blob/675292473b3ad4c131b900806077148a556d78c9/Makefile#L224C1-L225C8

**Comment by thaJeztah** [comment]
Yup, looks to have been introduced in https://github.com/opencontainers/runc/commit/b8f75f395504bef88c45111c2a69132c594bed79

- #4061 

Are you interested in contributing a PR to fix?

**Comment by santidhammo** [comment]
Sure, will be after dinner then.

**Comment by lifubang** [comment]
This issue has been fixed by #4205 .
