### ISSUE TITLE
lxc_contexts missing in ubuntu for selinux

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#422]
@rhatdan @crosbymichael 
While running runc unit test, observed that selinux tries to read the /etc/selinux/ubuntu/contexts/lxc_contexts. Looks like ubuntu 15.04 not having this file., local test fails in runc. though I've enabled selinux and file system is mounted

**Comment by rhatdan** [comment]
Please report a bug to the ubuntu shippers of selinux policy.  If they do  not ship that file or more importantly the types required to run Docker with SELinux. then you have to disable SELinux on that platform.

**Comment by SangeethaBusangari** [comment]
lxc_contexts. file not found even in /etc/selinux/ubuntu/contexts/ ubuntu 14.04. Have you raised a bug @rajasec

**Comment by crosbymichael** [comment]
Closing as this is not a runc issue but distro specific in the configuration that they ship.

Thanks!
