### ISSUE TITLE
GHSA-c5pj-mqfh-rvc3 "Runc allows an arbitrary systemd property to be injected" is a misunderstood vulnerability. Users do NOT need to update runc.

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#4263]
https://github.com/advisories/GHSA-c5pj-mqfh-rvc3 
("GitHub Reviewed" 🤔) is mislabeled as a vuln of runc < v1.2.0-rc.1.

"This issue has its root in how runc handles Config Annotations lists" is disinformation; the issue has its actual root in how CRI-O handles user input. https://github.com/cri-o/cri-o/commit/976ab1f4c916099fc1f2e6569f13e45df2f26b4f

Users do NOT need to update runc.

**Comment by haircommander** [comment]
hm did I file the gh advisory wrong? happy to edit anything that I messed up

**Comment by AkihiroSuda** [comment]
> hm did I file the gh advisory wrong? happy to edit anything that I messed up

GHSA-c5pj-mqfh-rvc3 seems published by NVD, not by you?

**Comment by AkihiroSuda** [comment]
The advisory https://github.com/advisories/GHSA-c5pj-mqfh-rvc3 is now withdrawn
