### ISSUE TITLE
error message - FATA[0000] Container start failed: [1] Invalid format: invalid id format: 

### ISSUE THREAD

**Issue by johntwei** [opencontainers/runc#427]
Not sure if this the right place to report my issue. I am new to runc.

I just built runc, followed the instructions, then got the following error message when tried to do "runc start".

"r.busybox" is the name of the parent directory.
current directory is "/root/TEST.runc/r.busybox"

 # docker export $(docker create busybox) > busybox.tar 
 # mkdir rootfs
 # tar -C rootfs -xf busybox.tar
 # runc spec .
 # runc start
FATA[0000] Container start failed: [1] Invalid format: invalid id format: r.busybox
 # ls 
busybox.tar  config.json  rootfs  runtime.json

**Comment by marcosnils** [comment]
@johntwei try renaming the folder "r.busybox" to something with just letters like "mycontainer"

**Comment by johntwei** [comment]
Thanks. That works. But, is this a known bug?

**Comment by marcosnils** [comment]
@johntwei not sure if it's a bug as I don't know the details about if container names can contain those characters. What I can tell is that runC specifically validates that the containerId should have the following format `^[\w_-]+$`, so I guess that validation must be there for a reason.

**Comment by johntwei** [comment]
Got it. The directory name that contains the rootfs/ is considered container's name. Then the directory name needs to follow the OCI naming requirements. Thanks for the clarification.
