### ISSUE TITLE
Readme section out of date

### ISSUE THREAD

**Issue by aochagavia** [opencontainers/runc#429]
https://github.com/opencontainers/runc#state-of-the-project states that a v1 of the spec is expected on July 2015.

**Comment by hqhq** [comment]
@aochagavia Thanks for reporting, I'll change it https://github.com/opencontainers/runc/pull/431

**Comment by aochagavia** [comment]
Thanks! I wasn't sure about what needed to be done, since I just stumbled upon this project after reading about docker.
