### ISSUE TITLE
Fd resue race causes runc init can't start due to a go stdlib bug

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#4294]
### Description

From https://cirrus-ci.com/task/6471857094787072:

> === RUN   TestInitJoinPID
>     exec_test.go:1471: unexpected error: unable to start container process: unable to start init: fork/exec /proc/self/fd/7: permission denied
> --- FAIL: TestInitJoinPID (0.29s)

I've only seen it happen once. Filing for visibility.

EDIT:
It's not a flaky test, but a really bug in practice.

**Comment by kolyshkin** [comment]
CentOS 7 is gone (see #4333), so this one can be closed I guess.

**Comment by kolyshkin** [comment]
I saw this once on Ubuntu 24.04 now:

https://github.com/opencontainers/runc/actions/runs/10823144914/job/30028174423?pr=4358

```
...
=== RUN   TestSharedPidnsInitKill
--- PASS: TestSharedPidnsInitKill (0.18s)
=== RUN   TestInitJoinPID
    exec_test.go:1444: unexpected error: unable to start container process: unable to start init: fork/exec /proc/self/fd/7: permission denied
--- FAIL: TestInitJoinPID (0.14s)
=== RUN   TestInitJoinNetworkAndUser
--- PASS: TestInitJoinNetworkAndUser (0.33s)
=== RUN   TestTmpfsCopyUp
...
```

So it might be a genuine issue with the test case.

**Comment by kolyshkin** [comment]
One more, in `test (ubuntu-20.04, 1.23.x, criu-dev)` but with a different test. From [logs](https://github.com/opencontainers/runc/actions/runs/10841017430/job/30084365134?pr=4398#logs)

```
=== RUN   TestSeccompPermitWriteMultipleConditions
    seccomp_test.go:251: |: unable to start container process: unable to start init: fork/exec /proc/self/fd/7: permission denied
--- FAIL: TestSeccompPermitWriteMultipleConditions (0.13s)
```

**Comment by kolyshkin** [comment]
Another failure in `test (ubuntu-20.04, 1.23.x, -race)`. From the [logs](https://github.com/opencontainers/runc/actions/runs/11151511704/job/30995106439):

```
=== RUN   TestSeccompDenyWriteConditional
    seccomp_test.go:205: unexpected error: unable to start container process: unable to start init: fork/exec /proc/self/fd/7: permission denied
--- FAIL: TestSeccompDenyWriteConditional (0.14s)
```

**Comment by kolyshkin** [comment]
From https://github.com/opencontainers/runc/actions/runs/11300641540/job/31433805394?pr=4441 (cross-i386):
```
=== RUN   TestRootfsPropagationSharedMount
    exec_test.go:1288: unexpected error: unable to start container process: unable to start init: fork/exec /proc/self/fd/7: permission denied
--- FAIL: TestRootfsPropagationSharedMount (0.13s)
```

**Comment by lifubang** [comment]
This is really a bug in practice, I can reproduce it in local.
We can start 1000 containers quickly, then we will have a change to reproduce.
Especially apply with the PR #4448, I don't know why, maybe because this PR make runc start more quickly than before.
