### ISSUE TITLE
CI: Replace CentOS Stream 8 with Alma, Rocky, or Oracle Linux due to EOL

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#4302]
> > > CentOS tests seem failing
> > 
> > For CentOS stream 8, that may be expected; it's EOL since May 31 (just got hit by that in some CI pipeline that als had it in the Matrix)
> 
> I guess we now have to replace CentOS with Alma, Rocky, or Oracle Linux?

_Originally posted by @AkihiroSuda in https://github.com/opencontainers/runc/issues/4292#issuecomment-2146085218_

**Comment by kolyshkin** [comment]
I guess we're fine with https://github.com/opencontainers/runc/pull/4304 for now. I'll ask around if we can get a free RHEL license (maybe even free compute resources) to test on.

**Comment by kolyshkin** [comment]
To test on RHEL using Red Hat's infra, we need to setup https://github.com/marketplace/packit-as-a-service org-wide. @caniszczyk @amye can you help?

**Comment by lifubang** [comment]
Google cloud has removed centos-8 stream now, it causes cirrus ci start failure: https://github.com/opencontainers/runc/pull/4299/checks?check_run_id=25802936493
`
Failed to start an instance: INVALID_ARGUMENT: Not Found 404 Not Found
POST [https://compute.googleapis.com:443/compute/v1/projects/cirrus-ci-community/zones/us-central1-c/instances](https://compute.googleapis.com/compute/v1/projects/cirrus-ci-community/zones/us-central1-c/instances)
{
"error": {
"code": 404,
"message": "The resource 'projects/centos-cloud/global/images/family/centos-stream-8' was not found",
"errors": [
{
"message": "The resource 'projects/centos-cloud/global/images/family/centos-stream-8' was not found",
"domain": "global",
"reason": "notFound"
}
]
}
}
`

**Comment by kolyshkin** [comment]
Let's remove it for now. Once we'll get help from org maintainers ([see above](https://github.com/opencontainers/runc/issues/4302#issuecomment-2148155522)), I'll work on adding RHEL.

Alternative solutions are also welcome, of course.

**Comment by kolyshkin** [comment]
1.1 backport: https://github.com/opencontainers/runc/pull/4308 (PTAL)
