### ISSUE TITLE
Follow libcontainer readme create container hit issue

### ISSUE THREAD

**Issue by HackToday** [opencontainers/runc#438]
I followed this : https://github.com/opencontainers/runc/blob/master/libcontainer/README.md

and with that go pogram, it said following:

&{/var/lib/container /proc/self/exe [/home/ubuntu/work/bin/hello init] criu 0xb55578 0x498a20}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x78 pc=0x4028d0]

goroutine 1 [running]:
main.main()
	/home/ubuntu/work/src/github.com/user/hello/hello.go:78 +0xa20

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

The 78 line is follopwing: (same as readme guide)

      err = container.Start(process)
        if err != nil {
                log.Fatal(err)
        }

**Comment by HackToday** [comment]
ping @crosbymichael

**Comment by Miloas** [comment]
Follow the readme guide , I get some errors too... 
I read the source code find that
``` golang
Cgroups: &configs.Cgroup{
        Name:            "test-container",
        Parent:          "system",
        AllowAllDevices: false,
        AllowedDevices:  configs.DefaultAllowedDevices,
    },
```
should be 
``` golang
Cgroups:  &configs.Cgroup{
        Name:            "test-container",
        Parent:          "system",
        Resources: &configs.Resources {
            AllowAllDevices: false,
            AllowedDevices: configs.DefaultAllowedDevices,
         },
 },
```
now. But when I changed this config code I got an another error:

```
System error: write parent: broken pipe
```
in
``` golang
container, err:= root.Create("some-id", config)
 if err != nil {
   log.Fatal(err)
}
```
Maybe this libcontainer's readme guide really should be updated...

**Comment by Miloas** [comment]
@crosbymichael Could you give us a new guide of libcontainer? thanks

**Comment by hqhq** [comment]
@HackToday @Miloas Sorry for the late response, that's really out dated instruction, just updated README in https://github.com/opencontainers/runc/pull/462  It works for me, could you check and see if that's clear enough for you to follow?
