### ISSUE TITLE
[ci] bats: command not found

### ISSUE THREAD

**Issue by lifubang** [opencontainers/runc#4411]
After merged #4409, the CI was always failed for arm64:
```
/bin/bash: line 1: bats: command not found
```

https://github.com/opencontainers/runc/actions/runs/11019452323/job/30602054521

And there are many warnings for all platform when setup bats:
```
/usr/bin/tar: ../../../../../usr: Cannot mkdir: Permission denied
```

**Comment by lifubang** [comment]
@akhilerm Could you have some suggestions?

**Comment by lifubang** [comment]
There are 2 problems:
1. Known cache issue: https://github.com/bats-core/bats-action/issues/9#issuecomment-2138032932 .
2. It seems like that there is no architecture in bats cache key. So if the bats binary has cached in amd64, it can't work on arm64 after restored from the cache.
https://github.com/bats-core/bats-action/blob/main/action.yaml#L112

If the second problem is true, I think we should revert #4409 or open an issue in https://github.com/bats-core/bats-action ?

**Comment by akhilerm** [comment]
I think second problem is there, but I am still curious why we didnt hit it in the CI for the PR.  Will raise an issue in bats-action to fix the same.

**Comment by lifubang** [comment]
> but I am still curious why we didnt hit it in the CI for the PR.

For the first time, there is no cache:
```
Cache not found for input keys: Linux-bats-1.9.0
```

**Comment by lifubang** [comment]
> Will raise an issue in bats-action to fix the same.

Thanks, please help to do this, if the next release is coming soon, it will be better.

**Comment by akhilerm** [comment]
Ref: https://github.com/bats-core/bats-action/issues/16

**Comment by akhilerm** [comment]
We might hit this issue in the next release https://github.com/bats-core/bats-action/issues/18, as we have ubuntu-20.04 runners.

**Comment by brokenpip3** [comment]
> There are 2 problems:
> 
>     1. Known cache issue: [bats-action: generates warnings trying to untar the cache bats-core/bats-action#9 (comment)](https://github.com/bats-core/bats-action/issues/9#issuecomment-2138032932) .
> 
>     2. It seems like that there is no architecture in bats cache key. So if the bats binary has cached in amd64, it can't work on arm64 after restored from the cache.
>        https://github.com/bats-core/bats-action/blob/main/action.yaml#L112
> 
> 
> If the second problem is true, I think we should revert #4409 or open an issue in https://github.com/bats-core/bats-action ?

for problem 1: the cache issue it's only for the libraries since we always use home local directory for bats.
If you don't need the libraries you should not hit that, you can disable the installation of those. If instead you need some of the bats libraries you can put them in a home directory and expose the BATS_LIB_PATH env to that directory, see this [example](https://github.com/jenkinsci/kubernetes-operator/blob/e40032497b9bea6bc5070b35c31f133d6b364447/.github/workflows/auto-tests-bats.yaml#L48-L54).

**Comment by brokenpip3** [comment]
https://github.com/bats-core/bats-action/issues/18#issuecomment-2374234510 :)
