### ISSUE TITLE
How to get the information about the CPU or memory used?

### ISSUE THREAD

**Issue by Miloas** [opencontainers/runc#442]
I know that docker can find these information from `/sys/fs/cgroup/cpu/system.slice/docker-$FULL_CONTAINER_ID.scope/`,
but how I get it in runc?

**Comment by rajasec** [comment]
Did you had chance to try with runc events commands which gives the usage statistics.

**Comment by Miloas** [comment]
@rajasec I know that , but I want get the information when the process finished, because I want get the max memory used. Do you have some good idea? Thanks for your reply.
