### ISSUE TITLE
CgroupParent attaches to incorrect slice with cgroupfs driver

### ISSUE THREAD

**Issue by cyphar** [opencontainers/runc#450]
On SUSE Linux Enterprise 12 (I'm working on getting this to be reproducible on other systems), the commit 4445a0050d1a28bc5c6e612baebc3854cbc2b52c causes the following bug:

Upon creating a new slice, activating it and attempting to join the container under the slice, the `cpuacct` cgroup joined is not correct. Reverting 4445a0050d1a28bc5c6e612baebc3854cbc2b52c (or 2b28b3c2769c4b0519889bfad1ebb2db37b13469, which is the same commit) fixes the bug.

```
% cat test.slice
[Unit]
Description=Test Docker Slice
DefaultDependencies=no
Before=slices.target

[Slice]
CPUShares=1337
MemoryLimit=777M
# cp test.slice /usr/lib/systemd/system/test.slice
# systemctl start test.slice
% docker run -d --cgroup-parent="test.slice/docker" --cpu-shares 127 --memory 50m alpine sleep 30000
<id>
%
```

If you check which cgroups the new container was attached to, the wrong `cpuacct` cgroup was attached to:

```
% cat /sys/fs/cgroups/memory/test.slice/docker/<id>/cgroup.procs
<pid>
% cat /sys/fs/cgroups/blkio/test.slice/docker/<id>/cgroup.procs
<pid>
```

Those are fine (they've attached to the correct slice). However, `cpuacct` was attached to the incorrect one (note the extra `user.slice` at the beginning, sometimes this is `system.slice`, which is odd):

```
% cat /sys/fs/cgroups/cpuacct/user.slice/test.slice/docker/<id>/cgroup.procs
<pid>
```

While I'm using `docker` commands above, after a very long set of bisects, the bug was caused by docker/docker@c22b292719b443ff2fcac646aa263d5a5b10025e (which is a vendor commit bringing in the above `libcontainer` commit).

Yes, I have tested this with `master` and it isn't fixed there either.

/cc @LK4D4 (who wrote the commit)

**Comment by cyphar** [comment]
This patch "fixes" the problem, but I'd rather like to know what problem @LK4D4 was solving with 4445a0050d1a28bc5c6e612baebc3854cbc2b52c. I have a feeling the solution is probably more subtle.

```diff
From 102d98ea4985ceecb4d5d223137156b0189bfe2e Mon Sep 17 00:00:00 2001
From: Aleksa Sarai <asarai@suse.com>
Date: Wed, 30 Dec 2015 20:21:49 +1100
Subject: [PATCH] cgroups: fs: fix setting of cgroup parent

Using cgroups.GetThisCgroupDir causes --cgroup-parent=<path> to cause
cpuacct to join the incorrect slice due to the root cgroup path being a
user slice.

Signed-off-by: Aleksa Sarai <asarai@suse.com>
---
 libcontainer/cgroups/fs/apply_raw.go | 5 +----
 1 file changed, 1 insertion(+), 4 deletions(-)

diff --git a/libcontainer/cgroups/fs/apply_raw.go b/libcontainer/cgroups/fs/apply_raw.go
index 0c4d207ee741..c5dd4731384a 100644
--- a/libcontainer/cgroups/fs/apply_raw.go
+++ b/libcontainer/cgroups/fs/apply_raw.go
@@ -246,10 +246,7 @@ func getCgroupData(c *configs.Cgroup, pid int) (*cgroupData, error) {
 }
 
 func (raw *cgroupData) parentPath(subsystem, mountpoint, root string) (string, error) {
-       // Use GetThisCgroupDir instead of GetInitCgroupDir, because the creating
-       // process could in container and shared pid namespace with host, and
-       // /proc/1/cgroup could point to whole other world of cgroups.
-       initPath, err := cgroups.GetThisCgroupDir(subsystem)
+       initPath, err := cgroups.GetInitCgroupDir(subsystem)
        if err != nil {
                return "", err
        }
-- 
2.6.4

```

**Comment by cyphar** [comment]
For reference, `/proc/<docker>/cgroup` is:

```
10:hugetlb:/
9:perf_event:/
8:blkio:/
7:freezer:/
6:devices:/
5:memory:/
4:cpuacct,cpu:/
3:cpuset:/
2:name=systemd:/system.slice/docker.service
```

**Comment by hqhq** [comment]
@cyphar Did you just confirmed that the whole issue is a bug in SLE?

The direct reason is the <docker> process is in a different cpu cgroup than other cgroup subsystems, but no idea why it happens only after docker service started.

And the commit @LK4D4 committed fixed the problem as the commends declared, it's a use case when users are using docker-in-docker and with host-shared pid namespace.

**Comment by cyphar** [comment]
@hqhq I'm still looking into it, but AFAICS I can't reproduce this weird behaviour from systemd on other systems. In either case, I can't see how Docker could be causing this (it's just reacting to `/proc/self/cgroup` as it should, and all other processes managed by systemd have the same behaviour).

I'm going to close this, since it looks like it's a bug on our side. Sorry about that.
