### ISSUE TITLE
Create session key for container

### ISSUE THREAD

**Issue by stefanberger** [opencontainers/runc#453]
I think a session key should be created for each container. At the moment even user-namespace enabled containers inherit the session key from the docker daemon. And then it is possible to clear that session key:

In container:

[root@68fed98d59e0 /]# keyctl show
Session Keyring
 415001033 --alswrv  65534 65534  keyring: _ses
 534719530 ---lswrv  65534 65534   \_ keyring: _uid.0
[root@68fed98d59e0 /]# keyctl clear 415001033
[root@68fed98d59e0 /]# keyctl show
Session Keyring
 415001033 --alswrv  65534 65534  keyring: _ses

On host:

# Before clearing inside container:
[root@foo docker]# keyctl show
Session Keyring
 415001033 --alswrv      0     0  keyring: _ses
 534719530 --alswrv      0 65534   \_ keyring: _uid.0

# After clearing inside container
[root@foo docker]# keyctl show
Session Keyring
 415001033 --alswrv      0     0  keyring: _ses

A simple fix seems to be to add 

syscall.Syscall(syscall.SYS_KEYCTL,1 , 0, 0)

to standard_init_linux.go's Init() function. '1' means: 

#define KEYCTL_JOIN_SESSION_KEYRING     1       /* join or start named session keyring */

See also: http://lxr.free-electrons.com/source/include/uapi/linux/keyctl.h#L38

This then leads to the following keyring in the container (_uid.1000 is missing unfortunately; 1000 is remapped user)

[root@763f16610123 /]# keyctl show
Session Keyring
 726122311 --alswrv      0     0  keyring: _ses

On host:

[root@foo ~]# keyctl show
Session Keyring
 984221826 --alswrv      0     0  keyring: _ses
 871135891 --alswrv      0 65534   \_ keyring: _uid.0

Regards,
   Stefan

**Comment by stefanberger** [comment]
For the above: I built docker 588fedef using the following command line:

# AUTO_GOPATH=1 DOCKER_BUILDTAGS="experimental" LD_LIBRARY_PATH=/lib64 hack/make.sh dynbinary

I am running it as follows:

./bundles/latest/dynbinary/docker daemon --userns-remap 1000:1000

On F22 with docker-1.8.2-7 I see two containers share the key rings. both were started with the command line 'docker run --ti --rm fedora /bin/bash'

(dnf -y install keyutils to install keyctl)

[root@541d1baa84d1 /]# keyctl show
Session Keyring
 180789246 --alswrv      0 65534  keyring: _uid_ses.0
 890149067 --alswrv      0 65534   \_ keyring: _uid.0
  74772948 --alswrv      0     0       \_ keyring: foobar

[root@587efd0b1b7d /]# keyctl show
Session Keyring
 180789246 --alswrv      0 65534  keyring: _uid_ses.0
 890149067 --alswrv      0 65534   \_ keyring: _uid.0
  74772948 --alswrv      0     0       \_ keyring: foobar


I think two containers should not share them. Maybe someone else should try it as well. With SELinux (sVirt) enabled, at least /proc/keys is inaccessible but keyctl still works.

**Comment by jfrazelle** [comment]
With seccomp support we block all kernel keyring  interactions

**Comment by jfrazelle** [comment]
This is in the default profile.

**Comment by stefanberger** [comment]
What am I doing wrong in the Fedora 22 setup?

**Comment by jfrazelle** [comment]
Seccomp was just merged and will be in 1.10 but you can try in master or experimental sorry I should have mentioned that

**Comment by jfrazelle** [comment]
This might help and feel free to mention any others https://github.com/jfrazelle/docker/blob/seccomp-docs/docs/security/seccomp.md

**Comment by stefanberger** [comment]
I hadn't played with the seccomp profile yet. So that's good. Though I think that a new session key should still be created just in case someone doesn't run the seccomp profile.

**Comment by jfrazelle** [comment]
Totally ya could be a cool feature of people want that ability in containers as well :)

**Comment by jfrazelle** [comment]
I see you commenting, thanks :), if you have opinions on what should or
should not be whitelisted as well let me know or open a PR, the default
profile is here
https://github.com/docker/docker/blob/master/daemon/execdriver/native/seccomp_default.go
thanks!!

**Comment by mrunalp** [comment]
@stefanberger No objections to adding this. Would you contribute the code for this feature?

**Comment by stefanberger** [comment]
@mrunalp PR sent.
