### ISSUE TITLE
Container restored with `runc restore` loses running processes

### ISSUE THREAD

**Issue by ssoor** [opencontainers/runc#4541]
### Description

A simple container, the startup process is sleep 60s, there is no error when executing `runc checkpoint` and `runc restore`, but there is no find `sleep 60s` process after `runc restore` is executed

### Steps to reproduce the issue

1. Run `docker export $(docker create busybox) | tar -C rootfs -xvf -` and run `runc spec`
2. Modify process.terminal=false and process.args=["sleep","60s"] in config.json
3. Execute the following shell script

``` shell
#!/bin/sh
/usr/bin/runc delete test

tty=$(tty)
exec >/dev/null
exec 2>/dev/null
exec </dev/null
/usr/bin/runc create --bundle $PWD test
exec 2>$tty
exec >$tty
exec <$tty

/usr/bin/runc start test
ps -aux | grep sleep
echo

runc checkpoint test
runc restore test
ps -aux | grep sleep
```

### Describe the results you received and expected

Current result: not find `sleep 60s` process
```shell
root      133124  0.0  0.0   4280   404 ?        Ss   14:27   0:00 sleep 60s
root      133137  0.0  0.0   9292  2252 pts/11   S+   14:27   0:00 grep sleep

root      133219  0.0  0.0   9292  2232 pts/11   S+   14:27   0:00 grep sleep
```
Expected result: `sleep 60s` process is running
```shell
root      133124  0.0  0.0   4280   404 ?        Ss   14:27   0:00 sleep 60s
root      133137  0.0  0.0   9292  2252 pts/11   S+   14:27   0:00 grep sleep

root      133124  0.0  0.0   4280   404 ?        Ss   14:27   0:00 sleep 60s
root      133219  0.0  0.0   9292  2232 pts/11   S+   14:27   0:00 grep sleep
```

### What version of runc are you using?

```shell
root@core:/mnt/source_code/dev/runc_test# runc --version
runc version 1.2.2
commit: v1.2.2-0-g7cb36325
spec: 1.2.0
go: go1.22.4
libseccomp: 2.5.3
```

### Host OS information
```shell
root@core:/mnt/source_code/dev/runc_test# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
### Host kernel information
```shell
root@core:/mnt/source_code/dev/runc_test# uname -a
Linux core 5.15.0-126-generic #136-Ubuntu SMP Wed Nov 6 10:38:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ssoor** [comment]
I checked the container list and could not find the container in the container list after `runc restore` .
```shell
runc list
runc checkpoint test
runc list
runc restore test
runc list
```
result:
```shell
ID          PID         STATUS      BUNDLE                           CREATED                          OWNER
test        137419      running     /mnt/source_code/dev/runc_test   2024-11-23T14:40:10.523808475Z   root
ID          PID         STATUS      BUNDLE      CREATED     OWNER
ID          PID         STATUS      BUNDLE      CREATED     OWNER
```

**Comment by ssoor** [comment]
I modified the shell script in step 3 and asked it to output information to get what happened. From the result, it can be seen that the executing `sleep 10s` process was directly terminated, but the exit code of the process is still unclear why.

New script
```shell
#!/bin/sh
/usr/bin/runc delete test

nohup recvtty ./test.sock >>./test_console.log&
nohup recvtty ./test2.sock >>./test_console.log&

CONSOLE_SOCKET=$PWD/test.sock
/usr/bin/runc create --bundle $PWD --console-socket "$CONSOLE_SOCKET" test
/usr/bin/runc start test

ps -aux | grep sleep

runc checkpoint test
CONSOLE_SOCKET=$PWD/test2.sock
runc restore -d --console-socket "$CONSOLE_SOCKET" test
runc list
ps -aux | grep sleep
```

result：
```shell
root@core:/mnt/source_code/dev/runc_test# ./run_tty.sh
nohup: redirecting stderr to stdout
nohup: redirecting stderr to stdout
root       77698  0.0  0.0   4412   396 pts/0    Ss+  03:38   0:00 sh -c echo starting...; sleep 10s;echo "10s $?";sleep 8s;echo "8s $?";echo stoping...;
root       77710  0.0  0.0   9292  2276 pts/13   S+   03:38   0:00 grep sleep
root       77711  0.0  0.0   4280   392 pts/0    S+   03:38   0:00 sleep 10s

ID          PID         STATUS      BUNDLE                           CREATED                          OWNER
test        77764       running     /mnt/source_code/dev/runc_test   2024-11-24T03:38:01.417947462Z   root
test1       16718       running     /mnt/source_code/dev/runc_test   2024-11-24T02:10:51.436707406Z   root
root       77764  0.0  0.0   4412   148 pts/0    Ss+  03:38   0:00 sh -c echo starting...; sleep 10s;echo "10s $?";sleep 8s;echo "8s $?";echo stoping...;
root       77793  0.0  0.0   4280   392 pts/0    S+   03:38   0:00 sleep 8s
root       77807  0.0  0.0   9292  2328 pts/13   S+   03:38   0:00 grep sleep
···

**Comment by cyphar** [comment]
What version of `criu` do you have?

**Comment by kolyshkin** [comment]
I tried to reproduce this but couldn't.

```console
root@kir-tp1:/home/kir/git/runc/tst# ./runc exec 1234 ps ax
PID   USER     TIME  COMMAND
    1 root      0:00 sleep infinity
    7 root      0:00 ps ax
root@kir-tp1:/home/kir/git/runc/tst# ./runc exec 1234 ls -l /proc/1/fd
total 0
lrwx------    1 root     root            64 Dec  7 00:02 0 -> /dev/null
lrwx------    1 root     root            64 Dec  7 00:02 1 -> /dev/null
lrwx------    1 root     root            64 Dec  7 00:02 2 -> /dev/null
root@kir-tp1:/home/kir/git/runc/tst# ./runc checkpoint 1234
root@kir-tp1:/home/kir/git/runc/tst# ./runc exec 1234 ps ax
ERRO[0000] exec failed: container does not exist        
root@kir-tp1:/home/kir/git/runc/tst# ./runc restore -d 1234
root@kir-tp1:/home/kir/git/runc/tst# ./runc exec 1234 ps ax
PID   USER     TIME  COMMAND
    1 root      0:00 sleep infinity
   23 root      0:00 ps ax
```

This was using runc from git head (although I got the same results with runc 1.2.2) with criu 4.0 on a Fedora 41 machine.

Container spec is default one (`runc spec`) with
 - "terminal" changed from `true` to `false`
 - "args" changed from `"sh"` to `"sleep", "infinity"`
 
 Container rootfs is some version of busybox.
 
 The only thing I can think of, 10s is not too much time and if you're doing it by hand the sleep might be finished by the time you restore. So, maybe run something different than `sleep 10s` or at least increase the time.

**Comment by ssoor** [comment]
I'm very sorry. I was busy with other things recently and didn't have time to reply. I just tried to reproduce it on my system, but it didn't work. It may be related to the system status at that time. I installed and upgraded the software packages during this period. Now it has returned to normal. I'm sorry for taking up everyone's time.

> I tried to reproduce this but couldn't.
> 
> ```
> root@kir-tp1:/home/kir/git/runc/tst# ./runc exec 1234 ps ax
> PID   USER     TIME  COMMAND
>     1 root      0:00 sleep infinity
>     7 root      0:00 ps ax
> root@kir-tp1:/home/kir/git/runc/tst# ./runc exec 1234 ls -l /proc/1/fd
> total 0
> lrwx------    1 root     root            64 Dec  7 00:02 0 -> /dev/null
> lrwx------    1 root     root            64 Dec  7 00:02 1 -> /dev/null
> lrwx------    1 root     root            64 Dec  7 00:02 2 -> /dev/null
> root@kir-tp1:/home/kir/git/runc/tst# ./runc checkpoint 1234
> root@kir-tp1:/home/kir/git/runc/tst# ./runc exec 1234 ps ax
> ERRO[0000] exec failed: container does not exist        
> root@kir-tp1:/home/kir/git/runc/tst# ./runc restore -d 1234
> root@kir-tp1:/home/kir/git/runc/tst# ./runc exec 1234 ps ax
> PID   USER     TIME  COMMAND
>     1 root      0:00 sleep infinity
>    23 root      0:00 ps ax
> ```
> 
> This was using runc from git head (although I got the same results with runc 1.2.2) with criu 4.0 on a Fedora 41 machine.
> 
> Container spec is default one (`runc spec`) with
> 
> * "terminal" changed from `true` to `false`
> * "args" changed from `"sh"` to `"sleep", "infinity"`
> 
> Container rootfs is some version of busybox.
> 
> The only thing I can think of, 10s is not too much time and if you're doing it by hand the sleep might be finished by the time you restore. So, maybe run something different than `sleep 10s` or at least increase the time.
