### ISSUE TITLE
Add non-recursive GetPids?

### ISSUE THREAD

**Issue by jimmidyson** [opencontainers/runc#457]
We are migrating from `docker/libcontainer` to here & one issue for us is the implementation of `GetPids` is now recursive. In Kubernetes we use this project's cgroups functionality to get pids from a particular cgroup & move (`Apply`) them to another one, but we don't want to do this recursively.

How would you feel in adding a non-recursive `GetPids`? Pretty trivial implementation wise, but not sure how you'd feel about that?

**Comment by LK4D4** [comment]
It sounds ok to me. Recursive behavior is not very common for such func.

**Comment by jimmidyson** [comment]
It was your PR (#330) that made it recursive :stuck_out_tongue_winking_eye: 

So how do you want to proceed? I'd prefer `GetPids` to be non-recursive & users walk the cgroup hierarchy themselves if they want to get pids from all sub-cgroups, but changing that functionality back to how it was would impact on existing users of the new `GetPids` (including Docker afaik). I can put in a PR for this if you let me know how you want to proceed.

**Comment by vishh** [comment]
Or we can provide both alternatives - `GetPids` and `GetAllPids` maybe?

**Comment by LK4D4** [comment]
@vishh +1

**Comment by vishh** [comment]
Ok. I'll send a patch in a bit. Hopefully @jimmidyson hasn't started working on a patch already.

**Comment by jimmidyson** [comment]
I'm nearly done tbh.

**Comment by vishh** [comment]
@jimmidyson: :+1:
