### ISSUE TITLE
Question: difference between SelinuxGetEnforce/SelinuxGetEnforceMode

### ISSUE THREAD

**Issue by ahmetalpbalkan** [opencontainers/runc#460]
Hi, in the `libcontainer/selinux` package, I'm trying to understand what are the `SelinuxGetEnforce`/`SelinuxGetEnforceMode` meant for?

It appears like one is parsing `/etc/selinux/config` and the other one is reading `/sys/fs/selinux/enforce`. What's the difference between these two in usage? Thanks in advance.

https://github.com/opencontainers/runc/blob/master/libcontainer/selinux/selinux.go#L234-L257
```go
func SelinuxGetEnforce() int {
	var enforce int

	enforceS, err := readCon(fmt.Sprintf("%s/enforce", selinuxPath))
	if err != nil {
		return -1
	}

	enforce, err = strconv.Atoi(string(enforceS))
	if err != nil {
		return -1
	}
	return enforce
}

func SelinuxGetEnforceMode() int {
	switch readConfig(selinuxTag) {
	case "enforcing":
		return Enforcing
	case "permissive":
		return Permissive
	}
	return Disabled
}
```
cc:@rhatdan

**Comment by rhatdan** [comment]
GetEnforce tells you the current state of the machine

At a shell you can type
```
# getenforce 
Enforcing
# setenforce 0
# getenforce 
Permissive
# setenforce 1
```

GetEnforceMode tells you the default state of the system, or basically what happens if you rebooted the machine.  

```
# grep ^SELINUX= /etc/selinux/config 
SELINUX=enforcing
```

**Comment by crosbymichael** [comment]
Closing as resolved.

Thanks!

**Comment by ahmetalpbalkan** [comment]
Thanks for answer @rhatdan. I believe one of them are unused anywhere, can't recall which one. In case we have concerns about unused code, I think this might be an instance.
