### ISSUE TITLE
Using libcontainer on LXC container

### ISSUE THREAD

**Issue by kimh** [opencontainers/runc#464]
Currently I'm using Docker on LXC container but Docker v1.10 will remove the support for LXC exec driver. To keep using Docker on LXC, I'm looking for the possibility to use libcontainer on LXC container.

It seems libcontainer doesn't work on LXC container so far, though. I've tried using libcontainer on priv container, but got some issues with cgroup which is probably because libcontainer only supports cgroupfs but not cgmanager which is used on LXC container. I would guess there are other things that don't work. Also, my ultimate goal is using libcontainer on non-priv container but this maybe not possible.

So here are my questions:

- What are the high level requirements for using libcontainer on priv LXC container?
- Is it technically possible to use libcontainer on non-priv LXC container as well?

**Comment by ashahab-altiscale** [comment]
Libcontainer and lxc does the same thing(unshare and setns). Do you mean using docker with libcontainer, or using lxc as an opencontainer implementation?

**Comment by kimh** [comment]
>Libcontainer and lxc does the same thing(unshare and setns).

Yes, I understood this.

>Do you mean using docker with libcontainer, or using lxc as an opencontainer implementation?

I think it's more like the former. I want to run Docker with libcontainer exec driver **on LXC container**, not on normal Linux host. Does this make sense??

**Comment by crosbymichael** [comment]
This is possible but it has to do with your lxc container configuration more than anything else.  Closing this as it is not a runc issue or something that we can fix.  You could try asking in IRC if anyone has experience with this type of task.
