### ISSUE TITLE
New tag please

### ISSUE THREAD

**Issue by jimmidyson** [opencontainers/runc#467]
@LK4D4 Now that #446 has been merged would really appreciate a tag when you get a chance so we can pull latest changes into cadvisor/kubernetes. Thanks in advance!

**Comment by cyphar** [comment]
We shouldn't tag until the issues in #470 are resolved (upstream Docker test cases fail on `master`). #470 solves the problem, but unfortunately it requires reverting a large patchset, so we're trying to resolve the underlying issue without reverting a feature.

**Comment by cyphar** [comment]
Update: #499 fixes the only (AFAIK) remaining issue before we can tag.

**Comment by LK4D4** [comment]
I'll try master with docker and if everything is ok will make a tag.

**Comment by LK4D4** [comment]
@jimmidyson I created v0.0.7

**Comment by jimmidyson** [comment]
@LK4D4 Thanks!

**Comment by jimmidyson** [comment]
@LK4D4 You forgot to bump version in [`main.go`](https://github.com/opencontainers/runc/blob/master/main.go#L13)

**Comment by LK4D4** [comment]
@jimmidyson crap, thanks :)
