### ISSUE TITLE
userns GidMappings for AdditionalGroups

### ISSUE THREAD

**Issue by jfrazelle** [opencontainers/runc#469]
I am unsure if the following is a specific design decision or not.

**Current Behavior**:
Running a container with userns & additional groups does NOT add GidMappings for the AdditionalGroups

**Possible Expected Behavior**:
Running container with userns & additional groups adds the additional groups as GidMappings to the group on the host.

Now I obviously understand how behavior 2 could have been avoided on purpose, but I also understand how someone (me) might think it should do this. Honestly I am torn between the two and just wondering what the intention is.

If the answer is #2, I have a patch :innocent: but this opens a new question should the patch modify the file libcontainer/container_userns_linux.go or is this something docker should do before even passing the config to libcontainer?

**Comment by jfrazelle** [comment]
ping @estesp @LK4D4 @crosbymichael

**Comment by jfrazelle** [comment]
As a sample use case, I would assume `--group-add audio` would map to audio group on the host, otherwise really what good is it, but also i understand how this might not be desirable, and maybe additional groups should be diabled w userns

**Comment by tianon** [comment]
The rationale for how that particular mapping works is that `--user nobody:audio` maps both those names within the container, so `--group-add` not doing so would be inconsistent; the way I get around this when I really want `xyz` on my host is to use tools like `id` (ie, `id -u nobody` to get the UID of `nobody` on my host, or `getent group audio | cut -d: -f3` to get the GID of `audio` on my host).

**Comment by jfrazelle** [comment]
My patch works super well ;) I am using it to watch a youtube in a userns-ed chrome container hehe

**Comment by jfrazelle** [comment]
it creates a `gid_map` like:
```
$ sudo cat /proc/8540/gid_map 
         0     886432         28
        30     886461      65506
        29         29          1
```

**Comment by estesp** [comment]
> I am using it to watch a youtube in a userns-ed chrome container hehe

This warms my user namespace heart :) And is also something only @jfrazelle would say, so it proves you haven't been hacked..

**Comment by jfrazelle** [comment]
ah i see @tianon's comment...

**Comment by jfrazelle** [comment]
closing I got what i needed and more :)
