### ISSUE TITLE
AppArmor issue with libcontainer on LXC privilege container

### ISSUE THREAD

**Issue by kimh** [opencontainers/runc#483]
Related with https://github.com/opencontainers/runc/issues/464, I'm trying to use libcontainer on priv LXC  container. More specifically, I'm trying to run https://github.com/kimh/libcontainer-example on priv LXC container.

I'm encountering several issues but right now I'm blocked by one error and I run out of ideas how to debug further.

Here is the error I'm getting now.

```
$ ROOTFS=$(pwd)/rootfs go run main.go
WARN[0000] signal: killed
[9] System error: could not synchronise with container process
exec: Wait was already called
signal: killed
done
```

This works if I disable `lxc-container-default` AppArmor profile on LXC host machine. It also works if I add `lxc.aa_profile = unconfined` to the LXC config of the container. So, apparently the issue is something to do with AppArmor.

However, I don't get any audit logs from AppArmor while getting the error. From the error, I know I'm hitting https://github.com/opencontainers/runc/blob/master/libcontainer/process_linux.go#L262 but I'm not sure how it's related to AppArmor.

Could anyone give me a pointer to how I can investigate further?

Here is [config.json](https://github.com/kimh/libcontainer-example/blob/master/config.json).
Here is [main.go](https://github.com/kimh/libcontainer-example/blob/master/main.go).

**Comment by kimh** [comment]
hi, it would be great if anyone can take a look at this. thanks!

**Comment by crosbymichael** [comment]
It is possible but you are going to have to give it all capabilities, no device restrictions, and mess with the settings alot to see what works.  Also you need the container to be unconfined.  Closing as this really is not any issue for runc but how you are configuring your outside containers.
