### ISSUE TITLE
integration tests for runc cli with bats

### ISSUE THREAD

**Issue by jfrazelle** [opencontainers/runc#485]
How do you feel about this, we could run them in a container :) I don't mind setting up all the initial scripts etc ;)

**Comment by hqhq** [comment]
That would be great, I'm totally +1 on this. :+1:

**Comment by mrunalp** [comment]
Sounds good!

**Comment by mikebrow** [comment]
Are you talking about the TAP compliant bash testing tool https://github.com/sstephenson/bats ?
I can help :-)

**Comment by mikebrow** [comment]
#dibs

**Comment by cyphar** [comment]
This was done in #659.
