### ISSUE TITLE
Add support for Cgroup.DeniedDevices and Cgroup.AllowAllDevices

### ISSUE THREAD

**Issue by mlaventure** [opencontainers/runc#498]
Although defined in `libcontainer/configs/cgroup_unix.go`, it is currently not possible to set neither `Cgroup.DeniedDevices` nor `Cgroup.AllowAllDevices`.

Likewise, the `DefaultAutoCreatedDevices` variable is never acted upon, meaning `/dev/fuse` is never created.

This will probably require a modification of the specs as it only allows listing devices that shall be both created AND allowed within the linux `runtime.json` ([see here] (https://github.com/opencontainers/specs/blob/master/runtime_config_linux.go#L34))

**Comment by crosbymichael** [comment]
This is closed by the spec bump
