### ISSUE TITLE
C/R on shared-Namespace container won't work properly

### ISSUE THREAD

**Issue by x1022as** [opencontainers/runc#502]
This is how I produce this:

1. create contA
```docker run -ti --name contA ubuntu bash```
2. create contB which will share ipc with contA, echo ipcs every 2 sec
```docker run --name contB --ipc container:contA ubuntu bash -c "while true; do ipcs -q; sleep 2; done"```
3. docker logs -f contB and get the output
4. in conA, perform ```ipcmk -Q```,  check contB logs, we will get the new message queue
5. perform Checkpoint/Restore on contB
6. create new ipc message queue in contA

result: after C/R, the NS-share relationship between contA and contB seem break. contB cannot see the new-added message queue .

docker C/R seems fail to restore the namespace, any idea how to deal with this? not sure if this is a criu or runc problem.

for further thought, if I migrate contA + contB (like a Pod) to another host, how to reserve the NS-relationship between them.

**Comment by mrunalp** [comment]
@avagin ping

**Comment by avagin** [comment]
Shared-namespaces are not supported by CR now. I will try to fix it in a near future. Thanks.

**Comment by x1022as** [comment]
thanks, @avagin I am just wondering this would be done by docker or criu, in my opinion it will be difficult for criu to achieve this for across-host migration.

**Comment by crosbymichael** [comment]
Closing as this is an issue and something that has to be developed in criu and nothing we can do at the moment in runc to support this. 

I think as a general rule for C/R, if you want it to be robust you need to keep things simple and sharing namespaces between containers introduces a lot of other issues for migration.
