### ISSUE TITLE
runc kill not working

### ISSUE THREAD

**Issue by qiancai** [opencontainers/runc#519]
Using a RHEL7.2 image includes "sleep 1000" as the PID 1 below, runc kill failed to kill it. 

        "process": {
                "terminal": true,
                "user": {
                        "uid": 0,
                        "gid": 0
                },
                "args": [
                        "sleep", "1000"
                ],
                "env": [
                        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                        "TERM=xterm"
                ],
                "cwd": "/"
        },

 # runc start (in one terminal)
 # runc kill (in another terminal)
runc is still running.

runc kill KILL was fine. Tried also with terminal set to false without luck. 

Tested on the master at commit f22a4fd5baad72a1da7ec91273872ff071b8750d .

state.json is attached.
[state.json.txt](https://github.com/opencontainers/runc/files/107184/state.json.txt)

**Comment by crosbymichael** [comment]
Sleep does not respond to a TERM, which is `kill`'s default.  You can do `runc kill 9` to send a SIGKILL that will terminate sleep.

**Comment by qiancai** [comment]
May I ask how to decide which command respond to TERM which are not? Since sleep can be killed without runc.

 # sleep 1000
 # kill 16217
 # sleep 1000
Terminated

**Comment by qiancai** [comment]
I also tried bash and it can't be killed with TERM as well.
