### ISSUE TITLE
hooks seems not working as expected

### ISSUE THREAD

**Issue by qiancai** [opencontainers/runc#520]
In config.json,

```
        "process": {
                "terminal": true,
                "user": {
                        "uid": 0,
                        "gid": 0
                },
                "args": [
                        "top"

```

In runtime.json,

```
        "hooks": {
                "prestart": [
                    {
                        "path": "/bin/touch",
                        "args": ["touch", "/root/prestart"]
                    }
                ],
                "poststart": [
                    {
                        "path": "/bin/touch",
                        "args": ["touch", "/root/poststart"]
                    }
                ]
```

`# runc --debug --log=/tmp/runcup.log start`
It returns immediately without showing top in a terminal.

```
# cat /tmp/runcup.log
WARN[0000] signal: killed                               
FATA[0000] Container start failed: [10] System error: write |1: broken pipe
```

Both files were created in host's /root directory rather than in the container's filesystem.

Running on the master branch at commit f22a4fd5baad72a1da7ec91273872ff071b8750d .

**Comment by mrunalp** [comment]
Hooks are run in the host namespaces. You have to make them join the container's namespaces. For e.g. checkout https://github.com/mrunalp/hooks

**Comment by wking** [comment]
On Wed, Jan 27, 2016 at 02:42:31PM -0800, Mrunal Patel wrote:
> Hooks are run in the host namespaces…

I'd really like to get docs for that landed in the spec.  For example,
see:

  The only important difference seems to be “hook processes are
  executed from the runtime namespace” [4,5,6].

in [1].  As I pointed out in those references, I think docs for the
hook namespace are currently blocking on landing an approved name for
the host namespace, which is in flight here [2].

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/Cn5L6g1prgA
     Subject: Unify container-process and hook-process structures
     Date: Mon, 4 Jan 2016 21:56:37 -0800
     Message-ID: <20160105055637.GG6362@odin.tremily.us>
[2]: https://github.com/opencontainers/specs/pull/275/files#diff-f07b73835a21496fc01afa719cfd3ba4R29

**Comment by qiancai** [comment]
Not sure if I said it clearly. The issue I saw was that once I specified poststart hook, the user specific command (in this case, "top") seems did not run at all, and the container was killed immediately.

**Comment by wking** [comment]
So both hooks ran, but there's some buggy runC container-process invocation when a poststart hook is set.  If you use a simpler container process (e.g. `echo hello`) and unset `process.terminal`, does it work as expected?

**Comment by qiancai** [comment]
Same error using "echo hello" as user specific command and set process.terminal to false.

```
# runc --debug --log=/tmp/runcup.log start
# cat /tmp/runcup.log 
WARN[0000] signal: killed                               
FATA[0000] Container start failed: [10] System error: write |1: broken pipe
```

**Comment by qiancai** [comment]
This is working fine now.
