### ISSUE TITLE
config: Single, unified config file

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/runc#528]
Per the changes to the spec... we need to move to a single config file see: 
https://github.com/opencontainers/specs/pull/284

**Comment by mikebrow** [comment]
Working on it...

**Comment by crosbymichael** [comment]
Once we cut the spec 0.3 we can update runc and do a release with this change

**Comment by mikebrow** [comment]
Sounds like a plan..   FYI I have it working on my box can rebase and do a PR when needed.

**Comment by crosbymichael** [comment]
@mikebrow this is the commit that you should update from the specs repo:

25cbfc427ba6154016f33c7ed1b8ed43b8b7b7ed

**Comment by mikebrow** [comment]
Thx, I've pulled down that version of the specs.. and moved it via godep to my godeps/ tree.  I see I have a couple things to do to get a workable solution with the changes to permissions for devices that have now moved in the spec to a whitelist in resoures { devices { devicecgroup.access ... Should make for a fun friday.
