### ISSUE TITLE
Cannot open /dev/mem

### ISSUE THREAD

**Issue by rakyll** [opencontainers/runc#533]
CAP_SYS_RAWIO is added to the capabilities.
```
"linux": {
		"capabilities": [
			"CAP_SYS_RAWIO",
			"CAP_AUDIT_WRITE",
			"CAP_KILL",
			"CAP_NET_BIND_SERVICE"
		]
	}
```

Mounting /dev/mem.
```
"mounts": [
		...
		{
			"name": "/dev/mem",
			"path": "/dev/mem"
		},
```

runtime.json for the mount:

```
                "/dev/mem": {
                        "type": "bind",
                        "source": "/dev/mem",
                        "options": [
                                "rw",
                                "sync",
                                "bind"
                        ]
                },
```

I cannot open the device in the container.
```
# cat /dev/mem
cat: can't open '/dev/mem': Operation not permitted
```

It would be great to have documentation with reference code how to mount /dev/mem.

**Comment by crosbymichael** [comment]
Instead of bind mounting the device inside your container you should add it to the devices list then it will also have the device permissions on it.  Cgroups is the thing giving you the EPERM here so by adding this to your devices list it will allow read,write,mknod for dev/mem

```json
                        {
                                "path": "/dev/mem",
                                "type": 99,
                                "major": 1,
                                "minor": 1,
                                "permissions": "rwm",
                                "fileMode": 8608,
                                "uid": 0,
                                "gid": 15
                        }
```

You still need that cap added as well.

**Comment by crosbymichael** [comment]
Its pretty hard to get all those numbers for the device though, we should probably work on some tooling to stat the device on the host and then populate it in the spec generation cuz it has hard doing it by hand

**Comment by rakyll** [comment]
Nice. The moment we figured out the solution, I saw your equivalent suggestion. It works now, thanks.
