### ISSUE TITLE
Potential race in initProcess start()?

### ISSUE THREAD

**Issue by Amey-D** [opencontainers/runc#535]
IIUC, the start() process of initProcess in process_linux.go runs the container process command first, and then creates network interfaces for the container shortly afterwards.  If the container is started with "--net=bridge", it will create the veth device, attach one end to the bridge and move the other end inside the network namespace of the container using the pid of the container process.  If the container process is short lived, could this lead to a race?

**Comment by crosbymichael** [comment]
No this will not happen because the process inside the container is blocking on a pipe and waits until the parent process sets everything up.  At the very end, after all the namespace, networking, mount setup is complete, the user's specified process is finally exec'd.
