### ISSUE TITLE
runc fails to start multiple processes

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#54]
I have included multiple process inside my container.json file and started runc.

runc gave following warning!!!
                 runc only supports one(1) process for the container

I was looking for "supervisord" kind of daemon to start my multiple services inside my container..
So I tried to modify the container.json to start multiple process and it gave the above mentioned message.

is it anything intentional as per runc design to have one process per container  ?

Thanks
Rajasec

**Comment by InformatiQ** [comment]
i think this is how it is designed
if you want multiple processes then use supervisord inside runc
or use something like lxc to create a system container

**Comment by mrunalp** [comment]
@rajasec The spec doesn't support multiple processes today. If it does in the future, then runc will support that feature. Thanks!

**Comment by rajasec** [comment]
@mrunalp 
I'm closing this issue now. We will take it up in future
