### ISSUE TITLE
Add bundle and rootfs to the list command

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/runc#548]
Per discussion in #507 bundle and rootfs were temporarily removed from the list command until it could be ascertained where and/or how best to identify and store the bundle (directory) for all use cases.

A solution for runc was to call os.Getwd() which returns the bundle directory being used on runc start command... however that option does not work for the docker use cases. 

This issue is a place holder for discussions to move this forward.

**Comment by mikebrow** [comment]
@crosbymichael What do you think about adding a bundle field to the specification file?  When runc generates the spec it can use the current working directory as the default for the new bundle field.  When the spec is loaded for start we can store the bundle directory in a new configs.Config.bundle variable.

**Comment by mikebrow** [comment]
Continuing the thought... the bundle field in the spec could be optional.. and if not explicitly defined we could use the current working directory.  If defined we could check to make sure it's there.  If we go this path we would not add it to the spec when running the runc spec command we would just leave it out.

**Comment by duglin** [comment]
If you mean include a field in config.json for the bundle dir, then I'm not sure we should do that. First, that would make the config.json file non-portable because you'd always have edit it before you could use it when you move a bundle dir around.  And second, I think the location of the file itself should be good enough.

**Comment by mikebrow** [comment]
I suppose that's a negative..

So how to get the configs.Config.bundle variable initialized for all the use cases..

runc can just use the current working directory for the create/start but @crosbymichael said something about a docker use case where the current working directory was not the bundle... 

Any process not creating the container from the bundle directory would need to pass the bundle directory as a parameter or environment variable, or some by other means... if we are not going to add it to the spec.
