### ISSUE TITLE
no bundlePath in state.json

### ISSUE THREAD

**Issue by qiancai** [opencontainers/runc#559]
From https://github.com/opencontainers/specs/blob/master/runtime.md

"The state.json file MUST contain all of the following properties:
...
bundlePath: (string) is the absolute path to the container's bundle directory. This is provided so that consumers can find the container's configuration and root filesystem on the host."

However, there is no such thing in state.json after 'runc start' right now.

**Comment by duglin** [comment]
ping @mikebrow

**Comment by mikebrow** [comment]
This is most likely a duplicate issue to issue #507.
