### ISSUE TITLE
Unable to mount filesystems located on block devices using config.json

### ISSUE THREAD

**Issue by sajones** [opencontainers/runc#572]
Based on [https://github.com/opencontainers/specs/blob/master/config.md#mounts](https://github.com/opencontainers/specs/blob/master/config.md#mounts), I expected to be able to mount a filesystem stored on a block device as container start using a config block like this:

```
    "mounts": [
      {
        "destination": "/proc",
        "type": "proc",
        "source": "proc"
      },
      {
        "destination": "/dev",
        "type": "tmpfs",
        "source": "tmpfs",
        "options": [
          "nosuid",
          "strictatime",
          "mode=755",
          "size=65536k"
        ]
      },
     ...
      {
        "destination": "/home/",
        "type": "xfs",
        "source": "/dev/mapper/vg_VolGroup-lv_container_home",
        "options": [
          "noatime",
          "inode64"
        ]
      }
    ]
```
When I attempt to start the container I end up with this error message:

```
Code: System error

Message: unknown mount device "xfs" to "/home/"

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@42
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@71
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@259
---
3: 1
Package: main.init
File: start.go@77
---
4: init
Package: main
File: utils.go@330
---
5: main
Package: runtime
File: proc.go@100
---
6: goexit
Package: runtime
File: asm_amd64.s@1721
WARN[0000] exit status 1                                
FATA[0000] Container start failed: [10] System error: could not synchronise with container process 
```

After looking at runc/libcontainer/rootfs_linux.go, it appears that runc/libcontainer only supports mounting 'proc', 'sysfs', 'mqueue', 'tmpfs', 'devpts', 'securityfs', 'bind', and 'cgroup' types. This appears to contradict the intent of the specification.

Is the use case of being able to mount actual filesystems as part of the container start process a desired one, or is the expected pattern to mount all desired filesystems on the host and then bind mount them into the container?

**Comment by crosbymichael** [comment]
It should be fine to update runc to support these mount types
