### ISSUE TITLE
Filtering options for list command

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/runc#574]
At current the `runc list` command displays all instances of containers.

It would be good to have some way to filter this list at the command line without having to pipe the output through a grep or other tool.

Suggestion:
Implement a filter.  Example of use: `runc list --filter "status=running"`

I would suggest starting with the following fields:
status (running, paused, ...)
id (container id)
pid (init process id)

Thoughts?

I volunteer to put a PR together for this if there's some interest/agreement.

**Comment by crosbymichael** [comment]
people can do this at a higher level.  the problem is that if we add one type of filter ppl will want more and more and it will never end.  if we have the json output ppl can filter however they want or just use grep

**Comment by mikebrow** [comment]
Ok... grep it is..  Cheers.

**Comment by crosbymichael** [comment]
thx
