### ISSUE TITLE
Spec requires a command named "state"

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/runc#589]
From: https://github.com/opencontainers/specs/blob/master/runtime.md#query-state
`Query State
state <container-id>
This operation MUST generate an error if it is not provided the ID of a container. This operation MUST return the state of a container as specified in the State section. In particular, the state MUST be serialized as JSON.`
And the state definition from the spec:
`When serialized in JSON, the format MUST adhere to the following pattern:
{
    "ociVersion": "0.2.0",
    "id": "oci-container1",
    "pid": 4422,
    "bundlePath": "/containers/redis"
}`

Of note:  runc list does not take a container id as a parameter and there are no filters, where this state query is for one container id.  Runc list serializes to json but does not comply with the format of the required state above... so to be compliant we need a new command.

I'll put a PR together for a command that complies with the spec.  Or if there is a disagreement we can raise an issue with the spec.

**Comment by mrunalp** [comment]
:+1:

**Comment by mikebrow** [comment]
Issue resolved.
