### ISSUE TITLE
Make CRIU support optional

### ISSUE THREAD

**Issue by nponeccop** [opencontainers/runc#624]
CRIU is not available everywhere (e.g. ArchLinux default kernel has the necessary options off). So an ability to disable the functionality and clean up the `--help` output would be nice.

**Comment by marcosnils** [comment]
CRIU is already optional.

**Comment by mikebrow** [comment]
CRIU is a requirement for the checkpoint & restore commands. But you don't need to use those commands to manage containers.  

I already did one spin at cleaning up the --help across the apis.  After you've downloaded the latest build if you have some specific ideas for additional help text I could update it based on your comments if you like.  

Cheers.

**Comment by crosbymichael** [comment]
Yes, there is no hard requirement on `criu` and everything else works except c/r.  I'm not sure if we should remove the commands or not if criu is not installed because it gives ppl a hint that c/r is available and that they should install criu if they want to take advantage of it.
