### ISSUE TITLE
Die on starting as a non-root

### ISSUE THREAD

**Issue by nponeccop** [opencontainers/runc#625]
Currently if run as a non-root `runc` tries to open "/run/opencontainer/containers" and fails.

It would be nice to output a more friendly message instead, as most functions cannot be completed while running as a non-root.

**Comment by marcosnils** [comment]
@nponeccop are you running the last version?

You should get a `FATA[0000] runc should be run as root` error message when trying to runC as a non-root user.

**Comment by nponeccop** [comment]
Sorry again. I'm running the last release, which is not HEAD.
