### ISSUE TITLE
Valid IDs

### ISSUE THREAD

**Issue by ip1981** [opencontainers/runc#635]
Why are IDs restricted by this pattern?

```
idRegex = regexp.MustCompile(`^[\w_-]+$`)
```

https://github.com/opencontainers/runc/blob/master/libcontainer/factory_linux.go#L29

**Comment by crosbymichael** [comment]
It is for valid filepath names because the container id needs to be written to disk in something like `/run` to store state.

**Comment by ip1981** [comment]
File names can include a way more other characters. I fail to see reasons for existing restrictions. `foo.com` is a valid file name, but not a valid id. Why?
