### ISSUE TITLE
Installation without sudo access

### ISSUE THREAD

**Issue by charleszheng44** [opencontainers/runc#642]
Since I installed `golang` to a custom path instead of `/usr/local/bin`, is that possible to install `runC` without `sudo` privilege?

**Comment by hqhq** [comment]
It is possible, since all `make install` does is to copy runc to `/usr/local/bin/runc`, you can copy it to any paths in your environment `PATH` list as you want without using `make` command.
But you always need `sudo` to use runc, I don't see the benefit from the avoidance of `sudo` when install `runC`.

**Comment by charleszheng44** [comment]
@hqhq when I did the `make install`, some go files point to the `/usr/loacl/bin/go`. It seems like `runC` can not be installed with custom `go` path without changing the source code.

**Comment by mikebrow** [comment]
Not sure what you are talking about regarding some go files pointing to a particular directory.

runc is a simple standalone binary executable. After you build it you can run it right from the directory where you built it. For example: `./runc --help` Or as hqhq says you can cp it to the directory of your choice. This is the code in the makefile for install:
`install:
	cp runc /usr/local/bin/runc`

As you can see make install merely uses linux cp to copy runc to a directory that is typically in the path for executing commands.  

As for running runc to launch containers you need to do that with privilege (`sudo`).

If you have questions or want to discuss, catch me on the freenode #opencontainers IRC.  Cheers.

**Comment by cyphar** [comment]
To clarify, you do **not** need root privileges to install `runc`. To use it, you still currently need `root` (though #774 will change this). Closing, but feel free to re-open it if you have anything to add.
