### ISSUE TITLE
Overriding the default args parameter in the spec

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/runc#645]
With the current spec command the args parameter defaults to `sh`.  This works well for containers that include the sh command, but not so well for other containers.   

One has to edit the `config.json` just to run hello-world. Examples: 
    `sed -i 's;"sh";"/hello";' config.json` 
    `sed -i 's/"sh"/"echo","-n","hi"/' config.json` 
    edit args using a text editor.

For usability sake... I recommend we either add an optional  `--args` parameter to the runc spec command, or the runc start command (or both) to enable overriding the default arg array; or we document using sed in the usage for the spec and start commands.  I prefer adding --args parameters.  

Thoughts?  I'll put a PR together for it.  

Cheers, Mike

**Comment by marcosnils** [comment]
The runC readme states: 
>It assumes that the file-system is found in a directory called rootfs and there is a user with uid and gid of 0 defined within that file-system.

Maybe adding that it assumes that the rootfs has `sh` is enough?

**Comment by crosbymichael** [comment]
The specs commands just creates an example config as a starting point for you to build on.  

its just meant as a starting point, thats all.

**Comment by mikebrow** [comment]
I'll update the usage for spec/start to reflect that.  This to reduce the possible number of incoming reported issues and questions.  Cheers.
