### ISSUE TITLE
Add Vagrantfile

### ISSUE THREAD

**Issue by matthaias** [opencontainers/runc#649]
I tried runc on OSX yesterday and missed a Vagrantfile :). I think that would make it easier for people with OSX or Windows to get started with runc. What do you think? In case you like the idea, I'm happy to provide a Vagrantfile via PR.

**Comment by albertoleal** [comment]
@matthaias you can use [this Dockerfile](https://github.com/albertoleal/dockerfiles/blob/master/runc/Dockerfile) or [this runc-playground project](
https://github.com/totherme/runc-playground)

**Comment by cyphar** [comment]
I think we should make the `script/test_Dockerfile` (which is used for running tests -- but it does build runC) more visible.

**Comment by matthaias** [comment]
Thanks.It' fine with me to close this issue, since i have no time at the moment to go deeper in trying runc. Also, only @c4milo and i were the only one with this request.

**Comment by crosbymichael** [comment]
The dockerfile is now in the root of the repo for easier builds and test runs.
