### ISSUE TITLE
Exec fails randomly

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/runc#662]
on:
  4.2.0-30-generic 
  Distributor ID:	Ubuntu
  Description:	Ubuntu 15.10
  Release:	15.10
  Codename:	wily

in a vbox with 4gig ram

using: 
runc -v 
  runc version 0.0.9
  commit: '54a6e5600483b3712d3ee15d40781bac48d3de41'
  spec: 0.4.0

Setup a busybox bundle

run the following script
```
#!/bin/bash


runc kill test_busybox KILL
sleep 1
runc delete test_busybox
sleep 1
runc start -d --console /dev/pts/ptmx test_busybox

for ((i=0; i < $1; i++)); do
  runc exec test_busybox echo Hello from exec >out 2>err
  rc=$?
  if [[ $rc != 0 || -s err ]]; then
    echo Error while running exec on iteration $i
    echo Exit code: $rc
    echo Error: $(cat err)
    echo Output: $(cat out)
    exit 1
  fi
done

echo PASS

runc kill test_busybox KILL
runc delete test_busybox
```

Output for various attempts: 

```
mike@mike-VirtualBox:~/go/src/github.com/busyboxtest2$ sudo ./runit.sh 1000
Error while running exec on iteration 148
Exit code: 1
Error: exec failed: write /proc/14762/oom_score_adj: invalid argument
Output: Hello from exec

mike@mike-VirtualBox:~/go/src/github.com/busyboxtest2$ sudo ./runit.sh 1000
Error while running exec on iteration 4
Exit code: 1
Error: exec failed: write /proc/14855/oom_score_adj: invalid argument
Output: Hello from exec

mike@mike-VirtualBox:~/go/src/github.com/busyboxtest2$ sudo ./runit.sh 1000
Error while running exec on iteration 102
Exit code: 1
Error: exec failed: write /proc/16311/oom_score_adj: invalid argument
Output: Hello from exec

```

**Comment by mikebrow** [comment]
After changing init_linux.go to be more descriptive:

func setOomScoreAdj(oomScoreAdj int, pid int) error {
	path := fmt.Sprintf("/proc/%d/oom_score_adj", pid)

	//return ioutil.WriteFile(path, []byte(strconv.Itoa(oomScoreAdj)), 0600)
	if err := ioutil.WriteFile(path, []byte(strconv.Itoa(oomScoreAdj)), 0600); err != nil {
		return fmt.Errorf("failed to write %v to %v: %v", strconv.Itoa(oomScoreAdj), path, err)
	}
	return nil
}

I get the following error output from the above script:

Exit code: 1
Error: exec failed: failed to write 0 to /proc/17697/oom_score_adj: write /proc/17697/oom_score_adj: invalid argument

**Comment by mikebrow** [comment]
Suggest changing:

`OomScoreAdj int `json:"oom_score_adj"` in Config struct in file libcontainer/configs/config.go 
`
to:

`OOMScoreAdj *int `json:"oom_score_adj,omit empty"`
` 
and refactoring code accordingly.

**Comment by hqhq** [comment]
I can't reproduce this and looks weird because 0 is a valid value for oom_score_adj.

**Comment by mikebrow** [comment]
Interesting... vbox running ubuntu 15.10 with the current master?

**Comment by mikebrow** [comment]
Just to note..  at the point of failure the file /proc/<pid>/oom_score_adj does exist, and I can open it and read two bytes from it...`"0\n"`

I tried writing the same two bytes back to it and get the same invalid argument error message back.

**Comment by mikebrow** [comment]
I suspect it is a timing problem with short lived processes where we are trying to set the oom_score_adj on a process that has already exited..

**Comment by mikebrow** [comment]
Confirmed we have a timing issue with short lived processes (like echo) if I move the call to setOomScoreAdj to right after the Start() call, as shown below, my stress test never fails:
```
func (p *setnsProcess) start() (err error) {
	defer p.parentPipe.Close()
	err = p.cmd.Start()
	// set oom_score_adj  <<<< new location>>>>
	if err := setOomScoreAdj(p.config.Config.OomScoreAdj, p.pid()); err != nil {
		return newSystemError(err)
	}

	p.childPipe.Close()
	if err != nil {
		return newSystemError(err)
	}
	if p.bootstrapData != nil {
		if _, err := io.Copy(p.parentPipe, p.bootstrapData); err != nil {
			return newSystemError(err)
		}
	}
	if err = p.execSetns(); err != nil {
		return newSystemError(err)
	}
	if len(p.cgroupPaths) > 0 {
		if err := cgroups.EnterPid(p.cgroupPaths, p.pid()); err != nil {
			return newSystemError(err)
		}
	}
	if err := utils.WriteJSON(p.parentPipe, p.config); err != nil {
		return newSystemError(err)
	}

	// set oom_score_adj <<<< old  location >>>>>
	//if err := setOomScoreAdj(p.config.Config.OomScoreAdj, p.pid()); err != nil {
	//	return newSystemError(err)
	//}

	if err := syscall.Shutdown(int(p.parentPipe.Fd()), syscall.SHUT_WR); err != nil {
		return newSystemError(err)
	}
	// wait for the child process to fully complete and receive an error message
	// if one was encountered
	var ierr *genericError
	if err := json.NewDecoder(p.parentPipe).Decode(&ierr); err != nil && err != io.EOF {
		return newSystemError(err)
	}
	// Must be done after Shutdown so the child will exit and we can wait for it.
	if ierr != nil {
		p.wait()
		return newSystemError(err)

	}
	return nil
}
```

**Comment by mrunalp** [comment]
@mikebrow We can't move it up above execSetns() as the pid isn't correct. We need synchronization like in init.

**Comment by mikebrow** [comment]
Thx, and yes moving to above the WriteJSON works so closing the issue.  Will draft some stress tests to try and find race conditions.  Cheers.
