### ISSUE TITLE
runc stats command?

### ISSUE THREAD

**Issue by jfrazelle** [opencontainers/runc#678]
a lot like `docker stats` or my tool that is basically docker stats github.com/jfrazelle/magneto

is this something you would like built in?

or is this a question for the spec?

**Comment by marcosnils** [comment]
So, containerd has a `stats` commands which returns stats for a running container. Does it make sense to include it in runC as well?.

**Comment by jfrazelle** [comment]
But but what if I don't run the container under containerd 0:)

On Wednesday, March 23, 2016, Marcos Nils <notifications@github.com> wrote:

> So, containerd has a stats commands which returns stats for a running
> container. Does it make sense to include it in runC as well?.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencontainers/runc/issues/678#issuecomment-200345721>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by mikebrow** [comment]
See runc events... :-)

**Comment by mikebrow** [comment]
Not pretty as it comes in json only form... Just needs a way to pretty it up a bit.

**Comment by jfrazelle** [comment]
I mean I built a tool to pipe runc events too, I just didn't know if it
should still be separate

On Wednesday, March 23, 2016, Mike Brown <notifications@github.com> wrote:

> See runc events... :-)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencontainers/runc/issues/678#issuecomment-200409770>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by mikebrow** [comment]
ah...  I'd like an option to format it as a table when not in every n timer mode.

**Comment by mikebrow** [comment]
runc events --stats --format table <cid>

**Comment by mikebrow** [comment]
or are you thinking combine list and events --stats?

**Comment by jfrazelle** [comment]
Ya so kinda like https://github.com/jfrazelle/magneto

On Wednesday, March 23, 2016, Mike Brown <notifications@github.com> wrote:

> or are you thinking combine list and events --stats?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencontainers/runc/issues/678#issuecomment-200413137>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by mikebrow** [comment]
Dunno... i like runc having a few options to make it more useful as a command line tool.. but some only want it to be a process in the middle for now with as little as possible to meet the spec.

**Comment by mikebrow** [comment]
Nice tool!  Forking that baby now :-)

**Comment by jfrazelle** [comment]
sweet ya I agree, was more of a wondering i also love the unix philosophy
different tools for different things :)

On Wed, Mar 23, 2016 at 9:26 AM, Mike Brown <notifications@github.com>
wrote:

> Nice tool! Forking that baby now :-)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencontainers/runc/issues/678#issuecomment-200422683>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
closing, and maybe in the future we can see

**Comment by marcosnils** [comment]
@jfrazelle :tada:
