### ISSUE TITLE
Raising rlimits higher than current hard limit fails in unprivileged containers

### ISSUE THREAD

**Issue by julz** [opencontainers/runc#680]
This may or may not be 'working-as-intended', but it seems worth discussing (and possibly specifying). 

As stands, creating a container that sets rlimits always works if the container is privileged, but fails if the container is unprivileged *unless* the current rlimits in the host are already as high or higher than the requested rlimit. This makes sense: the container root user does not have permissions to raise the rlimits higher than the current hard limit.

But the creator of the container (i.e. real root) _does_ have those permissions, and _did_ request it (via config.json). Imo we should move the rlimit setting earlier (before the creation of the user namespace) so that it succeeds for both cases, or use `prlimit` to set the limits as host root after spawning the process. I'd be happy to PR that change if people agree it's the correct behaviour? (or alternatively I'll PR the specs to note that an unprivileged container cannot request an rlimit higher than the current limit)

**Comment by mrunalp** [comment]
We discussed this during the OCI call today. I think moving the code to parent process of the container process should probably work. @julz will create a PR.
