### ISSUE TITLE
Add stop command

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/runc#681]
The spec has a requirement for the inclusion of a stop command.  The spec states:

```
Stop

stop <container-id>

This operation MUST generate an error if it is not provided the container ID. This operation MUST stop
and delete a running container. 

Stopping a container MUST stop all of the processes running within the scope of the container. 

Deleting a container MUST delete the associated namespaces and resources associated with the container. 

Once a container is deleted, its id MAY be used by subsequent containers. 

Attempting to stop a container that is not running MUST have no effect on the container and MUST generate an error.

```
I volunteer to do a PR for this new command.  Objections?

**Comment by crosbymichael** [comment]
I dont remember this.  Stop is pretty bad because what does stop mean?  TERM? SIGKILL? We don't want logic like docker where you SIGTERM, wait for it to die then after a timeout do a SIGKILL.

**Comment by mikebrow** [comment]
kk... probably need to move the issue to the spec then...

**Comment by crosbymichael** [comment]
Ok, lets close this then to not cause anyone confusion while its being discussed.
