### ISSUE TITLE
man section mismatch

### ISSUE THREAD

**Issue by onlyjob** [opencontainers/runc#693]
`runc` is installed to `/usr/bin` yet man pages are generates for section 8 which is usually used for administrative commands installed in `/usr/sbin`.

**Comment by cyphar** [comment]
I'm fairly sure we should actually be installing to `/usr/sbin` since we require `root` in order to actually run. WDYT @hqhq @mrunalp ?

**Comment by hqhq** [comment]
Yeah, I think installing to `/usr/sbin` will work.

**Comment by cyphar** [comment]
I've made a PR (#702) which adds `/usr/sbin` as the installation directory of `runc`. PTAL.

@onlyjob is this more acceptable?

**Comment by onlyjob** [comment]
Thanks, installing to `/usr/sbin` brings harmony with man page section. :)
