### ISSUE TITLE
Numeric user id passed as user name if user name is numeric in /etc/passwd

### ISSUE THREAD

**Issue by crosbymichael** [opencontainers/runc#695]
Ref: https://github.com/docker/docker/issues/21436

It looks like the user package is searching for a username first even though the format is numeric.  I think if we parseint that should take precedence over the `/etc/passwd` lookup.  What do you all think?

Please read the original issue for more details on the problem reported by a user of Docker.

**Comment by mrunalp** [comment]
I think we are following a convention in the lookup algorithm. I don't remember from where @tianon probably knows.

**Comment by cyphar** [comment]
I'm fairly sure I maintained the old semantics during my rewrite of `libcontainer/user`. AFAIK it's possible to have numeric usernames, so it feels like a weird restriction by runc.

**Comment by crosbymichael** [comment]
I see. Thanks.  Let me thing about this more.

**Comment by jordmoz** [comment]
It is possible to have numeric usernames, but I had to directly modify the password file to do it.  A quick googling around shows that numeric usernames are not recommended. So either:

1. Numeric usernames are OK: In that case, another --user flag should be introduced to pass user Ids (e.g. --userId) because otherwise there is a serious security hole (as I have shown in the original bug report (https://github.com/docker/docker/issues/21436)

or

2. Numeric usernames are not OK: In that case, numeric options passed to --user should be treated as an ID first, and not a name.

Adding a numeric user is not possible on Ubuntu 14.04 with the standard tools:

```
vagrant@node0:~$ sudo adduser 1234
adduser: Please enter a username matching the regular expression configured
via the NAME_REGEX[_SYSTEM] configuration variable.  Use the `--force-badname'
option to relax this check or reconfigure NAME_REGEX.
vagrant@node0:~$ sudo adduser --force-badname 1234
Allowing use of questionable username.
Adding user `1234' ...
Adding new group `1234' (1006) ...
Adding new user `1234' (1003) with group `1234' ...
useradd: group '1234' does not exist
adduser: `/usr/sbin/useradd -d /home/1234 -g 1234 -s /bin/bash -u 1003 1234' returned error code 6. Exiting.
vagrant@node0:~$ cat /etc/passwd | grep 1234
vagrant@node0:~$ cat /etc/group | grep 1234
1234:x:1006:
vagrant@node0:~$ 
```

**Comment by tianon** [comment]
The way `sudo` solves this is by forcing numeric arguments to start with `#` (ie, `sudo -u '#123' ...`), but that's really nasty IMO.

I think it sounds sane to switch the default to prefer direct usage if we're already numeric (such that `--user 123:456` will always lead to UID of 123 and GID of 456).  I think the original intent was to make sure that we were a faithful interface to `/etc/passwd`, but I agree that "shadowing" a user ID is certainly unexpected and ought to be fixed (especially given the conversation there that numeric usernames are heavily discouraged and in some cases outright refused by many of the existing tools).

**Comment by crosbymichael** [comment]
Ya, I'm with @tianon on this.  I think our original intent was that we have the same interface as other tools but we can do better and be more secure if we default to uid/gid if they can be parsed as ints then `/etc/passwd` lookup if not.

**Comment by mrunalp** [comment]
@crosbymichael I think it makes sense, I don't see any valid use cases for why one would want to create usernames that are numerical in /etc/passwd.

**Comment by cyphar** [comment]
Cool, I'll make this change.

**Comment by jordmoz** [comment]
thanks all!
