### ISSUE TITLE
bind mount a path from root filesystem inside a running container

### ISSUE THREAD

**Issue by sumitsanghrajka** [opencontainers/runc#697]
Is there a way to bind mount a path from root filesystem inside a running container which was started with pid and mnt namespaces ?

**Comment by cyphar** [comment]
Have you tried adding it to the `mounts` list in the spec file?

**Comment by sumitsanghrajka** [comment]
You mean the config.json file? 
But in my case the container is already running (using `runc start` with pid and mnt namespaces). 
I want to avoid stopping the container, updating config.json (adding another mount point in the mounts list) file and starting the container.

**Comment by mrunalp** [comment]
@sumitsanghrajka The only way this would work is using mount propagation. It is a bit hard to comprehend. I would suggest looking at the feature in docker and then mapping it the right configuration in runc.

**Comment by sumitsanghrajka** [comment]
@mrunalp Thanks. I will look into that.
I found another option which is explained here: https://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/
