### ISSUE TITLE
terminal not usable after detach container

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#709]
After starting the container with detached mode, the terminal is not in usable state.
Even we start via shell scripts, current terminal is not usable ( until we destroy & delete the container)

**Comment by mikebrow** [comment]
Try this:
runc start -d --console /dev/pts/ptmx test_busybox
runc exec test_busybox echo Hello from exec
sudo runc exec test_busybox sh

**Comment by LK4D4** [comment]
I saw that too! was fixed for me after reboot.

**Comment by mikebrow** [comment]
By default state for the container is stored in a location that is "deleted" on reboot. Are you guys saying you have a "stopped" container in destroyed state that you are trying to attach too?  < need more data :-) >  Cheers

**Comment by crosbymichael** [comment]
If you are going to use a tty with attach then you have to hold open the master side yourself since runc is not alive to do it.
