### ISSUE TITLE
canonicalize bundle path before starting container

### ISSUE THREAD

**Issue by Naitreey** [opencontainers/runc#714]
runc now supports two ways of starting a container:
- `cd` into the container bundle dir, then `runc start <container-id>`
- In any directory, `runc start (--bundle|-b) <bundle-path> <container-id>`

The inconsistency occurs when encountering bundle path which contains symlink.
- In the first form of invocation, the following error is printed and container is failed to start:

```
Container start failed: [8] Invalid configuration: /home/naitree/temp/u_link/rootfs is not an absolute path or is a symlink
```
- In the second form, `<bundle-path>` can actually contain symlink and container runs successfully.

It looks like in the second form, the bundle path is canonicalized before running container, while it isn't the case in the first form.

I think it's natural for the user to think that the following two form of invocations are functionally equivalent:

``` sh
cd <container-path> && runc start <container-id>
runc start --bundle <container-path> <container-id>
```

However, as of runc v0.0.9, this is not. I propose that it could be a good idea to consistently canonicalize bundle path (current directory or `--bundle` argument`) before starting container.

What do you people think of it?

(I realize the issue #586. However my concern is about bundle dir but not rootfs.)

**Comment by mikebrow** [comment]
In the first case the code is testing for sym links... @crosbymichael may be able to explain why that test was put in.  In the second case the code just sets the cwd to the bundle, and does not check.  I suppose it makes sense to make sure they both have the same behavior.

**Comment by crosbymichael** [comment]
Looks like it is just a bug.  We should just get the absolute path for the bundle from whatever is provided.  

As long as this is for the bundle its good to be changed but lets not change the rules about rootfs being a symlink at this point.  Too many issues haunt me from the past.

**Comment by cyphar** [comment]
We shouldn't be getting a symlink from `getcwd(2)` -- all of the magic with current directories is done inside shells. The kernel will always give you an absolute path (with all symlink components correctly dealt with).

**Comment by kunalkushwaha** [comment]
With current code this seems to be fixed. It reports error in case of symlinks in both  cases.

```
$ ll
total 0
lrwxrwxrwx 1 kunal kunal 21 Oct 28 11:08 config.json -> ../ubuntu/config.json
lrwxrwxrwx 1 kunal kunal 16 Oct 28 11:08 rootfs -> ../ubuntu/rootfs

$ sudo runc run testcon1 
/home/kunal/go/src/github.com/kunalkushwaha/quickcon/newubuntu/rootfs is not an absolute path or is a symlink

$ cd ..                 

$ sudo runc run -b newubuntu testcon1                                                          
/home/kunal/go/src/github.com/kunalkushwaha/quickcon/newubuntu/rootfs is not an absolute path or is a symlink
```

**Comment by hqhq** [comment]
@kunalkushwaha Yeah I can confirm it's fixed, thanks for reminding, I'll close.
