### ISSUE TITLE
rootfs shared mount propagation broken

### ISSUE THREAD

**Issue by qiancai** [opencontainers/runc#715]
```
# cat config.json
...
"rootfsPropagation": "shared"
...
```

Bundle is under /root/rootfs/

```
# runc start root

# mount -o bind /tmp/ /root/rootfs/mnt
```

```
container> ls /mnt/
<it is empty>
container> umount /mnt
umount: /mnt/: not mounted
```

On the other hand, "slave" seems work fine.

Tested at the commit id 89ab7f2

**Comment by hmeng-19** [comment]
@qiancai , I tested this on the upstream master, and it works for me. 
Do you still have the problem?

**Comment by qiancai** [comment]
I have not had a chance to test this lately. Great if it is works for you and this one can be closed.

**Comment by qiancai** [comment]
No, this is still not working for me using today's master.

**Comment by qiancai** [comment]
OK, just figured it out how it works.
