### ISSUE TITLE
Vol mounted overlayfs directory in is invisible to container

### ISSUE THREAD

**Issue by suryagaddipati** [opencontainers/runc#719]
` /cache/ssd/merged/6` is an overlayfs 'merged' directory

```
docker run  -it -v /cache/ssd/merged/6:/images busybox sh
/ # ls /images/
/#
```

on the host machine 

```
# ls /cache/ssd/merged/6
saf.txt  sf.txt

```

**Comment by suryagaddipati** [comment]
Closing. Seems to be a docker issue.

**Comment by cyphar** [comment]
To answer your question, I think that Docker uses just regular `bind` mounts for volumes. Those don't properly deal with sub-mountpoints and require `rbind` mounts (recursive bind mounts).
