### ISSUE TITLE
Unable to create more than 200 containers by default

### ISSUE THREAD

**Issue by dhiltgen** [opencontainers/runc#726]
If you attempt to create more than 200 containers, you get a rather confusing error message from the daemon.  

```
docker[5776]: time="2016-04-06T18:50:58Z" level=error msg="containerd: start container" error="oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded" id=364fa0569db4475be3ef5f4ecf8c4751a84fa064ad7f6e05505137c65a629430
docker[5776]: time="2016-04-06T18:50:58.265141539Z" level=error msg="Handler for POST /v1.15/containers/364fa0569db4475be3ef5f4ecf8c4751a84fa064ad7f6e05505137c65a629430/start returned error: rpc error: code = 2 desc = \"oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded\""
```

It appears that https://github.com/opencontainers/runc/pull/582 coupled with the default `/proc/sys/kernel/keys/` quota leads to this.

Ideally users shouldn't have to modify this by hand to run more than 200 containers on the system.

**Comment by marcosnils** [comment]
@dhiltgen have you tried containerd?. Seems to me like runC is already battle tested.

https://github.com/docker/containerd

**Comment by dhiltgen** [comment]
I was using docker 1.11.0-rc3

**Comment by crosbymichael** [comment]
This is being fixed in the upper layers.  There is not much we should do at this layer.

**Comment by crosbymichael** [comment]
@dhiltgen you can follow the progress for the change in docker here:

https://github.com/docker/docker/issues/22865
