### ISSUE TITLE
Use Go's new standard vendoring in 1.6+

### ISSUE THREAD

**Issue by pkieltyka** [opencontainers/runc#728]
I also suggest https://github.com/kardianos/govendor over Godeps.

**Comment by cyphar** [comment]
Sure, that's fine. But I think we should do a subtree merge or something like that to make sure that the history of vendoring isn't lost.

**Comment by cyphar** [comment]
I just tried `govendor` and it doesn't appear to work properly (it doesn't look like it correctly deals with nested requirements of packages and it also doesn't clean up unused files). Currently Docker's `hack/vendor.sh` does a better job. I'm going to take a look at `govend` and some others.

**Comment by LK4D4** [comment]
@cyphar I'm pretty sure that godep and glide are best vendoring tools now(glide even can vendor docker dependencies). I hate godep workflow, but it cleans unneeded files and that's only reason I prefer it over glide.

**Comment by cyphar** [comment]
@monstermunchkin said that `govend` might actually work nicely here.

The reason I don't like `godep` is because updating dependencies to a specific version (like in `hack/vendor.sh`) is a **huge** pain. I'd prefer we take the magical shell script from Docker rather than use Godep.

**Comment by LK4D4** [comment]
Yeah, I tried govend. It's really nice.

**Comment by crosbymichael** [comment]
We are now using go 1.6 if anyone would like to do the work of porting over our vendor dependencies to the new schema.

**Comment by jfrazelle** [comment]
DIBS






On Fri, Jun 10, 2016 at 5:00 PM -0700, "Michael Crosby" <notifications@github.com> wrote:












We are now using go 1.6 if anyone would like to do the work of porting over our vendor dependencies to the new schema.

**Comment by marcosnils** [comment]
I think I saw a PR from @cyphar that implemented this?

sent from mobile

**Comment by jfrazelle** [comment]
ah yeah its https://github.com/opencontainers/runc/pull/898/files

**Comment by marcosnils** [comment]
It's from @lk4d4 actually
https://github.com/opencontainers/runc/pull/898
sent from mobile

**Comment by crosbymichael** [comment]
@jfrazelle you trying to crash my browser giving me a link with `/files` on a PR with 18k line changes?

**Comment by jfrazelle** [comment]
So I was stuck there and yeah....






On Fri, Jun 10, 2016 at 5:08 PM -0700, "Michael Crosby" <notifications@github.com> wrote:












@jfrazelle you trying to crash my browser giving me a link with /files on a PR with 18k line changes?

**Comment by crosbymichael** [comment]
I think we resolved our vendoring issues using `vndr` that uses the go vendor setup
