### ISSUE TITLE
runc does not report failures happening in pre/post-hook

### ISSUE THREAD

**Issue by aboch** [opencontainers/runc#733]
For example in docker, on container start, if a failure happens while libnetwork programs the networking for the container (for example failing to program the container's default gw), daemon would always returns a generic oci error:
`docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exit status 1".`

This makes it impossible to debug an issue for which no warn or error level log was recorded.

I am opening the issue here per @tonistiigi advice.

**Comment by mlaventure** [comment]
A more generic description would be that the stderr output of hooks should
be propagated up I think.
