### ISSUE TITLE
unable to set hostname without a private UTS namespace

### ISSUE THREAD

**Issue by cloudtrends** [opencontainers/runc#74]
hi team,

According to the README.md introduction:
To run a container that you received just execute runc with the JSON format as the argument or have a container.json file in the current working directory.

But the runc command line told me that , the file needed is :  config.json not container.json .

So first , I move the content from container.json to config.json , the runc command show me another error :

FATA[0000] Container start failed: Rootfs ("/opt/usr/runc/rootfs") does not exist 

I read the document from rootfs , It told that :  rootfs "which is
always present in 2.6 systems." 

https://www.kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt

Then , I create a directory on /opt/usr/runc/rootfs/ , and run runc, but failed again:

FATA[0000] Container start failed: [7] Invalid configuration: unable to set hostname without a private UTS namespace 

In my config.json file , the hostname is equal as hostname command output .

What should I change in config.json file for runc  ?

thanks

**Comment by rajasec** [comment]
Reason for problem:
if config.Hostname != "" && !config.Namespaces.Contains(configs.NEWUTS) {
                return fmt.Errorf("unable to set hostname without a private UTS namespace")


In your namespaces of container.json or config.json, please add the following type in namespaces section

{
   "type" : "uts"
}

I hope this should solve your problem

Thanks
Rajasec

**Comment by cloudtrends** [comment]
hi rajasec,

I had read the code too, but after add the type uts item to config.json file ,
the error still here:
FATA[0000] Container start failed: [7] Invalid configuration: unable to set hostname without a private UTS namespace


the NEWUTS is defined in file:
src/github.com/opencontainers/runc/libcontainer/configs/namespaces_unix.go 

but I still have no clue to solve the problem.

thanks

**Comment by LK4D4** [comment]
@cloudtrends Try to use README from this pr #67

**Comment by cloudtrends** [comment]
LK4D4,

It's fine , after read the new README.md , all works well as expected .

I will close this issue.

thanks.
