### ISSUE TITLE
/proc/sys read-only

### ISSUE THREAD

**Issue by ovanes** [opencontainers/runc#741]
Currently running a privileged container allows to modify values in `/proc/sys` file system. As it turns out runC prohibits it and, finally, if docker completely moves to runC some deployments will break.

Can `/proc/sys` still be made writable?

**Comment by cyphar** [comment]
I'm confused, wasn't this fixed in #716? You can change the `ReadonlyPaths` list of paths so that it doesn't include `docker`. What's left is for Docker to correctly set the OCI config.

**Comment by crosbymichael** [comment]
This has been resolved in both runc and docker. Thanks for the issue.
