### ISSUE TITLE
compile runc-0.0.8 fails on fedora 21 mipsel

### ISSUE THREAD

**Issue by vanloswang** [opencontainers/runc#743]
```
mkdir -p $WORK/github.com/opencontainers/runc/libcontainer/cgroups/systemd/_obj/
cd /root/rpmbuild/BUILD/runc-1a124e9c2da68c867ed2c4f4ff19f0cd95cda0cd/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd
/usr/lib/golang/pkg/tool/linux_mips64le/compile -o $WORK/github.com/opencontainers/runc/libcontainer/cgroups/systemd.a -trimpath $WORK -p github.com/opencontainers/runc/libcontainer/cgroups/systemd -complete -buildid bfb68b2d847edd05348e0c005576bc809099fcec -D _/root/rpmbuild/BUILD/runc-1a124e9c2da68c867ed2c4f4ff19f0cd95cda0cd/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd -I $WORK -I /root/rpmbuild/BUILD/runc-1a124e9c2da68c867ed2c4f4ff19f0cd95cda0cd/pkg/linux_mips64le -I /usr/share/gocode/pkg/linux_mips64le -pack ./apply_systemd.go
```

The build process exit after output this message, and the exit status is 2. There is no enough information for me to debug this. Could someone give me some suggestions to fix it?

```
# go version
go version go1.6 linux/mips64le
```

The systemd version is:
`systemd-216-12`

**Comment by vanloswang** [comment]
I try the command by hand, it reports as bellow:
export GOPATH=/root/rpmbuild/BUILD/runc-1a124e9c2da68c867ed2c4f4ff19f0cd95cda0cd:/usr/share/gocode
/usr/lib/golang/pkg/tool/linux_mips64le/compile -o /root/rpmbuild/BUILD/runc-1a124e9c2da68c867ed2c4f4ff19f0cd95cda0cd/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd.a -trimpath /root/rpmbuild/BUILD/runc-1a124e9c2da68c867ed2c4f4ff19f0cd95cda0cd/src -p github.com/opencontainers/runc/libcontainer/cgroups/systemd -complete -buildid bfb68b2d847edd05348e0c005576bc809099fcec -D _/root/rpmbuild/BUILD/runc-1a124e9c2da68c867ed2c4f4ff19f0cd95cda0cd/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd -I /root/rpmbuild/BUILD/runc-1a124e9c2da68c867ed2c4f4ff19f0cd95cda0cd/src -I /root/rpmbuild/BUILD/runc-1a124e9c2da68c867ed2c4f4ff19f0cd95cda0cd/pkg/linux_mips64le -I /usr/share/gocode/pkg/linux_mips64le -pack ./apply_systemd.go
./apply_systemd.go:16: can't find import: "github.com/coreos/go-systemd/dbus"

It fails to import a package, but i already install it.

pwd
/usr/share/gocode/src/github.com/coreos/go-systemd/dbus
ls
dbus.go  methods.go  properties.go  set.go  subscription.go  subscription_set.go

**Comment by vanloswang** [comment]
I also tried the srpm golang-github-docker-libcontainer-2.1.1-0.2.gitc964368.fc21.src.rpm, it report as follow:
# rpmbuild -bb golang-github-docker-libcontainer.spec 
execute (%prep): /bin/sh -e /var/tmp/rpm-tmp.NGPcNw
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd /root/rpmbuild/BUILD
+ rm -rf libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ /usr/bin/gzip -dc /root/rpmbuild/SOURCES/libcontainer-c964368.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
execute (%build): /bin/sh -e /var/tmp/rpm-tmp.iRtJx2
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ export CGO_ENABLED=1
+ CGO_ENABLED=1
+ mkdir -p ./_build/src/github.com/docker
++ pwd
+ ln -s /root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f ./_build/src/github.com/docker/libcontainer
+ mkdir bin
++ pwd
+ export GOPATH=/root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f/_build:/usr/share/gocode
+ GOPATH=/root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f/_build:/usr/share/gocode
+ gobuild -o bin/nsinit github.com/docker/libcontainer/nsinit
+ go build -o bin/nsinit github.com/docker/libcontainer/nsinit
# github.com/docker/docker/pkg/system
/usr/share/gocode/src/github.com/docker/docker/pkg/system/stat_linux.go:13: cannot use s.Rdev (type uint32) as type uint64 in field value
# github.com/docker/libcontainer/cgroups/systemd
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:86: not enough arguments in call to theConn.StartTransientUnit
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:101: not enough arguments in call to theConn.StopUnit
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:120: not enough arguments in call to theConn.StartTransientUnit
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:129: not enough arguments in call to theConn.StopUnit
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:190: not enough arguments in call to theConn.StartTransientUnit

some package miss match ?

**Comment by vanloswang** [comment]
The version of the pkg golang-github-coreos-go-systemd-devel is as follow:
# rpm -qa | grep go-systemd
golang-github-coreos-go-systemd-devel-3-2.fc21.noarch

And the interface StartTransientUnit is defined golang-github-coreos-go-systemd-devel in  as follow:
func (c *Conn) StartTransientUnit(name string, mode string, properties []Property, ch chan<- string) (int, error) {
But the call in src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go is as bellow:
        // But if we get UnknownMethod error we don't
        if _, err := theConn.StartTransientUnit("test.scope", "invalid"); err != nil {
            if dbusError, ok := err.(dbus.Error); ok {
                if dbusError.Name == "org.freedesktop.DBus.Error.UnknownMethod" {
                    hasStartTransientUnit = false
                    return hasStartTransientUnit
                }
            }
        }

**Comment by vanloswang** [comment]
When downgrade golang-github-coreos-go-systemd-devel from 3-2.fc21 to 2-1.fc21, the compile process of golang-github-docker-libcontainer exit without any more output than runc.

# rpmbuild -bb golang-github-docker-libcontainer.spec 
execute (%prep): /bin/sh -e /var/tmp/rpm-tmp.Iahjdp
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd /root/rpmbuild/BUILD
+ rm -rf libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ /usr/bin/gzip -dc /root/rpmbuild/SOURCES/libcontainer-c964368.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
execute (%build): /bin/sh -e /var/tmp/rpm-tmp.QjZvTM
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ export CGO_ENABLED=1
+ CGO_ENABLED=1
+ mkdir -p ./_build/src/github.com/docker
++ pwd
+ ln -s /root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f ./_build/src/github.com/docker/libcontainer
+ mkdir bin
++ pwd
+ export GOPATH=/root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f/_build:/usr/share/gocode
+ GOPATH=/root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f/_build:/usr/share/gocode
+ gobuild -o bin/nsinit github.com/docker/libcontainer/nsinit
+ go build -o bin/nsinit github.com/docker/libcontainer/nsinit
# github.com/docker/docker/pkg/system
/usr/share/gocode/src/github.com/docker/docker/pkg/system/stat_linux.go:13: cannot use s.Rdev (type uint32) as type uint64 in field value


The exit value is 1 now.

**Comment by vanloswang** [comment]
add mips64 code supoort, compile successed.

**Comment by hqhq** [comment]
Do you mind contribute the code for mipsel support?
