### ISSUE TITLE
cannot build runc with golang 1.3 : make error 

### ISSUE THREAD

**Issue by rootfs** [opencontainers/runc#75]
Failed to build on Fedora 21, below is the make output
```bash
# make
go build -o runc .
# _/home/git/dev/runc
./events.go:61: syntax error: unexpected range, expecting {
./events.go:68: syntax error: argument to go/defer must be function call
./events.go:69: syntax error: need trailing comma before newline in composite literal
./events.go:70: non-declaration statement outside function body
./events.go:73: non-declaration statement outside function body
./events.go:92: non-declaration statement outside function body
./events.go:93: non-declaration statement outside function body
./events.go:94: syntax error: unexpected }
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2
```

After reverting 5aa82c95, make succeeded.

```bash
# git revert 5aa82c95
# make
go build -o runc .
```

My golang version is
```bash
# rpm -qa |grep golang
golang-pkg-linux-amd64-1.3.3-1.fc21.noarch
golang-src-1.3.3-1.fc21.noarch
golang-1.3.3-1.fc21.x86_64
golang-pkg-bin-linux-amd64-1.3.3-1.fc21.x86_64
```

**Comment by LK4D4** [comment]
golang1.3 support can add pretty much work for us. I think you should update golang, 1.4.2 should be in f22 now.
Thanks for report, though. Feel free to post all errors which you will find.

**Comment by rajasec** [comment]
My Go lang version
go version go1.4.2 linux/amd64

go fmt events.go

events.go:60:6: expected function/method call
events.go:61:8: expected operand, found 'range'
events.go:63:5: expected '{', found 'if'
events.go:64:23: missing ',' before newline in composite literal
events.go:65:6: expected operand, found 'continue'
events.go:69:6: missing ',' before newline in composite literal
events.go:70:10: expected '}', found ':='
events.go:71:3: expected declaration, found 'if'
