### ISSUE TITLE
move libcontainer/SPEC.md into runtime-spec project?

### ISSUE THREAD

**Issue by philips** [opencontainers/runc#760]
It feels like most of this file belongs here: https://github.com/opencontainers/runtime-spec/blob/master/runtime-linux.md

Maybe I am misreading the intent of this file though.

**Comment by hqhq** [comment]
It's legacy from old libcontainer days, since there are still many users who only use libcontainer as library, I think we can keep this `SPEC.md` in libcontainer for now.

**Comment by hqhq** [comment]
But yeah, contents in this file can be used to enrich runtime-spec, but I think most of them are already in https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md

**Comment by philips** [comment]
@hqhq can you try and fix it up?

**Comment by hqhq** [comment]
Yeah, I'll see what I can do.

**Comment by crosbymichael** [comment]
@hqhq has been porting alot of this over.  Its safe to close now.
