### ISSUE TITLE
spec_linux Invalid configuration: unable to restrict sys entries without a private MNT namespace

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#78]
When I pulled the latest runc from repo, I could not start the container due to the following error

FATA[0000] Container start failed: [7] Invalid configuration: unable to restrict sys entries without a private MNT namespace

Upon investigating. Looks like the namespaces had been moved from PortableSpec to struct Linux in spec_linux.go

File spec_linux.go
for _, ns := range spec.Linux.Namespaces {

Above for loop is not executed because spec.Linux.Namespaces is empty.

Same thing is applicable for spec.Linux.Devices which has been moved from Portable Spec to Linux struct.

Note:
if I make the following changes ( added back Namespaces and Devices in PortableSpec struct)

spec.Linux.Namespaces -->  spec.Namespaces, 
spec.Linux.Devices  --> spec.Devices

Then I'm able to start the container

Thanks
Rajasec

**Comment by LK4D4** [comment]
@rajasec I think update to readme was merged recently. Could you try it pls?

**Comment by rajasec** [comment]
Thanks @LK4D4 
I should have noted the `json:"linux" in spec_linux.go with respect to new json format
 After adding namespaces devices under linux, I could start my container.
I'll close the issue
