### ISSUE TITLE
Setting RLIMIT_STACK in config.json inside rlimits crashed the container during startup

### ISSUE THREAD

**Issue by sumitsanghrajka** [opencontainers/runc#787]
Is there anything I am missing here ? 
Here is my config.json file:
[config.txt](https://github.com/opencontainers/runc/files/237701/config.txt)

**Comment by justincormack** [comment]
That is a very small stack limit, I think it is just being exceeded probably.

**Comment by sumitsanghrajka** [comment]
The default on RHEL 7 is 8192. So I am bumping it up.

Output from ulimit -a (just the stack size):
`stack size              (kbytes, -s) 8192`

**Comment by sumitsanghrajka** [comment]
@justincormack you're right it is very small stack limit. I thought the value I am setting in config.json is in kbytes but it is in bytes. My bad. It works when I set it at a higher value in bytes.

Thanks.
