### ISSUE TITLE
ps command with UNIX format

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#788]
Not of bigger issue, minor issue while listing containers.

With current ps command in runc, it displays the processes running inside the container ( default option is -ef)
when option are specified, it gives error
runc ps containerID -eaf
flag not defined.

Currently by default runc supports ("-ef") UNIX format preceded by dash
when we give the options, we need to give as runc ps containerID eaf which is of BSD format ( without preceding dash)

**Comment by hqhq** [comment]
Yeah, it's a known issue, similar as https://github.com/opencontainers/runc/issues/752

**Comment by keloyang** [comment]
https://github.com/urfave/cli/pull/515,Treat all flags which followd behind the last arguments as normal arguments, this will resolve the problem which runc exec(ps) encounter.
