### ISSUE TITLE
Behavior of "runc list"

### ISSUE THREAD

**Issue by amitsaha** [opencontainers/runc#797]
The help for "runc list" states " runc list - lists containers started by runc with the given root" . However, by default it lists all running containers:

$ sudo /usr/local/sbin/runc list

```
[sudo] password for fedora:
ID               PID         STATUS      BUNDLE                                     CREATED
alpine-copy-1    4797        running     /home/fedora/runc-containers/alpine-copy   2016-05-01T01:09:18.3443786Z
alpine-test-1    3838        running     /home/fedora/runc-containers/alpine        2016-05-01T00:55:02.811703536Z
alpine-test-2    3897        running     /home/fedora/runc-containers/alpine        2016-05-01T01:02:08.537464909Z
busybox-test-1   5002        running     /home/fedora/runc-containers/busybox       2016-05-01T01:10:51.38449258Z
```

Now, I thought okay, may be I need to pass the bundle or the root file system as the argument:

```
[fedora@localhost ~]$ sudo /usr/local/sbin/runc list /home/fedora/runc-containers/alpine
ID               PID         STATUS      BUNDLE                                     CREATED
alpine-copy-1    4797        running     /home/fedora/runc-containers/alpine-copy   2016-05-01T01:09:18.3443786Z
alpine-test-1    3838        running     /home/fedora/runc-containers/alpine        2016-05-01T00:55:02.811703536Z
alpine-test-2    3897        running     /home/fedora/runc-containers/alpine        2016-05-01T01:02:08.537464909Z
busybox-test-1   5002        running     /home/fedora/runc-containers/busybox       2016-05-01T01:10:51.38449258Z
```

But the result is still the same. Not sure, if this is an inconsistency in the documentation or a bug. I would be keen to work on a fix for either if there is fixing needed.

**Comment by cyphar** [comment]
"Given root" refers to the root directory of the state files for all `runc` containers on the system. By default this is `/run/runc`, but you can change it with the `--root` flag to `runc`. But maybe this could be clearer in the documentation. In addition, maybe it should be possible to specify a bundle path.

WDYT @crosbymichael @mrunalp @hqhq?

**Comment by hqhq** [comment]
`--root` would work, only that it's a global option, people might not notice it, yes I think docs can be clearer.

@cyphar Specifying a bundle path is doable, but I don't see much value from it, we already have `BUNDLE` row which can help identifying some information.

**Comment by cyphar** [comment]
@hqhq I think I'd prefer we don't require users to do `| awk '$4 == "/some/bundle/path"` { print }'` in order to get the list of containers running from a particular bundle.

**Comment by marcosnils** [comment]
I don't see it that terrible to do runc list | grep "bundle/path". Eventually users might want different filtering options like id, creation_date, status, etc. +1 on just clearing the doc.

**Comment by cyphar** [comment]
@marcosnils But you can't just do grep, you have to use `awk`.

**Comment by cyphar** [comment]
Sorry, fat-fingered the comment button. :wink:

**Comment by marcosnils** [comment]
> But you can't just do grep, you have to use awk.

??  I don't see I can't use grep

**Comment by marcosnils** [comment]
```
marcos@XPS:~/Projects/containers$ sudo runc list | grep "/home/marcos/Projects/containers/test"
fulano      13642       running     /home/marcos/Projects/containers/test   2016-05-25T05:06:57.95773772Z
pepe        13178       destroyed   /home/marcos/Projects/containers/test   2016-05-25T05:05:53.401659224Z
```

@cyphar works like charm.

**Comment by cyphar** [comment]
Oh, I forgot you can't set a container ID to have `/` in them.

**Comment by wking** [comment]
On Tue, May 24, 2016 at 10:17:32PM -0700, Aleksa Sarai wrote:
> Oh, I forgot you can't set a container ID to have `/` in them.

That's not actually a spec requirement (see #675 and #676), but is
probably a safe assumption for now ;).

**Comment by kunalkushwaha** [comment]
I think this issue is resolved and can be closed.

**Comment by hqhq** [comment]
@kunalkushwaha Thanks for reminding, I think we can close it, feel free to comment if anyone has more questions.
