### ISSUE TITLE
runc and systemd slice (--systemd-cgroup flag)

### ISSUE THREAD

**Issue by papey** [opencontainers/runc#801]
OS : debian jessie / systemd 215

runc : 

```
VERSION:
   0.1.1
commit: 89c3c97a8482f3a57cd4bb683df1a7b2c61405d8
spec: 0.6.0-dev
```

bundle : 

```
test/
├── config.json
└── rootfs

```

rootfs is created with `debootsrap` and config.json generated using : `runc spec`

Basic start of the container works well using `runc start test` command.

Adding the --systemd-cgroup allow users to specify a systemd slice. Without a specific configuration, when the --systemd-cgroup flag is used, runc tries to attach the processus to the systemd system slice (defined in createCgroupConfig function https://github.com/opencontainers/runc/blob/master/libcontainer/specconv/spec_linux.go#L255)

but `runc --systemd-cgroup start test` gives : 

`process_linux.go:253: applying cgroup configuration for process caused "Cannot set property Delegate, or unknown property."`

Adding a specific slice config according to the OCI (https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#control-groups) : 

```
        "linux": {
                "resources": {
                        "devices": [
                                {
                                        "allow": false,
                                        "access": "rwm"
                                }
                        ],
                        "cgroupsPath": "system.slice:runc:434234"
                },
                "namespaces": [

```

Gives the same error.

**Comment by cyphar** [comment]
Yeah, it looks like we didn't add version checks [on this line](https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L186). I guess we're going to have to implement systemd version checking.

**Comment by papey** [comment]
Ok thx. Quite ugly but moving the pid to the right cgroup after runc startup works.

**Comment by mrunalp** [comment]
@papey Could you comment out https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L187 and see if it works? We'll have to test for delegate property or check systemd version like @cyphar pointed out.

**Comment by papey** [comment]
Thx. Sure, i'll try

**Comment by papey** [comment]
@mrunalp after changes, if `--systemd-cgroup` flag is set, runc spwaned process goes into a scope under system.slice : 

```
  ├─runc-test.scope
  │ └─1774 sh

```

Although, if I specified another slice in the config file, containerized process remains in system.slice
