### ISSUE TITLE
How runC should treat supplementary groups?

### ISSUE THREAD

**Issue by albertoleal** [opencontainers/runc#802]
We are wondering what the preferred way is to treat the supplementary groups a user is in. Say the user `alice` is in groups `group1` and `group2`:

```
/etc/passwd
alice:x:1001:1001::/home/alice:::::

/etc/group
group1:x:1001:alice
group2:x:1002:alice
```

and the OCI spec requires that the process defined in `process.json` will run as `alice:group1`. We are thinking of two possible options on how supplementary groups (in this case `group2`) can be applied.

## Option 1: Let the spec author explicitly request for it

Honour the [`AdditionalGids` field in the OCI spec][process_spec]. Currently, this works for the `AdditionalGroups` specified in `config.json` when [starting the container][spec_conv] (`runc start`). It would not work though for `AdditionalGids` specified in a `process.json` that is fed to `runc exec`.

## Option 2: RunC should apply the supplementary groups the user is a member of

RunC reads `/etc/group` and sets the supplementary groups to `group1` and `group2`. Currently this only works if `user.GID` is not specified in the spec. Otherwise, RunC will [only apply the primary group][exec_user].

We think that the second option is better since RunC should apply the supplementary groups a user is in regardless of whether a primary group is explicitly specified or not. We are happy to make a PR in either case.

[process_spec]: https://github.com/opencontainers/runtime-spec/blob/bf58a8f54497acc1f414a5e752057a6694feccf3/config.md#linux-and-solaris-user
[spec_conv]: https://github.com/opencontainers/runc/blob/master/libcontainer/specconv/spec_linux.go#L228-L230
[exec_user]: https://github.com/opencontainers/runc/blob/master/libcontainer/user/user.go#L319-L328
[libcontainer_conv]: https://github.com/opencontainers/runc/blob/master/utils_linux.go#L78

Thanks,
@glestaris and @albertoleal

/cc @cloudfoundry/garden

**Comment by glestaris** [comment]
Any thoughts on that? 

After further discussion, we are now leaning towards option 1, as OCI should remain agnostic of `/etc/passwd` and `/etc/group`.

Thanks,
@williammartin and @glestaris

**Comment by mrunalp** [comment]
We decided to go with explicitly specifying uid/gid/groups in the spec. There is an issue open around allowing specifying usernames that could be looked up but it won't be supported unless it is in the spec.

**Comment by cyphar** [comment]
@mrunalp Speaking of which, we still need to fix up the libcontainer API so that it doesn't take a user string (this just confuses people when reading the user setup code). In fact this problem should've been solved by replacing that code with just a struct with `{uid, gid, supps}`.
