### ISSUE TITLE
Running containers in an unattached mode

### ISSUE THREAD

**Issue by washraf** [opencontainers/runc#805]
I am using runc in my terminal by calling

`$ sudo runc start mycontainer`
or 
`$ sudo runc restore mycontainer`

The problem is when it runs or restores i have no control over the terminal and even pressing `Ctrl+C` or `Ctrl+Z` doesn't response and all i can do is to close my terminal and reopen it and it doesn't close the container by the.

I tried adding a `&` at the end with no effect.
#### Note:
>  My ultimate goal is to measure the time to start, checkpoint and restore a container

**Comment by albertoleal** [comment]
Hey @washraf , you can start a container in a detached mode. You just need to use [the `-d`flag](https://github.com/opencontainers/runc/blob/master/start.go#L43-L46).

For example:
````bash
$ sudo runc start -d mycontainer
```

**Comment by washraf** [comment]
Thanks, I don't know How I missed it :+1:
