### ISSUE TITLE
"too many links" error in kernel 2.6.32, stage "create session key"

### ISSUE THREAD

**Issue by slayercat** [opencontainers/runc#818]
```
[root@localhost a]# runc start x
could not create session key: too many links
Container start failed: [10] System error: could not synchronise with container process
[root@localhost a]# uname -a
Linux localhost.localdomain 2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 22:00:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost a]# runc -v
runc version 0.0.9
spec version 0.4.0

```

strace shows:
```
2564  <... select resumed> )            = 0 (Timeout)
2563  keyctl(0x1, 0xc82004b4f0, 0, 0, 0 <unfinished ...>
2564  select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
2563  <... keyctl resumed> )            = -1 EMLINK (Too many links)
2563  write(3, "{\"type\":1}", 10)      = 10

```

**Comment by mlaventure** [comment]
Your kernel is too old.

In your kernel version the keys where per process and couldn't be set if you had another thread. This was changed to be per thread around 3.6.

**Comment by slayercat** [comment]
thanks, @mlaventure . I downgrading runc to 0.0.5.

by this feature. runc dropped support of  centos 6.x. so I believe there shell be a config for switch off this.

And a notice message too.

**Comment by cyphar** [comment]
The issue with making the keyring stuff optional is that it's a security measure against key disclosure. But I'm fine with making it optional as long as there's a large warning.

**Comment by crosbymichael** [comment]
I'm ok having a way to switch this off but it should be on by default.  Should good ?
