### ISSUE TITLE
Fix broken libcontainer readme

### ISSUE THREAD

**Issue by variadico** [opencontainers/runc#846]
Hello. I was trying to follow the read me here: https://github.com/opencontainers/runc/tree/master/libcontainer

But, the example code doesn't work. I get this error instead.

```
FATA[0000] invalid character '@' looking for beginning of value 
WARN[0000] os: process already finished                 
2016/05/26 15:25:47 container.Start process_linux.go:240: running exec setns proc
```

I'm seeing that because `newContainerInit` fails to decode `pipe` JSON. `pipe` returns this.

```
@?j|?j0 1000 65536
?j0 1000 65536
```

Which I think are the `UidMappings` and `GidMappings`.

**Comment by cyphar** [comment]
Can you share the code you used?

**Comment by guilhermebr** [comment]
Hi, sorry for re-open this, but this is also happening with me.

I'm trying to follow the https://github.com/opencontainers/runc/tree/master/libcontainer README.md  instructions, so I created this code: https://gist.github.com/guilhermebr/621aeef546880fb19c83ae0dd6b190c6

and I'm getting this error:

```
root@de5cb58d4695 # go run main.go create container01
FATA[0000] invalid character '@' looking for beginning of value
WARN[0000] os: process already finished
FATA[0000] process_linux.go:245: running exec setns process for init caused "exit status 1"
exit status 1
```

so I changed the HostID from UidMappings and GidMappings for 0, like this gist:
https://gist.github.com/guilhermebr/69b82c8cb1ecd5db7e3e047a7c19f0ea

and now I'm getting this error:

```
FATA[0000] json: cannot unmarshal number into Go value of type libcontainer.initConfig
WARN[0000] os: process already finished
FATA[0000] process_linux.go:245: running exec setns process for init caused "exit status 1"
exit status 1
```

I removed the Uid and Gid mappings and the NEWUSER namespace, like this gist:
https://gist.github.com/guilhermebr/c4e6273107102b2df2e0eb73a28e1a7f
and I get this error:

``` 
FATA[0000] invalid character '\x18' looking for beginning of value
WARN[0000] os: process already finished
FATA[0000] process_linux.go:245: running exec setns process for init caused "exit status 1"
exit status 1
```

I'm running inside the runc_test a docker container, runc works well.

Using master branch (last commit 41b12c095b0cde82a8f22718bc15ceede5f60b0f)

**Comment by cyphar** [comment]
@guilhermebr You need to include this line in your code:

```
import _ "github.com/opencontainers/runc/libcontainer/nsenter"
```

This ensures that the namespace setup code runs.
