### ISSUE TITLE
checkpoint is failing on Fedora 23

### ISSUE THREAD

**Issue by hmeng-19** [opencontainers/runc#870]
Currently the test suite of runc is based on a ubuntu docker image (runc/script/test_Dockerfile). I am trying to write a Dockerfile, `runc/script/test_Dockerfile_1`, for testing runc on fedora 23.

You can find test_Dockerfile_1 here: https://github.com/hmeng-19/logs/blob/master/test_Dockerfile_1
 `test_Dockerfile_1` tries to mimic the summary of the following two ubuntu-oriented Dockerfiles:
1) https://github.com/docker-library/golang/blob/d7e2a8d90a9b8f5dfd5bcd428e0c33b68c40cc19/1.5/alpine/Dockerfile
2) https://github.com/opencontainers/runc/blob/master/script/test_Dockerfile

The docker image is created successfully after `docker build`:
 
    docker build -t runc_test:fedora -f script/test_Dockerfile_1
 
However, `TestCheckpoint` for `checkpoint_test.go` failed for both the test commands:
 
    docker run -e TESTFLAGS -ti --privileged --rm -v /home/hmeng/go/src/github.com/hmeng-19/runc:/go/src/github.com/opencontainers/runc runc_test:fedora make localunittest
    docker run -e TESTFLAGS -t --privileged --rm -v /home/hmeng/go/src/github.com/hmeng-19/runc:/go/src/github.com/opencontainers/runc runc_test:fedora make localintegration
 
The output of `docker run .... make localunittest` is here: https://github.com/hmeng-19/logs/blob/master/localunittest.log . The failure happened at `TestCheckpoint`, starting from line 267.

The output of `docker run .... make localintegration` is here: https://github.com/hmeng-19/logs/blob/master/localintegration.log . The 3rd test failed.
 
Clearly, both of these two failures are related to checkpoint and restore function of runc. As for as I see, there may have two reasons for the failure:
1) The `test_Dockerfile_1` file does not completely mimic the original ubuntu-oriented test_Dockerfile. This may happen because some packages mentioned in ubuntu-version Dockerfile, such as `build-essential` and `python-minimal` are difficult to mapped to fedora packages.

2) The setting of fedora:23 docker image relavant to the checkpointing and restoring function does not match the setting on ubuntu.

3) Some other reasons I did not realize?

**Comment by hmeng-19** [comment]
@mrunalp, @rhatdan , how do you think about this?
Let me know if you do not think this is the right place for my problem.

**Comment by rhatdan** [comment]
@hmeng-19  Change title of issue to be checkpoint is failing on Fedora 23.

 Does this problem happen on a Fedora system if you run the test using the default Ubuntu Dockerfile?

**Comment by hmeng-19** [comment]
@rhatdan , the test using the default Ubuntu Dockerfile can finish successfully on my Fedora system.

    docker run -e TESTFLAGS -ti --privileged --rm -v /home/hmeng/go/src/github.com/hmeng-19/runc:/go/src/github.com/opencontainers/runc runc_test make localunittest
    docker run -e TESTFLAGS -t --privileged --rm -v /home/hmeng/go/src/github.com/hmeng-19/runc:/go/src/github.com/opencontainers/runc runc_test make localintegration

**Comment by hmeng-19** [comment]
I think I need to explore this problem deeper before coming to upstream. Close it for now.
