### ISSUE TITLE
Runc Enhancements 

### ISSUE THREAD

**Issue by kgrvamsi** [opencontainers/runc#88]
Is there a possibility that i can see runc using in these ways

1)Taking a Ubuntu image and check for installed services 

               runc -c services.json

services.json

{
   "services":[{
"sname":"Nginx",
"parentfolder":"/var/lib/nginx",
"conffolder":"/etc/nginx",
"sservicestatus":"stopped"
}]
}

The service checks can be implemented any.

2)Can we execute commands like how we use to execute commands on Docker
    
       docker exec <container-id> command
       
       runc -e echo "Hello World"

3)Can we have more information about the Spec file we create for any container to run.

**Comment by crosbymichael** [comment]
This is more like a topic for the specs mailing list but in general we are trying to keep the scope small and expanding to the concept of a service will be a hard sell at the runtime level because of the many ways people want to implement or consume services.
