### ISSUE TITLE
Cannot start container using instructions from README on latest build

### ISSUE THREAD

**Issue by willmtemple** [opencontainers/runc#884]
I attempted to follow the instructions in the README to create a container from a docker image based on `busybox` using the latest commit ab10b6068b3f7ec99370eb66bf48592998cc9db1.

```
# mkdir rootfs
# docker export $(docker create busybox) | tar -C rootfs xvf -
# runc spec
# runc run test
```

Expected result: /bin/sh prompt
Actual result: idle, no output, dies on SIGINT

Using the repository version of `runc` on Fedora, I can `runc start test` as previous, with the compiled version from this repo, I get

`open /run/runc/test/state.json: no such file or directory`

While the `runc run test` is idle, I have
```
# runc ps test
UID        PID  PPID  C STIME TTY          TIME CMD
root     18960 18952  0 13:26 pts/5    00:00:00 /home/wtemple/.go/src/github.com/opencontainers/runc/runc init
```

Built with Fedora 23, BUILDTAGS="seccomp selinux", also tried with just BUILDTAGS="seccomp"

**Comment by mrunalp** [comment]
@willmtemple runc needs to be compiled with go 1.6 to work as we SIGCONT which isn't supported in previous versions of go. You can install go binaries directly and compile with it and it should work.

**Comment by reachrkr** [comment]
thx upgrading to 1.6 worked

**Comment by cyphar** [comment]
@mrunalp We should add this to the README unless we're all waiting for #886 / #888 to merge.

**Comment by washraf** [comment]
I am having the same issue running ubuntu 14.04 kernel 4.2.0-36-generic with GO 1.6.3 and latest runc version ??
