### ISSUE TITLE
Unable to build with the Readme steps 

### ISSUE THREAD

**Issue by reachrkr** [opencontainers/runc#887]
I am trying to build runc component  with the latest build and its failing with libseccomp package not found .How do i include this package as nothing is mentioned in the Readme conf

adminuser@adminuser:~/work/src/github.com/opencontainers/runc$ make
go build -i -ldflags "-X main.gitCommit=ab10b6068b3f7ec99370eb66bf48592998cc9db1 -X main.version=1.0.0-rc1" -tags "seccomp" -o runc .
#pkg-config --cflags libseccomp libseccomp
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
pkg-config: exit status 1
Makefile:26: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cyphar** [comment]
Do you have `libseccomp` installed on your system? If not, install it or use the following command:

```
% make BUILDTAGS=""
```

**Comment by reachrkr** [comment]
No i haven't  installed it . Any steps on the setting up will be helpful

**Comment by cyphar** [comment]
The "Build Tags" table says what dependencies are required for each `BUILDTAGS`. It also says the following in the "Building" section:

> In order to enable seccomp support you will need to install libseccomp on your platform. If you do not want to build runc with seccomp support you can add `BUILDTAGS=""` when running make.

**Comment by reachrkr** [comment]
ok thx . will set up libseccomp .

**Comment by reachrkr** [comment]
thanks @cyphar  installing libseccomp-dev worked  me :+1:

**Comment by reachrkr** [comment]
@cyphar  unable to test a docker busybox images mentioned ...  it stays at created state . Followed the steps mentioned in Readme . Am i doing anything wrong here ?


root@adminuser:/tmp/busybox#  ll
total 16
drwxrwxr-x  3 adminuser adminuser 4096 Jun  8 14:01 ./
drwxrwxrwt 11 root      root      4096 Jun  8 13:58 ../
-rw-rw-r--  1 adminuser adminuser 2299 Jun  8 13:59 config.json
drwxrwxr-x 12 adminuser adminuser 4096 Jun  8 14:02 rootfs/
root@adminuser:/tmp/busybox# sudo runc run
container id cannot be empty
root@adminuser:/tmp/busybox# sudo runc  run busybox
-------------------------------------------------------------------------------------------------------------------


ID               PID         STATUS      BUNDLE         CREATED
busybox     2517        created     /tmp/busybox   2016-06-08T08:36:28.890251738Z

**Comment by reachrkr** [comment]
thx upgrading to 1.6 worked .
