### ISSUE TITLE
selinux: switch to opencontainers/go-selinux

### ISSUE THREAD

**Issue by lucab** [opencontainers/runc#897]
While touching rkt code, I realized there is an embedded copy of libcontainer selinux package. The two versions are now [diverging](https://github.com/coreos/rkt/blob/master/pkg/selinux/selinux.go), and I would like to reconcile/contribute back.

Looking at the code, it looks like most of it isn't container specific and could be nicely split into its own module. Would you be ok in splitting this out in a self-standing selinux module? I'd be happy to submit current rkt changes into that and getting rid of existing forks.

**Comment by cyphar** [comment]
WDYT @rhatdan

**Comment by rhatdan** [comment]
Fine with me.

**Comment by lucab** [comment]
@cyphar any news on this? Can the new repo see the light?

I'm certainly in favour of this living under the opencontainers umbrella, I just have some minor wish items:
 * having a clear set of MAINTAINERS to ping (as I guess not all runc people would have interests in that)
 * having tagged releases to help downstream consumers

**Comment by cyphar** [comment]
I'm still waiting for a response from @caniszczyk and @crosbymichael.

**Comment by caniszczyk** [comment]
The @opencontainers/tob have the authorization to approve new projects, they would need to sign off it and we can move forward. @philips do you see anything wrong with this? This is essentially a utility package

**Comment by jonboulle** [comment]
This seems to be live (https://github.com/opencontainers/go-selinux/), except it hasn't been integrated back into this repository yet - is there a plan for that?

**Comment by lucab** [comment]
The first half of this has happened after https://github.com/opencontainers/tob/pull/29, thus I've re-titled it for the remaining part.

**Comment by crosbymichael** [comment]
We just need to do the work not to re-integrate this back into runc.  If someone has time it should be a very simple PR with the code vendored.

**Comment by vbatts** [comment]
I'm sure a PR would be welcome ;-)

**Comment by crosbymichael** [comment]
@vbatts naw

**Comment by vbatts** [comment]
dang

**Comment by hqhq** [comment]
@crosbymichael @vbatts I'll do it today.

**Comment by rhatdan** [comment]
I would prefer the repository be renamed to selinux with a subdir of the golang bindings.
I have been requested to move container-selinux to this repo, but moving the policy to something named go-selinux, makes no sense.
