### ISSUE TITLE
binaries released should be static?

### ISSUE THREAD

**Issue by jfrazelle** [opencontainers/runc#899]
Hey hey!
Cool new releases, was wondering if the binaries you upload could have the BUILDTAGS="apparmor seccomp" and be static :D

**Comment by jfrazelle** [comment]
maybe a shasum too 0:) what if I make a very small release script

**Comment by cyphar** [comment]
Maybe we should also add `selinux`. ;)

**Comment by crosbymichael** [comment]
Ya, i think in we should have an nice array, static and non static with sha's.  

We could have a simple make target, maybe like `make release` that will generate a folder with these different build configurations.

* static
* dynamic
* apparmor + selinux + seccomp
* apparmor + seccomp
* selinux + seccomp
* sha all the thigns
* anything else? man pages?
