### ISSUE TITLE
docker run with "--user nobody" which should have no ability to login system, however ,entered system with "-it"  option.

### ISSUE THREAD

**Issue by TheBeeMan** [opencontainers/runc#907]
Output of docker version:
```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   82141a2-unsupported
 Built:        Tue May 31 10:37:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   82141a2-unsupported
 Built:        Tue May 31 10:37:05 2016
 OS/Arch:      linux/amd64


Containers: 16
 Running: 1
 Paused: 0
 Stopped: 15
Images: 76
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 189
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.843 GiB
Name: thebeeman-vt
ID: TIJL:TE7H:57V2:JT6F:PK6M:YO56:FRAX:C3YP:JZYD:NMON:FM34:Q4OK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 37
 System Time: 2016-06-12T15:51:04.751837404+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by TheBeeMan** [comment]
Steps to reproduce the issue:
1. On docker host: 
# docker run --rm -it --user nobody debian:jessie /bin/bash
2. In the just-started container:
nobody@b9cb3cacb2a4:/$

it seems that user "nobody" has entered the system.

**Comment by cyphar** [comment]
Can you please open this issue against Docker itself? In addition, the reason this is happening is because `docker run` doesn't create a shell or attempt to log the user in -- it executes the program you specified with the user you specified.

**Comment by TheBeeMan** [comment]
ok,i got it.
Docker just run the specified instruction ,simply call setuid(user) during process, rather than create  a shell or attemp to log the user specified, 
Is that right ?

**Comment by cyphar** [comment]
Yes, if all you're doing is specifying `docker run -it --user nobody sh`. If you want, you could write a wrapper to make a "login" shell and make it the `ENTRYPOINT` of the image. But that's not the default.

**Comment by crosbymichael** [comment]
I'll close this because of @cyphar 's explanation.  

Thanks and let us know if you have any questions.
