### ISSUE TITLE
runc-rc1, new workflow and terminal=true containers

### ISSUE THREAD

**Issue by papey** [opencontainers/runc#910]
Regarding the documentation, runc-rc1 (https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc1) provide a new workflow based on 4 steps :
- create
- start
- kill
- delete

Readme specify that containers created with this new workflow have to be in "background mode" (terminal=false).

in the future, hooks will be removed from both in OCI and runC (see https://github.com/opencontainers/runtime-spec/pull/483 and https://github.com/opencontainers/runtime-spec/pull/483 for more info).

So how runC will handle the tty problem for terminal=true containers ? 

I see three options here :
- Update the tty.go code to fit the new workflow
- Delegate tty management to users
- Use runc run for terminal=true containers

What is the "official" position of the runC dev team about this subject ?

Thanks for reading/answers

**Comment by athoune** [comment]
Maybe something like :

* _runc create_ creates its own pty, don't detach and copy STDIN/STDOUT with the pty. Nothing happens.
* configure network stuff with nsenter
* _runc start_, a simple SIGCONT signal start the container.

It's ugly, but it handles the prepare/configure/step without hooks.

**Comment by cyphar** [comment]
This is probably related to the amiguity wrt `terminal: true` (opencontainers/runtime-spec#494), as well as lots of the issues with `--console` (#814).

**Comment by papey** [comment]
@athoune Regarding changes made by #886, runC will no longer use signals to start the container process.

@cyphar yes but tty is so close to the runtime (tty life time == container process life time) that it makes sens to me that runc handle this task.

**Comment by cyphar** [comment]
To be clear: I think we should fix it. I was just pointing you to places where you can find some more information. I've been trying to figure out how to properly fix `--console`'s interaction with user namespaces for a few weeks now.

**Comment by cyphar** [comment]
@papey I've implemented a bunch of terminal changes in #1018. Take a look if you're interested (that PR will close this one once merged).

**Comment by cyphar** [comment]
#1018 has been merged.
