### ISSUE TITLE
Replace PullApprove with lgtm.co

### ISSUE THREAD

**Issue by cyphar** [opencontainers/runc#916]
Currently we're using PullApprove (which is proprietary, and cannot be self-hosted). There is another project, called lgtm.co which is free software and self-hostable: https://github.com/lgtmco/lgtm

Can we please switch to using this for PR checks (and obviously open companion PRs on all OCI projects)?

**Comment by wking** [comment]
On Tue, Jun 14, 2016 at 08:56:53PM -0700, Aleksa Sarai wrote:
> There is another project, called lgtm.co which is free software and
> self-hostable: https://github.com/lgtmco/lgtm

It may not remain free for long.  From [1]:

  This product is free for small teams and non-profits, however, we
  will require a modest licensing fee for on-premise enterprise use in
  the near future.  Pricing to be published soon.

It's currently Apache 2.0 [2], although with only two contributors [3]
there is a chance they could change licences and move forward with a
more restrictive license.  I'm not sure what their plans are, and
folks could always fork the current Apache-licensed tip, but I think
it's worth getting more clarity on their plans before switching all
the recently-settled OCI tooling over.

[1]: https://lgtm.co/docs/install/#licensing:ee40007639ba1d9861b5cc3e7ade0aef
[2]: https://github.com/lgtmco/lgtm/blob/6a053194cd629c24815732cd095e1efdf0c82baa/LICENSE
[3]: https://github.com/lgtmco/lgtm/graphs/contributors

**Comment by wking** [comment]
On Tue, Jun 14, 2016 at 09:53:47PM -0700, W. Trevor King wrote:
> It may not remain free for long…

On the other hand, the “we think this is stable and aren't investing a
lot of time in major enhancements” [1] wording sounds a lot more like
“this will probably be open-source forever”.  But again, probably
worth pinging the authors to get clarification.

[1]: https://github.com/lgtmco/lgtm/tree/6a053194cd629c24815732cd095e1efdf0c82baa#development

**Comment by cyphar** [comment]
> It may not remain free for long. From [1]:

I use the term in the context of "free as in freedom software". I don't use the term "open source" anymore.

> It's currently Apache 2.0 [2], although with only two contributors [3] there is a chance they could change licences and move forward with a more restrictive license.

It works, it's free software and trivially self-hostable (single Go binary) if they decide to start charging us for it.

**Comment by wking** [comment]
On Tue, Jun 14, 2016 at 09:58:55PM -0700, Aleksa Sarai wrote:
> It works, it's free software and trivially self-hostable (single Go
> binary) if they decide to start charging us for it.

The “we will require a modest licensing fee for on-premise enterprise
use in the near future” language I linked earlier is from their “Self
Hosting” page.  I'm not clear on how they plan to do that without
changing the license, and I'm not clear on the distinction between
“on-premise enterprise use” and “self hosting”.  Apache 2.0 covers the
four freedoms [1,2], so I expect it would include relicensing the
project, in which case there is always the “fork the Apache code”
safety valve I mentioned in [3].

[1]: https://www.gnu.org/philosophy/free-sw.html
[2]: http://www.gnu.org/licenses/license-list.html#apache2
[3]: https://github.com/opencontainers/runc/issues/916#issuecomment-226087815

**Comment by cyphar** [comment]
No, I think that "enterprise use" probably refers to some kind of support contract? Or maybe they are planning on making it proprietary (which is a real shame). We can email them about it if you like.

**Comment by wking** [comment]
On Wed, Jun 15, 2016 at 08:12:31AM -0700, Aleksa Sarai wrote:
> We can email them about it if you like.

I've filed lgtmco/lgtm-docs#7 requesting clarification.

**Comment by wking** [comment]
On Wed, Jun 15, 2016 at 09:03:30AM -0700, W. Trevor King wrote:
> I've filed lgtmco/lgtm-docs#7 requesting clarification.

And the clarification is “the licensing-fee note was obsolete” [1,2],
so I'm +1 on switching to lgtm.co.

[1]: https://github.com/lgtmco/lgtm-docs/issues/7#issuecomment-226265541
[2]: https://github.com/lgtmco/lgtm-docs/commit/25e73dfc126f3b58e5f97e39902401a3bce07962

**Comment by kolyshkin** [comment]
As we have switched from pullapprove to native github review process (see https://github.com/opencontainers/runc/issues/2388), this issue is no longer relevant, thus closing.
