### ISSUE TITLE
Issue with configuring memory swappiness to other than default 

### ISSUE THREAD

**Issue by washraf** [opencontainers/runc#921]
```
"linux": {
                 "memory": {
                         "swappiness": 10
                 },
                 "resources": {
                         "devices": [
                                 {
                                         "allow": false,
                                         "access": "rwm"
                                 }
                         ]
                 },
 ...
```

I have configured the container for a swapped memory other than the default value.
when it runs it gives no effect and the memory.swappiness are still 60 (The default value)

**Comment by hmeng-19** [comment]
@washraf , I tried this on my machine and it works for me. After my container starts, the `memory.swappiness` file under its cgroup memory subsystem is `10`.

Do you mind sharing the strace log of your test. You can get the strace log by running the following command:

    sudo strace -f -o strace.log $(which runc) run testcontainer1

**Comment by kunalkushwaha** [comment]
I guess this issue is resolved. 

using ``ocitools generate --linux-mem-swappiness`` value can be set.

and in config.json ``memory`` section need to be under ``resources`` tag.

``` json
.
.
"linux": {
                 "resources": {
                         "devices": [
                                 {
                                         "allow": false,
                                         "access": "rwm"
                                 }
                         ]
                         },
                        "memory": {
                                 "swappiness": 10
                         },
 ...
```

Can this be closed?

**Comment by hqhq** [comment]
@washraf I think this is a misconfiguration issue, I'll close, feel free to comment is you have more questions.
