### ISSUE TITLE
https://runc.io certificate is expired

### ISSUE THREAD

**Issue by rhencke** [opencontainers/runc#926]
The certificate serving https://runc.io expired on June 22, 2016.

**Comment by cyphar** [comment]
I actually don't know who is responsible for hosting that site. /cc @crosbymichael

**Comment by wking** [comment]
On Thu, Jun 23, 2016 at 11:36:23PM -0700, Aleksa Sarai wrote:
> I actually don't know who is responsible for hosting that site.

whois says it's still [1] owned by @chanezon.

[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/UGqmPMr3R6M/eJLmkLbfCQAJ
     Subject: runc.io ownership
     Date: Fri, 11 Dec 2015 20:48:00 -0800
     Message-ID: <20151212044800.GG4349@odin.tremily.us>

**Comment by philips** [comment]
This domain should be transferred to the LF probably. cc @caniszczyk

**Comment by caniszczyk** [comment]
I'll follow up with @chanezon over email to get this done.

**Comment by crosbymichael** [comment]
The cert has been fixed, thanks for the issue.
