### ISSUE TITLE
Why not use Dockerfile for build

### ISSUE THREAD

**Issue by hqhq** [opencontainers/runc#93]
I see there are several build issues, myself met build issues too, I wonder why we don't use Dockerfile to setup an unified environment for building?

I thought runc was considered as an independent project which won't depend on Docker or other projects, but then I see we still use Docker for test, so I think we can use Docker for build as well.

Is there any specific reasons why we don't use Dockerfile? Thanks.

**Comment by kgrvamsi** [comment]
Can you send the output log of the build issue you got?

**Comment by hqhq** [comment]
I got:
```
$ make
go build -o runc .
# github.com/opencontainers/runc/libcontainer/seccomp
libcontainer/seccomp/seccomp.go:71: internal compiler error: unknown etype 0/STRUCT
make: *** [all] Error 2
```

I think it's because my golang is too old:
```
$ go version
go version go1.2.1 linux/amd64
```

Now I'm using `dockercore/libcontainer` image to build and test runc. It works perfectly.

**Comment by kgrvamsi** [comment]
ya its because of the old golang version and faced the same issue and when i changed it to 1.4 then i dont see this issue any where.Try using gvm when your facing issues like this so that u can change ur golang versions anytime

**Comment by kgrvamsi** [comment]
I think there is already a dockerfile in the repo dont know if it is useful for you

https://github.com/opencontainers/runc/blob/master/test_Dockerfile

**Comment by crosbymichael** [comment]
No reason, we can add one if you want ;)

**Comment by duglin** [comment]
@hqh see https://github.com/opencontainers/runc/pull/506/files#diff-42ea5667b327bb207485077410d5f499R1   :-)
