### ISSUE TITLE
systemd-cgroup uses incorrect subsystem path in recent systemd versions

### ISSUE THREAD

**Issue by euank** [opencontainers/runc#931]
This issue was discussed in a comment a while ago: https://github.com/docker/docker/issues/16256#issuecomment-218935000

Now that systemd 226+ is more common, this issue has further ramifications.

Under systemd versions of at least 226, `systemd` is under `init.scope`. The code [here](https://github.com/opencontainers/runc/blob/629e35666d31f743090452416c8df207d9fdbd34/libcontainer/cgroups/systemd/apply_systemd.go#L387) behaves incorrectly in this configuration.

The following is an example of what goes wrong in this configuration:

```
$ runc --systemd-cgroup run foo
$ cat /proc/$(pidof foo)/cgroups
9:net_cls:/system.slice/runc-foo.scope
8:memory:/init.scope/system.slice/runc-foo.scope
7:blkio:/init.scope/system.slice/runc-foo.scope
6:devices:/init.scope/system.slice/runc-foo.scope
5:cpuset:/system.slice/runc-foo.scope
4:perf_event:/system.slice/runc-foo.scope
3:cpu,cpuacct:/init.scope/system.slice/runc-foo.scope
2:freezer:/system.slice/runc-foo.scope
1:name=systemd:/system.slice/runc-foo.scope
$ # Note that some subsystems have `init.scope` as part of their path
$ head /sys/fs/cgroup/cpu,cpuacct/init.scope/system.slice/runc-foo.scope/tasks /sys/fs/cgroup/cpu,cpuacct/system.slice/runc-foo.scope/tasks
==> /sys/fs/cgroup/cpu,cpuacct/init.scope/system.slice/runc-foo.scope/tasks <==
1085
1090
1091
1092
==> /sys/fs/cgroup/cpu,cpuacct/system.slice/runc-foo.scope/tasks <==
$ 
```

Essentially, the problem is as described in the above comment: runc thinks some cgroup subsystems should be under `init.scope` under the mistaken assumption that the cgroup of pid 1 is always the root of the cgroup tree. In reality, everything should just be under the real root, `/`.

I've begun putting together a patch (currently [WIP](https://github.com/euank/runc/commits/fix-systemd-init-scope)), but wanted an issue to point at.

This impacts projects, such as cadvisor, which read container's cgroups.

cc @vishh @marineam

**Comment by cyphar** [comment]
I'm fairly sure this is related to some of the discussion we had in #895. Essentially we aren't treating subsystem paths separately when creating the implicit `cgroupsPath`.

**Comment by euank** [comment]
cc @derekwaynecarr I believe RHEL uses the systemd driver.. Do you guys somehow avoid encountering this issue? Do you have a patch floating around somewhere (I didn't see it glancing through the list of docker patches Redhat carries, but worth asking), or is it on an older systemd version / one without pid 1 in init.scope?

**Comment by derekwaynecarr** [comment]
@mrunalp was going to look at this.  systemd on fedora 24 is the first
release we have hit this.  RHEL and CentOS are on systemd < 225 I believe
so pre init.scope

**Comment by mrunalp** [comment]
@euank The approach of using dbus to query the root slice sounds good to me.
