### ISSUE TITLE
Version of libseccomp detection

### ISSUE THREAD

**Issue by mYmNeo** [opencontainers/runc#938]
There are three variables called `verMajor`, `verMinor`, `verMicro` to identify the version of libseccomp library, but they are fixed after building.If we upgrading the libseccomp library, the binary can not detect the new version.Should we change the detection fix mode to runtime mode such as using `pkg --modversion libseccomp`

**Comment by cyphar** [comment]
This is a question for the actual libseccomp-golang project (https://github.com/seccomp/libseccomp-golang). But yes, I'm not entirely sure why they implemented it that way.

**Comment by hqhq** [comment]
This is not a runc issue, traced by https://github.com/seccomp/libseccomp-golang/issues/11 .
