### ISSUE TITLE
`TestRunWithKernelMemory` failed

### ISSUE THREAD

**Issue by hmeng-19** [opencontainers/runc#946]
It seems that the commit https://github.com/opencontainers/runc/commit/8dd3d634556427c22769125ef2b0aa2ce613a2a7 broke the `TestRunWithKernelMemory` test somehow. Here is the error in the output of `make test`:

    --- FAIL: TestRunWithKernelMemory (0.13s)^M
        exec_test.go:671: runContainer failed with kernel memory limit: process_linux.go:291: setting cgroup config for ready process caused "cannot set kmem.limit_in_bytes after task have joined this cgroup"^M

Its previou commit https://github.com/opencontainers/runc/commit/9d7831e41d3ef428b67685eeb27f2b4a22a92391 works well for me.

**Comment by hqhq** [comment]
I can reproduce this problem on some machines, I opened a PR to revert that commit.
https://github.com/opencontainers/runc/pull/961

**Comment by cyphar** [comment]
@hqhq I was about to do the same, it's been bothering me for a few days.
