### ISSUE TITLE
CpuRtRuntime and CpuQuota are defined with the same json key "cpu_quota".

### ISSUE THREAD

**Issue by aclisp** [opencontainers/runc#948]
`CpuRtRuntime` and `CpuQuota` have the same json field.
`CpuRtPeriod` and `CpuPeriod` have the same json field.
It makes libcontainer get wrong value of `CpuQuota` from docker's `state.json`

https://github.com/opencontainers/runc/blob/master/libcontainer/configs/cgroup_unix.go#L72

```
	// CPU hardcap limit (in usecs). Allowed cpu time in a given period.
	CpuQuota int64 `json:"cpu_quota"`

	// CPU period to be used for hardcapping (in usecs). 0 to use system default.
	CpuPeriod int64 `json:"cpu_period"`

	// How many time CPU will use in realtime scheduling (in usecs).
	CpuRtRuntime int64 `json:"cpu_quota"`

	// CPU period to be used for realtime scheduling (in usecs).
	CpuRtPeriod int64 `json:"cpu_period"`
```

**Comment by cyphar** [comment]
I'm not sure whether it really makes sense to have two different values for the realtime and non-realtime quotas / periods (though, if you're planning to run both realtime and non-realtime programs in the same container, maybe there's a reason). I've opened a PR to fix it though.
