### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by senrabdet** [opencontainers/runc#952]
I'm trying to learn about runc.  In following the instructions on https://github.com/opencontainers/runc, and when I get to the point of doing "make test", it tries to run but I can an error:

Makefile:62: recipe for target 'localunittest' failed
make: **\* [localunittest] Error 1
Makefile:59: recipe for target 'unittest' failed
make[1]: **\* [unittest] Error 2
make[1]: Leaving directory '/home/user/work/src/github.com/opencontainers/runc'
Makefile:53: recipe for target 'test' failed
make: **\* [test] Error 2

I can run the busybox example successfully.

Q:  does this error represent something to worry about?  If so, should I provide an strace?  Is this a problem with my go setup (e.g., should I set the GOBIN variable)? go env shows:
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/work"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

Thanks!

**Comment by hmeng-19** [comment]
@senrabdet , I also noticed `make test` failed and filed an issue #946 . 
Would you mind checking whether it was the `TestRunWithKernelMemory` test failed on your machine.

**Comment by senrabdet** [comment]
Thanks(!), will try, get back.

**Comment by senrabdet** [comment]
I think I'm getting a larger number of fail messages that do include TestRunWithKernelMemory but more than that (from strace make test).  It looks like a lot of cgroup related issues - is that something I need to turn on in my kernel (is this output helpful?  Thank you for the help.

=== RUN   TestCheckpoint
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestCheckpoint (0.03s)
	checkpoint_test.go:96: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820016a00 pid:179}"
=== RUN   TestExecPS
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecPS (0.02s)
	exec_test.go:48: |: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200174f0 pid:183}"
=== RUN   TestUsernsExecPS
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestUsernsExecPS (0.02s)
	exec_test.go:48: |: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820017e50 pid:187}"
=== RUN   TestIPCPrivate
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestIPCPrivate (0.02s)
	utils_test.go:51: exec_test.go:78: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820178820 pid:191}"
		
=== RUN   TestIPCHost
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestIPCHost (0.02s)
	utils_test.go:51: exec_test.go:104: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820179180 pid:195}"
		
=== RUN   TestIPCJoinPath
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestIPCJoinPath (0.01s)
	utils_test.go:51: exec_test.go:131: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820179ae0 pid:199}"
		
=== RUN   TestIPCBadPath
--- PASS: TestIPCBadPath (0.02s)
=== RUN   TestRlimit
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestRlimit (0.01s)
	utils_test.go:51: exec_test.go:196: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820296550 pid:205}"
		
=== RUN   TestUsernsRlimit
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestUsernsRlimit (0.02s)
	utils_test.go:51: exec_test.go:196: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820296eb0 pid:209}"
		
=== RUN   TestEnter
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestEnter (0.02s)
	utils_test.go:51: exec_test.go:247: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820297860 pid:213}"
		
=== RUN   TestProcessEnv
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestProcessEnv (0.02s)
	utils_test.go:51: exec_test.go:334: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8203f61e0 pid:217}"
		
=== RUN   TestProcessCaps
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestProcessCaps (0.02s)
	utils_test.go:51: exec_test.go:382: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820016910 pid:221}"
		
=== RUN   TestAdditionalGroups
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestAdditionalGroups (0.02s)
	utils_test.go:51: exec_test.go:452: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820017310 pid:225}"
		
=== RUN   TestFreeze
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestFreeze (0.02s)
	utils_test.go:51: exec_test.go:514: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820017c70 pid:233}"
		
=== RUN   TestSystemdFreeze
--- SKIP: TestSystemdFreeze (0.00s)
	exec_test.go:475: Systemd is unsupported
=== RUN   TestCpuShares
[33mWARN[0m[0000] signal: killed                               
--- PASS: TestCpuShares (0.02s)
=== RUN   TestCpuSharesSystemd
--- SKIP: TestCpuSharesSystemd (0.00s)
	exec_test.go:536: Systemd is unsupported
=== RUN   TestPids
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestPids (0.02s)
	utils_test.go:51: exec_test.go:592: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8203f7180 pid:241}"
		
=== RUN   TestPidsSystemd
--- SKIP: TestPidsSystemd (0.00s)
	exec_test.go:567: Systemd is unsupported
=== RUN   TestRunWithKernelMemory
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestRunWithKernelMemory (0.02s)
	exec_test.go:671: runContainer failed with kernel memory limit: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8203f7ae0 pid:245}"
=== RUN   TestRunWithKernelMemorySystemd
--- SKIP: TestRunWithKernelMemorySystemd (0.00s)
	exec_test.go:650: Systemd is unsupported
=== RUN   TestContainerState
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestContainerState (0.02s)
	exec_test.go:724: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200f2460 pid:251}"
=== RUN   TestPassExtraFiles
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestPassExtraFiles (0.02s)
	exec_test.go:777: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200f2dc0 pid:255}"
=== RUN   TestMountCmds
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestMountCmds (0.02s)
	exec_test.go:858: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200f3720 pid:263}"
=== RUN   TestSysctl
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestSysctl (0.02s)
	utils_test.go:51: exec_test.go:906: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820372140 pid:267}"
		
=== RUN   TestMountCgroupRO
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestMountCgroupRO (0.02s)
	exec_test.go:934: |: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8203720a0 pid:271}"
=== RUN   TestMountCgroupRW
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestMountCgroupRW (0.02s)
	exec_test.go:983: |: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820372aa0 pid:275}"
=== RUN   TestOomScoreAdj
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestOomScoreAdj (0.02s)
	utils_test.go:51: exec_test.go:1046: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820373450 pid:284}"
		
=== RUN   TestHook
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestHook (0.02s)
	utils_test.go:51: exec_test.go:1118: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820373db0 pid:288}"
		
=== RUN   TestSTDIOPermissions
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestSTDIOPermissions (0.02s)
	utils_test.go:51: exec_test.go:1160: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200f2780 pid:292}"
		
=== RUN   TestRootfsPropagationSlaveMount
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestRootfsPropagationSlaveMount (0.02s)
	utils_test.go:51: exec_test.go:1237: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200f30e0 pid:296}"
		
=== RUN   TestRootfsPropagationSharedMount
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestRootfsPropagationSharedMount (0.02s)
	utils_test.go:51: exec_test.go:1354: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200f3ae0 pid:300}"
		
=== RUN   TestPIDHost
[33mWARN[0m[0000] signal: killed                               
[33mWARN[0m[0000] failed to write FROZEN to freezer.state: open /sys/fs/cgroup/freezer/integration/test/freezer.state: no such file or directory 
[33mWARN[0m[0000] failed to write THAWED to freezer.state: open /sys/fs/cgroup/freezer/integration/test/freezer.state: no such file or directory 
--- FAIL: TestPIDHost (0.02s)
	utils_test.go:51: exec_test.go:1423: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820016d70 pid:304}"
		
=== RUN   TestInitJoinPID
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestInitJoinPID (0.02s)
	utils_test.go:51: exec_test.go:1458: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820017c70 pid:308}"
		
=== RUN   TestInitJoinNetworkAndUser
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestInitJoinNetworkAndUser (0.02s)
	utils_test.go:51: exec_test.go:1563: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8204845f0 pid:312}"
		
=== RUN   TestExecIn
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecIn (0.02s)
	utils_test.go:51: execin_test.go:42: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820484fa0 pid:316}"
		
=== RUN   TestExecInUsernsRlimit
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecInUsernsRlimit (0.02s)
	utils_test.go:51: execin_test.go:109: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200f2910 pid:320}"
		
=== RUN   TestExecInRlimit
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecInRlimit (0.02s)
	utils_test.go:51: execin_test.go:109: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200f32c0 pid:324}"
		
=== RUN   TestExecInAdditionalGroups
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecInAdditionalGroups (0.02s)
	utils_test.go:51: execin_test.go:163: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200f3c70 pid:328}"
		
=== RUN   TestExecInError
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecInError (0.02s)
	utils_test.go:51: execin_test.go:224: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820016eb0 pid:332}"
		
	execin_test.go:221: exec: Wait was already called
=== RUN   TestExecInTTY
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecInTTY (0.02s)
	utils_test.go:51: execin_test.go:271: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820017810 pid:336}"
		
=== RUN   TestExecInEnvironment
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecInEnvironment (0.01s)
	utils_test.go:51: execin_test.go:328: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820484190 pid:340}"
		
=== RUN   TestExecinPassExtraFiles
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecinPassExtraFiles (0.03s)
	execin_test.go:393: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820484af0 pid:344}"
=== RUN   TestExecInOomScoreAdj
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecInOomScoreAdj (0.02s)
	utils_test.go:51: execin_test.go:465: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8204854a0 pid:348}"
		
=== RUN   TestExecInUserns
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestExecInUserns (0.02s)
	utils_test.go:51: execin_test.go:520: unexpected error: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc820485e00 pid:352}"
		
=== RUN   TestSeccompDenyGetcwd
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestSeccompDenyGetcwd (0.02s)
	seccomp_test.go:55: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8201cc7d0 pid:356}"
=== RUN   TestSeccompPermitWriteConditional
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestSeccompPermitWriteConditional (0.02s)
	seccomp_test.go:130: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200165a0 pid:360}"
=== RUN   TestSeccompDenyWriteConditional
[33mWARN[0m[0000] signal: killed                               
--- FAIL: TestSeccompDenyWriteConditional (0.02s)
	seccomp_test.go:191: process_linux.go:258: applying cgroup configuration for process caused "invalid path for memory cgroups: &{root:/sys/fs/cgroup innerPath:integration/test config:0xc8200172c0 pid:364}"
FAIL
exit status 1
FAIL	_/go/src/github.com/opencontainers/runc/libcontainer/integration	0.920s
?   	_

**Comment by hmeng-19** [comment]
@senrabdet , The OS on my machine is Fedora 23, and I did not recall any trouble when I first tried runc except for  installing `libseccomp-devel`.
The dependencies for testing runc are prepared in the docker container, and we should not worry about. 
Why not you also provide the OS info you are using so that others can help you better?

**Comment by senrabdet** [comment]
Thanks hmeng.  Am using Debian Stretch on VirtualBox 5 on Win10.
  uname -a:
Linux debian 4.6.0-1-amd64 #1 SMP Debian 4.6.2-2 (2016-06-25) x86_64 GNU/Linux

runc version 1.0.0-rc1

go version go1.6.2 linux/amd64

**Comment by kunalkushwaha** [comment]
@senrabdet  Are you still facing this issue?
if yes, can you give output of

 ``$ ls /sys/fs/cgroup/memory/``

**Comment by AkihiroSuda** [comment]
Closing as outdated
