### ISSUE TITLE
container.Start failed to start the process

### ISSUE THREAD

**Issue by hushan** [opencontainers/runc#973]
The error happened while using the container api to start a container:

$ go run run.go
2016/08/06 07:27:12 invalid character '\x18' looking for beginning of value
WARN[0000] os: process already finished
panic: process_linux.go:245: running exec setns process for init caused "exit status 1"

goroutine 1 [running]:
panic(0x75ca60, 0xc8200cc5b0)
        /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
main.main()
        /home/workspace/run.go:150 +0x1bb
exit status 2

run.go is using the same way the runc command tool to start the container, factory.Create and then Container.Start. It looks the bootstrapData(which starts with 0x18) was supplied to Json decoder to get the config.

full source at https://gist.github.com/hushan/67e1ddd22d4f2a686fb97a01e7299388

**Comment by JakeWarner** [comment]
Have you tried this?

https://github.com/opencontainers/runc/issues/846#issuecomment-233393066

**Comment by hushan** [comment]
Ok, that is the problem indeed. thanks @JakeWarner 
I find the relevant doc in package nsenter, it'd be better to mention it in the libcontainer main doc.

**Comment by ruqqq** [comment]
I am using @hushan's gist (after modification for nsenter) against the current runC master repo but can't seem to spawn the exec process successfully. After debugging, it shows that code execution for "init" process stops/freeze at `syscall.Openat` in standard_init_linux.go hence the exec didn't get called.

Any ideas?
